<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Corrado Caudek">

<title>66&nbsp; Applicazione Pratica – Testing Psicologico</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/irt/01_rasch_model.html" rel="next">
<link href="../../chapters/mokken/02_core_issues.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-70d37b45c5086134dc26dbb10e888fc0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-d0edb45afdd5f5fd9663be5d5709df0d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/mokken/01_logistic_regr.html">Mokken</a></li><li class="breadcrumb-item"><a href="../../chapters/mokken/03_applications.html"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Applicazione Pratica</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Testing Psicologico</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ccaudek/testing_psicologico/" title="Eseguire il codice" class="quarto-navigation-tool px-1" aria-label="Eseguire il codice"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Ricerca"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Informazioni Generali</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../prefazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefazione</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Calendario</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../cal_testing_psic_2025.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calendario Didattico e Programma del Corso</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Punteggi e scale</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/01_scores_scales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Punteggi e scale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E1_likert.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">✏ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E2_optimal_scoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E3_thurstone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">✏ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/02_development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sviluppo dello strumento</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/03_equating.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Equating nei Test Psicologici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E4_norming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">CTT</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/01_ctt_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Fondamenti teorici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/02_ctt_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">L’affidabilità del test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/03_ctt_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Metodi di stima dell’affidabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/04_err_std_mis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">L’errore standard della misurazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/05_err_std_stima.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">La stima del punteggio vero</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/06_ctt_applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Applicazioni della CTT</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Giudici</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/01_multilevel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Modelli multilivello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/02_interrater_reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">L’affidabilità tra giudici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/E1_irr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Validità</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/validity/01_validity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">La Validità del test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/validity/02_other_variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Relazioni test-criterio</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Generalizzabilità</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/gtheory/01_gtheory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Teoria della generalizzabilità</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Items</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/items/01_item_development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Lo sviluppo degli item</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/items/02_item_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Analisi degli item</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Analisi dei percorsi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/path_analysis/01_path_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Analisi dei percorsi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/path_analysis/02_clement_2022.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Riparazione affettiva post-infedeltà</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Networks</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/networks/01_networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Network psicologici</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">PCA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/pca/01_linear_algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Elementi di algebra lineare</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/pca/02_pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Analisi delle componenti principali</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">FA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/01_intro_fa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Introduzione all’analisi fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/02_analisi_fattoriale_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Il modello unifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/03_analisi_fattoriale_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Il modello statistico dell’analisi fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/04_analisi_fattoriale_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Il modello multifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/05_factor_scores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">I punteggi fattoriali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/06_constraints_on_parms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Attendibilità e modello fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/07_total_score.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Punteggio totale e modello fattoriale</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false">
 <span class="menu-text">Costruzione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/01_val_matrici.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Valutazione della matrice di correlazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/02_estrazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">L’estrazione dei fattori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/03_numero_fattori.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Il numero dei fattori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/04_rotazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">La rotazione fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/05_val_soluzione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Valutare e rifinire la soluzione fattoriale</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">CFA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/01_cfa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Analisti Fattoriale Confermativa</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/02_meanstructure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">La struttura delle medie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/03_cat_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Dati non gaussiani e categoriali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/04_mmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">CFA per matrici multi-tratto multi-metodo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/05_bifactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Modello bifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/06_efa_lavaan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Exploratory Structural Equation Modeling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/07_fa_in_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Strategia Integrata per un’Analisi Fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/E_02_bifactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false">
 <span class="menu-text">SEM</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/01_sem_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Introduzione ai Modelli SEM</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/02_data_preparation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Preparazione dei Dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/03_gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Test del Modello e Indicizzazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/04_mod_comp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Confronto tra modelli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/05_cfa_mod_comp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">CFA: confronto tra modelli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/06_refine_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">La revisione del modello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/07_group_invariance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Invarianza di misura</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/08_multilevel_sem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Modelli di Equazioni Strutturali Multilivello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/09_structural_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Modelli di Regressione Strutturale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/10_missing_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Dati mancanti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/11_small_samples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Modellizzazione SEM in Piccoli Campioni</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/13_esem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Exploratory structural equation modelling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/14_sem_power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Dimensione Campionaria e Analisi della Potenza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/15_prior_pred_mod_check.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Prior Predictive Model Checking</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="true">
 <span class="menu-text">Mokken</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/01_logistic_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Modello di Regressione Logistica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/02_core_issues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Analisi della Scala di Mokken</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/03_applications.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Applicazione Pratica</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false">
 <span class="menu-text">IRT</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/01_rasch_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">Modello di Rasch</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/02_assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">68</span>&nbsp; <span class="chapter-title">Assunzioni e Proprietà del Modello di Rasch</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/03_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title">Stima</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/04_1pl_2pl_3pl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Modelli 1PL, 2PL e 3PL</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/05_implementation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Implementazione</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false">
 <span class="menu-text">LGM</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/01_lgm_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">72</span>&nbsp; <span class="chapter-title">Curve di crescita latente</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/02_lgm_prelims.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">73</span>&nbsp; <span class="chapter-title">Considerazioni Preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/06_lgm_mixed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">74</span>&nbsp; <span class="chapter-title">LGM e modelli misti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/03_time_effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">75</span>&nbsp; <span class="chapter-title">Dati longitudinali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/05_intro_panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">76</span>&nbsp; <span class="chapter-title">Specificare e Interpretare un Modello Longitudinale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/07_growth_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">77</span>&nbsp; <span class="chapter-title">Curve di crescita latente</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/08_growth_cont.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">78</span>&nbsp; <span class="chapter-title">Il tempo su una metrica continua</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/09_time_inv_cov.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">79</span>&nbsp; <span class="chapter-title">Covariate indipendenti dal tempo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/10_growth_groups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">80</span>&nbsp; <span class="chapter-title">Modelli di crescita latenti a gruppi multipli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/11_lgm_wais.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">81</span>&nbsp; <span class="chapter-title">Lo Sviluppo dell’Intelligenza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/12_temp_reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">82</span>&nbsp; <span class="chapter-title">Affidabilità longitudinale</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false">
 <span class="menu-text">Predizione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/prediction/01_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">83</span>&nbsp; <span class="chapter-title">Predizione</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../99-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliografia</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendici</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a1_intro_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linguaggio R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a2_sums.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Simbolo di somma</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a3_calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Per liberarvi dai terrori preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false">
 <span class="menu-text">Soluzioni degli esercizi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/solutions_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Probabilità</span></span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Indice</h2>
   
  <ul>
  <li><a href="#introduzione" id="toc-introduzione" class="nav-link active" data-scroll-target="#introduzione"><span class="header-section-number">66.1</span> Introduzione</a></li>
  <li><a href="#importazione-dei-dati" id="toc-importazione-dei-dati" class="nav-link" data-scroll-target="#importazione-dei-dati"><span class="header-section-number">66.2</span> Importazione dei dati</a></li>
  <li><a href="#statistiche-descrittive" id="toc-statistiche-descrittive" class="nav-link" data-scroll-target="#statistiche-descrittive"><span class="header-section-number">66.3</span> Statistiche descrittive</a></li>
  <li><a href="#automated-item-selection-procedure-aisp" id="toc-automated-item-selection-procedure-aisp" class="nav-link" data-scroll-target="#automated-item-selection-procedure-aisp"><span class="header-section-number">66.4</span> Automated Item Selection Procedure (AISP)</a></li>
  <li><a href="#scalability-coefficients" id="toc-scalability-coefficients" class="nav-link" data-scroll-target="#scalability-coefficients"><span class="header-section-number">66.5</span> Scalability Coefficients</a></li>
  <li><a href="#monotonicità" id="toc-monotonicità" class="nav-link" data-scroll-target="#monotonicità"><span class="header-section-number">66.6</span> Monotonicità</a></li>
  <li><a href="#ordinamento-invariante-degli-item" id="toc-ordinamento-invariante-degli-item" class="nav-link" data-scroll-target="#ordinamento-invariante-degli-item"><span class="header-section-number">66.7</span> Ordinamento Invariante degli Item</a></li>
  <li><a href="#non-intersezione-delle-funzioni-di-risposta-degli-step-degli-item" id="toc-non-intersezione-delle-funzioni-di-risposta-degli-step-degli-item" class="nav-link" data-scroll-target="#non-intersezione-delle-funzioni-di-risposta-degli-step-degli-item"><span class="header-section-number">66.8</span> Non intersezione delle funzioni di risposta degli step degli item</a></li>
  <li><a href="#affidabilità" id="toc-affidabilità" class="nav-link" data-scroll-target="#affidabilità"><span class="header-section-number">66.9</span> Affidabilità</a></li>
  <li><a href="#identificazione-degli-outlier" id="toc-identificazione-degli-outlier" class="nav-link" data-scroll-target="#identificazione-degli-outlier"><span class="header-section-number">66.10</span> Identificazione degli Outlier</a></li>
  <li><a href="#considerazioni-conclusive" id="toc-considerazioni-conclusive" class="nav-link" data-scroll-target="#considerazioni-conclusive"><span class="header-section-number">66.11</span> Considerazioni conclusive</a></li>
  <li><a href="#informazioni-sullambiente-di-sviluppo" id="toc-informazioni-sullambiente-di-sviluppo" class="nav-link" data-scroll-target="#informazioni-sullambiente-di-sviluppo">Informazioni sull’Ambiente di Sviluppo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/mokken/01_logistic_regr.html">Mokken</a></li><li class="breadcrumb-item"><a href="../../chapters/mokken/03_applications.html"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Applicazione Pratica</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-mokken-applications" class="quarto-section-identifier"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Applicazione Pratica</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Prerequisiti</strong></p>
<p><strong>Concetti e Competenze Chiave</strong></p>
<p><strong>Preparazione del Notebook</strong></p>
<div id="a31d5db9" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Carica il file _common.R per impostazioni di pacchetti e opzioni</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"code"</span>, <span class="st">"_common.R"</span>) <span class="sc">|&gt;</span> <span class="fu">source</span>()</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Carica pacchetti aggiuntivi</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(TAM, mirt, mokken)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="introduzione" class="level2" data-number="66.1">
<h2 data-number="66.1" class="anchored" data-anchor-id="introduzione"><span class="header-section-number">66.1</span> Introduzione</h2>
<p>In questo capitolo, esamineremo l’applicazione pratica dei concetti e delle metodologie esplorate nel precedente capitolo, affrontando un’analisi dettagliata di un set di dati concreti. Il nostro focus è un caso di studio di grande rilevanza psicologica: l’indagine condotta dai ricercatori dell’ospedale Meyer, mirata a comprendere la capacità di coping delle famiglie di fronte alla diagnosi di una grave malattia in un figlio.</p>
<p>Questo lavoro non solo rappresenta un’opportunità per mettere in pratica le teorie e i metodi discussi, ma offre anche una finestra su questioni di vitale importanza nel campo della psicologia. Affrontare tematiche così delicate ci permette di esplorare le dinamiche familiari in situazioni di stress estremo, fornendo intuizioni preziose che possono guidare interventi psicosociali efficaci.</p>
<p>Per garantire la massima accuratezza e rilevanza dei nostri risultati, iniziamo con un’attenta preparazione e pulizia dei dati. Questo passo ci assicura che l’analisi sia condotta su informazioni ben distribuite e rappresentative, eliminando gli item con eccessiva asimmetria e curtosi.</p>
<p>Attraverso questa esplorazione approfondita, miriamo a dimostrare come le competenze metodologiche e analitiche possano essere efficacemente applicate a questioni di profondo impatto psicologico, evidenziando il potere dell’analisi statistica nel trasformare set di dati complessi in comprensioni approfondite e applicabili.</p>
</section>
<section id="importazione-dei-dati" class="level2" data-number="66.2">
<h2 data-number="66.2" class="anchored" data-anchor-id="importazione-dei-dati"><span class="header-section-number">66.2</span> Importazione dei dati</h2>
<div id="9bbb2a65" class="cell" data-tags="[&quot;hide-output&quot;]" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df_tot <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"../../data/fai_2022_11_20.rds"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>temp <span class="ot">&lt;-</span> df_tot <span class="sc">|&gt;</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(FLAG <span class="sc">==</span> <span class="st">"keep"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>temp<span class="sc">$</span>FLAG <span class="ot">&lt;-</span> <span class="cn">NULL</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Per migliorare la qualità del nostro set di dati, rimuoveremo gli item che presentano livelli eccessivi di asimmetria (skewness) e curtosi. Questo passaggio è fondamentale per garantire che i nostri dati siano ben distribuiti e rappresentativi, migliorando così l’affidabilità e la validità delle nostre analisi. Gli item con asimmetria e curtosi estreme possono infatti distorcere i risultati degli analisi statistiche e influenzare negativamente le conclusioni tratte dallo studio.</p>
<div id="bc78344e" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="4">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>items_stats <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">describe</span>(temp)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>items_skew_kurt_bad <span class="ot">&lt;-</span> items_stats <span class="sc">|&gt;</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">filter</span>(skew <span class="sc">&gt;</span> <span class="fl">2.5</span> <span class="sc">|</span> kurtosis <span class="sc">&gt;</span> <span class="fl">7.5</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">row.names</span>()</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(items_skew_kurt_bad)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "other"                  "child_birth_place"      "has_chronic_disease"   
 [4] "hospitalization_number" "emergency_care_number"  "divorce"               
 [7] "low_income"             "change_address"         "change_city"           
[10] "is_mother_italian"      "is_father_italian"      "is_father_working"     
[13] "is_child_italian"       "FAI_24"                 "FAI_32"                
[16] "FAI_52"                 "FAI_53"                 "FAI_61"                
[19] "FAI_74"                 "FAI_76"                 "FAI_77"                
[22] "FAI_138"                "FAI_152"                "FAI_174"               
[25] "FAI_175"                "FAI_182"                "FAI_193"               </code></pre>
</div>
</div>
<div id="0b56b379" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="6">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select the strings starting with "FAI_"</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>bad_fai_items <span class="ot">&lt;-</span> <span class="fu">grep</span>(<span class="st">"^FAI_"</span>, items_skew_kurt_bad, <span class="at">value =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> temp <span class="sc">|&gt;</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">!</span><span class="fu">any_of</span>(bad_fai_items))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ci concentreremo qui su un sottoinsieme di item, ovvero quelli che riguardano l’area delle caratteristiche del bambino.</p>
<div id="bc0183f8" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="7">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First subscale: items names.</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>item_subscale <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"FAI_49"</span>, <span class="st">"FAI_106"</span>, <span class="st">"FAI_60"</span>, <span class="st">"FAI_124"</span>, <span class="st">"FAI_86"</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"FAI_47"</span>, <span class="st">"FAI_121"</span>, <span class="st">"FAI_167"</span>, <span class="st">"FAI_99"</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"FAI_63"</span>, <span class="st">"FAI_168"</span>, <span class="st">"FAI_5"</span>, <span class="st">"FAI_132"</span>, <span class="st">"FAI_85"</span>, <span class="st">"FAI_81"</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"FAI_83"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># "FAI_152",  "FAI_175",</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"FAI_57"</span>, <span class="st">"FAI_91"</span>, <span class="st">"FAI_135"</span>, <span class="st">"FAI_1"</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Select only the items of this subscale.</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>subscale_data <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">all_of</span>(item_subscale))</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(subscale_data)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<style>
.list-inline {list-style: none; margin:0; padding: 0}
.list-inline>li {display: inline-block}
.list-inline>li:not(:last-child)::after {content: "\00b7"; padding: 0 .5ex}
</style>
<ol class="list-inline"><li>453</li><li>20</li></ol>
</div>
</div>
</section>
<section id="statistiche-descrittive" class="level2" data-number="66.3">
<h2 data-number="66.3" class="anchored" data-anchor-id="statistiche-descrittive"><span class="header-section-number">66.3</span> Statistiche descrittive</h2>
<p>Esaminiamo le statistiche descrittive degli item.</p>
<div id="90e938f4" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="8">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(subscale_data)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>A psych: 20 x 13</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">vars</th>
<th data-quarto-table-cell-role="th" scope="col">n</th>
<th data-quarto-table-cell-role="th" scope="col">mean</th>
<th data-quarto-table-cell-role="th" scope="col">sd</th>
<th data-quarto-table-cell-role="th" scope="col">median</th>
<th data-quarto-table-cell-role="th" scope="col">trimmed</th>
<th data-quarto-table-cell-role="th" scope="col">mad</th>
<th data-quarto-table-cell-role="th" scope="col">min</th>
<th data-quarto-table-cell-role="th" scope="col">max</th>
<th data-quarto-table-cell-role="th" scope="col">range</th>
<th data-quarto-table-cell-role="th" scope="col">skew</th>
<th data-quarto-table-cell-role="th" scope="col">kurtosis</th>
<th data-quarto-table-cell-role="th" scope="col">se</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">&lt;int&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">FAI_49</td>
<td>1</td>
<td>453</td>
<td>0.5629139</td>
<td>1.0320709</td>
<td>0</td>
<td>0.3085399</td>
<td>0.0000</td>
<td>0</td>
<td>4</td>
<td>4</td>
<td>2.0665609</td>
<td>3.6052375</td>
<td>0.04849092</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">FAI_106</td>
<td>2</td>
<td>453</td>
<td>0.6710817</td>
<td>0.9911011</td>
<td>0</td>
<td>0.4710744</td>
<td>0.0000</td>
<td>0</td>
<td>4</td>
<td>4</td>
<td>1.6036473</td>
<td>2.0835785</td>
<td>0.04656599</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">FAI_60</td>
<td>3</td>
<td>453</td>
<td>0.9403974</td>
<td>1.2169441</td>
<td>0</td>
<td>0.7272727</td>
<td>0.0000</td>
<td>0</td>
<td>4</td>
<td>4</td>
<td>1.1792903</td>
<td>0.2955897</td>
<td>0.05717702</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">FAI_124</td>
<td>4</td>
<td>453</td>
<td>1.0463576</td>
<td>1.1955175</td>
<td>1</td>
<td>0.8429752</td>
<td>1.4826</td>
<td>0</td>
<td>4</td>
<td>4</td>
<td>1.1667416</td>
<td>0.4658086</td>
<td>0.05617031</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">FAI_86</td>
<td>5</td>
<td>453</td>
<td>1.1898455</td>
<td>1.0171900</td>
<td>1</td>
<td>1.0606061</td>
<td>1.4826</td>
<td>0</td>
<td>4</td>
<td>4</td>
<td>0.9491960</td>
<td>0.6428214</td>
<td>0.04779175</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">FAI_47</td>
<td>6</td>
<td>453</td>
<td>1.6247241</td>
<td>1.1132778</td>
<td>2</td>
<td>1.5950413</td>
<td>1.4826</td>
<td>0</td>
<td>4</td>
<td>4</td>
<td>0.1994007</td>
<td>-0.7340689</td>
<td>0.05230635</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">FAI_121</td>
<td>7</td>
<td>453</td>
<td>0.4900662</td>
<td>0.7121035</td>
<td>0</td>
<td>0.3746556</td>
<td>0.0000</td>
<td>0</td>
<td>4</td>
<td>4</td>
<td>1.8321794</td>
<td>4.5725145</td>
<td>0.03345754</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">FAI_167</td>
<td>8</td>
<td>453</td>
<td>1.9072848</td>
<td>1.0306218</td>
<td>2</td>
<td>1.8815427</td>
<td>1.4826</td>
<td>0</td>
<td>4</td>
<td>4</td>
<td>0.1974188</td>
<td>-0.2695266</td>
<td>0.04842284</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">FAI_99</td>
<td>9</td>
<td>453</td>
<td>2.0618102</td>
<td>1.1543198</td>
<td>2</td>
<td>2.0220386</td>
<td>1.4826</td>
<td>0</td>
<td>4</td>
<td>4</td>
<td>0.3447637</td>
<td>-0.7883135</td>
<td>0.05423468</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">FAI_63</td>
<td>10</td>
<td>453</td>
<td>1.1501104</td>
<td>1.1615070</td>
<td>1</td>
<td>1.0192837</td>
<td>1.4826</td>
<td>0</td>
<td>4</td>
<td>4</td>
<td>0.7295382</td>
<td>-0.4985964</td>
<td>0.05457236</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">FAI_168</td>
<td>11</td>
<td>453</td>
<td>0.7748344</td>
<td>1.1298770</td>
<td>0</td>
<td>0.5399449</td>
<td>0.0000</td>
<td>0</td>
<td>4</td>
<td>4</td>
<td>1.4492317</td>
<td>1.1504289</td>
<td>0.05308625</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">FAI_5</td>
<td>12</td>
<td>453</td>
<td>1.0132450</td>
<td>1.1805209</td>
<td>1</td>
<td>0.8264463</td>
<td>1.4826</td>
<td>0</td>
<td>4</td>
<td>4</td>
<td>1.0371531</td>
<td>0.1238107</td>
<td>0.05546571</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">FAI_132</td>
<td>13</td>
<td>453</td>
<td>1.4238411</td>
<td>1.2360930</td>
<td>1</td>
<td>1.3002755</td>
<td>1.4826</td>
<td>0</td>
<td>4</td>
<td>4</td>
<td>0.5953586</td>
<td>-0.6157883</td>
<td>0.05807672</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">FAI_85</td>
<td>14</td>
<td>453</td>
<td>1.3311258</td>
<td>0.9027136</td>
<td>1</td>
<td>1.3002755</td>
<td>1.4826</td>
<td>0</td>
<td>4</td>
<td>4</td>
<td>0.2930726</td>
<td>-0.1115428</td>
<td>0.04241319</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">FAI_81</td>
<td>15</td>
<td>453</td>
<td>1.7969095</td>
<td>1.2685052</td>
<td>2</td>
<td>1.7465565</td>
<td>1.4826</td>
<td>0</td>
<td>4</td>
<td>4</td>
<td>0.2930069</td>
<td>-1.0004309</td>
<td>0.05959957</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">FAI_83</td>
<td>16</td>
<td>453</td>
<td>1.1986755</td>
<td>1.1825793</td>
<td>1</td>
<td>1.0468320</td>
<td>1.4826</td>
<td>0</td>
<td>4</td>
<td>4</td>
<td>0.8458362</td>
<td>-0.1601818</td>
<td>0.05556242</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">FAI_57</td>
<td>17</td>
<td>453</td>
<td>0.3863135</td>
<td>0.7123983</td>
<td>0</td>
<td>0.2341598</td>
<td>0.0000</td>
<td>0</td>
<td>4</td>
<td>4</td>
<td>2.2165283</td>
<td>5.6437160</td>
<td>0.03347139</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">FAI_91</td>
<td>18</td>
<td>453</td>
<td>0.5320088</td>
<td>0.9298228</td>
<td>0</td>
<td>0.3057851</td>
<td>0.0000</td>
<td>0</td>
<td>4</td>
<td>4</td>
<td>2.1393688</td>
<td>4.4338138</td>
<td>0.04368689</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">FAI_135</td>
<td>19</td>
<td>453</td>
<td>0.4039735</td>
<td>0.7686801</td>
<td>0</td>
<td>0.2231405</td>
<td>0.0000</td>
<td>0</td>
<td>4</td>
<td>4</td>
<td>2.2914674</td>
<td>5.8874641</td>
<td>0.03611574</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">FAI_1</td>
<td>20</td>
<td>453</td>
<td>0.4547461</td>
<td>0.7530503</td>
<td>0</td>
<td>0.2892562</td>
<td>0.0000</td>
<td>0</td>
<td>4</td>
<td>4</td>
<td>1.8594704</td>
<td>3.7153232</td>
<td>0.03538139</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Esaminiamo la distribuzione del punteggio totale.</p>
<div id="08742407" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="9">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>scores <span class="ot">&lt;-</span> <span class="fu">apply</span>(subscale_data, <span class="dv">1</span>, sum)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(scores)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-8-output-1.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="automated-item-selection-procedure-aisp" class="level2" data-number="66.4">
<h2 data-number="66.4" class="anchored" data-anchor-id="automated-item-selection-procedure-aisp"><span class="header-section-number">66.4</span> Automated Item Selection Procedure (AISP)</h2>
<p>Il primo passo nell’Analisi delle Scale Mokken (MSA) consiste nell’esecuzione dell’<em>Automated Item Selection Procedure</em> (AISP). Come precedentemente discusso, questa analisi ricerca insiemi di item (scale) che si conformano al modello di omogeneità monotona. Similmente all’analisi fattoriale esplorativa, l’AISP è un metodo per suddividere i dati in diverse sottoscale che soddisfano i criteri della MSA, includendo possibilmente anche l’individuazione di eventuali item non scalabili. Per eseguire la AISP, è necessario eseguire il codice seguente.</p>
<div id="9a31eb9e" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="10">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>subscale_data <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(subscale_data)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>scale <span class="ot">&lt;-</span> <span class="fu">aisp</span>(subscale_data, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(scale)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        0.3
FAI_49    1
FAI_106   1
FAI_60    1
FAI_124   1
FAI_86    0
FAI_47    2
FAI_121   0
FAI_167   0
FAI_99    0
FAI_63    2
FAI_168   0
FAI_5     1
FAI_132   2
FAI_85    2
FAI_81    1
FAI_83    1
FAI_57    2
FAI_91    0
FAI_135   0
FAI_1     0</code></pre>
</div>
</div>
<p>Nell’output precedente, <code>FAI_*</code> sono le etichette degli item considerati. Il valore .30 in alto indica il limite inferiore del coefficiente di scalabilità per la costruzione delle scale. ‘1’ indica che l’item appartiene alla scala 1 e 2 significa che l’item appartiene alla scala 2. ‘0’ indica che l’item non è scalabile. Dei 20 item di questa scala, sette item formano la scala 1 mentre altri cinque item formano la scala 2. Sette item risultano non scalabili.</p>
<p>È possibile modificare sia il limite inferiore c (il limite inferiore predefinito è .30) sia il livello di alpha, che di default è .05. Per esempio:</p>
<div id="b16805e4" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="11">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>scale <span class="ot">&lt;-</span> <span class="fu">aisp</span>(subscale_data, <span class="at">lowerbound =</span> <span class="fl">0.4</span>, <span class="at">alpha =</span> <span class="fl">0.1</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(scale)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        0.4
FAI_49    1
FAI_106   1
FAI_60    1
FAI_124   1
FAI_86    0
FAI_47    0
FAI_121   0
FAI_167   0
FAI_99    0
FAI_63    3
FAI_168   0
FAI_5     2
FAI_132   0
FAI_85    0
FAI_81    2
FAI_83    2
FAI_57    3
FAI_91    0
FAI_135   0
FAI_1     0</code></pre>
</div>
</div>
<p>Si noti che modificare il valore predefinito di c cambia la struttura della scala. Sijtsma e van der Ark (2017) hanno mostrato che il valore predefinito di .30 è quello che si dimostra più utile nella maggior parte delle applicazioni pratiche. Tuttavia, raccomandano di eseguire l’AISP 12 volte con c=0, .05, .10, .15, .20, .25, .30, .35, .40, .45, .50 e .55, così da potere esaminare le seguenti condizioni:</p>
<ol type="1">
<li><p>Nei dati unidimensionali, all’aumentare di c, si trova successivamente (a) la maggior parte o tutti gli item in una scala; (b) una scala più piccola; e (c) una o poche scale piccole e diversi item non scalabili. Viene raccomandato di prendere il risultato della fase (a) come finale.</p></li>
<li><p>Nei dati multidimensionali, all’aumentare di c, si trova successivamente (a) la maggior parte o tutti gli item in una scala; (b) due o più scale; e (c) due o più scale più piccole e diversi item non scalabili. Prendere il risultato della fase (b) come finale.</p></li>
</ol>
<p>La decisione finale sulla struttura dei dati dovrebbe essere presa dal ricercatore sulla base di considerazioni teoriche e non sono statistiche.</p>
<p>Per eseguire l’AISP con molteplici limiti inferiori, possiamo usare l’istruzione seguente:</p>
<div id="726bce95" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="12">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aisp</span>(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    subscale_data, </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">lowerbound =</span> <span class="fu">c</span>(.<span class="dv">05</span>, .<span class="dv">10</span>, .<span class="dv">15</span>, .<span class="dv">20</span>, .<span class="dv">25</span>, .<span class="dv">30</span>, .<span class="dv">35</span>, .<span class="dv">40</span>, .<span class="dv">45</span>, .<span class="dv">50</span>, .<span class="dv">55</span>), </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">verbose =</span> <span class="cn">FALSE</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>A matrix: 20 x 11 of type dbl</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">0.05</th>
<th data-quarto-table-cell-role="th" scope="col">0.1</th>
<th data-quarto-table-cell-role="th" scope="col">0.15</th>
<th data-quarto-table-cell-role="th" scope="col">0.2</th>
<th data-quarto-table-cell-role="th" scope="col">0.25</th>
<th data-quarto-table-cell-role="th" scope="col">0.3</th>
<th data-quarto-table-cell-role="th" scope="col">0.35</th>
<th data-quarto-table-cell-role="th" scope="col">0.4</th>
<th data-quarto-table-cell-role="th" scope="col">0.45</th>
<th data-quarto-table-cell-role="th" scope="col">0.5</th>
<th data-quarto-table-cell-role="th" scope="col">0.55</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">FAI_49</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">FAI_106</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">FAI_60</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">FAI_124</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">FAI_86</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">FAI_47</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">FAI_121</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">FAI_167</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">FAI_99</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">FAI_63</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>3</td>
<td>3</td>
<td>3</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">FAI_168</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>3</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">FAI_5</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">FAI_132</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>2</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">FAI_85</td>
<td>2</td>
<td>2</td>
<td>0</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">FAI_81</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">FAI_83</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">FAI_57</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>3</td>
<td>3</td>
<td>3</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">FAI_91</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>3</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">FAI_135</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">FAI_1</td>
<td>2</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Per eseguire un’analisi della dimensionalità utilizzando un metodo diverso, ovvero l’algoritmo genetico (Straat, van der Ark &amp; Sijtsma, 2013), si può utilizzare il seguente codice:</p>
<div id="e0595519" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="13">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>scale <span class="ot">&lt;-</span> <span class="fu">aisp</span>(subscale_data, <span class="at">search =</span> <span class="st">"ga"</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(scale)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        0.3
FAI_49    1
FAI_106   1
FAI_60    1
FAI_124   1
FAI_86    0
FAI_47    2
FAI_121   0
FAI_167   0
FAI_99    0
FAI_63    2
FAI_168   0
FAI_5     1
FAI_132   2
FAI_85    2
FAI_81    1
FAI_83    1
FAI_57    2
FAI_91    0
FAI_135   0
FAI_1     0</code></pre>
</div>
</div>
<p>I risultati dell’algoritmo genetico sono equivalenti a quelli ottenuti utilizzando il limite inferiore raccomandato di 0.3.</p>
<p>I risultati dell’analisi della dimensionalità ottenuti tramite l’AISP e l’algoritmo genetico (GA) dovrebbero essere replicabili in altri campioni. Pertanto, nelle procedure AISP e GA, la dimensione del campione è un fattore critico. Sijtsma e Molenaar (2002) affermano che l’AISP richiede almeno 100 partecipanti. Tuttavia, in studi basati su simulazioni di Monte Carlo, Straat, van der Ark e Sijtsma (2014) hanno dimostrato che sia l’AISP sia il GA necessitano di un campione compreso tra 250 e 500 partecipanti quando la qualità degli item (ovvero la loro capacità discriminante) è elevata, e tra 1250 e 1750 partecipanti quando la qualità degli item è scarsa.</p>
<p>Possiamo selezionare gli item della scala 1 individuata dalla AISP nel modo seguente.</p>
<div id="ab2afab5" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="14">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>aisp.lb <span class="ot">&lt;-</span> <span class="fu">aisp</span>(subscale_data, <span class="at">lowerbound =</span> .<span class="dv">3</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>good_items <span class="ot">&lt;-</span> subscale_data[, aisp.lb <span class="sc">==</span> <span class="dv">1</span>]</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(good_items) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "FAI_49"  "FAI_106" "FAI_60"  "FAI_124" "FAI_5"   "FAI_81"  "FAI_83" </code></pre>
</div>
</div>
</section>
<section id="scalability-coefficients" class="level2" data-number="66.5">
<h2 data-number="66.5" class="anchored" data-anchor-id="scalability-coefficients"><span class="header-section-number">66.5</span> Scalability Coefficients</h2>
<p>Il codice seguente ritorna i valori <span class="math inline">\(H_{ij}\)</span>, <span class="math inline">\(H_j\)</span>, e <span class="math inline">\(H\)</span>. Nelle parentesi tonde sono riportati gli errori standard.</p>
<div id="f15915a8" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="15">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>scal_coef <span class="ot">&lt;-</span> <span class="fu">coefH</span>(good_items, <span class="at">se =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>scal_coef <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Hij
        FAI_49  se      FAI_106 se      FAI_60  se      FAI_124 se      FAI_5  
FAI_49                   0.561  (0.057)  0.608  (0.054)  0.601  (0.048)  0.212 
FAI_106  0.561  (0.057)                  0.617  (0.042)  0.722  (0.039)  0.317 
FAI_60   0.608  (0.054)  0.617  (0.042)                  0.688  (0.037)  0.280 
FAI_124  0.601  (0.048)  0.722  (0.039)  0.688  (0.037)                  0.288 
FAI_5    0.212  (0.056)  0.317  (0.055)  0.280  (0.052)  0.288  (0.052)        
FAI_81   0.254  (0.060)  0.354  (0.056)  0.324  (0.050)  0.381  (0.053)  0.413 
FAI_83   0.223  (0.057)  0.381  (0.056)  0.430  (0.047)  0.387  (0.048)  0.409 
        se      FAI_81  se      FAI_83  se     
FAI_49  (0.056)  0.254  (0.060)  0.223  (0.057)
FAI_106 (0.055)  0.354  (0.056)  0.381  (0.056)
FAI_60  (0.052)  0.324  (0.050)  0.430  (0.047)
FAI_124 (0.052)  0.381  (0.053)  0.387  (0.048)
FAI_5            0.413  (0.049)  0.409  (0.048)
FAI_81  (0.049)                  0.551  (0.041)
FAI_83  (0.048)  0.551  (0.041)                

$Hi
        Item H  se     
FAI_49    0.410 (0.039)
FAI_106   0.493 (0.032)
FAI_60    0.484 (0.029)
FAI_124   0.502 (0.029)
FAI_5     0.323 (0.037)
FAI_81    0.386 (0.034)
FAI_83    0.404 (0.032)

$H
Scale H      se 
  0.428 (0.026) 

$Hij
        FAI_49  se      FAI_106 se      FAI_60  se      FAI_124 se      FAI_5  
FAI_49                   0.561  (0.057)  0.608  (0.054)  0.601  (0.048)  0.212 
FAI_106  0.561  (0.057)                  0.617  (0.042)  0.722  (0.039)  0.317 
FAI_60   0.608  (0.054)  0.617  (0.042)                  0.688  (0.037)  0.280 
FAI_124  0.601  (0.048)  0.722  (0.039)  0.688  (0.037)                  0.288 
FAI_5    0.212  (0.056)  0.317  (0.055)  0.280  (0.052)  0.288  (0.052)        
FAI_81   0.254  (0.060)  0.354  (0.056)  0.324  (0.050)  0.381  (0.053)  0.413 
FAI_83   0.223  (0.057)  0.381  (0.056)  0.430  (0.047)  0.387  (0.048)  0.409 
        se      FAI_81  se      FAI_83  se     
FAI_49  (0.056)  0.254  (0.060)  0.223  (0.057)
FAI_106 (0.055)  0.354  (0.056)  0.381  (0.056)
FAI_60  (0.052)  0.324  (0.050)  0.430  (0.047)
FAI_124 (0.052)  0.381  (0.053)  0.387  (0.048)
FAI_5            0.413  (0.049)  0.409  (0.048)
FAI_81  (0.049)                  0.551  (0.041)
FAI_83  (0.048)  0.551  (0.041)                

$Hi
        Item H  se     
FAI_49    0.410 (0.039)
FAI_106   0.493 (0.032)
FAI_60    0.484 (0.029)
FAI_124   0.502 (0.029)
FAI_5     0.323 (0.037)
FAI_81    0.386 (0.034)
FAI_83    0.404 (0.032)

$H
Scale H      se 
  0.428 (0.026) 

$covHij
               [,1]          [,2]          [,3]          [,4]          [,5]
 [1,]  3.256522e-03  1.972567e-03  1.673569e-03  6.850269e-04  0.0009303758
 [2,]  1.972567e-03  2.872632e-03  1.379662e-03  5.619181e-04  0.0007468355
 [3,]  1.673569e-03  1.379662e-03  2.324218e-03  7.130034e-04  0.0009755748
 [4,]  6.850269e-04  5.619181e-04  7.130034e-04  3.132843e-03  0.0014577910
 [5,]  9.303758e-04  7.468355e-04  9.755748e-04  1.457791e-03  0.0035999264
 [6,]  1.176059e-03  1.372448e-03  1.121228e-03  1.001618e-03  0.0007258314
 [7,]  1.143505e-03  6.796210e-04  6.075535e-04  3.611057e-04  0.0005325189
 [8,]  9.205140e-04  4.625925e-04  3.783489e-04  2.484545e-04  0.0003248843
 [9,]  1.281966e-04  2.342448e-04  1.519768e-04  1.410060e-03  0.0006882034
[10,]  4.801610e-05  3.000776e-04  1.972389e-04  6.442391e-04  0.0016398978
[11,]  6.330714e-05  1.877564e-04  2.994296e-04  4.332023e-04  0.0002887708
[12,]  7.230668e-04  6.943860e-04  7.140702e-04  2.950943e-04  0.0003590450
[13,]  3.194478e-04  4.391644e-04  3.080059e-04  1.808926e-03  0.0006665414
[14,]  3.310593e-04  2.500548e-04  2.591961e-04  5.841647e-04  0.0016242307
[15,] -2.626538e-05  1.143234e-04  3.461109e-04  5.949934e-04  0.0002896028
[16,]  1.885976e-04  2.599218e-04  3.321093e-04  1.573800e-03  0.0006905796
[17,]  1.132431e-04  1.511628e-04  5.240330e-05  5.614512e-04  0.0016082483
[18,]  2.425335e-04  4.564482e-04  2.708591e-04  4.202745e-04  0.0002271944
[19,]  6.016676e-05 -5.677038e-08  6.439974e-05  4.080167e-04  0.0003000318
[20,] -6.323510e-05  2.770648e-04  9.115472e-05  4.564269e-04 -0.0000318649
[21,] -1.452389e-04  4.045822e-05 -1.410212e-04 -8.502939e-05  0.0001437967
               [,6]          [,7]          [,8]         [,9]        [,10]
 [1,]  1.176059e-03  1.143505e-03  9.205140e-04 1.281966e-04 0.0000480161
 [2,]  1.372448e-03  6.796210e-04  4.625925e-04 2.342448e-04 0.0003000776
 [3,]  1.121228e-03  6.075535e-04  3.783489e-04 1.519768e-04 0.0001972389
 [4,]  1.001618e-03  3.611057e-04  2.484545e-04 1.410060e-03 0.0006442391
 [5,]  7.258314e-04  5.325189e-04  3.248843e-04 6.882034e-04 0.0016398978
 [6,]  3.235792e-03  3.934074e-04  4.943276e-04 4.792224e-04 0.0002711309
 [7,]  3.934074e-04  1.765623e-03  7.886910e-04 3.994963e-04 0.0003576934
 [8,]  4.943276e-04  7.886910e-04  1.518517e-03 3.437684e-04 0.0004289051
 [9,]  4.792224e-04  3.994963e-04  3.437684e-04 3.075515e-03 0.0011512604
[10,]  2.711309e-04  3.576934e-04  4.289051e-04 1.151260e-03 0.0030881212
[11,]  1.580928e-03  7.872979e-04  6.366403e-04 1.439675e-03 0.0011535909
[12,]  5.881401e-04  7.514867e-04  4.972229e-04 5.983421e-05 0.0002224072
[13,]  7.426056e-04  4.490709e-04  9.903078e-05 1.401373e-03 0.0005654204
[14,]  3.670699e-04  4.022907e-04  2.546547e-04 5.617317e-04 0.0015767924
[15,]  1.394333e-03  3.075009e-04  2.545034e-04 4.954782e-04 0.0003710759
[16,]  5.291520e-04  1.750076e-04  4.106679e-04 1.618941e-03 0.0007001615
[17,]  2.446268e-04  2.201295e-04  2.059815e-04 6.070280e-04 0.0017308946
[18,]  1.440363e-03  3.706182e-04  4.282926e-04 4.721104e-04 0.0005205689
[19,] -2.408574e-05  7.725707e-05  8.859144e-05 7.086189e-04 0.0004992864
[20,]  6.059513e-04  6.986203e-05 -5.566603e-05 8.917753e-04 0.0004276745
[21,]  2.480873e-04 -1.299639e-05 -3.392847e-05 3.442378e-04 0.0005256114
             [,11]         [,12]        [,13]        [,14]         [,15]
 [1,] 6.330714e-05  7.230668e-04 3.194478e-04 0.0003310593 -2.626538e-05
 [2,] 1.877564e-04  6.943860e-04 4.391644e-04 0.0002500548  1.143234e-04
 [3,] 2.994296e-04  7.140702e-04 3.080059e-04 0.0002591961  3.461109e-04
 [4,] 4.332023e-04  2.950943e-04 1.808926e-03 0.0005841647  5.949934e-04
 [5,] 2.887708e-04  3.590450e-04 6.665414e-04 0.0016242307  2.896028e-04
 [6,] 1.580928e-03  5.881401e-04 7.426056e-04 0.0003670699  1.394333e-03
 [7,] 7.872979e-04  7.514867e-04 4.490709e-04 0.0004022907  3.075009e-04
 [8,] 6.366403e-04  4.972229e-04 9.903078e-05 0.0002546547  2.545034e-04
 [9,] 1.439675e-03  5.983421e-05 1.401373e-03 0.0005617317  4.954782e-04
[10,] 1.153591e-03  2.224072e-04 5.654204e-04 0.0015767924  3.710759e-04
[11,] 3.100653e-03  3.797460e-04 5.558660e-04 0.0004499206  1.388343e-03
[12,] 3.797460e-04  1.353425e-03 3.361125e-04 0.0003599263  3.711701e-04
[13,] 5.558660e-04  3.361125e-04 2.679508e-03 0.0010149171  9.133291e-04
[14,] 4.499206e-04  3.599263e-04 1.014917e-03 0.0025074061  7.814797e-04
[15,] 1.388343e-03  3.711701e-04 9.133291e-04 0.0007814797  2.239613e-03
[16,] 5.671980e-04  3.549025e-04 1.809069e-03 0.0006726168  7.152364e-04
[17,] 5.230923e-04  8.662901e-05 5.994210e-04 0.0016280518  4.484829e-04
[18,] 1.453794e-03  3.694086e-04 6.818643e-04 0.0005001348  1.390561e-03
[19,] 3.721344e-04  8.121422e-05 6.065452e-04 0.0004767595  4.240890e-05
[20,] 6.949490e-04  2.048871e-04 8.608315e-04 0.0001955560  4.525888e-04
[21,] 3.341346e-04 -7.180751e-05 6.989798e-05 0.0004952616  1.117222e-04
             [,16]        [,17]        [,18]         [,19]         [,20]
 [1,] 1.885976e-04 1.132431e-04 0.0002425335  6.016676e-05 -6.323510e-05
 [2,] 2.599218e-04 1.511628e-04 0.0004564482 -5.677038e-08  2.770648e-04
 [3,] 3.321093e-04 5.240330e-05 0.0002708591  6.439974e-05  9.115472e-05
 [4,] 1.573800e-03 5.614512e-04 0.0004202745  4.080167e-04  4.564269e-04
 [5,] 6.905796e-04 1.608248e-03 0.0002271944  3.000318e-04 -3.186490e-05
 [6,] 5.291520e-04 2.446268e-04 0.0014403628 -2.408574e-05  6.059513e-04
 [7,] 1.750076e-04 2.201295e-04 0.0003706182  7.725707e-05  6.986203e-05
 [8,] 4.106679e-04 2.059815e-04 0.0004282926  8.859144e-05 -5.566603e-05
 [9,] 1.618941e-03 6.070280e-04 0.0004721104  7.086189e-04  8.917753e-04
[10,] 7.001615e-04 1.730895e-03 0.0005205689  4.992864e-04  4.276745e-04
[11,] 5.671980e-04 5.230923e-04 0.0014537943  3.721344e-04  6.949490e-04
[12,] 3.549025e-04 8.662901e-05 0.0003694086  8.121422e-05  2.048871e-04
[13,] 1.809069e-03 5.994210e-04 0.0006818643  6.065452e-04  8.608315e-04
[14,] 6.726168e-04 1.628052e-03 0.0005001348  4.767595e-04  1.955560e-04
[15,] 7.152364e-04 4.484829e-04 0.0013905614  4.240890e-05  4.525888e-04
[16,] 2.714269e-03 9.497205e-04 0.0009504702  8.252786e-04  9.374942e-04
[17,] 9.497205e-04 2.781060e-03 0.0011345975  3.571314e-04  1.293712e-04
[18,] 9.504702e-04 1.134597e-03 0.0023072463  5.416910e-05  4.234757e-04
[19,] 8.252786e-04 3.571314e-04 0.0000541691  2.416128e-03  1.043338e-03
[20,] 9.374942e-04 1.293712e-04 0.0004234757  1.043338e-03  2.288321e-03
[21,] 8.680063e-05 4.749021e-04 0.0002621942  4.096861e-04  5.441687e-04
              [,21]
 [1,] -1.452389e-04
 [2,]  4.045822e-05
 [3,] -1.410212e-04
 [4,] -8.502939e-05
 [5,]  1.437967e-04
 [6,]  2.480873e-04
 [7,] -1.299639e-05
 [8,] -3.392847e-05
 [9,]  3.442378e-04
[10,]  5.256114e-04
[11,]  3.341346e-04
[12,] -7.180751e-05
[13,]  6.989798e-05
[14,]  4.952616e-04
[15,]  1.117222e-04
[16,]  8.680063e-05
[17,]  4.749021e-04
[18,]  2.621942e-04
[19,]  4.096861e-04
[20,]  5.441687e-04
[21,]  1.663587e-03

$covHi
             [,1]         [,2]         [,3]         [,4]         [,5]
[1,] 0.0014980127 0.0007465455 0.0007793789 0.0007134071 0.0005453263
[2,] 0.0007465455 0.0010331381 0.0006387837 0.0006398164 0.0005589013
[3,] 0.0007793789 0.0006387837 0.0008679826 0.0006400363 0.0005827344
[4,] 0.0007134071 0.0006398164 0.0006400363 0.0008379947 0.0005613310
[5,] 0.0005453263 0.0005589013 0.0005827344 0.0005613310 0.0013482139
[6,] 0.0004596982 0.0005289703 0.0005019538 0.0005248655 0.0006078101
[7,] 0.0004856933 0.0005415021 0.0005393324 0.0005410202 0.0005874255
             [,6]         [,7]
[1,] 0.0004596982 0.0004856933
[2,] 0.0005289703 0.0005415021
[3,] 0.0005019538 0.0005393324
[4,] 0.0005248655 0.0005410202
[5,] 0.0006078101 0.0005874255
[6,] 0.0011488908 0.0004461349
[7,] 0.0004461349 0.0010515910

$covH
             [,1]
[1,] 0.0006624019
</code></pre>
</div>
</div>
<p>Possiamo interpretare i coefficienti di scalabilità nel modo seguente.</p>
<ol type="1">
<li><p><strong>Coefficiente di Scalabilità tra Coppie di Item (Hij):</strong> Per ogni coppia di item (i, j), il coefficiente <span class="math inline">\(H_{ij}\)</span> valuta l’efficacia con cui questi due item riflettono la variabile latente. Un coefficiente <span class="math inline">\(H_{ij}\)</span> positivo per coppie di item appartenenti alla stessa scala di Mokken indica che questi item sono coerenti e misurano efficacemente la stessa variabile latente. Matematicamente, <span class="math inline">\(H_{ij}\)</span> è definito per ogni coppia di item i e j, dove i, j = 1, …, J.</p></li>
<li><p><strong>Coeffiente di Scalabilità dell’Item (Hj):</strong> Il coefficiente <span class="math inline">\(H_{j}\)</span> di un singolo item è analogo ai parametri di discriminazione nei modelli IRT parametrici. Esprime l’efficacia con cui un item distingue tra individui a diversi livelli della variabile latente. Per essere considerato efficace, <span class="math inline">\(H_{j}\)</span> dovrebbe superare un certo limite inferiore, generalmente stabilito a c &gt; 0.3.</p></li>
<li><p><strong>Coefficiente di Scalabilità del Test (H):</strong> H rappresenta la scalabilità complessiva dell’intero insieme di item. L’interpretazione di H segue le seguenti soglie euristiche:</p>
<ul>
<li><strong>Debole:</strong> se 0.3 ≤ H &lt; 0.4.</li>
<li><strong>Moderato:</strong> se 0.4 ≤ H &lt; 0.5.</li>
<li><strong>Forte:</strong> se H &gt; 0.5.</li>
</ul>
<p>Questi valori indicano la forza con cui l’insieme di item misura la variabile latente. I coefficienti di scalabilità degli item forniscono indicazioni sulla discriminazione degli item e sulla loro aderenza al modello di omogeneità monotona. Item con bassa discriminazione non contribuiscono a un ordinamento affidabile degli esaminandi e dovrebbero essere scartati.</p></li>
</ol>
<p>Secondo Sijtsma e Molenaar (2002), le assunzioni di unidimensionalità, indipendenza locale e monotonicità implicano le seguenti restrizioni sui coefficienti di scalabilità: - 0 ≤ <span class="math inline">\(H_{ij}\)</span> ≤ 1, per tutte le coppie di item i ≠ j. - 0 ≤ <span class="math inline">\(H_{j}\)</span> ≤ 1, per tutti gli item j. - 0 ≤ <span class="math inline">\(H\)</span> ≤ 1, per l’intero insieme di item.</p>
<p>I coefficienti di scalabilità sono fondamentali per valutare quanto efficacemente un insieme di item lavori insieme per misurare una variabile latente. Valori alti di <span class="math inline">\(H\)</span> suggeriscono che l’insieme di item è fortemente correlato e misura in modo affidabile la variabile latente, garantendo che l’analisi con la MSA sia valida e affidabile.</p>
<p>È possibile ottenere il numero di valori negativi <span class="math inline">\(H_{ij}\)</span> per ciascun item usando il codice seguente.</p>
<div id="2008a3c9" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="16">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>scal_coef <span class="ot">&lt;-</span> <span class="fu">coefH</span>(good_items, <span class="at">se =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>Hij</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(scal_coef, <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">sum</span>(x <span class="sc">&lt;</span> <span class="dv">0</span>)) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Hij
           FAI_49   FAI_106    FAI_60   FAI_124     FAI_5    FAI_81    FAI_83
FAI_49  1.0000000 0.5613569 0.6075009 0.6005396 0.2118286 0.2539023 0.2229846
FAI_106 0.5613569 1.0000000 0.6172766 0.7223965 0.3168352 0.3539449 0.3812326
FAI_60  0.6075009 0.6172766 1.0000000 0.6879216 0.2795178 0.3243635 0.4303254
FAI_124 0.6005396 0.7223965 0.6879216 1.0000000 0.2879511 0.3813744 0.3866023
FAI_5   0.2118286 0.3168352 0.2795178 0.2879511 1.0000000 0.4132827 0.4085199
FAI_81  0.2539023 0.3539449 0.3243635 0.3813744 0.4132827 1.0000000 0.5506000
FAI_83  0.2229846 0.3812326 0.4303254 0.3866023 0.4085199 0.5506000 1.0000000

$Hi
   FAI_49   FAI_106    FAI_60   FAI_124     FAI_5    FAI_81    FAI_83 
0.4096841 0.4929127 0.4838063 0.5019022 0.3231299 0.3862103 0.4040312 

$H
[1] 0.4279251

 FAI_49 FAI_106  FAI_60 FAI_124   FAI_5  FAI_81  FAI_83 
      0       0       0       0       0       0       0 </code></pre>
</div>
</div>
<p>L’istruzione seguente esegue la procedura frequentista del test di ipotesi, con l’ipotesi alternativa che i coefficienti di scalabilità sono maggiori di zero. Il test è unidirezionale, dunque il valore soglia della statistica <span class="math inline">\(z\)</span> è 1.65.</p>
<div id="7c901357" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="17">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coefZ</span>(good_items) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Zij
           FAI_49   FAI_106    FAI_60   FAI_124    FAI_5    FAI_81    FAI_83
FAI_49   0.000000 11.122254 11.766708 11.519386 4.077595  4.303706  4.213676
FAI_106 11.122254  0.000000 12.328013 14.049032 6.189922  6.313023  7.368202
FAI_60  11.766708 12.328013  0.000000 14.039308 5.741312  6.231554  8.542324
FAI_124 11.519386 14.049032 14.039308  0.000000 5.889676  7.265907  7.779304
FAI_5    4.077595  6.189922  5.741312  5.889676 0.000000  8.141997  8.214378
FAI_81   4.303706  6.313023  6.231554  7.265907 8.141997  0.000000 10.794877
FAI_83   4.213676  7.368202  8.542324  7.779304 8.214378 10.794877  0.000000

$Zi
  FAI_49  FAI_106   FAI_60  FAI_124    FAI_5   FAI_81   FAI_83 
18.87934 23.25525 23.49005 24.24297 15.73678 17.72590 19.40083 

$Z
[1] 37.97973
</code></pre>
</div>
</div>
<p>Nel caso presente, il test indica che i coefficienti di scalabilità di tutti gli item, sia considerati singolarmente sia considerati a coppie, sono maggiori di zero. Lo stesso si può dire per il coefficiente di scalabilità della scala nel suo complesso.</p>
</section>
<section id="monotonicità" class="level2" data-number="66.6">
<h2 data-number="66.6" class="anchored" data-anchor-id="monotonicità"><span class="header-section-number">66.6</span> Monotonicità</h2>
<p>Come spiegato in precedenza, la monotonicità è un’importante assunzione della MSA. La probabilità di una risposta corretta dovrebbe aumentare con θ. La monotonicità può essere esaminata con il seguente codice:</p>
<div id="49baf11e" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="18">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>monoton <span class="ot">&lt;-</span> <span class="fu">check.monotonicity</span>(good_items)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(monoton) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        ItemH #ac #vi #vi/#ac maxvi sum sum/#ac zmax #zsig crit
FAI_49   0.41  20   0       0     0   0       0    0     0    0
FAI_106  0.49  12   0       0     0   0       0    0     0    0
FAI_60   0.48  18   0       0     0   0       0    0     0    0
FAI_124  0.50  21   0       0     0   0       0    0     0    0
FAI_5    0.32  24   0       0     0   0       0    0     0    0
FAI_81   0.39  24   0       0     0   0       0    0     0    0
FAI_83   0.40  21   0       0     0   0       0    0     0    0</code></pre>
</div>
</div>
<p>Ogni riga dell’output rappresenta un item (ad esempio, FAI_49, FAI_106, ecc.). La spiegazione delle colonne è la seguente:</p>
<ol type="1">
<li><p><strong>ItemH</strong>: Il coefficiente H per ogni item, che misura l’omogeneità dell’item. Un valore più alto indica una maggiore omogeneità. Nelle scale di Mokken, si cercano generalmente valori superiori a 0.3.</p></li>
<li><p><strong>#ac (Active pairs)</strong>: Il numero di coppie attive, ovvero coppie di risposte che contribuiscono alla stima dell’H.</p></li>
<li><p><strong>#vi (Violations)</strong>: Il numero di violazioni della monotonicità. La monotonicità implica che, man mano che aumenta il punteggio totale del test, la probabilità di una risposta positiva all’item non diminuisce.</p></li>
<li><p><strong>#vi/#ac</strong>: Il rapporto tra il numero di violazioni e il numero di coppie attive.</p></li>
<li><p><strong>maxvi (Maximum violation)</strong>: La massima violazione osservata.</p></li>
<li><p><strong>sum (Sum of violation size)</strong>: La somma delle dimensioni delle violazioni.</p></li>
<li><p><strong>sum/#ac</strong>: Il rapporto tra la somma delle dimensioni delle violazioni e il numero di coppie attive.</p></li>
<li><p><strong>zmax</strong>: Il valore massimo della statistica Z per le violazioni.</p></li>
<li><p><strong>#zsig (Number of significant Z)</strong>: Numero di statistiche Z significative.</p></li>
<li><p><strong>crit</strong>: Un criterio per giudicare se le violazioni sono problematiche.</p></li>
</ol>
<p>Nel caso presente, sembra che non ci siano violazioni della monotonicità per nessuno degli item elencati. Questo significa che per questi item, all’aumentare del punteggio totale, non si osserva una diminuzione della probabilità di una risposta positiva, mantenendo quindi una buona coerenza interna e validità per la scala.</p>
<p>Un grafico della monotonicità per una coppia di item si ottiene nel modo seguente.</p>
<div id="c037cc2a" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="19">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">check.monotonicity</span>(good_items), <span class="at">item =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-18-output-1.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-18-output-2.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>La figura di questo esempio illustra i grafici di monotonicità per gli Item 49 e 106. Il grafico è diviso in due pannelli. Il pannello sul lato sinistro mostra le Funzioni di Risposta del Passaggio dell’Item (ISRFs), mentre il pannello sul lato destro mostra la Funzione di Risposta all’Item (IRF) complessiva per ciascun item. Il grafico evidenzia che sia l’IRF sia le ISRFs sono sempre non decrescenti per l’item 49; per l’item 106, invece, si osserva una piccola violazione della monotonicità.</p>
<p>Se esaminiamo tutti gli item dell’area relativa alle caratteristiche del bambino (non solo quelli selezionati dalla procedura AISP) notiamo come, per alcuni item, si osserva un numero di violazioni maggiore di zero.</p>
<div id="ab6c8cf7" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="20">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>monoton2 <span class="ot">&lt;-</span> <span class="fu">check.monotonicity</span>(subscale_data)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(monoton2) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        ItemH #ac #vi #vi/#ac maxvi  sum sum/#ac zmax #zsig crit
FAI_49   0.25  24   0    0.00  0.00 0.00  0.0000 0.00     0    0
FAI_106  0.30  15   0    0.00  0.00 0.00  0.0000 0.00     0    0
FAI_60   0.30  18   0    0.00  0.00 0.00  0.0000 0.00     0    0
FAI_124  0.32  24   0    0.00  0.00 0.00  0.0000 0.00     0    0
FAI_86   0.16  21   0    0.00  0.00 0.00  0.0000 0.00     0    0
FAI_47   0.23  24   0    0.00  0.00 0.00  0.0000 0.00     0    0
FAI_121  0.18  23   0    0.00  0.00 0.00  0.0000 0.00     0    0
FAI_167  0.18  24   2    0.08  0.04 0.07  0.0031 1.07     0   31
FAI_99   0.12  24   1    0.04  0.05 0.05  0.0023 1.58     0   31
FAI_63   0.23  24   0    0.00  0.00 0.00  0.0000 0.00     0    0
FAI_168  0.23  18   1    0.06  0.06 0.06  0.0032 0.73     0   25
FAI_5    0.23  24   0    0.00  0.00 0.00  0.0000 0.00     0    0
FAI_132  0.21  24   0    0.00  0.00 0.00  0.0000 0.00     0    0
FAI_85   0.17  19   1    0.05  0.07 0.07  0.0035 1.08     0   30
FAI_81   0.24  24   1    0.04  0.04 0.04  0.0015 0.52     0   17
FAI_83   0.24  24   0    0.00  0.00 0.00  0.0000 0.00     0    0
FAI_57   0.21  15   0    0.00  0.00 0.00  0.0000 0.00     0    0
FAI_91   0.18  21   0    0.00  0.00 0.00  0.0000 0.00     0    0
FAI_135  0.15  21   1    0.05  0.03 0.03  0.0016 0.39     0   22
FAI_1    0.10  21   0    0.00  0.00 0.00  0.0000 0.00     0    0</code></pre>
</div>
</div>
</section>
<section id="ordinamento-invariante-degli-item" class="level2" data-number="66.7">
<h2 data-number="66.7" class="anchored" data-anchor-id="ordinamento-invariante-degli-item"><span class="header-section-number">66.7</span> Ordinamento Invariante degli Item</h2>
<p>Il passo successivo nella MSA è indagare l’ordinamento invariante degli item (IIO) o la non intersezione delle Funzioni di Risposta all’Item (IRFs). È fondamentale determinare se l’ordine degli item sia lo stesso per tutti i rispondenti con diversi livelli del tratto. Esistono diversi metodi per esaminare l’IIO. Il metodo predefinito nel pacchetto R <code>mokken</code> è l’IIO manifesto o MIIO (Manifest IIO) (Ligtvoet, Van der Ark, Te Marvelde &amp; Sijtsma, 2010). Per esaminare l’ordinamento invariante degli item, eseguiamo il seguente codice.</p>
<div id="c0fe3b6f" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="21">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>iio <span class="ot">&lt;-</span> <span class="fu">check.iio</span>(good_items)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(iio) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$method
[1] "MIIO"

$item.summary
        ItemH #ac #vi #vi/#ac maxvi  sum sum/#ac tmax #tsig crit
FAI_81   0.39  18   0    0.00  0.00 0.00  0.0000 0.00     0    0
FAI_83   0.40  18   0    0.00  0.00 0.00  0.0000 0.00     0    0
FAI_124  0.50  18   1    0.06  0.31 0.31  0.0171 3.50     1   83
FAI_5    0.32  18   2    0.11  0.42 0.73  0.0407 3.50     2  145
FAI_60   0.48  18   1    0.06  0.42 0.42  0.0236 2.49     1   97
FAI_106  0.49  18   0    0.00  0.00 0.00  0.0000 0.00     0    0
FAI_49   0.41  18   0    0.00  0.00 0.00  0.0000 0.00     0    0

$backward.selection
        step 1 step 2
FAI_81       0      0
FAI_83       0      0
FAI_124      1      0
FAI_5        2     NA
FAI_60       1      0
FAI_106      0      0
FAI_49       0      0

$HT
[1] 0.3358101
</code></pre>
</div>
</div>
<p>L’output include due tabelle principali. La prima tabella contiene le seguenti colonne. La prima colonna, “ItemH”, mostra il coefficiente di scalabilità Hi per ciascun item, ‘#ac’ indica il numero totale di coppie attive, ‘#vi’ segnala il numero totale di violazioni, ‘#vi/#ac’ mostra il numero medio di violazioni per coppia attiva, ‘maxvi’ indica la massima violazione, ‘sum’ rappresenta la somma di tutte le violazioni, ‘sum/#ac’ mostra la media delle violazioni per coppia attiva, ‘tmax’ indica la statistica di test massima, ‘#tsig’ il numero di violazioni significative, e il valore ‘crit’ è una somma ponderata di altri elementi come ‘itemH’, ‘#ac’, ecc. Valori elevati di ‘crit’ indicano item di scarsa qualità (il valore 0 è perfetto, valori più alti sono peggiori).</p>
<p>L’output precedente mostra che l’Item FAI_5 ha 2 violazioni. In altre parole, la IRF per questo item si interseca con la IRF di altri due item, ed entrambe queste violazioni sono significative (#tsig per questo item è 2). Poiché ha il numero più alto di violazioni, è un buon candidato per essere rimosso dal test. Rimuovere questo item risolve l’intersezione degli altri item con questo item.</p>
<p>Per esaminare graficamente queste intersezione, usiamo il codice seguente.</p>
<div id="faf5eb09" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="22">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(iio)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-1.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-2.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-3.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-4.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-5.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-6.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-7.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-8.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-9.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-10.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-11.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-12.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-13.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-14.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-15.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-16.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-17.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-18.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-19.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-20.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-21-output-21.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="non-intersezione-delle-funzioni-di-risposta-degli-step-degli-item" class="level2" data-number="66.8">
<h2 data-number="66.8" class="anchored" data-anchor-id="non-intersezione-delle-funzioni-di-risposta-degli-step-degli-item"><span class="header-section-number">66.8</span> Non intersezione delle funzioni di risposta degli step degli item</h2>
<p>Per indagare sulla non intersezione delle funzioni di risposta degli step degli item si possono impiegare le matrici P++ e P– (Molenaar &amp; Sijtsma, 2000).</p>
<div id="6f8106a5" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="23">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>pmatrix <span class="ot">&lt;-</span> <span class="fu">check.pmatrix</span>(good_items)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pmatrix) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        ItemH  #ac #vi #vi/#ac maxvi  sum sum/#ac zmax #zsig crit
FAI_49   0.41 1920  17    0.01  0.05 0.65   3e-04 2.93    15   67
FAI_106  0.49 1920  10    0.01  0.06 0.39   2e-04 4.21    10   59
FAI_60   0.48 1920  23    0.01  0.06 0.94   5e-04 3.88    22   81
FAI_124  0.50 1920  20    0.01  0.06 0.84   4e-04 4.60    20   80
FAI_5    0.32 1920  25    0.01  0.06 1.07   6e-04 3.88    24   92
FAI_81   0.39 1920  28    0.01  0.05 1.09   6e-04 3.60    27   89
FAI_83   0.40 1920  17    0.01  0.06 0.68   4e-04 4.60    16   78</code></pre>
</div>
</div>
<p>Come spiegato nelle sezioni precedenti, la colonna ‘#vi’ indica il numero di violazioni delle ISRF. La colonna ‘#zsig’ mostra il numero di violazioni statisticamente significative. Le violazioni possono anche essere controllate graficamente utilizzando il seguente codice:</p>
<div id="5e8f2138" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="24">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">check.pmatrix</span>(good_items), <span class="at">item =</span> <span class="dv">5</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-23-output-1.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-23-output-2.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>La non intersezione delle ISRF può essere esaminata anche con il metodo del punteggio residuo.</p>
<div id="d0fb8bfd" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="25">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>restscore <span class="ot">&lt;-</span> <span class="fu">check.restscore</span>(good_items) </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(restscore) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        ItemH #ac #vi #vi/#ac maxvi  sum sum/#ac zmax #zsig crit
FAI_49   0.41 288   5    0.02  0.08 0.23  0.0008 1.19     0   18
FAI_106  0.49 288   7    0.02  0.07 0.33  0.0011 2.16     2   34
FAI_60   0.48 288   6    0.02  0.14 0.47  0.0016 2.19     4   50
FAI_124  0.50 288   9    0.03  0.15 0.56  0.0019 2.78     1   44
FAI_5    0.32 288  14    0.05  0.15 1.01  0.0035 2.78     5   74
FAI_81   0.39 288   8    0.03  0.10 0.44  0.0015 1.70     1   37
FAI_83   0.40 288   9    0.03  0.07 0.40  0.0014 2.07     1   36</code></pre>
</div>
</div>
<p>I risultati del metodo del punteggio residuo sono diversi da quelli delle matrici P++ e P–. L’output viene interpretato come abbiamo fatto in precedenza. La colonna ‘#vi’ indica il numero di violazioni delle ISRF. La colonna ‘#zsig’ mostra il numero di violazioni statisticamente significative. Questa colonna mostra che il numero di violazioni statisticamente significative è molto inferiore rispetto a quelle riportate dalle matrici P++ e P–. La violazione della non intersezione può essere esaminata graficamente nel modo seguente. Per esempio, consideriamo gli item FAI_49 e FAI_5.</p>
<div id="94f9b34a" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="26">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(restscore, <span class="at">item.pairs =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">5</span>))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-25-output-1.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-25-output-2.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="affidabilità" class="level2" data-number="66.9">
<h2 data-number="66.9" class="anchored" data-anchor-id="affidabilità"><span class="header-section-number">66.9</span> Affidabilità</h2>
<p>Il pacchetto Mokken calcola quattro diversi coefficienti di affidabilità: l’affidabilità della scala Mokken (MS) ρ, (Mokken, 1971), Lambda-2 (Guttman, 1945), l’alpha di Cronbach (Cronbach, 1951), e il coefficiente di affidabilità della classe latente (LCRC, van der Ark, van der Palm, &amp; Sijtsma, 2011).</p>
<ol type="1">
<li><p><strong>MS (Molenaar-Sijtsma Method)</strong>: Questo indice è basato sul metodo Molenaar-Sijtsma di stima dell’affidabilità per scale non parametriche, come quelle analizzate con l’analisi Mokken. Questo metodo considera la varianza tra gli item e la varianza totale per stimare l’affidabilità.</p></li>
<li><p><strong>Alpha (Cronbach’s Alpha)</strong>: L’alpha di Cronbach è forse il più noto indice di affidabilità, utilizzato per valutare la consistenza interna degli item di un test. Misura fino a che punto gli item di un test sono correlati tra loro.</p></li>
<li><p><strong>Lambda-2</strong>: Un altro indice di affidabilità, simile all’alpha di Cronbach, ma talvolta considerato più robusto poiché tiene conto delle correlazioni medie tra gli item.</p></li>
<li><p><strong>LCRC (Latent Class Reliability Coefficient)</strong>: Questo è un indice di affidabilità che tiene conto dell’approccio delle classi latenti. È particolarmente utile quando gli item possono essere raggruppati in sottoscale che riflettono diversi costrutti o dimensioni.</p></li>
</ol>
<p>Per ottenere queste stime dell’affidabilità è possibile eseguire il seguente codice.</p>
<div id="07195e87" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="27">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check.reliability</span>(good_items, <span class="at">LCRC =</span> <span class="cn">TRUE</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<dl>
    <dt>$MS</dt>
        <dd>0.819110476790128</dd>
    <dt>$alpha</dt>
        <dd>0.81675073603741</dd>
    <dt>$lambda.2</dt>
        <dd>0.824148383038108</dd>
    <dt>$LCRC</dt>
        <dd>0.843559865692261</dd>
</dl>
</div>
</div>
<p>In generale, tutti i valori ottenuti indicano che la scala in considerazione ha un’alta affidabilità. Questo significa che è probabile che produca risultati coerenti nel tempo e che gli item che la compongono siano correlati tra loro in modo significativo, contribuendo tutti a misurare lo stesso costrutto o costrutti correlati.</p>
</section>
<section id="identificazione-degli-outlier" class="level2" data-number="66.10">
<h2 data-number="66.10" class="anchored" data-anchor-id="identificazione-degli-outlier"><span class="header-section-number">66.10</span> Identificazione degli Outlier</h2>
<p>Gli outlier sono persone con modelli di risposta aberranti o molti errori di Guttman. Sijtsma e van der Ark (2017) raccomandano di rimuovere gli outlier e di rieseguire l’analisi senza di essi. Se c’è una differenza notevole nei risultati, allora la rimozione degli outlier è giustificata. Per ottenere il numero di errori di Guttman per ogni rispondente eseguiamo il seguente codice:</p>
<div id="ac89dfb8" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="28">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>gutt <span class="ot">&lt;-</span> <span class="fu">check.errors</span>(good_items)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(gutt)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Gplus
  [1]  2  6  0  7  2  4 23 30  2  7 15  0  1  9  2  0  5 24  3  3  0  0 11 51  0
 [26]  4  2 19  9  2 60  2  9 35  2 17 39  2  4  3  3 12  3  0 10  2  0  0 37  4
 [51] 68  0  2 31  2  0 12 36  1 70 12  1 28 27 25  3  4 10  9 16 28 22 81 26  1
 [76]  0 65 28  0 25  3 59 60 40  0  5  0  0  1  0  8  3  8  6 27 12 22 16 12  4
[101] 12  9  0  0 20 25 25  6  4  6  0 47 20 18  4  7  6 33 14 25 12  4  0  1 65
[126] 17 83 26 65  5  5 30  2  9 42  7 13  8 16  3 41  0 12 21  4  8 26 22  3 46
[151]  7 14 38 12 12  1  6  4 32 11  2  6 17  1  8  8 27  8  3  5 58  2 62  3  0
[176] 12 10 45 21  0  2 10 31 19 46 11 21  2 25  9 17  2  4 20 21 49 18 19 14 16
[201] 44  5  7 14 41 24 44  0 18  9 31 12  9 46  8  6 11 14 23 41 24  1  7 39 23
[226]  0 23  3  6  2  2  4  0  0  8 24 38  0 16 62  2  2 21  7 25  9  0  0  8 14
[251] 10  4  1  0  2 18  0 21 19  0 12  0 41  8  7 16 25 20  3 41  3  0  6 18  0
[276]  4  2  4  4 12  5 13  6  9  7  6  0  6  7  2  0  0 13 26  8 41 30  2  0  6
[301]  6  0  5  2  0  0 39 48  0 43  8 15 10  0  4 25 16  9  0  5  2  2  8  2  8
[326]  7  1  0 53 32  9  3  0  4 13  3  6 35 30  2 34  8 10 10  5 23 22 24 12  3
[351]  0  9 16 21 39 27 47 19 28 32  7  2 16  0  3 26 34  6  4 11  7 25  1 15  6
[376] 10 38 17  0  6  3 38  4  0 52  5  2  3  0  0 14  0 27 22 32  8 32 14  2 31
[401] 14 29 52 12 11 32  2  3 17  2  0  5 62 86 34  5 24 39  7 10 31  0  0 25 10
[426] 19 31 13  7 31 36  8  0  0 28  6 23 15 52  3  1  7  4 33 24 11 24  0  2  3
[451]  0  1  0

$UGplus
$UGplus$U1Gplus
[1] 54.5

$UGplus$U2Gplus
[1] 354.5259

</code></pre>
</div>
</div>
<p>Il vettore <code>$Gplus</code> mostra il numero di errori di Guttman G+ per ogni persona. I valori 54.5 e 354.5259 sono le Tukey fences per il rilevamento degli outlier. Essi segnalano i casi in cui il numero di errori di Guttman G+ è oltre il Tukey fence della distribuzione di G+.</p>
<p>Il primo valore, 54.5, è il limite per il numero di errori di Guttman se la distribuzione è approssimativamente normale. I rispondenti con un numero di errori di Guttman superiore al limite possono essere considerati sospetti. Il valore 354.5259 è un limite di soglia per il numero di errori di Guttman se la distribuzione è asimmetrica.</p>
<div id="feffbdd5" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="29">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(gutt<span class="sc">$</span>Gplus)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="03_applications_files/figure-html/cell-28-output-1.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Per il caso presente, l’istogramma del numero di errori di Gutmann mostra che la loro distribuzione è asimmetrica positiva. Pertanto, possiamo scegliere il secondo limite soglia. Per trovare le persone con valori G+ sopra il Tucky fence superiore, eseguiamo il seguente codice.</p>
<div id="b78a7982" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="30">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>err <span class="ot">&lt;-</span> gutt<span class="sc">$</span>Gplus </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(err <span class="sc">&gt;</span> <span class="fl">354.5259</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">

</div>
</div>
<p>I risultati indicano che, in base a questo secondo criterio, non ci sono modelli di risposta sospetti nei dati.</p>
<p>Se questa procedura producesse invece come risultato l’individuazione di alcuni outlier, potremmo rimuoverli dai dati nel modo seguente:</p>
<p><code>good_items_clean &lt;- good_items[-which(err &gt; 354.5259), ]</code></p>
</section>
<section id="considerazioni-conclusive" class="level2" data-number="66.11">
<h2 data-number="66.11" class="anchored" data-anchor-id="considerazioni-conclusive"><span class="header-section-number">66.11</span> Considerazioni conclusive</h2>
<p>In questo capitolo, abbiamo esplorato un approccio pratico all’analisi di un set di dati reali, utilizzando il caso di studio sull’indagine della capacità di coping delle famiglie di fronte alla diagnosi di una grave malattia in un figlio, condotta dai ricercatori del Meyer. Attraverso una serie di passaggi metodici e analitici rigorosi, siamo riusciti a trasformare un complesso insieme di dati in informazioni comprensibili e significative.</p>
<p>Abbiamo iniziato importando i dati e conducendo un’accurata pulizia per rimuovere gli item con eccessiva asimmetria e curtosi. Successivamente, abbiamo implementato la Procedura di Selezione Automatica degli Item (AISP) nell’ambito dell’Analisi delle Scale Mokken (MSA) per identificare e selezionare scale omogenee e coerenti.</p>
<p>Una volta stabilite le scale, abbiamo approfondito le caratteristiche degli item, esaminando le loro statistiche descrittive e la loro distribuzione. Abbiamo anche valutato la loro affidabilità attraverso vari coefficienti, tra cui l’Alpha di Cronbach e il Coefficiente di Affidabilità della Classe Latente (LCRC), rilevando un’alta coerenza interna.</p>
<p>Ulteriori analisi hanno incluso la verifica della monotonicità degli item e dell’ordinamento invariante degli item (IIO), fondamentali per garantire che la scala rispettasse i principi teorici sottostanti la MSA. Infine, abbiamo esaminato la presenza di outlier, utilizzando i Tukey fences per identificare e gestire i modelli di risposta aberranti.</p>
<p>In conclusione, questo capitolo dimostra come l’applicazione metodica e sistematica delle tecniche di analisi statistica possa fornire intuizioni preziose e comprensibili da un set di dati complesso. Ciò non solo rafforza la validità e l’affidabilità della ricerca, ma fornisce anche una base solida per ulteriori indagini e interpretazioni.</p>
</section>
<section id="informazioni-sullambiente-di-sviluppo" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="informazioni-sullambiente-di-sviluppo">Informazioni sull’Ambiente di Sviluppo</h2>
<div id="9e5219b2" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="31">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>R version 4.4.1 (2024-06-14)
Platform: aarch64-apple-darwin20
Running under: macOS 15.0

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] C

time zone: Europe/Rome
tzcode source: internal

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] mokken_3.1.2         poLCA_1.6.0.1        MASS_7.3-61         
 [4] scatterplot3d_0.3-44 mirt_1.42            lattice_0.22-6      
 [7] TAM_4.2-21           CDM_8.2-6            mvtnorm_1.3-1       
[10] ggokabeito_0.1.0     viridis_0.6.5        viridisLite_0.4.2   
[13] ggpubr_0.6.0         ggExtra_0.10.1       bayesplot_1.11.1    
[16] gridExtra_2.3        patchwork_1.3.0      semTools_0.5-6      
[19] semPlot_1.1.6        lavaan_0.6-18        psych_2.4.6.26      
[22] scales_1.3.0         markdown_1.13        knitr_1.48          
[25] lubridate_1.9.3      forcats_1.0.0        stringr_1.5.1       
[28] dplyr_1.1.4          purrr_1.0.2          readr_2.1.5         
[31] tidyr_1.3.1          tibble_3.2.1         ggplot2_3.5.1       
[34] tidyverse_2.0.0      here_1.0.1          

loaded via a namespace (and not attached):
  [1] splines_4.4.1        later_1.3.2          pbdZMQ_0.3-13       
  [4] R.oo_1.26.0          XML_3.99-0.17        rpart_4.1.23        
  [7] lifecycle_1.0.4      rstatix_0.7.2        rprojroot_2.0.4     
 [10] globals_0.16.3       rockchalk_1.8.157    backports_1.5.0     
 [13] magrittr_2.0.3       openxlsx_4.2.7.1     Hmisc_5.1-3         
 [16] rmarkdown_2.28       httpuv_1.6.15        qgraph_1.9.8        
 [19] zip_2.3.1            sessioninfo_1.2.2    pbapply_1.7-2       
 [22] minqa_1.2.8          audio_0.1-11         multcomp_1.4-26     
 [25] abind_1.4-8          quadprog_1.5-8       R.utils_2.12.3      
 [28] nnet_7.3-19          TH.data_1.1-2        sandwich_3.1-1      
 [31] listenv_0.9.1        testthat_3.2.1.1     RPushbullet_0.3.4   
 [34] vegan_2.6-8          arm_1.14-4           parallelly_1.38.0   
 [37] permute_0.9-7        codetools_0.2-20     tidyselect_1.2.1    
 [40] farver_2.1.2         lme4_1.1-35.5        base64enc_0.1-3     
 [43] jsonlite_1.8.9       polycor_0.8-1        progressr_0.14.0    
 [46] Formula_1.2-5        survival_3.7-0       emmeans_1.10.4      
 [49] tools_4.4.1          snow_0.4-4           Rcpp_1.0.13         
 [52] glue_1.7.0           mnormt_2.1.1         xfun_0.47           
 [55] mgcv_1.9-1           admisc_0.36          IRdisplay_1.1       
 [58] withr_3.0.1          beepr_2.0            fastmap_1.2.0       
 [61] boot_1.3-31          fansi_1.0.6          digest_0.6.37       
 [64] mi_1.1               timechange_0.3.0     R6_2.5.1            
 [67] mime_0.12            estimability_1.5.1   colorspace_2.1-1    
 [70] gtools_3.9.5         jpeg_0.1-10          R.methodsS3_1.8.2   
 [73] utf8_1.2.4           generics_0.1.3       data.table_1.16.0   
 [76] corpcor_1.6.10       SimDesign_2.17.1     htmlwidgets_1.6.4   
 [79] pkgconfig_2.0.3      sem_3.1-16           gtable_0.3.5        
 [82] brio_1.1.5           htmltools_0.5.8.1    carData_3.0-5       
 [85] png_0.1-8            rstudioapi_0.16.0    tzdb_0.4.0          
 [88] reshape2_1.4.4       uuid_1.2-1           curl_5.2.3          
 [91] coda_0.19-4.1        checkmate_2.3.2      nlme_3.1-166        
 [94] nloptr_2.1.1         repr_1.1.7           zoo_1.8-12          
 [97] parallel_4.4.1       miniUI_0.1.1.1       foreign_0.8-87      
[100] pillar_1.9.0         grid_4.4.1           vctrs_0.6.5         
[103] promises_1.3.0       car_3.1-2            OpenMx_2.21.12      
[106] xtable_1.8-4         Deriv_4.1.6          cluster_2.1.6       
[109] dcurver_0.9.2        GPArotation_2024.3-1 htmlTable_2.4.3     
[112] evaluate_1.0.0       pbivnorm_0.6.0       cli_3.6.3           
[115] kutils_1.73          compiler_4.4.1       rlang_1.1.4         
[118] crayon_1.5.3         future.apply_1.11.2  ggsignif_0.6.4      
[121] fdrtool_1.2.18       plyr_1.8.9           stringi_1.8.4       
[124] munsell_0.5.1        lisrelToR_0.3        pacman_0.5.1        
[127] Matrix_1.7-0         IRkernel_1.3.2       hms_1.1.3           
[130] glasso_1.11          future_1.34.0        shiny_1.9.1         
[133] igraph_2.0.3         broom_1.0.6          RcppParallel_5.1.9  </code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiato!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiato!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ccaudek\.github\.io\/testing_psicologico\/intro\.html");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/mokken/02_core_issues.html" class="pagination-link" aria-label="Analisi della Scala di Mokken">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Analisi della Scala di Mokken</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/irt/01_rasch_model.html" class="pagination-link" aria-label="Modello di Rasch">
        <span class="nav-page-text"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">Modello di Rasch</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Testing Psicologico</strong> è una dispensa scritta da Corrado Caudek.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>