# Project settings
project:
  type: book
  output-dir: docs

# Book settings
book:
  title: "Testing Psicologico"
  subtitle: "Anno Accademico 2024/2025"
  author: "Corrado Caudek"
  date: "last-modified" # Automatically include last modified date
  search: true # Enable search functionality
  repo-url: https://github.com/ccaudek/testing_psicologico/
  site-url: https://ccaudek.github.io/testing_psicologico/intro.html
  page-footer:
    left: |
      **Testing Psicologico** è una dispensa scritta da Corrado Caudek.
    right: |
      Realizzato con <a href="https://quarto.org/">Quarto</a>.
  sidebar:
    collapse-level: 1 # Automatically collapse sidebar to level 1
    pinned: true # Pin sidebar for easier navigation

  chapters: # Define book chapters and structure
    - index.qmd
    - prefazione.qmd

    - part: "Calendario"
      chapters:
        - cal_testing_psic_2025.qmd

    - part: "Punteggi e scale"
      chapters:
        - chapters/measurement/01_scores_scales.qmd
        - chapters/measurement/E1_likert.ipynb
        - chapters/measurement/E2_optimal_scoring.ipynb
        - chapters/measurement/E3_thurstone.ipynb
        - chapters/measurement/02_development.qmd
        - chapters/measurement/03_equating.qmd
        - chapters/measurement/E4_norming.ipynb

    - part: "CTT"
      chapters:
        - chapters/ctt/01_ctt_1.qmd
        - chapters/ctt/02_ctt_2.ipynb
        - chapters/ctt/03_ctt_3.ipynb
        - chapters/ctt/04_err_std_mis.ipynb
        - chapters/ctt/05_err_std_stima.ipynb
        - chapters/ctt/06_ctt_applications.ipynb

    - part: "Giudici"
      chapters:
        - chapters/raters/01_multilevel.qmd
        - chapters/raters/02_interrater_reliability.qmd
        - chapters/raters/E1_irr.ipynb

    - part: "Validità"
      chapters:
        - chapters/validity/01_validity.qmd
        - chapters/validity/02_other_variables.qmd

    - part: "Generalizzabilità"
      chapters:
        - chapters/gtheory/01_gtheory.ipynb

    - part: "Items"
      chapters:
        - chapters/items/01_item_development.ipynb
        - chapters/items/02_item_analysis.ipynb

    - part: "Analisi dei percorsi"
      chapters:
        - chapters/path_analysis/01_path_analysis.qmd
        - chapters/path_analysis/02_clement_2022.qmd
        
    - part: "Networks"
      chapters:
        - chapters/networks/01_networks.qmd

    - part: "PCA"
      chapters:
        - chapters/pca/01_linear_algebra.qmd
        - chapters/pca/02_pca.qmd

    - part: "FA"
      chapters:
        - chapters/fa/01_intro_fa.qmd
        - chapters/fa/02_analisi_fattoriale_1.qmd
        - chapters/fa/03_analisi_fattoriale_2.qmd
        - chapters/fa/04_analisi_fattoriale_3.qmd
        - chapters/fa/05_factor_scores.qmd
        - chapters/fa/06_constraints_on_parms.qmd
        - chapters/fa/07_total_score.qmd

    - part: Costruzione
      chapters:
        - chapters/extraction/01_val_matrici.qmd
        - chapters/extraction/02_estrazione.qmd
        - chapters/extraction/03_numero_fattori.ipynb
        - chapters/extraction/04_rotazione.ipynb
        - chapters/extraction/05_val_soluzione.ipynb

    - part: "CFA"
      chapters:
        - chapters/cfa/01_cfa.qmd
        - chapters/cfa/02_meanstructure.qmd
        - chapters/cfa/03_cat_data.qmd
        - chapters/cfa/04_mmm.ipynb
        - chapters/cfa/05_bifactor.ipynb
        - chapters/cfa/06_efa_lavaan.qmd
        - chapters/cfa/07_fa_in_r.qmd
        - chapters/cfa/E_01.ipynb
        - chapters/cfa/E_02_bifactor.ipynb

    - part: "SEM"
      chapters:
        - chapters/sem/01_sem_intro.qmd
        - chapters/sem/02_data_preparation.qmd
        - chapters/sem/03_gof.qmd
        - chapters/sem/04_mod_comp.qmd
        - chapters/sem/05_cfa_mod_comp.qmd
        - chapters/sem/06_refine_solution.ipynb
        - chapters/sem/07_group_invariance.qmd
        - chapters/sem/08_multilevel_sem.ipynb
        - chapters/sem/09_structural_regr.qmd
        - chapters/sem/10_missing_data.qmd
        - chapters/sem/11_small_samples.ipynb
        - chapters/sem/13_esem.qmd
        - chapters/sem/14_sem_power.ipynb
        - chapters/sem/E_01.ipynb
        - chapters/sem/15_prior_pred_mod_check.ipynb

    - part: "Mokken"
      chapters:
        - chapters/mokken/01_logistic_regr.qmd
        - chapters/sem/E_01.ipynb
        - chapters/mokken/02_core_issues.qmd
        - chapters/mokken/03_applications.ipynb

    - part: IRT
      chapters:
        - chapters/irt/01_rasch_model.qmd
        - chapters/irt/02_assumptions.qmd
        - chapters/irt/03_estimation.qmd
        - chapters/irt/04_1pl_2pl_3pl.qmd
        - chapters/irt/05_implementation.qmd
        # - chapters/irt/07_irt_poly.ipynb

    - part: LGM
      chapters:
        - chapters/lgm/01_lgm_intro.ipynb
        - chapters/lgm/02_lgm_prelims.ipynb
        - chapters/lgm/06_lgm_mixed.ipynb
        - chapters/lgm/03_time_effects.ipynb
        - chapters/lgm/05_intro_panel.ipynb
        - chapters/lgm/07_growth_1.ipynb
        - chapters/lgm/08_growth_cont.ipynb
        - chapters/lgm/09_time_inv_cov.ipynb
        - chapters/lgm/10_growth_groups.ipynb
        - chapters/lgm/11_lgm_wais.qmd
        - chapters/lgm/12_temp_reliability.ipynb

    - part: Predizione
      chapters:
        - chapters/prediction/01_prediction.qmd

    - 99-references.qmd

  appendices:
    - chapters/appendix/a1_intro_r.ipynb
    - chapters/appendix/a2_sums.ipynb
    - chapters/appendix/a3_calculus.ipynb

    - part: "Soluzioni degli esercizi"
      chapters:
        - chapters/appendix/solutions_probability.ipynb

# Cross-references
crossref:
  appendix-title: "Appendice"

# Table of Contents
toc: true # Enable table of contents
toc-depth: 5 # Set depth of table of contents

# Bibliography and citations
bibliography: ./references.bib
biblio-style: apalike # Use APA-like formatting
csl: apa.csl # Citation style language file
link-citations: true # Link citations in the document

# Language settings
lang: it # Set document language to Italian

format:
  html:
    theme: 
      light:
        - cosmo
        - custom.scss
      dark:
        - darkly
    reader-mode: true
    fig-align: center
    toc-location: right
    code-fold: false
    code-link: true
    engine: knitr
    author-meta: Corrado Caudek
    callout-appearance: simple

execute:
  freeze: auto  # Skip re-executing unchanged code chunks
  echo: true  # Display code in the output document
  warning: false  # Suppress warnings in output
  message: false  # Suppress messages in output
  fig.width: 6  # Set figure width (in inches)
  fig.asp: 0.618  # Set figure aspect ratio (golden ratio for aesthetics)
  fig.retina: 2  # High resolution for retina displays
  fig.align: "center"  # Center-align all figures
  fig.show: "hold"  # Group multiple figures from a chunk

editor: source

# Website-specific settings
website:
  cookie-consent:
    type: express
    style: headline
  google-analytics:
    tracking-id: "G-TP2WLBPMS6"
    anonymize-ip: true # Anonymize IPs for better privacy
