project:
  type: book
  output-dir: docs

book:
  title: "Testing Psicologico"
  subtitle: "Con applicazioni in R"
  author: "Corrado Caudek"
  date: "last-modified"
  search: true
  cover-image: figures/icon_psychological_testing.png
  repo-url: https://github.com/ccaudek/testing_psicologico/
  repo-actions: [edit]
  site-url: https://ccaudek.github.io/testing_psicologico/intro.html
  page-footer:
    left: |
      Testing Psicologico è stato scritto da Corrado Caudek.
    right: |
      Questo libro è stato realizzato con <a href="https://quarto.org/">Quarto</a>.
  sidebar:
    collapse-level: 1
    pinned: true

  chapters:
    - index.qmd

    - prefazione.qmd

    - part: "Punteggi e scale"
      chapters:
        - chapters/measurement/01_scores_scales.ipynb
        - chapters/measurement/E1_likert.ipynb
        - chapters/measurement/E2_optimal_scoring.ipynb
        - chapters/measurement/E3_thurstone.ipynb

    - part: "CTT"
      chapters:
        - chapters/ctt/01_ctt_1.ipynb
        - chapters/ctt/02_ctt_2.ipynb
        - chapters/ctt/03_ctt_3.ipynb
        - chapters/ctt/04_err_std_mis.ipynb
        - chapters/ctt/05_err_std_stima.ipynb
        - chapters/ctt/06_ctt_applications.ipynb
    
    - part: "Validità"
      chapters:
        - chapters/validity/01_validity.ipynb
        - chapters/validity/02_other_variables.ipynb

    - part: "Teoria della generalizzabilità"
      chapters:
        - chapters/gtheory/01_gtheory.ipynb

    - part: "Il modello del'analisi fattoriale"
      chapters:
        - chapters/fa/01_intro_fa.ipynb
        - chapters/fa/02_analisi_fattoriale_1.ipynb
        - chapters/fa/03_analisi_fattoriale_2.ipynb
        - chapters/fa/04_analisi_fattoriale_3.ipynb
        - chapters/fa/05_factor_scores.ipynb
        - chapters/fa/06_constraints_on_parms.ipynb
        - chapters/fa/07_total_score.ipynb

    - part: "Analisi fattoriale confermativa"
      chapters:
        - chapters/cfa/01_cfa.ipynb
        - chapters/cfa/02_meanstructure.ipynb
        - chapters/cfa/03_cat_data.ipynb
        - chapters/cfa/04_mmm.ipynb
        - chapters/cfa/05_bifactor.ipynb
        - chapters/cfa/06_efa_lavaan.ipynb
        - chapters/cfa/E_01.ipynb

    - 99-references.qmd

  appendices:
    - chapters/appendix/a12_sum_notation.ipynb

    - part: "Soluzioni degli esercizi"
      chapters:
        - chapters/appendix/solutions_probability.ipynb

crossref:
  appendix-title: "Appendice"

bibliography: ./references.bib

lang: it

format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    code-link: true

    author-meta: "Corrado Caudek"
    callout-appearance: simple

editor: visual

website:
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-TP2WLBPMS6"
    anonymize-ip: true
