project:
  type: book
  output-dir: docs

book:
  title: "Testing Psicologico"
  subtitle: "Con applicazioni in R"
  author: "Corrado Caudek"
  date: "last-modified"
  search: true
  cover-image: figures/icon_psychological_testing.png
  repo-url: https://github.com/ccaudek/testing_psicologico/
  repo-actions: [edit]
  site-url: https://ccaudek.github.io/testing_psicologico/intro.html
  page-footer:
    left: |
      Testing Psicologico è stato scritto da Corrado Caudek.
    right: |
      Questo libro è stato realizzato con <a href="https://quarto.org/">Quarto</a>.
  sidebar:
    collapse-level: 1
    pinned: true

  chapters:
    - index.qmd

    - prefazione.qmd

    - part: "Punteggi e scale"
      chapters:
        - chapters/measurement/01_scores_scales.ipynb
        - chapters/measurement/E1_likert.ipynb
        - chapters/measurement/E2_optimal_scoring.ipynb
        - chapters/measurement/E3_thurstone.ipynb
        - chapters/measurement/02_development.ipynb

    - part: "CTT"
      chapters:
        - chapters/ctt/01_ctt_1.ipynb
        - chapters/ctt/02_ctt_2.ipynb
        - chapters/ctt/03_ctt_3.ipynb
        - chapters/ctt/04_err_std_mis.ipynb
        - chapters/ctt/05_err_std_stima.ipynb
        - chapters/ctt/06_ctt_applications.ipynb
    
    - part: "Giudici"
      chapters:
        - chapters/raters/01_multilevel.ipynb
        - chapters/raters/02_interrater_reliability.ipynb
        - chapters/raters/E1_irr.ipynb

    - part: "Validità"
      chapters:
        - chapters/validity/01_validity.ipynb
        - chapters/validity/02_other_variables.ipynb

    - part: "Generalizzabilità"
      chapters:
        - chapters/gtheory/01_gtheory.ipynb

    - part: "Items"
      chapters:
        - chapters/items/01_item_development.ipynb
        - chapters/items/02_item_analysis.ipynb

    - part: "Analisi dei percorsi"
      chapters:
        - chapters/path_analysis/01_path_analysis.ipynb

    - part: "FA"
      chapters:
        - chapters/fa/01_intro_fa.ipynb
        - chapters/fa/02_analisi_fattoriale_1.ipynb
        - chapters/fa/03_analisi_fattoriale_2.ipynb
        - chapters/fa/04_analisi_fattoriale_3.ipynb
        - chapters/fa/05_factor_scores.ipynb
        - chapters/fa/06_constraints_on_parms.ipynb
        - chapters/fa/07_total_score.ipynb

    - part: Costruzione 
      chapters:
        - chapters/extraction/01_val_matrici.ipynb
        - chapters/extraction/02_estrazione.ipynb
        - chapters/extraction/03_numero_fattori.ipynb
        - chapters/extraction/04_rotazione.ipynb
        - chapters/extraction/05_val_soluzione.ipynb

    - part: "CFA"
      chapters:
        - chapters/cfa/01_cfa.ipynb
        - chapters/cfa/02_meanstructure.ipynb
        - chapters/cfa/03_cat_data.ipynb
        - chapters/cfa/04_mmm.ipynb
        - chapters/cfa/05_bifactor.ipynb
        - chapters/cfa/06_efa_lavaan.ipynb
        - chapters/cfa/E_01.ipynb
    
    - part: "SEM"
      chapters:
        - chapters/sem/01_sem_intro.ipynb
        - chapters/sem/02_data_preparation.ipynb
        - chapters/sem/03_gof.ipynb
        - chapters/sem/04_mod_comp.ipynb
        - chapters/sem/05_cfa_mod_comp.ipynb
        - chapters/sem/06_refine_solution.ipynb
        - chapters/sem/07_group_invariance.ipynb
        - chapters/sem/08_multilevel_sem.ipynb
        - chapters/sem/09_structural_regr.ipynb
        - chapters/sem/10_missing_data.ipynb
        - chapters/sem/11_small_samples.ipynb
        - chapters/sem/12_temp_reliability.ipynb
        - chapters/sem/E_01.ipynb

    - part: "Mokken"
      chapters:
        - chapters/mokken/01_core_issues.ipynb
        - chapters/mokken/02_applications.ipynb

    - part: IRT
      chapters:
        - chapters/irt/01_logistic_regr.ipynb
        - chapters/irt/E_01.ipynb
        - chapters/irt/02_rasch_model.ipynb
        - chapters/irt/03_assumptions.ipynb
        - chapters/irt/04_estimation.ipynb
        - chapters/irt/05_1pl_2pl_3pl.ipynb
        - chapters/irt/06_implementation.ipynb
        - chapters/irt/07_irt_poly.ipynb

    - 99-references.qmd

  appendices:
    - chapters/appendix/a1_intro_r.ipynb
    - chapters/appendix/a2_sums.ipynb
    - chapters/appendix/a3_calculus.ipynb
    - chapters/appendix/a4_linear_alg.ipynb

    - part: "Soluzioni degli esercizi"
      chapters:
        - chapters/appendix/solutions_probability.ipynb

crossref:
  appendix-title: "Appendice"

bibliography: ./references.bib

lang: it

format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    code-link: true

    author-meta: "Corrado Caudek"
    callout-appearance: simple

editor: visual

website:
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-TP2WLBPMS6"
    anonymize-ip: true
