
::: {.content-hidden unless-format="html"}
# Benvenuti {.unnumbered .unlisted}
:::

\chapter*{}

\vfill

Questo sito web è dedicato al materiale didattico dell'insegnamento di [Testing Psicologico](https://unifi.coursecatalogue.cineca.it/insegnamenti/2024/47120_B267-23-24_119693/2023/47118/3252?coorte=2024) (A.A. 2024/2025), rivolto agli studenti del primo anno del Corso di Laurea Magistrale [Psicologia Clinica e della Salute e Neuropsicologia](https://unifi.coursecatalogue.cineca.it/corsi/2024/3252?annoOrdinamento=2023) dell'[Università degli Studi di Firenze](https://www.unifi.it/).

L’insegnamento si propone quale stimolo e guida per l’apprendimento delle basi dell'assessment psicologico.

## Informazioni sull'insegnamento {.unnumbered}

- **Codice**: B033288 - Testing Psicologico </br>
- **Modulo**: B033288 - Testing Psicologico (Cognomi L-Z) </br>
- **Corso di laurea**: Laurea Magistrale: Psicologia Clinica e della Salute e Neuropsicologia </br>
- **Anno Accademico**: 2024-2025 </br>
- **Calendario**: Il corso si terrà dal 4 marzo al 31 maggio 2025.</br>
- **Orario delle lezioni**: Le lezioni si svolgeranno il martedì dalle 10:30 alle 13:30 e il giovedì dalle 8:30 alle 11:30.</br>
- **Luogo**: Le lezioni si terranno presso il Plesso didattico La Torretta.</br>
- **Modalità di svolgimento della didattica**: Le lezioni ed esercitazioni saranno svolte in modalità frontale.</br>

::: {.callout-note}
Questo sito web è la fonte ufficiale per tutte le informazioni relative al programma dell'insegnamento *B033288 - Testing Psicologico* (Cognomi A-K) per l'A.A. 2024-2025 e le modalità d'esame.
:::

## Syllabus

Il Syllabus può essere scaricato utilizzando questo [link](syllabus/syllabus.pdf).
