<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Corrado Caudek">
<title>70&nbsp; Modelli 1PL, 2PL e 3PL – Testing Psicologico</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/irt/05_implementation.html" rel="next">
<link href="../../chapters/irt/03_estimation.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9ac0fa60fcd2ae55f2ddd9f231fc218f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-d0edb45afdd5f5fd9663be5d5709df0d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/irt/01_rasch_model.html">IRT</a></li><li class="breadcrumb-item"><a href="../../chapters/irt/04_1pl_2pl_3pl.html"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Modelli 1PL, 2PL e 3PL</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Testing Psicologico</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ccaudek/testing_psicologico/" title="Eseguire il codice" class="quarto-navigation-tool px-1" aria-label="Eseguire il codice"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Ricerca"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Informazioni Generali</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../prefazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefazione</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Calendario</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../cal_testing_psic_2025.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calendario Didattico e Programma del Corso</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Punteggi e scale</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/01_scores_scales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Punteggi e scale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E1_likert.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">✏ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E2_optimal_scoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E3_thurstone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">✏ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/02_development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sviluppo dello strumento</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/03_equating.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Equating nei Test Psicologici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E4_norming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">CTT</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/01_ctt_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Fondamenti teorici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/02_ctt_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">L’affidabilità del test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/03_ctt_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Metodi di stima dell’affidabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/04_err_std_mis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">L’errore standard della misurazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/05_err_std_stima.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">La stima del punteggio vero</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/06_ctt_applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Applicazioni della CTT</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Giudici</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/01_multilevel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Modelli multilivello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/02_interrater_reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">L’affidabilità tra giudici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/E1_irr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Validità</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/validity/01_validity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">La Validità del test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/validity/02_other_variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Relazioni test-criterio</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Generalizzabilità</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/gtheory/01_gtheory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Teoria della generalizzabilità</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Items</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/items/01_item_development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Lo sviluppo degli item</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/items/02_item_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Analisi degli item</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Analisi dei percorsi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/path_analysis/01_path_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Analisi dei percorsi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/path_analysis/02_clement_2022.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Riparazione affettiva post-infedeltà</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Networks</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/networks/01_networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Network psicologici</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">PCA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/pca/01_linear_algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Elementi di algebra lineare</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/pca/02_pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Analisi delle componenti principali</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">FA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/01_intro_fa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Introduzione all’analisi fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/02_analisi_fattoriale_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Il modello unifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/03_analisi_fattoriale_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Il modello statistico dell’analisi fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/04_analisi_fattoriale_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Il modello multifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/05_factor_scores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">I punteggi fattoriali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/06_constraints_on_parms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Attendibilità e modello fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/07_total_score.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Punteggio totale e modello fattoriale</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false">
 <span class="menu-text">Costruzione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/01_val_matrici.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Valutazione della matrice di correlazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/02_estrazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">L’estrazione dei fattori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/03_numero_fattori.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Il numero dei fattori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/04_rotazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">La rotazione fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/05_val_soluzione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Valutare e rifinire la soluzione fattoriale</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">CFA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/01_cfa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Analisti Fattoriale Confermativa</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/02_meanstructure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">La struttura delle medie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/03_cat_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Dati non gaussiani e categoriali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/04_mmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">CFA per matrici multi-tratto multi-metodo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/05_bifactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Modello bifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/06_efa_lavaan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Exploratory Structural Equation Modeling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/07_fa_in_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Strategia Integrata per un’Analisi Fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/E_02_bifactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false">
 <span class="menu-text">SEM</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/01_sem_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Introduzione ai Modelli SEM</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/02_data_preparation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Preparazione dei Dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/03_gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Test del Modello e Indicizzazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/04_mod_comp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Confronto tra modelli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/05_cfa_mod_comp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">CFA: confronto tra modelli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/06_refine_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">La revisione del modello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/07_group_invariance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Invarianza di misura</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/08_multilevel_sem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Modelli di Equazioni Strutturali Multilivello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/09_structural_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Modelli di Regressione Strutturale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/10_missing_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Dati mancanti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/11_small_samples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Modellizzazione SEM in Piccoli Campioni</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/13_esem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Exploratory structural equation modelling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/14_sem_power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Dimensione Campionaria e Analisi della Potenza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/15_prior_pred_mod_check.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Prior Predictive Model Checking</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false">
 <span class="menu-text">Mokken</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/01_logistic_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Modello di Regressione Logistica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/02_core_issues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Analisi della Scala di Mokken</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/03_applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Applicazione Pratica</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="true">
 <span class="menu-text">IRT</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/01_rasch_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">Modello di Rasch</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/02_assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">68</span>&nbsp; <span class="chapter-title">Assunzioni e Proprietà del Modello di Rasch</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/03_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title">Stima</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/04_1pl_2pl_3pl.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Modelli 1PL, 2PL e 3PL</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/05_implementation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Implementazione</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false">
 <span class="menu-text">LGM</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/01_lgm_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">72</span>&nbsp; <span class="chapter-title">Curve di crescita latente</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/02_lgm_prelims.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">73</span>&nbsp; <span class="chapter-title">Considerazioni Preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/06_lgm_mixed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">74</span>&nbsp; <span class="chapter-title">LGM e modelli misti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/03_time_effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">75</span>&nbsp; <span class="chapter-title">Dati longitudinali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/05_intro_panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">76</span>&nbsp; <span class="chapter-title">Specificare e Interpretare un Modello Longitudinale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/07_growth_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">77</span>&nbsp; <span class="chapter-title">Curve di crescita latente</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/08_growth_cont.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">78</span>&nbsp; <span class="chapter-title">Il tempo su una metrica continua</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/09_time_inv_cov.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">79</span>&nbsp; <span class="chapter-title">Covariate indipendenti dal tempo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/10_growth_groups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">80</span>&nbsp; <span class="chapter-title">Modelli di crescita latenti a gruppi multipli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/11_lgm_wais.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">81</span>&nbsp; <span class="chapter-title">Lo Sviluppo dell’Intelligenza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/12_temp_reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">82</span>&nbsp; <span class="chapter-title">Affidabilità longitudinale</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false">
 <span class="menu-text">Predizione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/prediction/01_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">83</span>&nbsp; <span class="chapter-title">Predizione</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../99-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliografia</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendici</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a1_intro_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linguaggio R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a2_sums.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Simbolo di somma</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a3_calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Per liberarvi dai terrori preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false">
 <span class="menu-text">Soluzioni degli esercizi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/solutions_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Probabilità</span></span></a>
  </div>
</li>
      </ul>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Indice</h2>
   
  <ul>
<li><a href="#introduzione" id="toc-introduzione" class="nav-link active" data-scroll-target="#introduzione"><span class="header-section-number">70.1</span> Introduzione</a></li>
  <li><a href="#un-esempio-pratico" id="toc-un-esempio-pratico" class="nav-link" data-scroll-target="#un-esempio-pratico"><span class="header-section-number">70.2</span> Un Esempio Pratico</a></li>
  <li>
<a href="#modello-1pl" id="toc-modello-1pl" class="nav-link" data-scroll-target="#modello-1pl"><span class="header-section-number">70.3</span> Modello 1PL</a>
  <ul>
<li><a href="#il-ruolo-del-parametro-alpha" id="toc-il-ruolo-del-parametro-alpha" class="nav-link" data-scroll-target="#il-ruolo-del-parametro-alpha"><span class="header-section-number">70.3.1</span> Il Ruolo del Parametro <span class="math inline">\(\alpha\)</span></a></li>
  <li><a href="#esempio-pratico" id="toc-esempio-pratico" class="nav-link" data-scroll-target="#esempio-pratico"><span class="header-section-number">70.3.2</span> Esempio Pratico</a></li>
  <li><a href="#modello-di-rasch-e-modello-1pl-confronto-e-differenze" id="toc-modello-di-rasch-e-modello-1pl-confronto-e-differenze" class="nav-link" data-scroll-target="#modello-di-rasch-e-modello-1pl-confronto-e-differenze"><span class="header-section-number">70.3.3</span> Modello di Rasch e Modello 1PL: Confronto e Differenze</a></li>
  <li><a href="#modello-2pl" id="toc-modello-2pl" class="nav-link" data-scroll-target="#modello-2pl"><span class="header-section-number">70.3.4</span> Modello 2PL</a></li>
  <li><a href="#implementazione-in-r-con-il-pacchetto-mirt" id="toc-implementazione-in-r-con-il-pacchetto-mirt" class="nav-link" data-scroll-target="#implementazione-in-r-con-il-pacchetto-mirt"><span class="header-section-number">70.3.5</span> Implementazione in R con il Pacchetto <code>mirt</code></a></li>
  <li><a href="#confronto-tra-modello-1pl-e-modello-2pl" id="toc-confronto-tra-modello-1pl-e-modello-2pl" class="nav-link" data-scroll-target="#confronto-tra-modello-1pl-e-modello-2pl"><span class="header-section-number">70.3.6</span> Confronto tra Modello 1PL e Modello 2PL</a></li>
  <li><a href="#differenze-chiave-tra-modello-1pl-e-modello-2pl" id="toc-differenze-chiave-tra-modello-1pl-e-modello-2pl" class="nav-link" data-scroll-target="#differenze-chiave-tra-modello-1pl-e-modello-2pl"><span class="header-section-number">70.3.7</span> Differenze Chiave tra Modello 1PL e Modello 2PL</a></li>
  </ul>
</li>
  <li>
<a href="#modello-3pl" id="toc-modello-3pl" class="nav-link" data-scroll-target="#modello-3pl"><span class="header-section-number">70.4</span> Modello 3PL</a>
  <ul>
<li><a href="#caratteristiche-del-modello-3pl" id="toc-caratteristiche-del-modello-3pl" class="nav-link" data-scroll-target="#caratteristiche-del-modello-3pl"><span class="header-section-number">70.4.1</span> Caratteristiche del Modello 3PL</a></li>
  </ul>
</li>
  <li>
<a href="#invarianza-di-gruppo-nella-item-response-theory" id="toc-invarianza-di-gruppo-nella-item-response-theory" class="nav-link" data-scroll-target="#invarianza-di-gruppo-nella-item-response-theory"><span class="header-section-number">70.5</span> Invarianza di Gruppo nella Item Response Theory</a>
  <ul>
<li><a href="#confronto-con-la-teoria-classica-dei-test" id="toc-confronto-con-la-teoria-classica-dei-test" class="nav-link" data-scroll-target="#confronto-con-la-teoria-classica-dei-test"><span class="header-section-number">70.5.1</span> Confronto con la Teoria Classica dei Test</a></li>
  </ul>
</li>
  <li><a href="#riflessioni-conclusive" id="toc-riflessioni-conclusive" class="nav-link" data-scroll-target="#riflessioni-conclusive"><span class="header-section-number">70.6</span> Riflessioni Conclusive</a></li>
  <li><a href="#session-info" id="toc-session-info" class="nav-link" data-scroll-target="#session-info"><span class="header-section-number">70.7</span> Session Info</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/irt/01_rasch_model.html">IRT</a></li><li class="breadcrumb-item"><a href="../../chapters/irt/04_1pl_2pl_3pl.html"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Modelli 1PL, 2PL e 3PL</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-irt-123pl" class="quarto-section-identifier"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Modelli 1PL, 2PL e 3PL</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
In questo capitolo apprenderai come:
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>adattare e interpretare i modelli IRT: 1PL, 2PL e 3PL, comprendendo le differenze concettuali e pratiche tra loro;<br>
</li>
<li>analizzare il principio dell’invarianza di gruppo e la sua importanza per confronti equi tra popolazioni diverse.<br>
</li>
</ul>
</div>
</div>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prerequisiti
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Leggere il capitolo 8, <em>Item Response Theory</em>, del testo <em>Principles of psychological assessment</em> di <span class="citation" data-cites="petersen2024principles">Petersen (<a href="../../99-references.html#ref-petersen2024principles" role="doc-biblioref">2024</a>)</span>.</li>
</ul>
</div>
</div>
<div class="callout callout-style-simple callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Preparazione del Notebook
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"code"</span>, <span class="st">"_common.R"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Load packages</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/ns-load.html">requireNamespace</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span></span>
<span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">eRm</span>, <span class="va">mirt</span>, <span class="va">grid</span>, <span class="va">TAM</span>, <span class="va">ggmirt</span>, <span class="va">psychotools</span>, <span class="va">latex2exp</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<section id="introduzione" class="level2" data-number="70.1"><h2 data-number="70.1" class="anchored" data-anchor-id="introduzione">
<span class="header-section-number">70.1</span> Introduzione</h2>
<p>All’interno della teoria della risposta agli item (IRT), il <strong>modello di Rasch</strong> rappresenta l’approccio più restrittivo, poiché impone vincoli stringenti sulle relazioni tra abilità delle persone e difficoltà degli item. Questi vincoli garantiscono semplicità e proprietà matematiche utili, ma limitano la flessibilità del modello nel rappresentare dati complessi.</p>
<p>Progressivamente, tali restrizioni possono essere allentate per definire modelli più flessibili:</p>
<ul>
<li>Il <strong>modello 1PL (One-Parameter Logistic)</strong>, che conserva l’assunzione di uguale discriminazione tra gli item ma non richiede tutte le proprietà rigorose del modello di Rasch.<br>
</li>
<li>Il <strong>modello 2PL (Two-Parameter Logistic)</strong>, che introduce un parametro aggiuntivo per descrivere la capacità discriminante degli item, consentendo una rappresentazione più accurata delle risposte.<br>
</li>
<li>Il <strong>modello 3PL (Three-Parameter Logistic)</strong>, che aggiunge un terzo parametro per tenere conto della probabilità di risposta corretta casuale (detta anche “guessing”).</li>
</ul>
<p>Questa progressione da Rasch a 1PL, 2PL e 3PL permette una maggiore adattabilità del modello IRT, bilanciando semplicità e flessibilità a seconda delle esigenze specifiche dei dati e dell’analisi.</p>
</section><section id="un-esempio-pratico" class="level2" data-number="70.2"><h2 data-number="70.2" class="anchored" data-anchor-id="un-esempio-pratico">
<span class="header-section-number">70.2</span> Un Esempio Pratico</h2>
<p>In questo capitolo, utilizzeremo nuovamente i dati che abbiamo esaminato in precedenza nel <a href="03_estimation.html" class="quarto-xref"><span>Capitolo 69</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">data.fims.Aus.Jpn.scored</span>, package <span class="op">=</span> <span class="st">"TAM"</span><span class="op">)</span></span>
<span><span class="va">fims</span> <span class="op">&lt;-</span> <span class="va">data.fims.Aus.Jpn.scored</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Il data set include 400 partecipanti. Per facilitare la manipolazione dei dati, cambiamo il nome delle colonne.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">responses</span> <span class="op">&lt;-</span> <span class="va">fims</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">400</span>, <span class="fl">2</span><span class="op">:</span><span class="fl">15</span><span class="op">]</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">responses</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/grep.html">gsub</a></span><span class="op">(</span><span class="st">"M1PTI"</span>, <span class="st">"I"</span>, <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">responses</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu">glimpse</span><span class="op">(</span><span class="va">responses</span><span class="op">)</span></span>
<span><span class="co">#&gt; Rows: 400</span></span>
<span><span class="co">#&gt; Columns: 14</span></span>
<span><span class="co">#&gt; $ I1  &lt;dbl&gt; 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,…</span></span>
<span><span class="co">#&gt; $ I2  &lt;dbl&gt; 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,…</span></span>
<span><span class="co">#&gt; $ I3  &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,…</span></span>
<span><span class="co">#&gt; $ I6  &lt;dbl&gt; 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,…</span></span>
<span><span class="co">#&gt; $ I7  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…</span></span>
<span><span class="co">#&gt; $ I11 &lt;dbl&gt; 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,…</span></span>
<span><span class="co">#&gt; $ I12 &lt;dbl&gt; 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…</span></span>
<span><span class="co">#&gt; $ I14 &lt;dbl&gt; 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,…</span></span>
<span><span class="co">#&gt; $ I17 &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,…</span></span>
<span><span class="co">#&gt; $ I18 &lt;dbl&gt; 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,…</span></span>
<span><span class="co">#&gt; $ I19 &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…</span></span>
<span><span class="co">#&gt; $ I21 &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,…</span></span>
<span><span class="co">#&gt; $ I22 &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,…</span></span>
<span><span class="co">#&gt; $ I23 &lt;dbl&gt; 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,…</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Definiamo il fattore <code>gender</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">gender</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">fims</span><span class="op">$</span><span class="va">SEX</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">400</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">gender</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"male"</span>, <span class="st">"female"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">gender</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; gender</span></span>
<span><span class="co">#&gt;   male female </span></span>
<span><span class="co">#&gt;    246    154</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="modello-1pl" class="level2" data-number="70.3"><h2 data-number="70.3" class="anchored" data-anchor-id="modello-1pl">
<span class="header-section-number">70.3</span> Modello 1PL</h2>
<p>Il <strong>modello ad un parametro logistico (1PL)</strong> descrive la probabilità che un rispondente con un certo livello di abilità dia una risposta corretta a un item specifico. La formula del modello è:</p>
<p><span class="math display">\[
P(X_i = 1 \mid \theta_v, \alpha, \delta_i) = \frac{\exp(\alpha(\theta_v - \delta_i))}{1 + \exp(\alpha(\theta_v - \delta_i))} = \frac{1}{1 + \exp(-\alpha(\theta_v - \delta_i))}, \tag{1}
\]</span></p>
<p>dove:</p>
<ul>
<li>
<span class="math inline">\(\theta_v\)</span> è il livello di abilità del rispondente <span class="math inline">\(v\)</span>,</li>
<li>
<span class="math inline">\(\delta_i\)</span> è il parametro di difficoltà dell’item <span class="math inline">\(i\)</span>,</li>
<li>
<span class="math inline">\(\alpha\)</span> è il parametro di discriminazione dell’item, fissato e uguale per tutti gli item nel modello 1PL.</li>
</ul>
<p>L’assunzione fondamentale del modello 1PL è che <strong><span class="math inline">\(\alpha\)</span> sia costante</strong> per tutti gli item, indicando che tutti gli item hanno la stessa capacità di discriminazione tra rispondenti con abilità diverse.</p>
<section id="il-ruolo-del-parametro-alpha" class="level3" data-number="70.3.1"><h3 data-number="70.3.1" class="anchored" data-anchor-id="il-ruolo-del-parametro-alpha">
<span class="header-section-number">70.3.1</span> Il Ruolo del Parametro <span class="math inline">\(\alpha\)</span>
</h3>
<p>Il parametro <span class="math inline">\(\alpha\)</span> definisce la pendenza della curva caratteristica dell’item (ICC). Maggiore è <span class="math inline">\(\alpha\)</span>, più ripida è la curva ICC, e maggiore è la capacità dell’item di discriminare tra rispondenti con abilità vicine alla difficoltà dell’item (<span class="math inline">\(\delta_i\)</span>).</p>
<ul>
<li>
<span class="math inline">\(\alpha = 0\)</span>: L’item non discrimina affatto; la probabilità di risposta corretta è costante e indipendente dal livello di abilità.</li>
<li>
<span class="math inline">\(\alpha &gt; 0\)</span>: L’item discrimina, e la sua capacità discriminatoria cresce con l’aumento di <span class="math inline">\(\alpha\)</span>.</li>
</ul></section><section id="esempio-pratico" class="level3" data-number="70.3.2"><h3 data-number="70.3.2" class="anchored" data-anchor-id="esempio-pratico">
<span class="header-section-number">70.3.2</span> Esempio Pratico</h3>
<p>Consideriamo tre item (<span class="math inline">\(i_1\)</span>, <span class="math inline">\(i_2\)</span>, <span class="math inline">\(i_3\)</span>) con la stessa difficoltà <span class="math inline">\(\delta = 0\)</span> e tre valori di discriminazione: <span class="math inline">\(\alpha_1 = 0.0\)</span>, <span class="math inline">\(\alpha_2 = 1.0\)</span> e <span class="math inline">\(\alpha_3 = 2.0\)</span>. Esaminiamo due rispondenti con livelli di abilità:</p>
<ul>
<li>Rispondente A con <span class="math inline">\(\theta_A = -1\)</span>,</li>
<li>Rispondente B con <span class="math inline">\(\theta_B = 1\)</span>.</li>
</ul>
<p><strong>Item con $= 0.0</strong></p>
<p>Con <span class="math inline">\(\alpha = 0\)</span>, la probabilità di risposta corretta è costante, pari a 0.5 per tutti i livelli di abilità:</p>
<p><span class="math display">\[
P(X_i = 1 \mid \theta, \delta) = 0.5.
\]</span></p>
<p>Questo item non discrimina tra rispondenti con abilità diverse e non aggiunge alcuna informazione utile.</p>
<p><strong>Item con <span class="math inline">\(\alpha\)</span> = 1.0</strong></p>
<p>Con <span class="math inline">\(\alpha = 1.0\)</span>, la probabilità di risposta corretta dipende dal livello di abilità:</p>
<p><span class="math display">\[
P(X_i = 1 \mid \theta, \delta) = \frac{1}{1 + \exp(-(\theta - \delta))}.
\]</span></p>
<ul>
<li>Per <span class="math inline">\(\theta_A = -1\)</span>: <span class="math inline">\(P(X_i = 1) \approx 0.269\)</span>,</li>
<li>Per <span class="math inline">\(\theta_B = 1\)</span>: <span class="math inline">\(P(X_i = 1) \approx 0.731\)</span>.</li>
</ul>
<p>La curva ICC è moderatamente ripida e l’item discrimina tra rispondenti con abilità diverse.</p>
<p><strong>Item con <span class="math inline">\(\alpha\)</span> = 2.0</strong></p>
<p>Con <span class="math inline">\(\alpha = 2.0\)</span>, l’ICC diventa più ripida:</p>
<p><span class="math display">\[
P(X_i = 1 \mid \theta, \delta) = \frac{1}{1 + \exp(-2(\theta - \delta))}.
\]</span></p>
<ul>
<li>Per <span class="math inline">\(\theta_A = -1\)</span>: <span class="math inline">\(P(X_i = 1) \approx 0.119\)</span>,</li>
<li>Per <span class="math inline">\(\theta_B = 1\)</span>: <span class="math inline">\(P(X_i = 1) \approx 0.881\)</span>.</li>
</ul>
<p>La maggiore ripidità riflette una capacità discriminatoria più alta, permettendo di distinguere con maggiore precisione i rispondenti in base alle loro abilità.</p>
<p>In conclusione, nel modello 1PL, il parametro <span class="math inline">\(\alpha\)</span> controlla la capacità degli item di discriminare tra rispondenti con abilità diverse. Un aumento di <span class="math inline">\(\alpha\)</span> rende la curva ICC più ripida, migliorando la discriminazione, mentre un <span class="math inline">\(\alpha\)</span> più basso rende la curva piatta e riduce la capacità informativa dell’item. Tuttavia, nel 1PL, l’assunzione che <span class="math inline">\(\alpha\)</span> sia costante per tutti gli item rappresenta un limite rispetto ai modelli più complessi, come il 2PL, che permettono a ogni item di avere una discriminazione diversa.</p>
</section><section id="modello-di-rasch-e-modello-1pl-confronto-e-differenze" class="level3" data-number="70.3.3"><h3 data-number="70.3.3" class="anchored" data-anchor-id="modello-di-rasch-e-modello-1pl-confronto-e-differenze">
<span class="header-section-number">70.3.3</span> Modello di Rasch e Modello 1PL: Confronto e Differenze</h3>
<p>Il modello di Rasch e il modello 1PL (One-Parameter Logistic) sono due approcci alla misurazione che condividono una struttura matematica simile. Entrambi utilizzano un parametro di discriminazione (α) costante per tutti gli item, pur permettendo variazioni nei parametri di difficoltà (δᵢ).</p>
<p>La differenza tecnica principale sta nel valore del parametro α:</p>
<ul>
<li>Nel modello di Rasch, α è sempre fissato a 1.0</li>
<li>Nel modello 1PL, α può assumere qualsiasi valore costante, anche diverso da 1.0</li>
</ul>
<p>Matematicamente, i due modelli sono equivalenti: è possibile convertire i parametri da un modello all’altro attraverso una semplice riscalatura, moltiplicando o dividendo θᵥ e δᵢ per α, mantenendo invariate le probabilità di risposta corretta.</p>
<p>Nonostante la loro equivalenza matematica, i due modelli si distinguono per filosofia e obiettivi:</p>
<p>Il modello 1PL si concentra sull’adattamento ai dati empirici:</p>
<ul>
<li>Mira a descrivere al meglio i dati osservati</li>
<li>Offre flessibilità nella scelta del parametro α</li>
<li>Si adatta ai dati esistenti</li>
</ul>
<p>Il modello di Rasch privilegia la misurazione oggettiva:</p>
<ul>
<li>Pone l’enfasi sulla costruzione di misure stabili e generalizzabili</li>
<li>Considera il modello come uno standard di riferimento</li>
<li>Richiede che i dati si conformino al modello, non viceversa</li>
<li>Si pone come strumento per sviluppare misurazioni valide e oggettive</li>
</ul>
<p>In sintesi, mentre il modello 1PL è più orientato alla descrizione statistica dei dati, il modello di Rasch si propone come standard per la costruzione di strumenti di misurazione oggettivi e universalmente applicabili.</p>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Esercizio 70.1</strong></span> In <span class="math inline">\(\mathsf{R}\)</span>, il modello di Rasch si implementa nel modo seguente:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mirt_rm</span> <span class="op">&lt;-</span> <span class="fu">mirt</span><span class="op">(</span><span class="va">responses</span>, <span class="fl">1</span>, <span class="st">"Rasch"</span>, verbose <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Il modello 1PL si implementa nel modo seguente:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mirt_1pl</span> <span class="op">&lt;-</span> <span class="fu">mirt</span><span class="op">(</span><span class="va">responses</span>, <span class="fl">1</span>, <span class="st">"1PL"</span>, verbose <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Confrontiamo i due modelli:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mirt_rm</span>, <span class="va">mirt_1pl</span><span class="op">)</span></span>
<span><span class="co">#&gt;           AIC SABIC   HQ  BIC logLik     X2 df   p</span></span>
<span><span class="co">#&gt; mirt_rm  5663  5675 5687 5723  -2816              </span></span>
<span><span class="co">#&gt; mirt_1pl 5662  5673 5684 5718  -2817 -0.705 -1 NaN</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I modelli <code>mirt_rm</code> e <code>mirt_1pl</code> sono praticamente equivalenti in termini di adattamento ai dati. Il modello <code>mirt_1pl</code> mostra lievi miglioramenti nei criteri di informazione (AIC e BIC), ma la differenza è minima.</p>
</div>
</section><section id="modello-2pl" class="level3" data-number="70.3.4"><h3 data-number="70.3.4" class="anchored" data-anchor-id="modello-2pl">
<span class="header-section-number">70.3.4</span> Modello 2PL</h3>
<p>Il <strong>modello 2PL</strong> (Modello IRT a due parametri) rappresenta un’estensione del modello 1PL che consente una maggiore flessibilità, poiché permette alle Curve Caratteristiche degli Item (ICC) di avere pendenze diverse. Questo significa che, a differenza del modello 1PL e del modello di Rasch, le ICC degli item non sono necessariamente parallele. Nel modello 2PL, ogni item è descritto da due parametri fondamentali:</p>
<ol type="1">
<li>
<strong>Parametro di difficoltà (<span class="math inline">\(b\)</span>):</strong> Indica il livello di abilità (<span class="math inline">\(\theta\)</span>) a cui la probabilità di risposta corretta è del 50%. Determina il posizionamento della curva ICC lungo l’asse delle abilità.</li>
<li>
<strong>Parametro di discriminazione (<span class="math inline">\(a\)</span>):</strong> Regola la pendenza della curva ICC, rappresentando la capacità dell’item di distinguere tra rispondenti con abilità simili. Un valore più alto di <span class="math inline">\(a\)</span> indica una maggiore sensibilità dell’item alle variazioni di abilità.</li>
</ol>
<p>La formula generale per le ICC nel modello 2PL è:</p>
<p><span class="math display">\[
P(X_i = 1 \mid \theta, a_i, b_i) = \frac{1}{1 + \exp(-a_i (\theta - b_i))},
\]</span></p>
<p>dove:</p>
<ul>
<li>
<span class="math inline">\(\theta\)</span> rappresenta l’abilità del rispondente,</li>
<li>
<span class="math inline">\(a_i\)</span> è il parametro di discriminazione per l’item <span class="math inline">\(i\)</span>,</li>
<li>
<span class="math inline">\(b_i\)</span> è il parametro di difficoltà per l’item <span class="math inline">\(i\)</span>.</li>
</ul></section><section id="implementazione-in-r-con-il-pacchetto-mirt" class="level3" data-number="70.3.5"><h3 data-number="70.3.5" class="anchored" data-anchor-id="implementazione-in-r-con-il-pacchetto-mirt">
<span class="header-section-number">70.3.5</span> Implementazione in R con il Pacchetto <code>mirt</code>
</h3>
<p>Utilizziamo il pacchetto <strong>mirt</strong> per adattare il modello 2PL ai dati. Il comando <code>mirt()</code> permette di stimare i parametri specificando il modello 2PL:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>mirt_2pl <span class="ot">&lt;-</span> <span class="fu">mirt</span>(responses, <span class="dv">1</span>, <span class="st">"2PL"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>Iteration<span class="sc">:</span> <span class="dv">1</span>, Log<span class="sc">-</span>Lik<span class="sc">:</span> <span class="sc">-</span><span class="fl">2818.855</span>, Max<span class="sc">-</span>Change<span class="sc">:</span> <span class="fl">0.66304</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>Iteration<span class="sc">:</span> <span class="dv">2</span>, Log<span class="sc">-</span>Lik<span class="sc">:</span> <span class="sc">-</span><span class="fl">2772.597</span>, Max<span class="sc">-</span>Change<span class="sc">:</span> <span class="fl">0.26013</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>Iteration<span class="sc">:</span> <span class="dv">3</span>, Log<span class="sc">-</span>Lik<span class="sc">:</span> <span class="sc">-</span><span class="fl">2762.517</span>, Max<span class="sc">-</span>Change<span class="sc">:</span> <span class="fl">0.12884</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>Iteration<span class="sc">:</span> <span class="dv">4</span>, Log<span class="sc">-</span>Lik<span class="sc">:</span> <span class="sc">-</span><span class="fl">2760.353</span>, Max<span class="sc">-</span>Change<span class="sc">:</span> <span class="fl">0.06587</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>Iteration<span class="sc">:</span> <span class="dv">5</span>, Log<span class="sc">-</span>Lik<span class="sc">:</span> <span class="sc">-</span><span class="fl">2759.824</span>, Max<span class="sc">-</span>Change<span class="sc">:</span> <span class="fl">0.03961</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>Iteration<span class="sc">:</span> <span class="dv">6</span>, Log<span class="sc">-</span>Lik<span class="sc">:</span> <span class="sc">-</span><span class="fl">2759.675</span>, Max<span class="sc">-</span>Change<span class="sc">:</span> <span class="fl">0.02169</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>Iteration<span class="sc">:</span> <span class="dv">7</span>, Log<span class="sc">-</span>Lik<span class="sc">:</span> <span class="sc">-</span><span class="fl">2759.622</span>, Max<span class="sc">-</span>Change<span class="sc">:</span> <span class="fl">0.01040</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>Iteration<span class="sc">:</span> <span class="dv">8</span>, Log<span class="sc">-</span>Lik<span class="sc">:</span> <span class="sc">-</span><span class="fl">2759.609</span>, Max<span class="sc">-</span>Change<span class="sc">:</span> <span class="fl">0.00642</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>Iteration<span class="sc">:</span> <span class="dv">9</span>, Log<span class="sc">-</span>Lik<span class="sc">:</span> <span class="sc">-</span><span class="fl">2759.605</span>, Max<span class="sc">-</span>Change<span class="sc">:</span> <span class="fl">0.00396</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>Iteration<span class="sc">:</span> <span class="dv">10</span>, Log<span class="sc">-</span>Lik<span class="sc">:</span> <span class="sc">-</span><span class="fl">2759.602</span>, Max<span class="sc">-</span>Change<span class="sc">:</span> <span class="fl">0.00160</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>Iteration<span class="sc">:</span> <span class="dv">11</span>, Log<span class="sc">-</span>Lik<span class="sc">:</span> <span class="sc">-</span><span class="fl">2759.602</span>, Max<span class="sc">-</span>Change<span class="sc">:</span> <span class="fl">0.00089</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>Iteration<span class="sc">:</span> <span class="dv">12</span>, Log<span class="sc">-</span>Lik<span class="sc">:</span> <span class="sc">-</span><span class="fl">2759.602</span>, Max<span class="sc">-</span>Change<span class="sc">:</span> <span class="fl">0.00064</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>Iteration<span class="sc">:</span> <span class="dv">13</span>, Log<span class="sc">-</span>Lik<span class="sc">:</span> <span class="sc">-</span><span class="fl">2759.601</span>, Max<span class="sc">-</span>Change<span class="sc">:</span> <span class="fl">0.00020</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>Iteration<span class="sc">:</span> <span class="dv">14</span>, Log<span class="sc">-</span>Lik<span class="sc">:</span> <span class="sc">-</span><span class="fl">2759.601</span>, Max<span class="sc">-</span>Change<span class="sc">:</span> <span class="fl">0.00009</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Per analizzare graficamente le Curve Caratteristiche degli Item, usiamo la funzione <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">mirt_2pl</span>, type <span class="op">=</span> <span class="st">"trace"</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04_1pl_2pl_3pl_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>Se desideriamo visualizzare tutte le ICC in un unico grafico, senza separarle per item, aggiungiamo l’opzione <code>facet_items = FALSE</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">mirt_2pl</span>, type <span class="op">=</span> <span class="st">"trace"</span>, facet_items <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04_1pl_2pl_3pl_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>La funzione <code><a href="https://rdrr.io/r/stats/coef.html">coef()</a></code> consente di ottenere le stime dei parametri degli item:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">mirt_2pl</span>, IRTpars <span class="op">=</span> <span class="cn">TRUE</span>, simplify <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="co">#&gt; $items</span></span>
<span><span class="co">#&gt;          a      b g u</span></span>
<span><span class="co">#&gt; I1   1.147 -1.022 0 1</span></span>
<span><span class="co">#&gt; I2   1.769 -0.911 0 1</span></span>
<span><span class="co">#&gt; I3   1.372 -1.680 0 1</span></span>
<span><span class="co">#&gt; I6   1.479 -0.043 0 1</span></span>
<span><span class="co">#&gt; I7   1.071  2.441 0 1</span></span>
<span><span class="co">#&gt; I11  1.594 -0.957 0 1</span></span>
<span><span class="co">#&gt; I12  0.703  1.079 0 1</span></span>
<span><span class="co">#&gt; I14  0.771 -0.612 0 1</span></span>
<span><span class="co">#&gt; I17  0.707  1.758 0 1</span></span>
<span><span class="co">#&gt; I18  0.750 -0.502 0 1</span></span>
<span><span class="co">#&gt; I19  1.831  1.459 0 1</span></span>
<span><span class="co">#&gt; I21 -0.214 -7.076 0 1</span></span>
<span><span class="co">#&gt; I22  0.277  7.657 0 1</span></span>
<span><span class="co">#&gt; I23  1.521 -1.503 0 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $means</span></span>
<span><span class="co">#&gt; F1 </span></span>
<span><span class="co">#&gt;  0 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $cov</span></span>
<span><span class="co">#&gt;    F1</span></span>
<span><span class="co">#&gt; F1  1</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Queste stime includono:</p>
<ul>
<li>
<span class="math inline">\(a\)</span>, parametro di discriminazione,</li>
<li>
<span class="math inline">\(b\)</span>, parametro di difficoltà.</li>
</ul></section><section id="confronto-tra-modello-1pl-e-modello-2pl" class="level3" data-number="70.3.6"><h3 data-number="70.3.6" class="anchored" data-anchor-id="confronto-tra-modello-1pl-e-modello-2pl">
<span class="header-section-number">70.3.6</span> Confronto tra Modello 1PL e Modello 2PL</h3>
<p>Per valutare quale modello si adatta meglio ai dati, confrontiamo il modello 1PL (discriminazione fissa) con il modello 2PL (discriminazione variabile) utilizzando la funzione <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mirt_rm</span>, <span class="va">mirt_2pl</span><span class="op">)</span></span>
<span><span class="co">#&gt;           AIC SABIC   HQ  BIC logLik     X2 df p</span></span>
<span><span class="co">#&gt; mirt_rm  5663  5675 5687 5723  -2816            </span></span>
<span><span class="co">#&gt; mirt_2pl 5575  5598 5619 5687  -2760 113.77 13 0</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Interpretazione dei Risultati</strong></p>
<ol type="1">
<li>
<strong>Criteri di Informazione (AIC e BIC):</strong> Il modello 2PL tipicamente mostra valori di AIC e BIC più bassi rispetto al modello 1PL, indicando un miglior adattamento ai dati.</li>
<li>
<strong>Log-Likelihood:</strong> Il modello 2PL presenta un log-likelihood superiore rispetto al modello 1PL, a indicare una maggiore probabilità di osservare i dati sotto il modello 2PL.</li>
<li>
<strong>Test di <span class="math inline">\(X^2\)</span>:</strong> Se il p-value associato è significativo (<span class="math inline">\(p &lt; 0.05\)</span>), ciò suggerisce che il modello 2PL spiega significativamente più variazione rispetto al modello 1PL.</li>
</ol></section><section id="differenze-chiave-tra-modello-1pl-e-modello-2pl" class="level3" data-number="70.3.7"><h3 data-number="70.3.7" class="anchored" data-anchor-id="differenze-chiave-tra-modello-1pl-e-modello-2pl">
<span class="header-section-number">70.3.7</span> Differenze Chiave tra Modello 1PL e Modello 2PL</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 37%">
<col style="width: 37%">
</colgroup>
<thead><tr class="header">
<th><strong>Caratteristica</strong></th>
<th><strong>Modello 1PL</strong></th>
<th><strong>Modello 2PL</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Parametro di discriminazione (<span class="math inline">\(a\)</span>)</strong></td>
<td>Fisso per tutti gli item (<span class="math inline">\(a = \alpha\)</span> costante)</td>
<td>Variabile tra gli item (<span class="math inline">\(a_i\)</span> specifico)</td>
</tr>
<tr class="even">
<td><strong>Curva ICC</strong></td>
<td>Tutte le curve ICC sono parallele</td>
<td>Le curve ICC possono avere pendenze diverse</td>
</tr>
<tr class="odd">
<td><strong>Adattamento ai dati</strong></td>
<td>Meno flessibile, buono per dati uniformi</td>
<td>Più flessibile, cattura differenze di discriminazione</td>
</tr>
</tbody>
</table>
<p>In conclusione, il modello 2PL è particolarmente utile quando gli item differiscono nella loro capacità di discriminare tra rispondenti con abilità simili. Questo lo rende una scelta preferibile rispetto al modello 1PL in situazioni in cui gli item non sono omogenei in termini di discriminazione. Tuttavia, la maggiore flessibilità del modello 2PL comporta una maggiore complessità e richiede un dataset con sufficiente variabilità per stimare accuratamente i parametri <span class="math inline">\(a_i\)</span> e <span class="math inline">\(b_i\)</span>.</p>
</section></section><section id="modello-3pl" class="level2" data-number="70.4"><h2 data-number="70.4" class="anchored" data-anchor-id="modello-3pl">
<span class="header-section-number">70.4</span> Modello 3PL</h2>
<p>Il <strong>modello IRT a tre parametri (3PL)</strong> è un’estensione del modello 2PL che aggiunge un terzo parametro, il <strong>guessing</strong> (<span class="math inline">\(g\)</span>), per tenere conto della probabilità di rispondere correttamente a un item semplicemente per caso. Questo parametro è particolarmente utile nei test a scelta multipla, dove i rispondenti con abilità molto bassa possono comunque selezionare la risposta corretta in modo casuale.</p>
<p>La probabilità di risposta corretta nel modello 3PL è espressa come:</p>
<p><span class="math display">\[
P(X_i = 1 \mid \theta, a_i, b_i, g_i) = g_i + (1 - g_i) \cdot \frac{1}{1 + \exp(-a_i (\theta - b_i))},
\]</span></p>
<p>dove:</p>
<ul>
<li>
<span class="math inline">\(\theta\)</span>: abilità latente del rispondente,</li>
<li>
<span class="math inline">\(a_i\)</span>: parametro di discriminazione dell’item <span class="math inline">\(i\)</span> (controlla la pendenza della curva ICC),</li>
<li>
<span class="math inline">\(b_i\)</span>: parametro di difficoltà dell’item <span class="math inline">\(i\)</span> (indica il livello di abilità richiesto per una probabilità del 50% di risposta corretta, escludendo il guessing),</li>
<li>
<span class="math inline">\(g_i\)</span>: parametro di guessing (probabilità minima di rispondere correttamente a un item, anche per rispondenti con abilità molto bassa).</li>
</ul>
<section id="caratteristiche-del-modello-3pl" class="level3" data-number="70.4.1"><h3 data-number="70.4.1" class="anchored" data-anchor-id="caratteristiche-del-modello-3pl">
<span class="header-section-number">70.4.1</span> Caratteristiche del Modello 3PL</h3>
<ol type="1">
<li>
<strong>Parametro di Guessing (<span class="math inline">\(g\)</span>):</strong>
<ul>
<li>Introduce un asintoto inferiore maggiore di zero nella curva caratteristica dell’item (ICC).</li>
<li>Ad esempio, un valore <span class="math inline">\(g_i = 0.25\)</span> indica che, anche per abilità molto basse (<span class="math inline">\(\theta \to -\infty\)</span>), la probabilità di rispondere correttamente all’item è almeno del 25%. Questo valore è tipico per test a scelta multipla con quattro opzioni, dove c’è il 25% di probabilità di indovinare.</li>
</ul>
</li>
<li>
<strong>Relazione con il Modello 2PL:</strong>
<ul>
<li>Il modello 3PL generalizza il modello 2PL aggiungendo il parametro <span class="math inline">\(g\)</span>, che aumenta la flessibilità per rappresentare meglio il comportamento degli item in situazioni reali.</li>
<li>Mentre nel modello 2PL la probabilità di risposta corretta può scendere a zero per abilità molto basse, nel modello 3PL la probabilità minima è definita da <span class="math inline">\(g\)</span>.</li>
</ul>
</li>
<li>
<strong>Curve Caratteristiche degli Item (ICC):</strong>
<ul>
<li>La presenza del parametro <span class="math inline">\(g\)</span> modifica la forma della curva ICC, che non tocca mai lo zero ma si avvicina asintoticamente al valore di <span class="math inline">\(g\)</span> per <span class="math inline">\(\theta\)</span> molto basso.</li>
</ul>
</li>
<li>
<strong>Complessità del Modello:</strong>
<ul>
<li>L’aggiunta del parametro <span class="math inline">\(g\)</span> rende il modello più complesso rispetto al 2PL, aumentando il numero di parametri da stimare.</li>
<li>Per ottenere stime affidabili, è necessario disporre di un dataset con un numero sufficiente di item e rispondenti.</li>
</ul>
</li>
</ol>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Esercizio 70.2</strong></span> Utilizziamo il pacchetto <strong>mirt</strong> per stimare i parametri del modello 3PL:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mirt_3pl</span> <span class="op">&lt;-</span> <span class="fu">mirt</span><span class="op">(</span><span class="va">responses</span>, <span class="fl">1</span>, <span class="st">"3PL"</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Le curve ICC possono essere visualizzate con il comando:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">mirt_3pl</span>, type <span class="op">=</span> <span class="st">"trace"</span>, facet_items <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04_1pl_2pl_3pl_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>Utilizziamo la funzione <code><a href="https://rdrr.io/r/stats/coef.html">coef()</a></code> per ottenere le stime dei parametri degli item (<span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span>, <span class="math inline">\(g\)</span>):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">mirt_3pl</span>, IRTpars <span class="op">=</span> <span class="cn">TRUE</span>, simplify <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="co">#&gt; $items</span></span>
<span><span class="co">#&gt;          a      b     g u</span></span>
<span><span class="co">#&gt; I1   1.410 -0.493 0.244 1</span></span>
<span><span class="co">#&gt; I2   2.667 -0.404 0.291 1</span></span>
<span><span class="co">#&gt; I3   1.445 -1.633 0.000 1</span></span>
<span><span class="co">#&gt; I6   1.514  0.009 0.019 1</span></span>
<span><span class="co">#&gt; I7   1.163  2.297 0.000 1</span></span>
<span><span class="co">#&gt; I11  1.487 -0.984 0.000 1</span></span>
<span><span class="co">#&gt; I12  2.131  1.275 0.207 1</span></span>
<span><span class="co">#&gt; I14  0.805 -0.586 0.000 1</span></span>
<span><span class="co">#&gt; I17  3.076  1.320 0.138 1</span></span>
<span><span class="co">#&gt; I18  0.724 -0.510 0.000 1</span></span>
<span><span class="co">#&gt; I19  1.844  1.449 0.000 1</span></span>
<span><span class="co">#&gt; I21 -5.264 -2.271 0.167 1</span></span>
<span><span class="co">#&gt; I22  9.179  1.990 0.090 1</span></span>
<span><span class="co">#&gt; I23  1.625 -1.452 0.000 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $means</span></span>
<span><span class="co">#&gt; F1 </span></span>
<span><span class="co">#&gt;  0 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $cov</span></span>
<span><span class="co">#&gt;    F1</span></span>
<span><span class="co">#&gt; F1  1</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Confronto tra modelli 2PL e 3PL</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mirt_2pl</span>, <span class="va">mirt_3pl</span><span class="op">)</span></span>
<span><span class="co">#&gt;           AIC SABIC   HQ  BIC logLik     X2 df p</span></span>
<span><span class="co">#&gt; mirt_2pl 5575  5598 5619 5687  -2760            </span></span>
<span><span class="co">#&gt; mirt_3pl 5564  5599 5631 5732  -2740 38.784 14 0</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Il <strong>modello 3PL</strong> presenta un AIC inferiore rispetto al modello 2PL, suggerendo un miglior adattamento ai dati.</li>
<li>Tuttavia, il BIC penalizza maggiormente la complessità del modello, favorendo leggermente il modello 2PL.</li>
<li>La significatività del test <span class="math inline">\(X^2\)</span> (<span class="math inline">\(p = 0.0004\)</span>) indica che il modello 3PL offre un miglioramento significativo rispetto al modello 2PL.</li>
</ul>
<p><strong>Valutazione della bontà dell’adattamento</strong></p>
<p>Per verificare se il modello 3PL rappresenta adeguatamente i dati, utilizziamo la statistica <span class="math inline">\(M2\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">M2</span><span class="op">(</span><span class="va">mirt_3pl</span><span class="op">)</span></span>
<span><span class="co">#&gt;          M2 df     p  RMSEA RMSEA_5 RMSEA_95   SRMSR    TLI    CFI</span></span>
<span><span class="co">#&gt; stats 76.06 63 0.125 0.0228       0  0.03944 0.04533 0.9751 0.9827</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Il valore <span class="math inline">\(p = 0.125\)</span> indica che il modello 3PL non può essere rifiutato come rappresentazione adeguata dei dati.</li>
<li>Il <strong>RMSEA</strong> inferiore a 0.05 (limite superiore: 0.039) suggerisce un buon adattamento.</li>
</ul>
<p><strong>Adattamento degli item</strong></p>
<p>Il comando <code>itemfit()</code> calcola le statistiche di adattamento (fit) per ciascun item del modello 3PL, fornendo i valori di infit e outfit insieme ai relativi z-score che indicano quanto questi valori si discostano da quelli attesi secondo una distribuzione normale standardizzata.</p>
<ul>
<li>L’infit (<em>Information-weighted fit</em>) si concentra principalmente sui rispondenti con un livello di abilità simile alla difficoltà dell’item, ed è quindi particolarmente sensibile alle discrepanze nella “zona di interesse” dell’item, dove la probabilità di risposta corretta si aggira intorno al 50%.</li>
<li>L’outfit (<em>Outlier-sensitive fit</em>) invece considera tutti i rispondenti, inclusi quelli con abilità molto diverse dalla difficoltà dell’item, risultando più sensibile a risposte inaspettate o estreme.</li>
</ul>
<p>Per entrambe le statistiche, valori compresi tra 0.7 e 1.3 indicano un buon adattamento dell’item al modello. Valori inferiori a 0.7 suggeriscono che l’item è troppo prevedibile o ridondante, mentre valori superiori a 1.3 indicano la presenza di risposte inaspettate. Per quanto riguarda gli z-score, valori con modulo inferiore a 2 sono considerati accettabili, mentre valori superiori potrebbero indicare problemi di adattamento.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">itemfit</span><span class="op">(</span><span class="va">mirt_3pl</span>, <span class="st">"infit"</span>, method <span class="op">=</span> <span class="st">"ML"</span><span class="op">)</span> <span class="co"># infit and outfit stats</span></span>
<span><span class="co">#&gt;    item outfit z.outfit infit z.infit</span></span>
<span><span class="co">#&gt; 1    I1  1.005    0.084 0.983  -0.273</span></span>
<span><span class="co">#&gt; 2    I2  0.865   -0.367 0.873  -2.016</span></span>
<span><span class="co">#&gt; 3    I3  0.876   -0.404 0.909  -0.940</span></span>
<span><span class="co">#&gt; 4    I6  0.981   -0.145 0.916  -1.503</span></span>
<span><span class="co">#&gt; 5    I7  0.783   -0.797 0.896  -0.899</span></span>
<span><span class="co">#&gt; 6   I11  1.462    2.383 0.886  -1.567</span></span>
<span><span class="co">#&gt; 7   I12  0.945   -0.929 0.942  -1.157</span></span>
<span><span class="co">#&gt; 8   I14  0.967   -0.565 1.009   0.223</span></span>
<span><span class="co">#&gt; 9   I17  0.784   -2.457 0.807  -2.709</span></span>
<span><span class="co">#&gt; 10  I18  1.025    0.539 1.013   0.349</span></span>
<span><span class="co">#&gt; 11  I19  0.590   -1.393 0.816  -2.165</span></span>
<span><span class="co">#&gt; 12  I21  0.915   -0.983 0.917  -0.963</span></span>
<span><span class="co">#&gt; 13  I22  0.860   -0.978 0.844  -1.160</span></span>
<span><span class="co">#&gt; 14  I23  0.778   -0.736 0.872  -1.370</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Dall’analisi dei risultati emerge che la maggior parte degli item mostra un buon adattamento al modello. In particolare, l’item I1 presenta valori ottimali sia per outfit (1.005) che per infit (0.983), con z-score molto contenuti (0.084 e -0.273 rispettivamente). Anche gli item I3, I6, I14, I18 e I21 mostrano valori di adattamento soddisfacenti, rientrando negli intervalli di accettabilità sia per le statistiche di fit che per gli z-score.</p>
<p>Tuttavia, alcuni item presentano aspetti critici che meritano attenzione. L’item I11 mostra un outfit elevato (1.462) con uno z-score significativo (2.383), suggerendo la presenza di risposte anomale da parte di soggetti con livelli di abilità distanti dalla difficoltà dell’item. L’item I17, pur avendo valori di fit accettabili (outfit = 0.784, infit = 0.807), presenta uno z-score problematico per l’infit (-2.709), indicando possibili discrepanze significative per i rispondenti con abilità vicine alla difficoltà dell’item.</p>
<p>Un caso particolare è rappresentato dall’item I19, che mostra un outfit inferiore alla soglia minima (0.590) e uno z-score dell’infit significativo (-2.165). Questi valori potrebbero indicare che l’item è troppo prevedibile o eccessivamente facile rispetto al livello atteso dal modello.</p>
<p>Nel complesso, sebbene la maggior parte degli item mostri un adattamento soddisfacente, potrebbe essere opportuno rivedere gli item I11, I17 e I19 per migliorare la qualità complessiva dello strumento di misura.</p>
</div>
</section></section><section id="invarianza-di-gruppo-nella-item-response-theory" class="level2" data-number="70.5"><h2 data-number="70.5" class="anchored" data-anchor-id="invarianza-di-gruppo-nella-item-response-theory">
<span class="header-section-number">70.5</span> Invarianza di Gruppo nella Item Response Theory</h2>
<p>L’invarianza di gruppo dei parametri degli item rappresenta una delle caratteristiche più importanti della IRT. Questo principio afferma che le proprietà misurate di un item - come la sua difficoltà, discriminazione e probabilità di indovinare la risposta corretta - sono caratteristiche intrinseche dell’item stesso e rimangono stabili indipendentemente dalla popolazione di riferimento.</p>
<p>Per comprendere meglio questo concetto, consideriamo un esempio concreto. Immaginiamo di somministrare lo stesso test a due gruppi distinti di esaminandi:</p>
<ul>
<li>il primo gruppo è composto da individui con abilità relativamente bassa, con punteggi che variano tra -3 e -1 sulla scala di abilità (con una media di -2);</li>
<li>il secondo gruppo invece include individui con abilità più elevata, con punteggi tra +1 e +3 (media +2).</li>
</ul>
<p>Quando analizziamo le risposte utilizzando il metodo della massima verosimiglianza, osserviamo un fenomeno notevole: per ogni item, otteniamo gli stessi parametri indipendentemente dal gruppo analizzato. Per esempio, se per un determinato item otteniamo un parametro di discriminazione a = 1.27 e un parametro di difficoltà b = 0.39 analizzando l’intero campione, ritroveremo sostanzialmente gli stessi valori anche analizzando separatamente il gruppo con abilità bassa o quello con abilità alta.</p>
<p>Questo risultato ha implicazioni pratiche molto importanti. Significa che:</p>
<ol type="1">
<li>le caratteristiche dell’item rimangono stabili anche quando il test viene somministrato a popolazioni diverse;</li>
<li>possiamo confrontare in modo valido le prestazioni di gruppi diversi sullo stesso item;</li>
<li>le stime dei parametri dell’item sono robuste e generalizzabili;</li>
<li>la calibrazione degli item può essere effettuata su un campione e poi applicata con fiducia a popolazioni diverse.</li>
</ol>
<p>L’invarianza di gruppo rappresenta quindi una proprietà fondamentale che distingue i modelli IRT dai modelli classici della teoria dei test, permettendo confronti più equi e interpretazioni più affidabili dei risultati dei test tra diverse popolazioni.</p>
<p>Questa proprietà è particolarmente utile in contesti pratici, come quando si devono confrontare gruppi culturali diversi, classi scolastiche di diverso livello, o quando si vuole verificare se un test funziona allo stesso modo per popolazioni diverse. L’invarianza garantisce che le differenze osservate riflettano reali differenze nelle abilità misurate, piuttosto che artefatti dovuti alle caratteristiche del campione utilizzato per la calibrazione.</p>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Esercizio 70.3</strong></span> Questo esercizio utilizza una simulazione in R per dimostrare visivamente il principio di invarianza dei parametri degli item nella IRT. La funzione <code>groupinv()</code> simula le risposte di due gruppi distinti di esaminandi e visualizza le loro curve caratteristiche dell’item (ICC).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">groupinv</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">mdl</span>, <span class="va">t1l</span>, <span class="va">t1u</span>, <span class="va">t2l</span>, <span class="va">t2u</span><span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/missing.html">missing</a></span><span class="op">(</span><span class="va">t1l</span><span class="op">)</span><span class="op">)</span> <span class="va">t1l</span> <span class="op">&lt;-</span> <span class="op">-</span><span class="fl">3</span></span>
<span>    <span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/missing.html">missing</a></span><span class="op">(</span><span class="va">t1u</span><span class="op">)</span><span class="op">)</span> <span class="va">t1u</span> <span class="op">&lt;-</span> <span class="op">-</span><span class="fl">1</span></span>
<span>    <span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/missing.html">missing</a></span><span class="op">(</span><span class="va">t2l</span><span class="op">)</span><span class="op">)</span> <span class="va">t2l</span> <span class="op">&lt;-</span> <span class="fl">1</span></span>
<span>    <span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/missing.html">missing</a></span><span class="op">(</span><span class="va">t2u</span><span class="op">)</span><span class="op">)</span> <span class="va">t2u</span> <span class="op">&lt;-</span> <span class="fl">3</span></span>
<span>    <span class="va">theta</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="op">-</span><span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">.1875</span><span class="op">)</span></span>
<span>    <span class="va">f</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">21</span>, <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">theta</span><span class="op">)</span><span class="op">)</span></span>
<span>    <span class="va">wb</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">1</span>, <span class="op">-</span><span class="fl">3</span>, <span class="fl">3</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span></span>
<span>    <span class="va">wa</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">0.2</span>, <span class="fl">2.8</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span></span>
<span>    <span class="va">wc</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">0</span>, <span class="fl">.35</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span></span>
<span>    <span class="kw">if</span> <span class="op">(</span><span class="va">mdl</span> <span class="op">==</span> <span class="fl">1</span> <span class="op">|</span> <span class="va">mdl</span> <span class="op">==</span> <span class="fl">2</span><span class="op">)</span> <span class="op">{</span></span>
<span>        <span class="va">wc</span> <span class="op">&lt;-</span> <span class="fl">0</span></span>
<span>    <span class="op">}</span></span>
<span>    <span class="kw">if</span> <span class="op">(</span><span class="va">mdl</span> <span class="op">==</span> <span class="fl">1</span><span class="op">)</span> <span class="op">{</span></span>
<span>        <span class="va">wa</span> <span class="op">&lt;-</span> <span class="fl">1</span></span>
<span>    <span class="op">}</span></span>
<span>    <span class="kw">for</span> <span class="op">(</span><span class="va">g</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">theta</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>        <span class="va">P</span> <span class="op">&lt;-</span> <span class="va">wc</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">wc</span><span class="op">)</span> <span class="op">/</span> <span class="op">(</span><span class="fl">1</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="op">-</span><span class="va">wa</span> <span class="op">*</span> <span class="op">(</span><span class="va">theta</span> <span class="op">-</span> <span class="va">wb</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span>    <span class="op">}</span></span>
<span>    <span class="va">p</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">theta</span><span class="op">)</span>, <span class="va">f</span>, <span class="va">P</span><span class="op">)</span> <span class="op">/</span> <span class="va">f</span></span>
<span>    <span class="va">lowerg1</span> <span class="op">&lt;-</span> <span class="fl">0</span></span>
<span>    <span class="kw">for</span> <span class="op">(</span><span class="va">g</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">theta</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>        <span class="kw">if</span> <span class="op">(</span><span class="va">theta</span><span class="op">[</span><span class="va">g</span><span class="op">]</span> <span class="op">&lt;=</span> <span class="va">t1l</span><span class="op">)</span> <span class="op">{</span></span>
<span>            <span class="va">lowerg1</span> <span class="op">&lt;-</span> <span class="va">lowerg1</span> <span class="op">+</span> <span class="fl">1</span></span>
<span>        <span class="op">}</span></span>
<span>    <span class="op">}</span></span>
<span>    <span class="va">upperg1</span> <span class="op">&lt;-</span> <span class="fl">0</span></span>
<span>    <span class="kw">for</span> <span class="op">(</span><span class="va">g</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">theta</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>        <span class="kw">if</span> <span class="op">(</span><span class="va">theta</span><span class="op">[</span><span class="va">g</span><span class="op">]</span> <span class="op">&lt;=</span> <span class="va">t1u</span><span class="op">)</span> <span class="op">{</span></span>
<span>            <span class="va">upperg1</span> <span class="op">&lt;-</span> <span class="va">upperg1</span> <span class="op">+</span> <span class="fl">1</span></span>
<span>        <span class="op">}</span></span>
<span>    <span class="op">}</span></span>
<span>    <span class="va">theta1</span> <span class="op">&lt;-</span> <span class="va">theta</span><span class="op">[</span><span class="va">lowerg1</span><span class="op">:</span><span class="va">upperg1</span><span class="op">]</span></span>
<span>    <span class="va">p1</span> <span class="op">&lt;-</span> <span class="va">p</span><span class="op">[</span><span class="va">lowerg1</span><span class="op">:</span><span class="va">upperg1</span><span class="op">]</span></span>
<span>    <span class="va">lowerg2</span> <span class="op">&lt;-</span> <span class="fl">0</span></span>
<span>    <span class="kw">for</span> <span class="op">(</span><span class="va">g</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">theta</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>        <span class="kw">if</span> <span class="op">(</span><span class="va">theta</span><span class="op">[</span><span class="va">g</span><span class="op">]</span> <span class="op">&lt;=</span> <span class="va">t2l</span><span class="op">)</span> <span class="op">{</span></span>
<span>            <span class="va">lowerg2</span> <span class="op">&lt;-</span> <span class="va">lowerg2</span> <span class="op">+</span> <span class="fl">1</span></span>
<span>        <span class="op">}</span></span>
<span>    <span class="op">}</span></span>
<span>    <span class="va">upperg2</span> <span class="op">&lt;-</span> <span class="fl">0</span></span>
<span>    <span class="kw">for</span> <span class="op">(</span><span class="va">g</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">theta</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>        <span class="kw">if</span> <span class="op">(</span><span class="va">theta</span><span class="op">[</span><span class="va">g</span><span class="op">]</span> <span class="op">&lt;=</span> <span class="va">t2u</span><span class="op">)</span> <span class="op">{</span></span>
<span>            <span class="va">upperg2</span> <span class="op">&lt;-</span> <span class="va">upperg2</span> <span class="op">+</span> <span class="fl">1</span></span>
<span>        <span class="op">}</span></span>
<span>    <span class="op">}</span></span>
<span>    <span class="va">theta2</span> <span class="op">&lt;-</span> <span class="va">theta</span><span class="op">[</span><span class="va">lowerg2</span><span class="op">:</span><span class="va">upperg2</span><span class="op">]</span></span>
<span>    <span class="va">p2</span> <span class="op">&lt;-</span> <span class="va">p</span><span class="op">[</span><span class="va">lowerg2</span><span class="op">:</span><span class="va">upperg2</span><span class="op">]</span></span>
<span>    <span class="va">theta12</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">theta1</span>, <span class="va">theta2</span><span class="op">)</span></span>
<span>    <span class="va">p12</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">p1</span>, <span class="va">p2</span><span class="op">)</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>lab <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">7</span>, <span class="fl">5</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">theta12</span>, <span class="va">p12</span>,</span>
<span>        xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">3</span>, <span class="fl">3</span><span class="op">)</span>, ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span>,</span>
<span>        xlab <span class="op">=</span> <span class="st">"Ability"</span>, ylab <span class="op">=</span> <span class="st">"Probability of Correct Response"</span></span>
<span>    <span class="op">)</span></span>
<span>    <span class="kw">if</span> <span class="op">(</span><span class="va">mdl</span> <span class="op">==</span> <span class="fl">1</span><span class="op">)</span> <span class="op">{</span></span>
<span>        <span class="va">maintext</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"Pooled Groups"</span>, <span class="st">"\n"</span>, <span class="st">"b="</span>, <span class="va">wb</span><span class="op">)</span></span>
<span>    <span class="op">}</span></span>
<span>    <span class="kw">if</span> <span class="op">(</span><span class="va">mdl</span> <span class="op">==</span> <span class="fl">2</span><span class="op">)</span> <span class="op">{</span></span>
<span>        <span class="va">maintext</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"Pooled Groups"</span>, <span class="st">"\n"</span>, <span class="st">"a="</span>, <span class="va">wa</span>, <span class="st">"b="</span>, <span class="va">wb</span><span class="op">)</span></span>
<span>    <span class="op">}</span></span>
<span>    <span class="kw">if</span> <span class="op">(</span><span class="va">mdl</span> <span class="op">==</span> <span class="fl">3</span><span class="op">)</span> <span class="op">{</span></span>
<span>        <span class="va">maintext</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span></span>
<span>            <span class="st">"Pooled Groups"</span>, <span class="st">"\n"</span>,</span>
<span>            <span class="st">"a="</span>, <span class="va">wa</span>, <span class="st">"b="</span>, <span class="va">wb</span>, <span class="st">"c="</span>, <span class="va">wc</span></span>
<span>        <span class="op">)</span></span>
<span>    <span class="op">}</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>new <span class="op">=</span> <span class="st">"T"</span><span class="op">)</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">theta</span>, <span class="va">P</span>,</span>
<span>        xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">3</span>, <span class="fl">3</span><span class="op">)</span>, ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span>, type <span class="op">=</span> <span class="st">"l"</span>,</span>
<span>        xlab <span class="op">=</span> <span class="st">""</span>, ylab <span class="op">=</span> <span class="st">""</span>, main <span class="op">=</span> <span class="va">maintext</span></span>
<span>    <span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="fu">groupinv</span><span class="op">(</span><span class="fl">1</span>, <span class="op">-</span><span class="fl">3</span>, <span class="op">-</span><span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">3</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04_1pl_2pl_3pl_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>Nel grafico risultante, osserviamo due segmenti di punti che rappresentano le risposte dei due gruppi. La linea continua mostra la curva ICC stimata utilizzando i dati di entrambi i gruppi. Il fatto che questa curva si adatti bene ai punti di entrambi i gruppi, nonostante la loro diversa distribuzione di abilità, dimostra visivamente il principio di invarianza: i parametri dell’item rimangono stabili indipendentemente dal gruppo considerato.</p>
<p>Questa visualizzazione è particolarmente efficace perché:</p>
<ol type="1">
<li>mostra chiaramente la separazione tra i due gruppi di abilità;</li>
<li>permette di verificare che la stessa curva ICC si adatta bene a entrambi i gruppi;</li>
<li>conferma che le stime dei parametri (riportate nel titolo del grafico) sono valide per l’intero range di abilità.</li>
</ol>
<p>L’esercizio fornisce quindi una dimostrazione empirica dell’invarianza di gruppo, una delle proprietà fondamentali che rendono la IRT uno strumento robusto per la misurazione psicometrica.</p>
</div>
<section id="confronto-con-la-teoria-classica-dei-test" class="level3" data-number="70.5.1"><h3 data-number="70.5.1" class="anchored" data-anchor-id="confronto-con-la-teoria-classica-dei-test">
<span class="header-section-number">70.5.1</span> Confronto con la Teoria Classica dei Test</h3>
<p>La differenza più notevole tra IRT e CTT riguarda proprio il modo in cui viene trattata l’invarianza dei parametri degli item rispetto ai gruppi esaminati. Questo aspetto emerge chiaramente analizzando come le due teorie definiscono e misurano la difficoltà degli item.</p>
<p>Nella CTT, la difficoltà di un item è definita come la proporzione di risposte corrette nel campione. Questa definizione rende il parametro di difficoltà intrinsecamente dipendente dalla popolazione esaminata: lo stesso item mostrerà una “difficoltà” diversa se somministrato a gruppi con differenti livelli di abilità. Per esempio, se somministriamo un test a due classi di livello diverso, nella CTT otterremo due stime di difficoltà diverse per lo stesso item, rendendo problematico qualsiasi confronto diretto tra i gruppi.</p>
<p>L’IRT risolve questa limitazione fondamentale introducendo parametri che sono teoricamente invarianti rispetto alla popolazione. Il parametro di difficoltà (<span class="math inline">\(\beta\)</span>) in particolare rappresenta una proprietà intrinseca dell’item che rimane costante indipendentemente dal gruppo esaminato. Questo significa che, a differenza della CTT, l’IRT può fornire stime comparabili della difficoltà dell’item anche quando viene somministrato a popolazioni con distribuzioni di abilità molto diverse.</p>
<p>L’invarianza nella IRT si manifesta nella curva caratteristica dell’item (ICC): la relazione tra abilità e probabilità di risposta corretta mantiene la stessa forma matematica indipendentemente dal gruppo considerato (come abbiamo osservato nell’esempio precedente). Questa proprietà ha importanti implicazioni pratiche:</p>
<ul>
<li>possiamo stimare i parametri dell’item utilizzando qualsiasi sottogruppo della popolazione e ottenere risultati coerenti;</li>
<li>è possibile confrontare direttamente le prestazioni di gruppi diversi sullo stesso item;</li>
<li>la calibrazione degli item può essere effettuata su un campione e poi applicata con fiducia ad altri gruppi.</li>
</ul>
<p>Tuttavia, è importante notare che mentre nella CTT la dipendenza dalla popolazione è una limitazione intrinseca del modello, nell’IRT l’invarianza è una proprietà teorica che nella pratica può essere influenzata da vari fattori. Le stime empiriche dei parametri possono mostrare alcune variazioni dovute all’errore campionario, e l’invarianza è garantita solo quando l’item misura effettivamente lo stesso costrutto in tutti i gruppi considerati.</p>
<p>Questa differenza fondamentale tra CTT e IRT nell’approccio all’invarianza di gruppo rende l’IRT particolarmente adatta per applicazioni che richiedono confronti affidabili tra popolazioni diverse, come nel testing adattivo, negli studi longitudinali e nelle comparazioni tra gruppi culturali diversi.</p>
</section></section><section id="riflessioni-conclusive" class="level2" data-number="70.6"><h2 data-number="70.6" class="anchored" data-anchor-id="riflessioni-conclusive">
<span class="header-section-number">70.6</span> Riflessioni Conclusive</h2>
<p>In questo capitolo, abbiamo esplorato la progressione dei modelli IRT, partendo dal modello di Rasch fino al più flessibile modello 3PL. Ogni modello offre un equilibrio unico tra semplicità e adattabilità, consentendo di rispondere a esigenze diverse nell’ambito della misurazione psicometrica.</p>
<ul>
<li>Il <strong>modello di Rasch</strong>, con i suoi vincoli rigorosi, si distingue per la sua capacità di fornire misurazioni oggettive e stabili, risultando particolarmente utile nella costruzione di strumenti di misurazione.</li>
<li>Il <strong>modello 1PL</strong> mantiene la semplicità del modello di Rasch ma introduce una maggiore flessibilità consentendo di variare il parametro di discriminazione a livello teorico.</li>
<li>Il <strong>modello 2PL</strong> aggiunge un ulteriore livello di complessità, permettendo a ogni item di avere una discriminazione specifica, migliorando l’adattamento ai dati reali.</li>
<li>Il <strong>modello 3PL</strong> completa questa progressione introducendo il parametro di guessing, necessario per tenere conto delle risposte corrette casuali, tipiche nei test a scelta multipla.</li>
</ul>
<p>Questa evoluzione riflette l’importanza di adattare il modello alle caratteristiche dei dati e alle finalità dell’analisi. Abbiamo anche sottolineato l’importanza dell’<strong>invarianza di gruppo</strong>, una proprietà chiave che consente confronti equi tra popolazioni diverse, distinguendo l’IRT dalla Teoria Classica dei Test (CTT).</p>
<p>In definitiva, la scelta del modello dipende dall’obiettivo specifico dello studio e dalla complessità dei dati osservati. Il modello di Rasch offre rigore e semplicità, mentre i modelli 2PL e 3PL offrono flessibilità e precisione. Questa progressione dimostra la versatilità della IRT come framework per la misurazione psicometrica, supportando applicazioni che spaziano dalla ricerca accademica allo sviluppo di test standardizzati.</p>
</section><section id="session-info" class="level2" data-number="70.7"><h2 data-number="70.7" class="anchored" data-anchor-id="session-info">
<span class="header-section-number">70.7</span> Session Info</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; R version 4.4.2 (2024-10-31)</span></span>
<span><span class="co">#&gt; Platform: aarch64-apple-darwin20</span></span>
<span><span class="co">#&gt; Running under: macOS Sequoia 15.3.2</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Matrix products: default</span></span>
<span><span class="co">#&gt; BLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib </span></span>
<span><span class="co">#&gt; LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; locale:</span></span>
<span><span class="co">#&gt; [1] C/UTF-8/C/C/C/C</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; time zone: Europe/Rome</span></span>
<span><span class="co">#&gt; tzcode source: internal</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; attached base packages:</span></span>
<span><span class="co">#&gt; [1] grid      stats4    stats     graphics  grDevices utils     datasets </span></span>
<span><span class="co">#&gt; [8] methods   base     </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; other attached packages:</span></span>
<span><span class="co">#&gt;  [1] latex2exp_0.9.6   psychotools_0.7-4 ggmirt_0.1.0      TAM_4.2-21       </span></span>
<span><span class="co">#&gt;  [5] CDM_8.2-6         mvtnorm_1.3-3     mirt_1.44.0       lattice_0.22-6   </span></span>
<span><span class="co">#&gt;  [9] eRm_1.0-6         ggokabeito_0.1.0  see_0.11.0        MASS_7.3-65      </span></span>
<span><span class="co">#&gt; [13] viridis_0.6.5     viridisLite_0.4.2 ggpubr_0.6.0      ggExtra_0.10.1   </span></span>
<span><span class="co">#&gt; [17] gridExtra_2.3     patchwork_1.3.0   bayesplot_1.11.1  semTools_0.5-6   </span></span>
<span><span class="co">#&gt; [21] semPlot_1.1.6     lavaan_0.6-19     psych_2.4.12      scales_1.3.0     </span></span>
<span><span class="co">#&gt; [25] markdown_1.13     knitr_1.50        lubridate_1.9.4   forcats_1.0.0    </span></span>
<span><span class="co">#&gt; [29] stringr_1.5.1     dplyr_1.1.4       purrr_1.0.4       readr_2.1.5      </span></span>
<span><span class="co">#&gt; [33] tidyr_1.3.1       tibble_3.2.1      ggplot2_3.5.1     tidyverse_2.0.0  </span></span>
<span><span class="co">#&gt; [37] here_1.0.1       </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; loaded via a namespace (and not attached):</span></span>
<span><span class="co">#&gt;   [1] splines_4.4.2        later_1.4.1          R.oo_1.27.0         </span></span>
<span><span class="co">#&gt;   [4] XML_3.99-0.18        rpart_4.1.24         lifecycle_1.0.4     </span></span>
<span><span class="co">#&gt;   [7] Rdpack_2.6.3         rstatix_0.7.2        rprojroot_2.0.4     </span></span>
<span><span class="co">#&gt;  [10] globals_0.16.3       rockchalk_1.8.157    backports_1.5.0     </span></span>
<span><span class="co">#&gt;  [13] magrittr_2.0.3       openxlsx_4.2.8       Hmisc_5.2-3         </span></span>
<span><span class="co">#&gt;  [16] rmarkdown_2.29       yaml_2.3.10          httpuv_1.6.15       </span></span>
<span><span class="co">#&gt;  [19] qgraph_1.9.8         zip_2.3.2            sessioninfo_1.2.3   </span></span>
<span><span class="co">#&gt;  [22] pbapply_1.7-2        minqa_1.2.8          multcomp_1.4-28     </span></span>
<span><span class="co">#&gt;  [25] abind_1.4-8          audio_0.1-11         quadprog_1.5-8      </span></span>
<span><span class="co">#&gt;  [28] R.utils_2.13.0       nnet_7.3-20          TH.data_1.1-3       </span></span>
<span><span class="co">#&gt;  [31] sandwich_3.1-1       listenv_0.9.1        testthat_3.2.3      </span></span>
<span><span class="co">#&gt;  [34] vegan_2.6-10         arm_1.14-4           parallelly_1.42.0   </span></span>
<span><span class="co">#&gt;  [37] permute_0.9-7        codetools_0.2-20     tidyselect_1.2.1    </span></span>
<span><span class="co">#&gt;  [40] farver_2.1.2         lme4_1.1-36          base64enc_0.1-3     </span></span>
<span><span class="co">#&gt;  [43] jsonlite_1.9.1       polycor_0.8-1        progressr_0.15.1    </span></span>
<span><span class="co">#&gt;  [46] Formula_1.2-5        survival_3.8-3       emmeans_1.10.7      </span></span>
<span><span class="co">#&gt;  [49] tools_4.4.2          Rcpp_1.0.14          glue_1.8.0          </span></span>
<span><span class="co">#&gt;  [52] mnormt_2.1.1         admisc_0.37          xfun_0.51           </span></span>
<span><span class="co">#&gt;  [55] mgcv_1.9-1           withr_3.0.2          beepr_2.0           </span></span>
<span><span class="co">#&gt;  [58] fastmap_1.2.0        boot_1.3-31          digest_0.6.37       </span></span>
<span><span class="co">#&gt;  [61] mi_1.1               timechange_0.3.0     R6_2.6.1            </span></span>
<span><span class="co">#&gt;  [64] mime_0.13            estimability_1.5.1   colorspace_2.1-1    </span></span>
<span><span class="co">#&gt;  [67] gtools_3.9.5         jpeg_0.1-10          R.methodsS3_1.8.2   </span></span>
<span><span class="co">#&gt;  [70] generics_0.1.3       data.table_1.17.0    corpcor_1.6.10      </span></span>
<span><span class="co">#&gt;  [73] SimDesign_2.19.1     htmlwidgets_1.6.4    pkgconfig_2.0.3     </span></span>
<span><span class="co">#&gt;  [76] sem_3.1-16           gtable_0.3.6         brio_1.1.5          </span></span>
<span><span class="co">#&gt;  [79] htmltools_0.5.8.1    carData_3.0-5        png_0.1-8           </span></span>
<span><span class="co">#&gt;  [82] reformulas_0.4.0     rstudioapi_0.17.1    tzdb_0.5.0          </span></span>
<span><span class="co">#&gt;  [85] reshape2_1.4.4       coda_0.19-4.1        checkmate_2.3.2     </span></span>
<span><span class="co">#&gt;  [88] nlme_3.1-167         nloptr_2.2.1         zoo_1.8-13          </span></span>
<span><span class="co">#&gt;  [91] parallel_4.4.2       miniUI_0.1.1.1       foreign_0.8-88      </span></span>
<span><span class="co">#&gt;  [94] pillar_1.10.1        vctrs_0.6.5          promises_1.3.2      </span></span>
<span><span class="co">#&gt;  [97] car_3.1-3            OpenMx_2.21.13       xtable_1.8-4        </span></span>
<span><span class="co">#&gt; [100] Deriv_4.1.6          cluster_2.1.8.1      dcurver_0.9.2       </span></span>
<span><span class="co">#&gt; [103] GPArotation_2024.3-1 htmlTable_2.4.3      evaluate_1.0.3      </span></span>
<span><span class="co">#&gt; [106] pbivnorm_0.6.0       cli_3.6.4            kutils_1.73         </span></span>
<span><span class="co">#&gt; [109] compiler_4.4.2       rlang_1.1.5          future.apply_1.11.3 </span></span>
<span><span class="co">#&gt; [112] ggsignif_0.6.4       fdrtool_1.2.18       plyr_1.8.9          </span></span>
<span><span class="co">#&gt; [115] stringi_1.8.4        munsell_0.5.1        lisrelToR_0.3       </span></span>
<span><span class="co">#&gt; [118] pacman_0.5.1         Matrix_1.7-3         hms_1.1.3           </span></span>
<span><span class="co">#&gt; [121] glasso_1.11          future_1.34.0        shiny_1.10.0        </span></span>
<span><span class="co">#&gt; [124] rbibutils_2.3        igraph_2.1.4         broom_1.0.7         </span></span>
<span><span class="co">#&gt; [127] RcppParallel_5.1.10</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-petersen2024principles" class="csl-entry" role="listitem">
Petersen, I. T. (2024). <em>Principles of psychological assessment: With applied examples in R</em>. CRC Press.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiato!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiato!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ccaudek\.github\.io\/testing_psicologico\/intro\.html");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../chapters/irt/03_estimation.html" class="pagination-link" aria-label="Stima">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title">Stima</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/irt/05_implementation.html" class="pagination-link" aria-label="Implementazione">
        <span class="nav-page-text"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Implementazione</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Testing Psicologico</strong> è una dispensa scritta da Corrado Caudek.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


</body></html>