<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Corrado Caudek">

<title>11&nbsp; Modelli multilivello – Testing Psicologico</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/raters/02_interrater_reliability.html" rel="next">
<link href="../../chapters/ctt/06_ctt_applications.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/raters/01_multilevel.html">Giudici</a></li><li class="breadcrumb-item"><a href="../../chapters/raters/01_multilevel.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Modelli multilivello</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Testing Psicologico</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ccaudek/testing_psicologico/" title="Eseguire il codice" class="quarto-navigation-tool px-1" aria-label="Eseguire il codice"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Ricerca"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Benvenuti</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../prefazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefazione</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Punteggi e scale</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/01_scores_scales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Punteggi e scale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E1_likert.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E2_optimal_scoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E3_thurstone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">CTT</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/01_ctt_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Fondamenti teorici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/02_ctt_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">L’affidabilità del test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/03_ctt_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Metodi di stima dell’affidabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/04_err_std_mis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">L’errore standard della misurazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/05_err_std_stima.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">La stima del punteggio vero</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/06_ctt_applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Applicazioni della CTT</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Giudici</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/01_multilevel.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Modelli multilivello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/02_interrater_reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">L’affidabilità tra giudici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/E1_irr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Validità</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/validity/01_validity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">La validità del test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/validity/02_other_variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Relazioni test-criterio</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Generalizzabilità</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/gtheory/01_gtheory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Teoria della generalizzabilità</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Items</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/items/01_item_development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Lo sviluppo degli item</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/items/02_item_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Analisi degli item</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Analisi dei percorsi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/path_analysis/01_path_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Analisi dei percorsi</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">FA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/01_intro_fa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Introduzione all’analisi fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/02_analisi_fattoriale_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Il modello unifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/03_analisi_fattoriale_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Il modello statistico dell’analisi fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/04_analisi_fattoriale_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Il modello multifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/05_factor_scores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">I punteggi fattoriali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/06_constraints_on_parms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Attendibilità e modello fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/07_total_score.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Punteggio totale e modello fattoriale</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Costruzione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/01_val_matrici.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Valutazione della matrice di correlazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/02_estrazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">L’estrazione dei fattori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/03_numero_fattori.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Il numero dei fattori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/04_rotazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">La rotazione fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/05_val_soluzione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Valutare e rifinire la soluzione fattoriale</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">CFA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/01_cfa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Analisti Fattoriale Confermativa</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/02_meanstructure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">La struttura delle medie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/03_cat_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Dati non gaussiani e categoriali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/04_mmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">CFA per matrici multi-tratto multi-metodo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/05_bifactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Modello bifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/06_efa_lavaan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Exploratory Structural Equation Modeling (ESEM)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">SEM</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/01_sem_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Introduzione ai Modelli SEM</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/02_data_preparation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Preparazione dei Dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/03_gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Test del Modello e Indicizzazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/04_mod_comp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Confronto tra modelli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/05_cfa_mod_comp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">CFA: confronto tra modelli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/06_refine_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">La revisione del modello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/07_group_invariance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Invarianza di misura</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/08_multilevel_sem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Modelli di Equazioni Strutturali Multilivello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/09_structural_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Modelli di Regressione Strutturale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/10_missing_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Dati mancanti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/11_small_samples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Modellizzazione SEM in Piccoli Campioni</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/12_temp_reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Affidabilità longitudinale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false">
 <span class="menu-text">Mokken</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/01_core_issues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Analisi della Scala di Mokken</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/02_applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Applicazione Pratica</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">IRT</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/01_logistic_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Modello di Regressione Logistica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/02_rasch_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Modello di Rasch</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/03_assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Assunzioni e Proprietà del Modello di Rasch</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/04_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Stima</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/05_1pl_2pl_3pl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Oltre il Modello di Rasch</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/06_implementation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Implementazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/07_irt_poly.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">Modelli per Risposte Politomiche</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../99-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliografia</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendici</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a1_intro_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linguaggio R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a2_sums.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Simbolo di somma</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a3_calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Per liberarvi dai terrori preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a4_linear_alg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Elementi di algebra lineare</span></span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false">
 <span class="menu-text">Soluzioni degli esercizi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/solutions_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Probabilità</span></span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Indice</h2>
   
  <ul>
  <li><a href="#introduzione" id="toc-introduzione" class="nav-link active" data-scroll-target="#introduzione"><span class="header-section-number">11.1</span> Introduzione</a>
  <ul class="collapse">
  <li><a href="#analisi-della-relazione-tra-tempo-di-reazione-e-privazione-del-sonno" id="toc-analisi-della-relazione-tra-tempo-di-reazione-e-privazione-del-sonno" class="nav-link" data-scroll-target="#analisi-della-relazione-tra-tempo-di-reazione-e-privazione-del-sonno"><span class="header-section-number">11.1.1</span> Analisi della Relazione tra Tempo di Reazione e Privazione del Sonno</a></li>
  </ul></li>
  <li><a href="#complete-pooling" id="toc-complete-pooling" class="nav-link" data-scroll-target="#complete-pooling"><span class="header-section-number">11.2</span> Complete pooling</a>
  <ul class="collapse">
  <li><a href="#interpretazione-del-modello-di-regressione-e-visualizzazione-grafica" id="toc-interpretazione-del-modello-di-regressione-e-visualizzazione-grafica" class="nav-link" data-scroll-target="#interpretazione-del-modello-di-regressione-e-visualizzazione-grafica"><span class="header-section-number">11.2.1</span> Interpretazione del Modello di Regressione e Visualizzazione Grafica</a></li>
  </ul></li>
  <li><a href="#approccio-di-no-pooling" id="toc-approccio-di-no-pooling" class="nav-link" data-scroll-target="#approccio-di-no-pooling"><span class="header-section-number">11.3</span> Approccio di No Pooling</a>
  <ul class="collapse">
  <li><a href="#caratteristiche-del-no-pooling" id="toc-caratteristiche-del-no-pooling" class="nav-link" data-scroll-target="#caratteristiche-del-no-pooling"><span class="header-section-number">11.3.1</span> Caratteristiche del No Pooling</a></li>
  <li><a href="#implementazione-del-modello-di-no-pooling" id="toc-implementazione-del-modello-di-no-pooling" class="nav-link" data-scroll-target="#implementazione-del-modello-di-no-pooling"><span class="header-section-number">11.3.2</span> Implementazione del Modello di No Pooling</a></li>
  <li><a href="#verifica-del-fattore-subject" id="toc-verifica-del-fattore-subject" class="nav-link" data-scroll-target="#verifica-del-fattore-subject"><span class="header-section-number">11.3.3</span> Verifica del Fattore <code>Subject</code></a></li>
  </ul></li>
  <li><a href="#approccio-di-partial-pooling" id="toc-approccio-di-partial-pooling" class="nav-link" data-scroll-target="#approccio-di-partial-pooling"><span class="header-section-number">11.4</span> Approccio di Partial Pooling</a>
  <ul class="collapse">
  <li><a href="#implementazione-dei-modelli-a-effetti-misti" id="toc-implementazione-dei-modelli-a-effetti-misti" class="nav-link" data-scroll-target="#implementazione-dei-modelli-a-effetti-misti"><span class="header-section-number">11.4.1</span> Implementazione dei Modelli a Effetti Misti</a></li>
  <li><a href="#articolazione-e-applicazione-del-modello-multilivello" id="toc-articolazione-e-applicazione-del-modello-multilivello" class="nav-link" data-scroll-target="#articolazione-e-applicazione-del-modello-multilivello"><span class="header-section-number">11.4.2</span> Articolazione e Applicazione del Modello Multilivello</a></li>
  <li><a href="#spiegazione-della-matrice-di-varianza-covarianza-nel-modello-multilivello" id="toc-spiegazione-della-matrice-di-varianza-covarianza-nel-modello-multilivello" class="nav-link" data-scroll-target="#spiegazione-della-matrice-di-varianza-covarianza-nel-modello-multilivello"><span class="header-section-number">11.4.3</span> Spiegazione della Matrice di Varianza-Covarianza nel Modello Multilivello</a></li>
  <li><a href="#tabella-delle-variabili" id="toc-tabella-delle-variabili" class="nav-link" data-scroll-target="#tabella-delle-variabili"><span class="header-section-number">11.4.4</span> Tabella delle Variabili</a></li>
  </ul></li>
  <li><a href="#stimare-i-parametri-del-modello" id="toc-stimare-i-parametri-del-modello" class="nav-link" data-scroll-target="#stimare-i-parametri-del-modello"><span class="header-section-number">11.5</span> Stimare i parametri del modello</a></li>
  <li><a href="#interpretare-loutput-di-lmer-ed-estrarre-le-stime" id="toc-interpretare-loutput-di-lmer-ed-estrarre-le-stime" class="nav-link" data-scroll-target="#interpretare-loutput-di-lmer-ed-estrarre-le-stime"><span class="header-section-number">11.6</span> Interpretare l’output di <code>lmer()</code> ed estrarre le stime</a>
  <ul class="collapse">
  <li><a href="#effetti-fissi" id="toc-effetti-fissi" class="nav-link" data-scroll-target="#effetti-fissi"><span class="header-section-number">11.6.1</span> Effetti fissi</a></li>
  <li><a href="#effetti-random" id="toc-effetti-random" class="nav-link" data-scroll-target="#effetti-random"><span class="header-section-number">11.6.2</span> Effetti random</a></li>
  </ul></li>
  <li><a href="#considerazioni-conclusive" id="toc-considerazioni-conclusive" class="nav-link" data-scroll-target="#considerazioni-conclusive"><span class="header-section-number">11.7</span> Considerazioni Conclusive</a></li>
  <li><a href="#session-info" id="toc-session-info" class="nav-link" data-scroll-target="#session-info"><span class="header-section-number">11.8</span> Session Info</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.dev/ccaudek/testing_psicologico/blob/main/chapters/raters/01_multilevel.ipynb" class="toc-action"><i class="bi bi-github"></i>Modifica questa pagina</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/raters/01_multilevel.html">Giudici</a></li><li class="breadcrumb-item"><a href="../../chapters/raters/01_multilevel.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Modelli multilivello</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-multilevel" class="quarto-section-identifier"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Modelli multilivello</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Prerequisiti</strong></p>
<p><strong>Concetti e Competenze Chiave</strong></p>
<p><strong>Preparazione del Notebook</strong></p>
<div id="cell-2" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"code"</span>, <span class="st">"_common.R"</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">source</span>()</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">"pacman"</span>)) <span class="fu">install.packages</span>(<span class="st">"pacman"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    car, lme4, lavaan, semPlot, repr, kableExtra</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Caricamento dei namespace richiesti: pacman
</code></pre>
</div>
</div>
<section id="introduzione" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="introduzione"><span class="header-section-number">11.1</span> Introduzione</h2>
<p>I modelli multilivello, noti anche come modelli gerarchici o a effetti misti, rappresentano una metodologia statistica potente e flessibile, particolarmente adatta per analizzare dati strutturati in più livelli. Questi modelli permettono di considerare simultaneamente variazioni a livelli diversi, come quello individuale e quello di gruppo, fornendo una comprensione più dettagliata e accurata dei fenomeni studiati.</p>
<p>In psicologia i modelli multilivello assumono un’importanza cruciale. Gli psicologi utilizzano frequentemente dati raccolti in contesti complessi, dove gli effetti individuali e contestuali si intrecciano. Ad esempio, nella valutazione delle prestazioni cognitive o della risposta emotiva, i modelli multilivello consentono di distinguere tra variazioni dovute a caratteristiche individuali (come l’abilità cognitiva o la personalità) e quelle derivanti da fattori esterni (come l’ambiente scolastico o familiare).</p>
<p>I modelli multilivello sono particolarmente utili per: - Analizzare dati longitudinali, dove le misurazioni ripetute sugli stessi soggetti introducono correlazioni naturali. - Studiare l’impatto di fattori contestuali su variabili psicologiche, consentendo di esaminare come l’ambiente influenzi i comportamenti o gli stati mentali. - Gestire la variabilità intra-individuale e inter-individuale in modo più efficace, offrendo una rappresentazione più realistica della complessità dei fenomeni psicologici.</p>
<p>In questo capitolo, ci focalizzeremo sull’analisi di un’indagine sperimentale condotta per studiare l’impatto della deprivazione del sonno sulle prestazioni psicomotorie. I dati utilizzati provengono dallo studio di Belenky et al.&nbsp;(2003) sugli effetti della deprivazione del sonno. Questi dati sono accessibili nel dataset <code>sleepstudy</code>, incluso nel pacchetto <code>lme4</code> di R {cite:t}<code>bates2014fitting</code>.</p>
<p>Importiamo i dati.</p>
<div id="cell-5" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(sleepstudy)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Il data frame comprende 180 righe (osservazioni) e tre variabili:</p>
<ul>
<li><code>Reaction</code>: Average reaction time (ms)</li>
<li><code>Days</code>: Number of days of sleep deprivation</li>
<li><code>Subject</code>: Subject number on which the observation was made.</li>
</ul>
<p>Questi dati forniscono un esempio di dati multilivello, caratterizzati da misurazioni ripetute su una stessa variabile dipendente - in questo caso, il tempo medio di reazione (RT) - raccolte dai medesimi partecipanti per un periodo di dieci giorni. Tale struttura di dati è molto diffusa in psicologia, dove spesso si valutano le variazioni delle risposte o dei comportamenti di individui nel tempo.</p>
<p>Il dataset esaminato focalizza su diciotto partecipanti, sottoposti a una condizione di sonno limitato a tre ore. Nell’arco di dieci giorni, questi partecipanti hanno partecipato quotidianamente a un “test di vigilanza psicomotoria” della durata di dieci minuti. Durante il test, era richiesto loro di monitorare uno schermo e di premere un pulsante quanto più rapidamente possibile alla comparsa di uno stimolo. La variabile dipendente principale dello studio è il tempo medio di risposta (RT) di ciascun partecipante.</p>
<p>Per analizzare questi dati, è utile iniziare con una rappresentazione grafica. Se ci concentriamo sui dati di un singolo soggetto, questo ci permette di osservare le tendenze e le variazioni nel tempo di reazione di quel particolare individuo, fornendo insight su come la restrizione del sonno possa influire sulle sue prestazioni nel corso dei dieci giorni dello studio.</p>
<div id="cell-7" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>just_308 <span class="ot">&lt;-</span> sleepstudy <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(Subject <span class="sc">==</span> <span class="st">"308"</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-8" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(just_308, <span class="fu">aes</span>(<span class="at">x =</span> Days, <span class="at">y =</span> Reaction)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">2.5</span>) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">9</span>) </span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_multilevel_files/figure-html/cell-5-output-1.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Esaminiamo ora i dati di tutti i 18 soggetti.</p>
<div id="cell-10" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sleepstudy, <span class="fu">aes</span>(<span class="at">x =</span> Days, <span class="at">y =</span> Reaction)) <span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">9</span>) <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span>Subject)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_multilevel_files/figure-html/cell-6-output-1.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="descrizione-del-disegno-sperimentale" class="level4" data-number="11.1.0.1">
<h4 data-number="11.1.0.1" class="anchored" data-anchor-id="descrizione-del-disegno-sperimentale"><span class="header-section-number">11.1.0.1</span> Descrizione del Disegno Sperimentale</h4>
<ul>
<li><strong>Fase di Adattamento e Baseline</strong>: I primi tre giorni dello studio (T1, T2 e B) sono stati utilizzati per l’adattamento e l’addestramento (T1 e T2), seguiti da una misurazione baseline (B). Durante questo periodo, ai soggetti è stato chiesto di rimanere a letto per 8 ore (dalle 23:00 alle 07:00).</li>
<li><strong>Condizioni di Sonno</strong>: Dal quarto giorno in poi, per sette giorni (E1-E7), i soggetti hanno sperimentato diverse condizioni di sonno, variando la durata del tempo a letto (TIB) da 3 a 9 ore.</li>
</ul>
<p>I primi due giorni (codificati come 0 e 1) sono stati dedicati all’adattamento e all’addestramento, mentre il terzo giorno (codificato come 2) ha visto la misurazione baseline. L’analisi dovrebbe idealmente partire dal giorno di baseline per riflettere l’effetto della restrizione del sonno sulle prestazioni. Per evitare che l’adattamento influenzi i risultati, i giorni 0 e 1 devono dunque essere esclusi dall’analisi, poiché qualsiasi variazione di prestazione in questi giorni è attribuibile all’addestramento piuttosto che alla restrizione del sonno.</p>
</section>
<section id="preparazione-dei-dati" class="level4" data-number="11.1.0.2">
<h4 data-number="11.1.0.2" class="anchored" data-anchor-id="preparazione-dei-dati"><span class="header-section-number">11.1.0.2</span> Preparazione dei Dati</h4>
<ul>
<li><strong>Rimozione delle Osservazioni Iniziali</strong>: Dal dataset, eliminiamo le osservazioni dove la variabile “Days” è codificata come 0 o 1.</li>
<li><strong>Creazione di una Nuova Variabile “days_deprived”</strong>: Creiamo una nuova variabile basata su “Days”, iniziando la sequenza dal giorno 2. In questa nuova variabile, il giorno 2 viene ricodificato come 0, il giorno 3 come 1, e così via. Questa variabile rappresenta il numero di giorni di privazione del sonno. Salviamo il dataset modificato con il nome <code>sleep2</code>, che ora riflette accuratamente il periodo di restrizione del sonno per l’analisi.</li>
</ul>
<div id="cell-12" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="6">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>sleep2 <span class="ot">&lt;-</span> sleepstudy <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(Days <span class="sc">&gt;=</span> <span class="dv">2</span>L) <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">days_deprived =</span> Days <span class="sc">-</span> <span class="dv">2</span>L)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-13" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="7">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>sleep2 <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(days_deprived, Days)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>A data.frame: 8 x 3</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" scope="col">days_deprived</th>
<th data-quarto-table-cell-role="th" scope="col">Days</th>
<th data-quarto-table-cell-role="th" scope="col">n</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;int&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>2</td>
<td>18</td>
</tr>
<tr class="even">
<td>1</td>
<td>3</td>
<td>18</td>
</tr>
<tr class="odd">
<td>2</td>
<td>4</td>
<td>18</td>
</tr>
<tr class="even">
<td>3</td>
<td>5</td>
<td>18</td>
</tr>
<tr class="odd">
<td>4</td>
<td>6</td>
<td>18</td>
</tr>
<tr class="even">
<td>5</td>
<td>7</td>
<td>18</td>
</tr>
<tr class="odd">
<td>6</td>
<td>8</td>
<td>18</td>
</tr>
<tr class="even">
<td>7</td>
<td>9</td>
<td>18</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="cell-14" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="8">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sleep2, <span class="fu">aes</span>(<span class="at">x =</span> days_deprived, <span class="at">y =</span> Reaction)) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">7</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span>Subject) <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Reaction Time"</span>, <span class="at">x =</span> <span class="st">"Days deprived of sleep (0 = baseline)"</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_multilevel_files/figure-html/cell-9-output-1.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="analisi-della-relazione-tra-tempo-di-reazione-e-privazione-del-sonno" class="level3" data-number="11.1.1">
<h3 data-number="11.1.1" class="anchored" data-anchor-id="analisi-della-relazione-tra-tempo-di-reazione-e-privazione-del-sonno"><span class="header-section-number">11.1.1</span> Analisi della Relazione tra Tempo di Reazione e Privazione del Sonno</h3>
<p>Nel contesto dello studio sulla privazione del sonno, l’analisi dei dati suggerisce che, a parte una singola eccezione (il soggetto 335), il tempo di reazione medio tende ad aumentare progressivamente con ogni giorno aggiuntivo di privazione del sonno. Questo pattern indica che potrebbe essere utile descrivere le prestazioni di ciascun partecipante attraverso un modello di regressione lineare.</p>
<p>La regressione lineare è rappresentata dall’equazione generale:</p>
<p><span class="math display">\[ E(Y) = \beta_0 + \beta_1 X, \]</span></p>
<p>dove $ Y $ è la variabile dipendente (in questo caso, il tempo di reazione), $ _0 $ rappresenta l’intercetta (il tempo di reazione medio al giorno zero, prima dell’inizio della privazione del sonno) e $ _1 $ è la pendenza (la variazione del tempo di reazione per ogni giorno aggiuntivo di privazione del sonno). Questi parametri ($ _0 $ e $ _1 $) sono stimati dai dati.</p>
<p>Quando si modellano i dati di ciascun partecipante, emergono diverse domande: dobbiamo adattare lo stesso modello di regressione lineare a tutti i partecipanti, o sarebbe più appropriato utilizzare un modello diverso per ogni soggetto? Oppure esiste un approccio intermedio che bilancia questi estremi?</p>
<p>Per rispondere a queste domande, esploriamo tre approcci differenti, come illustrato da {cite:t}<code>McElreath_rethinking</code>:</p>
<ol type="1">
<li><p><strong>Complete Pooling</strong>: Questo approccio implica l’utilizzo di un unico modello di regressione lineare per tutti i partecipanti. Significa che assumiamo la stessa relazione lineare (stessa intercetta e pendenza) per tutti, ignorando le differenze individuali.</p></li>
<li><p><strong>No Pooling</strong>: In questo approccio, ogni partecipante ha un proprio modello di regressione lineare individuale, con intercetta e pendenza uniche. Qui si riconosce che ogni individuo può rispondere diversamente alla privazione del sonno, e quindi il modello è personalizzato per ciascun soggetto.</p></li>
<li><p><strong>Partial Pooling</strong>: Questo approccio intermedio cerca di bilanciare gli estremi dei due metodi precedenti. Include alcuni elementi comuni tra i soggetti (ad esempio, una pendenza media) ma permette anche una certa variazione individuale.</p></li>
</ol>
</section>
</section>
<section id="complete-pooling" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="complete-pooling"><span class="header-section-number">11.2</span> Complete pooling</h2>
<p>L’approccio di “complete pooling” in analisi statistica implica l’utilizzo di un modello che calcola un’unica intercetta e una sola pendenza per l’intero dataset. Questo metodo si basa sull’ipotesi che tutti i soggetti nel dataset condividano le stesse caratteristiche di base riguardo alla relazione tra la variabile dipendente e indipendente.</p>
<section id="caratteristiche-del-complete-pooling" class="level4" data-number="11.2.0.1">
<h4 data-number="11.2.0.1" class="anchored" data-anchor-id="caratteristiche-del-complete-pooling"><span class="header-section-number">11.2.0.1</span> Caratteristiche del Complete Pooling</h4>
<ul>
<li><strong>Unicità delle Stime</strong>: Il modello stima un singolo set di parametri (intercetta e pendenza) per tutti i dati, considerando l’intero campione come un’unità omogenea.</li>
<li><strong>Ignorare le Variazioni Individuali</strong>: Questo approccio non tiene conto delle possibili differenze individuali nelle intercette o nelle pendenze tra i diversi soggetti. Ad esempio, ignorara come ciascun soggetto reagisce in modo diverso alla privazione del sonno.</li>
</ul>
</section>
<section id="limitazioni-dellapproccio-di-complete-pooling" class="level4" data-number="11.2.0.2">
<h4 data-number="11.2.0.2" class="anchored" data-anchor-id="limitazioni-dellapproccio-di-complete-pooling"><span class="header-section-number">11.2.0.2</span> Limitazioni dell’Approccio di Complete Pooling</h4>
<p>Dall’analisi preliminare dei dati, abbiamo notato che l’approccio di complete pooling potrebbe non essere adatto per il nostro studio. La visualizzazione dei dati suggerisce che ogni partecipante potrebbe avere una propria relazione unica tra il tempo di reazione e i giorni di privazione del sonno, indicando la necessità di valori individuali per le intercette e le pendenze.</p>
</section>
<section id="modello-di-regressione-lineare-in-complete-pooling" class="level4" data-number="11.2.0.3">
<h4 data-number="11.2.0.3" class="anchored" data-anchor-id="modello-di-regressione-lineare-in-complete-pooling"><span class="header-section-number">11.2.0.3</span> Modello di Regressione Lineare in Complete Pooling</h4>
<p>Il modello generale lineare (GLM) per l’approccio di complete pooling è formulato come segue:</p>
<p><span class="math display">\[Y_{sd} = \beta_0 + \beta_1 X_{sd} + e_{sd},\]</span></p>
<p>dove: - $ Y_{sd} $ rappresenta il tempo di reazione medio del soggetto $ s $ nel giorno $ d $. - $ X_{sd} $ è il numero di giorni di privazione del sonno (variabile “days_deprived”), che varia da 0 a 7. - $ e_{sd} $ è il termine di errore, che rappresenta le fluttuazioni casuali non spiegate dal modello.</p>
</section>
<section id="implementazione-in-r" class="level4" data-number="11.2.0.4">
<h4 data-number="11.2.0.4" class="anchored" data-anchor-id="implementazione-in-r"><span class="header-section-number">11.2.0.4</span> Implementazione in R</h4>
<p>Per adattare questo modello in R, si utilizza la funzione <code>lm()</code>:</p>
<div id="cell-16" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="9">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>cp_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Reaction <span class="sc">~</span> days_deprived, sleep2)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cp_model)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>
Call:
lm(formula = Reaction ~ days_deprived, data = sleep2)

Residuals:
     Min       1Q   Median       3Q      Max 
-112.284  -26.732    2.143   27.734  140.453 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    267.967      7.737  34.633  &lt; 2e-16 ***
days_deprived   11.435      1.850   6.183 6.32e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 50.85 on 142 degrees of freedom
Multiple R-squared:  0.2121,    Adjusted R-squared:  0.2066 
F-statistic: 38.23 on 1 and 142 DF,  p-value: 6.316e-09</code></pre>
</div>
</div>
</section>
<section id="interpretazione-del-modello-di-regressione-e-visualizzazione-grafica" class="level3" data-number="11.2.1">
<h3 data-number="11.2.1" class="anchored" data-anchor-id="interpretazione-del-modello-di-regressione-e-visualizzazione-grafica"><span class="header-section-number">11.2.1</span> Interpretazione del Modello di Regressione e Visualizzazione Grafica</h3>
<p>Il modello di regressione che abbiamo considerato offre una stima del tempo di risposta medio per i soggetti allo studio al Giorno 0 (prima della privazione del sonno) e la variazione media del tempo di risposta per ogni giorno aggiuntivo di privazione. Secondo questo modello, il tempo di risposta medio iniziale è stimato essere di circa 268 millisecondi, con un incremento medio di circa 11 millisecondi per ogni giorno successivo di privazione del sonno.</p>
<section id="considerazioni-sui-limiti-del-modello" class="level4" data-number="11.2.1.1">
<h4 data-number="11.2.1.1" class="anchored" data-anchor-id="considerazioni-sui-limiti-del-modello"><span class="header-section-number">11.2.1.1</span> Considerazioni sui Limiti del Modello</h4>
<p>È importante notare, tuttavia, che questo modello potrebbe avere delle limitazioni nella sua applicabilità: - <strong>Assunzione di Indipendenza</strong>: Il modello assume che tutte le osservazioni siano indipendenti. Questa assunzione potrebbe non essere valida nel nostro studio, dato che le osservazioni provengono da misurazioni ripetute sugli stessi soggetti. - <strong>Errori Standard dei Coefficienti</strong>: La presunta indipendenza delle osservazioni implica che gli errori standard dei coefficienti di regressione potrebbero non essere completamente affidabili.</p>
</section>
<section id="aggiunta-delle-previsioni-al-grafico" class="level4" data-number="11.2.1.2">
<h4 data-number="11.2.1.2" class="anchored" data-anchor-id="aggiunta-delle-previsioni-al-grafico"><span class="header-section-number">11.2.1.2</span> Aggiunta delle Previsioni al Grafico</h4>
<p>Per visualizzare meglio questi risultati, possiamo aggiungere le previsioni del modello al grafico che abbiamo già creato. Utilizziamo la funzione <code>geom_abline()</code> di R per tracciare la linea di regressione stimata direttamente sul grafico esistente: - <strong>Utilizzo di <code>geom_abline()</code></strong>: Questa funzione ci permette di aggiungere una linea di regressione al grafico, specificando l’intercetta e la pendenza. - <strong>Coefficienti del Modello</strong>: Utilizziamo <code>coef(cp_model)</code> per ottenere i coefficienti di regressione (intercetta e pendenza) dal nostro modello. Questa funzione restituisce un vettore con due elementi corrispondenti all’intercetta e alla pendenza, che possono essere poi utilizzati per definire la linea nel grafico.</p>
<p>In conclusione, l’aggiunta delle previsioni del modello al grafico fornisce una rappresentazione visiva dell’effetto stimato della privazione del sonno sul tempo di risposta. Tuttavia, è essenziale tenere presente le limitazioni e le assunzioni del modello, in particolare l’indipendenza delle osservazioni, che potrebbe non essere una rappresentazione accurata dei dati nel contesto di misurazioni ripetute.</p>
<div id="cell-18" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="10">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sleep2, <span class="fu">aes</span>(<span class="at">x =</span> days_deprived, <span class="at">y =</span> Reaction)) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_abline</span>(</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">intercept =</span> <span class="fu">coef</span>(cp_model)[<span class="dv">1</span>],</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">slope =</span> <span class="fu">coef</span>(cp_model)[<span class="dv">2</span>],</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">color =</span> <span class="st">"blue"</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">7</span>) <span class="sc">+</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span>Subject) <span class="sc">+</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Reaction Time"</span>, <span class="at">x =</span> <span class="st">"Days deprived of sleep (0 = baseline)"</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_multilevel_files/figure-html/cell-11-output-1.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Dall’analisi effettuata, emerge che il modello attuale non si adatta in modo ottimale ai dati raccolti. Questa situazione indica la necessità di esplorare un approccio diverso per modellare in modo più accurato le relazioni presenti nei dati.</p>
</section>
</section>
</section>
<section id="approccio-di-no-pooling" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="approccio-di-no-pooling"><span class="header-section-number">11.3</span> Approccio di No Pooling</h2>
<p>In alternativa al modello di “complete pooling”, consideriamo l’approccio di “no pooling”. Questo approccio si basa sull’idea di adattare modelli di regressione separati per ogni partecipante, trattando ogni individuo come un’entità distinta.</p>
<section id="caratteristiche-del-no-pooling" class="level3" data-number="11.3.1">
<h3 data-number="11.3.1" class="anchored" data-anchor-id="caratteristiche-del-no-pooling"><span class="header-section-number">11.3.1</span> Caratteristiche del No Pooling</h3>
<ul>
<li><strong>Indipendenza delle Stime</strong>: In questo approccio, ogni partecipante ha il proprio set di stime per l’intercetta e la pendenza. Le stime relative a un partecipante non sono influenzate dalle stime degli altri.</li>
<li><strong>Stime Individualizzate</strong>: Si stima separatamente una coppia di intercetta/pendenza per ciascuno dei 18 partecipanti, riconoscendo la possibilità di variazioni significative nelle risposte individuali.</li>
</ul>
</section>
<section id="implementazione-del-modello-di-no-pooling" class="level3" data-number="11.3.2">
<h3 data-number="11.3.2" class="anchored" data-anchor-id="implementazione-del-modello-di-no-pooling"><span class="header-section-number">11.3.2</span> Implementazione del Modello di No Pooling</h3>
<p>Esistono due modi principali per implementare questo approccio: 1. <strong>Regressioni Separate per Ogni Partecipante</strong>: Eseguire una serie di regressioni lineari individuali, una per ogni soggetto. 2. <strong>Modello di Regressione Unificato con Effetti Principali e Interazione</strong>: Utilizzare un unico modello di regressione che includa sia gli effetti principali sia l’interazione tra le variabili <code>Subject</code> (soggetto) e <code>Day</code> (giorno). Questo metodo permette di includere tutte le stime in un unico modello.</p>
<p>Per il secondo approccio, è necessario considerare le seguenti fasi: - <strong>Creazione di Variabili Dummy per il Fattore <code>Subject</code></strong>: Poiché <code>Subject</code> ha 18 livelli, saranno necessarie 17 variabili dummy per rappresentare questi livelli. In R, questo può essere fatto automaticamente definendo <code>Subject</code> come un fattore. - <strong>Includere <code>Subject</code> come Fattore nel Modello</strong>: Aggiungere <code>Subject</code>, definito come un fattore, come predittore nel modello. L’inclusione dell’interazione tra <code>Subject</code> e <code>days_deprived</code> permette variazioni nelle intercette e nelle pendenze tra i soggetti.</p>
</section>
<section id="verifica-del-fattore-subject" class="level3" data-number="11.3.3">
<h3 data-number="11.3.3" class="anchored" data-anchor-id="verifica-del-fattore-subject"><span class="header-section-number">11.3.3</span> Verifica del Fattore <code>Subject</code></h3>
<p>Prima di procedere, è importante assicurarsi che <code>Subject</code> sia definito correttamente come un fattore. Questo può essere verificato utilizzando la funzione <code>summary()</code> in R, che fornisce una sintesi delle caratteristiche della variabile, compreso se è trattata come un fattore.</p>
<div id="cell-20" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="11">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>sleep2 <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summary</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>    Reaction          Days         Subject   days_deprived 
 Min.   :203.0   Min.   :2.00   308    : 8   Min.   :0.00  
 1st Qu.:265.2   1st Qu.:3.75   309    : 8   1st Qu.:1.75  
 Median :303.2   Median :5.50   310    : 8   Median :3.50  
 Mean   :308.0   Mean   :5.50   330    : 8   Mean   :3.50  
 3rd Qu.:347.7   3rd Qu.:7.25   331    : 8   3rd Qu.:5.25  
 Max.   :466.4   Max.   :9.00   332    : 8   Max.   :7.00  
                                (Other):96                 </code></pre>
</div>
</div>
<p>La funzione <code>pull()</code> viene utilizzata per estrarre una specifica colonna da un data frame. Con le seguenti istruzioni verifichiamo se la colonna <code>Subject</code> è codificata come <code>factor</code>.</p>
<div id="cell-22" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="12">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>sleep2 <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(Subject) <span class="sc">|&gt;</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">is.factor</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
TRUE
</div>
</div>
<p>Adattiamo il modello di regressione ai dati. Si noti che la sintassi seguente può essere semplificata utilizzando <code>Reaction ~ days_deprived * Subject</code>.</p>
<div id="cell-24" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="13">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>np_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Reaction <span class="sc">~</span> days_deprived <span class="sc">+</span> Subject <span class="sc">+</span> days_deprived<span class="sc">:</span>Subject,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> sleep2</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(np_model)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>
Call:
lm(formula = Reaction ~ days_deprived + Subject + days_deprived:Subject, 
    data = sleep2)

Residuals:
     Min       1Q   Median       3Q      Max 
-106.521   -8.541    1.143    8.889  128.545 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              288.2175    16.4772  17.492  &lt; 2e-16 ***
days_deprived             21.6905     3.9388   5.507 2.49e-07 ***
Subject309               -87.9262    23.3023  -3.773 0.000264 ***
Subject310               -62.2856    23.3023  -2.673 0.008685 ** 
Subject330               -14.9533    23.3023  -0.642 0.522422    
Subject331                 9.9658    23.3023   0.428 0.669740    
Subject332                27.8157    23.3023   1.194 0.235215    
Subject333                -2.7581    23.3023  -0.118 0.906000    
Subject334               -50.2051    23.3023  -2.155 0.033422 *  
Subject335               -25.3429    23.3023  -1.088 0.279207    
Subject337                24.6143    23.3023   1.056 0.293187    
Subject349               -59.2183    23.3023  -2.541 0.012464 *  
Subject350               -40.2023    23.3023  -1.725 0.087343 .  
Subject351               -24.2467    23.3023  -1.041 0.300419    
Subject352                43.0655    23.3023   1.848 0.067321 .  
Subject369               -21.5040    23.3023  -0.923 0.358154    
Subject370               -53.3072    23.3023  -2.288 0.024107 *  
Subject371               -30.4896    23.3023  -1.308 0.193504    
Subject372                 2.4772    23.3023   0.106 0.915535    
days_deprived:Subject309 -17.3334     5.5703  -3.112 0.002380 ** 
days_deprived:Subject310 -17.7915     5.5703  -3.194 0.001839 ** 
days_deprived:Subject330 -13.6849     5.5703  -2.457 0.015613 *  
days_deprived:Subject331 -16.8231     5.5703  -3.020 0.003154 ** 
days_deprived:Subject332 -19.2947     5.5703  -3.464 0.000765 ***
days_deprived:Subject333 -10.8151     5.5703  -1.942 0.054796 .  
days_deprived:Subject334  -3.5745     5.5703  -0.642 0.522423    
days_deprived:Subject335 -25.8995     5.5703  -4.650 9.47e-06 ***
days_deprived:Subject337   0.7518     5.5703   0.135 0.892895    
days_deprived:Subject349  -5.2644     5.5703  -0.945 0.346731    
days_deprived:Subject350   1.6007     5.5703   0.287 0.774382    
days_deprived:Subject351 -13.1681     5.5703  -2.364 0.019867 *  
days_deprived:Subject352 -14.4019     5.5703  -2.585 0.011057 *  
days_deprived:Subject369  -7.8948     5.5703  -1.417 0.159273    
days_deprived:Subject370  -1.0495     5.5703  -0.188 0.850912    
days_deprived:Subject371  -9.3443     5.5703  -1.678 0.096334 .  
days_deprived:Subject372 -10.6041     5.5703  -1.904 0.059613 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 25.53 on 108 degrees of freedom
Multiple R-squared:  0.849, Adjusted R-squared:  0.8001 
F-statistic: 17.35 on 35 and 108 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Per chiarire, il soggetto di riferimento è il 308; in R, la modalità predefinita è quella di ordinare i livelli del fattore in ordine alfabetico e di scegliere il primo come soggetto di riferimento. Questo significa che l’intercetta e la pendenza per il soggetto 308 sono rappresentate rispettivamente da <code>(Intercept)</code> e <code>days_deprived</code>, poiché tutte le altre 17 variabili dummy saranno nulle per il soggetto 308.</p>
<p>Tutti i coefficienti di regressione degli altri soggetti sono rappresentati come scostamenti da questo soggetto di riferimento. Se desideriamo calcolare l’intercetta e la pendenza per un dato soggetto, dobbiamo semplicemente sommare gli scostamenti corrispondenti. Pertanto, abbiamo:</p>
<p>Intercetta per 308: 288.217<br>
Pendenza per 308: 21.69</p>
<p>Intercetta per 335: <code>(Intercept) + Subject335</code> = 288.217 + -25.343 = 262.874<br>
Pendenza per 335: <code>days_deprived + days_deprived:Subject335</code> = 21.69 + -25.899 = -4.209</p>
<p>E così via.</p>
<p>Nel modello “no pooling”, non viene stimata un’intercetta e una pendenza complessive per l’intera popolazione; in questo caso, <code>(Intercept)</code> e <code>days_deprived</code> sono stime dell’intercetta e della pendenza per il soggetto 308, che è stato scelto (arbitrariamente) come soggetto di riferimento. Per ottenere stime per l’intera popolazione, è possibile procedere con una seconda fase dell’analisi statistica in cui calcoliamo le medie delle intercette e delle pendenze individuali.</p>
<div id="cell-26" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="14">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(np_model) <span class="sc">|&gt;</span> <span class="fu">as.data.frame</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>A data.frame: 36 x 1</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">coef(np_model)</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">(Intercept)</td>
<td>288.2174667</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">days_deprived</td>
<td>21.6904952</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">Subject309</td>
<td>-87.9262083</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">Subject310</td>
<td>-62.2856250</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">Subject330</td>
<td>-14.9532917</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">Subject331</td>
<td>9.9658167</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">Subject332</td>
<td>27.8157333</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">Subject333</td>
<td>-2.7581167</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">Subject334</td>
<td>-50.2051167</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">Subject335</td>
<td>-25.3428833</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">Subject337</td>
<td>24.6143167</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">Subject349</td>
<td>-59.2183250</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">Subject350</td>
<td>-40.2022833</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">Subject351</td>
<td>-24.2467083</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">Subject352</td>
<td>43.0654583</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">Subject369</td>
<td>-21.5040417</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">Subject370</td>
<td>-53.3072333</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">Subject371</td>
<td>-30.4895750</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">Subject372</td>
<td>2.4772250</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">days_deprived:Subject309</td>
<td>-17.3333512</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">days_deprived:Subject310</td>
<td>-17.7915000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">days_deprived:Subject330</td>
<td>-13.6848524</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">days_deprived:Subject331</td>
<td>-16.8231262</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">days_deprived:Subject332</td>
<td>-19.2946845</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">days_deprived:Subject333</td>
<td>-10.8151060</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">days_deprived:Subject334</td>
<td>-3.5745167</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">days_deprived:Subject335</td>
<td>-25.8994869</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">days_deprived:Subject337</td>
<td>0.7517702</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">days_deprived:Subject349</td>
<td>-5.2643643</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">days_deprived:Subject350</td>
<td>1.6007274</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">days_deprived:Subject351</td>
<td>-13.1680905</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">days_deprived:Subject352</td>
<td>-14.4018881</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">days_deprived:Subject369</td>
<td>-7.8948310</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">days_deprived:Subject370</td>
<td>-1.0494833</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">days_deprived:Subject371</td>
<td>-9.3442786</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">days_deprived:Subject372</td>
<td>-10.6041357</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Calcoliamo le intercette individuali:</p>
<div id="cell-28" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="15">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>all_intercepts <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coef</span>(np_model)[<span class="st">"(Intercept)"</span>],</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coef</span>(np_model)[<span class="dv">3</span><span class="sc">:</span><span class="dv">19</span>] <span class="sc">+</span> <span class="fu">coef</span>(np_model)[<span class="st">"(Intercept)"</span>]</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Calcliamo le pendenze individuali:</p>
<div id="cell-30" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="16">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>all_slopes <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coef</span>(np_model)[<span class="st">"days_deprived"</span>],</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coef</span>(np_model)[<span class="dv">20</span><span class="sc">:</span><span class="dv">36</span>] <span class="sc">+</span> <span class="fu">coef</span>(np_model)[<span class="st">"days_deprived"</span>]</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Creiamo un DataFrame con le colonne Subject, intercept e slope:</p>
<div id="cell-32" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="17">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>ids <span class="ot">&lt;-</span> sleep2 <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(Subject) <span class="sc">|&gt;</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">levels</span>() <span class="sc">|&gt;</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">factor</span>()</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ids)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 308 309 310 330 331 332 333 334 335 337 349 350 351 352 369 370 371 372
18 Levels: 308 309 310 330 331 332 333 334 335 337 349 350 351 352 369 ... 372</code></pre>
</div>
</div>
<div id="cell-33" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="18">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make a tibble with the data extracted above</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>np_coef <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Subject =</span> ids,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">intercept =</span> all_intercepts,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">slope =</span> all_slopes</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(np_coef)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 x 3
   Subject intercept slope
   &lt;fct&gt;       &lt;dbl&gt; &lt;dbl&gt;
 1 308          288. 21.7 
 2 309          200.  4.36
 3 310          226.  3.90
 4 330          273.  8.01
 5 331          298.  4.87
 6 332          316.  2.40
 7 333          285. 10.9 
 8 334          238. 18.1 
 9 335          263. -4.21
10 337          313. 22.4 
11 349          229. 16.4 
12 350          248. 23.3 
13 351          264.  8.52
14 352          331.  7.29
15 369          267. 13.8 
16 370          235. 20.6 
17 371          258. 12.3 
18 372          291. 11.1 </code></pre>
</div>
</div>
<p>Esaminiamo l’adattamento di questo modello ai dati.</p>
<div id="cell-35" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="19">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sleep2, <span class="fu">aes</span>(<span class="at">x =</span> days_deprived, <span class="at">y =</span> Reaction)) <span class="sc">+</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_abline</span>(</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> np_coef,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">mapping =</span> <span class="fu">aes</span>(</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">intercept =</span> intercept,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">slope =</span> slope</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>        ),</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">color =</span> <span class="st">"blue"</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">7</span>) <span class="sc">+</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span>Subject) <span class="sc">+</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Reaction Time"</span>, <span class="at">x =</span> <span class="st">"Days deprived of sleep (0 = baseline)"</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_multilevel_files/figure-html/cell-20-output-1.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Questa situazione è notevolmente migliorata rispetto al modello di pooling completo. Se desideriamo testare l’ipotesi nulla secondo cui la pendenza della retta di regressione è uguale a zero, possiamo farlo eseguendo un test <span class="math inline">\(t\)</span> di Student sul campione di pendenze individuali.</p>
<div id="cell-37" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="20">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>np_coef <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(slope) <span class="sc">|&gt;</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">t.test</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>
    One Sample t-test

data:  pull(np_coef, slope)
t = 6.1971, df = 17, p-value = 9.749e-06
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
  7.542244 15.328613
sample estimates:
mean of x 
 11.43543 </code></pre>
</div>
</div>
<p>Questo test suggerisce che la pendenza media di 11.435 è diversa da zero, t(17) = 6.20 p &lt; .001.</p>
</section>
</section>
<section id="approccio-di-partial-pooling" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="approccio-di-partial-pooling"><span class="header-section-number">11.4</span> Approccio di Partial Pooling</h2>
<p>Nell’ambito dell’analisi dei dati psicologici, i ricercatori si trovano spesso a dover gestire un delicato equilibrio. Da un lato, vi è l’approccio di <em>complete pooling</em>, che tratta tutti i dati come se appartenessero a un unico gruppo omogeneo, e dall’altro, l’approccio di <em>no-pooling</em>, che considera i dati di ciascun soggetto in modo isolato, senza sfruttare le informazioni aggregate. Entrambi gli estremi hanno limitazioni significative: il <em>complete pooling</em> può mascherare le variazioni individuali, mentre il <em>no-pooling</em> può non sfruttare appieno le informazioni disponibili dall’intero set di dati.</p>
<p>Per superare queste limitazioni, emerge l’approccio di <em>partial pooling</em>. Questo metodo utilizza i modelli lineari a effetti misti, che rappresentano una via di mezzo tra i due estremi menzionati. Il <em>partial pooling</em> permette di trarre vantaggio dalle informazioni provenienti dall’insieme dei partecipanti, migliorando così le stime dei soggetti individuali. Attraverso questo approccio, si ottengono stime che non solo tengono conto delle peculiarità di ciascun individuo ma sono anche informate dalle tendenze generali osservate nel gruppo più ampio.</p>
<p>L’approccio di <em>partial pooling</em> permette di separare più efficacemente le tendenze generali dagli errori casuali in ciascun partecipante e si dimostra più adatto per generalizzare i risultati a una popolazione più ampia, al di là dei soggetti specifici coinvolti nello studio.</p>
<section id="implementazione-dei-modelli-a-effetti-misti" class="level3" data-number="11.4.1">
<h3 data-number="11.4.1" class="anchored" data-anchor-id="implementazione-dei-modelli-a-effetti-misti"><span class="header-section-number">11.4.1</span> Implementazione dei Modelli a Effetti Misti</h3>
<ul>
<li><strong>Trattare i Soggetti come Fattori Casuali</strong>: Nel <em>partial pooling</em>, i soggetti vengono considerati come un fattore casuale anziché fisso. Ciò implica che i livelli del fattore (i soggetti nel nostro caso) sono visti come un campione casuale da una popolazione più ampia.</li>
<li><strong>Modello Lineare a Effetti Misti</strong>: Questo tipo di modello statistico consente di includere i fattori casuali nell’analisi. In un modello misto, le stime per ogni soggetto sono “informate” o influenzate dalle informazioni aggregate degli altri soggetti.</li>
<li><strong>Shrinkage o Restringimento</strong>: Il fenomeno dello <em>shrinkage</em> indica che le stime per ciascun soggetto vengono regolate o “spostate” verso le stime medie della popolazione, permettendo una valutazione più equilibrata e meno influenzata da variazioni estreme o casuali.</li>
</ul>
</section>
<section id="articolazione-e-applicazione-del-modello-multilivello" class="level3" data-number="11.4.2">
<h3 data-number="11.4.2" class="anchored" data-anchor-id="articolazione-e-applicazione-del-modello-multilivello"><span class="header-section-number">11.4.2</span> Articolazione e Applicazione del Modello Multilivello</h3>
<p>Il modello multilivello che analizziamo è strutturato per cogliere le relazioni dinamiche tra variabili a livelli diversi. Esaminiamo i dettagli di ogni livello e il loro significato nel contesto del modello.</p>
<section id="livello-1-modellazione-della-relazione-individuale" class="level4" data-number="11.4.2.1">
<h4 data-number="11.4.2.1" class="anchored" data-anchor-id="livello-1-modellazione-della-relazione-individuale"><span class="header-section-number">11.4.2.1</span> Livello 1: Modellazione della Relazione Individuale</h4>
<p>Il primo livello del modello esprime la relazione lineare individuale tra la variabile di risposta (tempo di reazione) e i predittori (giorni di privazione del sonno):</p>
<p><span class="math display">\[
Y_{sd} = \beta_{0s} + \beta_{1s} X_{sd} + e_{sd},
\]</span></p>
<p>dove <span class="math inline">\(Y_{sd}\)</span> è il tempo di reazione del soggetto <span class="math inline">\(s\)</span> al giorno <span class="math inline">\(d\)</span>, <span class="math inline">\(\beta_{0s}\)</span> e <span class="math inline">\(\beta_{1s}\)</span> sono i parametri individuali di intercetta e pendenza, e <span class="math inline">\(e_{sd}\)</span> rappresenta l’errore per ogni soggetto e giorno. I parametri <span class="math inline">\(\beta_{0s}\)</span> e <span class="math inline">\(\beta_{1s}\)</span> sono considerati derivati, poiché dipendono dalle variabili a Livello 2.</p>
</section>
<section id="livello-2-modellazione-delle-variazioni-tra-soggetti" class="level4" data-number="11.4.2.2">
<h4 data-number="11.4.2.2" class="anchored" data-anchor-id="livello-2-modellazione-delle-variazioni-tra-soggetti"><span class="header-section-number">11.4.2.2</span> Livello 2: Modellazione delle Variazioni Tra Soggetti</h4>
<p>Al secondo livello, definiamo come l’intercetta e la pendenza cambiano tra i soggetti:</p>
<p><span class="math display">\[
\beta_{0s} = \gamma_{0} + S_{0s},
\]</span></p>
<p><span class="math display">\[
\beta_{1s} = \gamma_{1} + S_{1s}.
\]</span></p>
<p>Qui, <span class="math inline">\(\gamma_0\)</span> e <span class="math inline">\(\gamma_1\)</span> sono gli effetti fissi che rappresentano l’intercetta e la pendenza medie della popolazione, mentre <span class="math inline">\(S_{0s}\)</span> e <span class="math inline">\(S_{1s}\)</span> sono gli effetti casuali che permettono variazioni individuali.</p>
</section>
<section id="componenti-di-varianza" class="level4" data-number="11.4.2.3">
<h4 data-number="11.4.2.3" class="anchored" data-anchor-id="componenti-di-varianza"><span class="header-section-number">11.4.2.3</span> Componenti di Varianza</h4>
<p>Le componenti di varianza nel modello sono espresse come:</p>
<p><span class="math display">\[
\langle S_{0s}, S_{1s} \rangle \sim N(\langle 0, 0 \rangle, \mathbf{\Sigma}),
\]</span></p>
<p><span class="math display">\[
\mathbf{\Sigma} = \begin{pmatrix}{\tau_{00}}^2 &amp; \rho\tau_{00}\tau_{11} \\ \rho\tau_{00}\tau_{11} &amp; {\tau_{11}}^2 \end{pmatrix},
\]</span></p>
<p><span class="math display">\[
e_{sd} \sim N(0, \sigma^2).
\]</span></p>
<p>La matrice <span class="math inline">\(\mathbf{\Sigma}\)</span> determina la distribuzione degli effetti casuali, con <span class="math inline">\({\tau_{00}}^2\)</span> e <span class="math inline">\({\tau_{11}}^2\)</span> che indicano le varianze delle intercette e delle pendenze casuali, mentre <span class="math inline">\(\rho\)</span> è la correlazione tra questi effetti.</p>
</section>
<section id="interpretazione-complessiva-del-modello" class="level4" data-number="11.4.2.4">
<h4 data-number="11.4.2.4" class="anchored" data-anchor-id="interpretazione-complessiva-del-modello"><span class="header-section-number">11.4.2.4</span> Interpretazione Complessiva del Modello</h4>
<p>Unendo le equazioni di Livello 1 e Livello 2, otteniamo una visione completa del modello:</p>
<p><span class="math display">\[
Y_{sd} = \gamma_0 + S_{0s} + (\gamma_1 + S_{1s}) X_{sd} + e_{sd},
\]</span></p>
<p>dove</p>
<ul>
<li>$ Y_{sd} $: È il valore osservato della variabile di risposta per il soggetto $ s $ al giorno $ d $.</li>
<li>$ _0 $ e $ _1 $: Sono gli effetti fissi. $ _0 $ rappresenta l’intercetta generale, ovvero la media della popolazione per la variabile di risposta quando la variabile predittiva $ X $ è zero. $ _1 $ rappresenta la pendenza generale, che indica come la variabile di risposta cambia in media con un’unità di incremento della variabile predittiva $ X $.</li>
<li>$ S_{0s} $ e $ S_{1s} $: Sono gli effetti casuali. $ S_{0s} $ è l’effetto casuale dell’intercetta per il soggetto $ s $, mentre $ S_{1s} $ è l’effetto casuale della pendenza. Questi termini rappresentano come ciascun soggetto si discosta dalla media della popolazione.</li>
<li>$ X_{sd} $: È la variabile predittiva per il soggetto $ s $ al giorno $ d $.</li>
<li>$ e_{sd} $: È l’errore casuale associato a ciascuna osservazione.</li>
</ul>
</section>
<section id="interpretazione-degli-effetti-fissi-e-casuali" class="level4" data-number="11.4.2.5">
<h4 data-number="11.4.2.5" class="anchored" data-anchor-id="interpretazione-degli-effetti-fissi-e-casuali"><span class="header-section-number">11.4.2.5</span> Interpretazione degli Effetti Fissi e Casuali</h4>
<ul>
<li>Gli effetti fissi ($ _0 $ e $ _1 $) sono costanti per tutti i soggetti e riflettono le caratteristiche della popolazione generale.</li>
<li>Gli effetti casuali ($ S_{0s} $ e $ S_{1s} $) variano da soggetto a soggetto e sono modellati come distribuzioni normali centrate attorno a zero. Questo significa che la distribuzione degli effetti casuali è centrata attorno agli effetti fissi della popolazione.</li>
</ul>
</section>
<section id="uso-di-campioni-per-informare-sulla-popolazione" class="level4" data-number="11.4.2.6">
<h4 data-number="11.4.2.6" class="anchored" data-anchor-id="uso-di-campioni-per-informare-sulla-popolazione"><span class="header-section-number">11.4.2.6</span> Uso di Campioni per Informare sulla Popolazione</h4>
<p>Trattare i soggetti come variabili casuali anziché fisse ci consente di usare i dati del campione per inferire sulla popolazione più ampia. Invece di stimare valori specifici per ogni soggetto, il modello stima la distribuzione da cui questi valori sono estratti, fornendo una visione più generalizzata e applicabile a livello di popolazione.</p>
</section>
</section>
<section id="spiegazione-della-matrice-di-varianza-covarianza-nel-modello-multilivello" class="level3" data-number="11.4.3">
<h3 data-number="11.4.3" class="anchored" data-anchor-id="spiegazione-della-matrice-di-varianza-covarianza-nel-modello-multilivello"><span class="header-section-number">11.4.3</span> Spiegazione della Matrice di Varianza-Covarianza nel Modello Multilivello</h3>
<p>La matrice di varianza-covarianza nel modello multilivello gioca un ruolo cruciale nel definire come gli effetti casuali variano e sono correlati tra loro all’interno della popolazione studiata. Questa matrice è rappresentata come segue:</p>
<p><span class="math display">\[
\Sigma =
\begin{pmatrix}
\tau_{00}^2 &amp; \rho \tau_{00} \tau_{11} \\
\rho \tau_{00} \tau_{11} &amp; \tau_{11}^2
\end{pmatrix},
\]</span></p>
<p>dove <span class="math inline">\(\Sigma\)</span> denota la matrice di varianza-covarianza per gli effetti casuali <span class="math inline">\(\langle S_{0s}, S_{1s} \rangle\)</span>, che sono modellati come normalmente distribuiti con una media di zero e una varianza-covarianza data da <span class="math inline">\(\Sigma\)</span>.</p>
<section id="componenti-della-matrice" class="level4" data-number="11.4.3.1">
<h4 data-number="11.4.3.1" class="anchored" data-anchor-id="componenti-della-matrice"><span class="header-section-number">11.4.3.1</span> Componenti della Matrice</h4>
<ul>
<li><strong>Varianze degli Effetti Casuali</strong>:
<ul>
<li><span class="math inline">\(\tau_{00}^2\)</span>: Varianza dell’effetto casuale sull’intercetta (<span class="math inline">\(S_{0s}\)</span>). Questo parametro indica quanto i soggetti differiscono nella loro reazione iniziale (tempo di reazione al Giorno 0) prima di qualsiasi privazione del sonno.</li>
<li><span class="math inline">\(\tau_{11}^2\)</span>: Varianza dell’effetto casuale sulla pendenza (<span class="math inline">\(S_{1s}\)</span>). Misura la variazione tra i soggetti nella loro reattività agli effetti della privazione del sonno.</li>
</ul></li>
<li><strong>Covarianze</strong>:
<ul>
<li><span class="math inline">\(\rho \tau_{00} \tau_{11}\)</span>: Covarianza tra l’intercetta e la pendenza casuali. Questo termine riflette come la reazione iniziale di un soggetto (intercetta) sia correlata con la variazione della sua reattività al sonno (pendenza). Un valore positivo di <span class="math inline">\(\rho\)</span> indica che soggetti con un tempo di reazione inizialmente più lento tendono a mostrare un aumento più marcato del tempo di reazione con la privazione del sonno, e viceversa.</li>
</ul></li>
</ul>
</section>
<section id="significato-e-importanza-di-sigma" class="level4" data-number="11.4.3.2">
<h4 data-number="11.4.3.2" class="anchored" data-anchor-id="significato-e-importanza-di-sigma"><span class="header-section-number">11.4.3.2</span> Significato e Importanza di <span class="math inline">\(\Sigma\)</span></h4>
<ul>
<li><strong>Distribuzione degli Effetti Casuali</strong>: La matrice <span class="math inline">\(\Sigma\)</span> determina le probabilità di estrarre una coppia specifica di effetti casuali (<span class="math inline">\(S_{0s}, S_{1s}\)</span>) per un soggetto dal pool più ampio della popolazione.</li>
<li><strong>Analisi delle Variazioni Individuali</strong>: Attraverso <span class="math inline">\(\Sigma\)</span>, possiamo comprendere meglio quanto e in che modo i soggetti variano sia nella loro reazione iniziale sia nella loro risposta alla privazione del sonno.</li>
<li><strong>Interpretazione dei Risultati</strong>: La comprensione di <span class="math inline">\(\Sigma\)</span> aiuta a interpretare i risultati del modello in termini di varianza e covarianza tra i soggetti, permettendo di trarre conclusioni più precise sulla popolazione studiata.</li>
</ul>
<p>La matrice di varianza-covarianza <span class="math inline">\(\Sigma\)</span> è fondamentale nel modello multilivello perché fornisce un quadro dettagliato della varianza e della covarianza degli effetti casuali, consentendo di cogliere le sottili variazioni e correlazioni tra i soggetti. Questa comprensione arricchisce l’analisi e rende possibili conclusioni più accurate sulla popolazione.</p>
</section>
</section>
<section id="tabella-delle-variabili" class="level3" data-number="11.4.4">
<h3 data-number="11.4.4" class="anchored" data-anchor-id="tabella-delle-variabili"><span class="header-section-number">11.4.4</span> Tabella delle Variabili</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 10%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th>Variabile</th>
<th>Tipo</th>
<th>Descrizione</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(Y_{sd}\)</span></td>
<td>Osservata</td>
<td>Valore di <code>Reaction</code> per il soggetto <span class="math inline">\(s\)</span> al giorno <span class="math inline">\(d\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(X_{sd}\)</span></td>
<td>Osservata</td>
<td>Valore di <code>days_deprived</code> (0-7) per il soggetto <span class="math inline">\(s\)</span> al giorno <span class="math inline">\(d\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\beta_{0s}\)</span></td>
<td>Derivata</td>
<td>Parametro di intercetta di livello 1 per il soggetto <span class="math inline">\(s\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\beta_{1s}\)</span></td>
<td>Derivata</td>
<td>Parametro di pendenza di livello 1 per il soggetto <span class="math inline">\(s\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(e_{sd}\)</span></td>
<td>Derivata</td>
<td>Errore per il soggetto <span class="math inline">\(s\)</span> al giorno <span class="math inline">\(d\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\gamma_0\)</span></td>
<td>Fissa</td>
<td>Intersezione generale (media di <span class="math inline">\(\beta_{0s}\)</span> nella popolazione)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\gamma_1\)</span></td>
<td>Fissa</td>
<td>Pendenza generale (media di <span class="math inline">\(\beta_{1s}\)</span> nella popolazione)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(S_{0s}\)</span></td>
<td>Casuale</td>
<td>Effetto random di intercetta per il soggetto <span class="math inline">\(s\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(S_{1s}\)</span></td>
<td>Casuale</td>
<td>Effetto random di pendenza per il soggetto <span class="math inline">\(s\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mathbf{\Sigma}\)</span></td>
<td>Casuale</td>
<td>Matrice di varianza-covarianza</td>
</tr>
<tr class="odd">
<td><span class="math inline">\({\tau_{00}}^2\)</span></td>
<td>Casuale</td>
<td>Varianza degli effetti random di intercetta</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\rho\)</span></td>
<td>Casuale</td>
<td>Correlazione tra intercetta e pendenza</td>
</tr>
<tr class="odd">
<td><span class="math inline">\({\tau_{11}}^2\)</span></td>
<td>Casuale</td>
<td>Varianza degli effetti random di pendenza</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\sigma^2\)</span></td>
<td>Casuale</td>
<td>Varianza dell’errore</td>
</tr>
</tbody>
</table>
<section id="spiegazione-delle-categorie-di-variabili-nel-modello-multilivello" class="level4" data-number="11.4.4.1">
<h4 data-number="11.4.4.1" class="anchored" data-anchor-id="spiegazione-delle-categorie-di-variabili-nel-modello-multilivello"><span class="header-section-number">11.4.4.1</span> Spiegazione delle Categorie di Variabili nel Modello Multilivello</h4>
<p>Nella tabella delle variabili del modello multilivello, utilizziamo tre categorie specifiche per classificare le diverse variabili: <em>fisso</em>, <em>casuale</em> e <em>derivato</em>. Queste categorie ci aiutano a comprendere il ruolo e la natura di ciascuna variabile all’interno del modello:</p>
<section id="variabili-fisse" class="level5" data-number="11.4.4.1.1">
<h5 data-number="11.4.4.1.1" class="anchored" data-anchor-id="variabili-fisse"><span class="header-section-number">11.4.4.1.1</span> Variabili Fisse</h5>
<ul>
<li><strong>Definizione</strong>: Le variabili fisse sono quelle che assumiamo costanti attraverso il campione e la popolazione. Sono parametri che rappresentano le caratteristiche generali della popolazione da cui il campione è tratto.</li>
<li><strong>Esempi</strong>: Nella tabella, <span class="math inline">\(\gamma_0\)</span> (intercetta generale) e <span class="math inline">\(\gamma_1\)</span> (pendenza generale) sono variabili fisse.</li>
<li><strong>Ruolo nel Modello</strong>: Riflettono le tendenze centrali o gli effetti medi nella popolazione oggetto di studio.</li>
</ul>
</section>
<section id="variabili-casuali" class="level5" data-number="11.4.4.1.2">
<h5 data-number="11.4.4.1.2" class="anchored" data-anchor-id="variabili-casuali"><span class="header-section-number">11.4.4.1.2</span> Variabili Casuali</h5>
<ul>
<li><strong>Definizione</strong>: Le variabili casuali indicano i parametri che possono variare tra i soggetti o altre unità di analisi. Questi parametri sono concepiti come estratti da una distribuzione più ampia.</li>
<li><strong>Esempi</strong>: <span class="math inline">\(S_{0s}\)</span> (intercetta casuale per soggetto) e <span class="math inline">\(S_{1s}\)</span> (pendenza casuale per soggetto) sono esempi di variabili casuali.</li>
<li><strong>Ruolo nel Modello</strong>: Consentono di modellare e comprendere la varianza e la covarianza all’interno del campione, riflettendo la variabilità individuale o di gruppo.</li>
</ul>
</section>
<section id="variabili-derivate" class="level5" data-number="11.4.4.1.3">
<h5 data-number="11.4.4.1.3" class="anchored" data-anchor-id="variabili-derivate"><span class="header-section-number">11.4.4.1.3</span> Variabili Derivate</h5>
<ul>
<li><strong>Definizione</strong>: ‘Derivato’ non è un termine standard nella modellistica statistica, ma lo utilizziamo qui per distinguere le variabili che non sono direttamente stimabili, ma piuttosto calcolate o derivate da altre variabili nel modello.</li>
<li><strong>Esempi</strong>: <span class="math inline">\(\beta_{0s}\)</span> (intercetta di livello 1 per soggetto) e <span class="math inline">\(\beta_{1s}\)</span> (pendenza di livello 1 per soggetto) sono variabili derivate, calcolate combinando variabili fisse e casuali.</li>
<li><strong>Ruolo nel Modello</strong>: Le variabili derivate rappresentano i parametri specifici per ciascun soggetto o unità di analisi, derivati dalla combinazione delle influenze fisse e casuali.</li>
</ul>
<p>In conclusione, il modello misto permette di tenere conto della variazione sia a livello di popolazione sia a livello individuale. Questa capacità di distinguere tra variazioni generali e specifiche dei soggetti è cruciale in molte situazioni, come quando si analizzano effetti di trattamenti o condizioni sperimentali diverse su gruppi di soggetti.</p>
</section>
</section>
</section>
</section>
<section id="stimare-i-parametri-del-modello" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="stimare-i-parametri-del-modello"><span class="header-section-number">11.5</span> Stimare i parametri del modello</h2>
<p>Per stimare i parametri del modello usando R, utilizzeremo la funzione <code>lmer()</code> del pacchetto <code>lme4</code> {cite:t}<code>bates2014fitting</code>. Questa funzione permette di specificare sia i fattori fissi (come i giorni di deprivazione del sonno) sia i fattori casuali (come i soggetti), ottenendo un modello che bilancia efficacemente le informazioni individuali con quelle aggregate.</p>
<p>La sintassi base di <code>lmer()</code> è la seguente:</p>
<p><span class="math display">\[ \text{lmer(formula, data, ...)}, \]</span></p>
<p>dove formula esprime la struttura del modello sottostante in un formato compatto e data è il data frame in cui si trovano le variabili menzionate nella formula.</p>
<p>Il formato generale della formula del modello per N effetti fissi (fix) e K effetti casuali (ran) è:</p>
<p><span class="math display">\[ \text{DV ~ fix1 + fix2 + ... + fixN + (ran1 + ran2 + ... + ranK | random\_factor1)} \]</span></p>
<p>Le interazioni tra i fattori A e B possono essere specificate utilizzando sia A * B (interazione ed effetti principali) che A:B (solo l’interazione).</p>
<p>Una differenza chiave dalla sintassi standard dei modelli R è la presenza di un termine di effetto casuale, racchiuso tra parentesi, ad esempio <code>(ran1 + ran2 + ... + ranK | random_factor)</code>. Ogni espressione tra parentesi rappresenta gli effetti casuali associati a un singolo fattore casuale. È possibile avere più di un termine di effetti casuali in una singola formula (fattori casuali incrociati). I termini relativi agli effetti casuali forniscono istruzioni a <code>lmer()</code> su come costruire le matrici di varianza-covarianza.</p>
<p>Sul lato sinistro della barra <code>|</code> vengono elencati gli effetti che vogliamo fare variare tra i livelli del fattore casuale indicato sul lato destro. Di solito, la variabile sul lato destro è una variabile che identifica i soggetti (ad esempio, <code>subject_id</code>).</p>
<p>Consideriamo le seguenti possibili formule di modello per i dati <code>sleep2</code> e le matrici di varianza-covarianza che esse costruiscono.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 37%">
<col style="width: 62%">
</colgroup>
<thead>
<tr class="header">
<th>model</th>
<th>syntax</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. random intercepts only</td>
<td>Reaction ~ days_deprived + (1 | Subject)</td>
</tr>
<tr class="even">
<td>2. random intercepts and slopes</td>
<td>Reaction ~ days_deprived + (1 + days_deprived | Subject)</td>
</tr>
<tr class="odd">
<td>3. model 2 alternate syntax</td>
<td>Reaction ~ days_deprived + (days_deprived | Subject)</td>
</tr>
<tr class="even">
<td>4. random slopes only</td>
<td>Reaction ~ days_deprived + (0 + days_deprived | Subject)</td>
</tr>
<tr class="odd">
<td>5. model 2 + zero-covariances</td>
<td>Reaction ~ days_deprived + (days_deprived || Subject)</td>
</tr>
</tbody>
</table>
<p>Modello 1:</p>
<p><span class="math display">\[ \mathbf{\Sigma} =
\begin{pmatrix}
\tau_{00}^2 &amp; 0 \\
0 &amp; 0
\end{pmatrix}
\]</span></p>
<p>Modelli 2 e 3:</p>
<p><span class="math display">\[  \mathbf{\Sigma} =
\begin{pmatrix}
\tau_{00}^2 &amp; \rho \tau_{00} \tau_{11} \\
\rho \tau_{00} \tau_{11} &amp; \tau_{11}^2
\end{pmatrix}
\]</span></p>
<p>Modello 4:</p>
<p><span class="math display">\[  \mathbf{\Sigma} =
\begin{pmatrix}
0 &amp; 0 \\
0 &amp; \tau_{11}^2
\end{pmatrix}
\]</span></p>
<p>Modello 5:</p>
<p><span class="math display">\[  \mathbf{\Sigma} =
\begin{pmatrix}
\tau_{00}^2 &amp; 0 \\
0 &amp; \tau_{11}^2
\end{pmatrix}
\]</span></p>
<p>Il modello più ragionevole per i dati dell’esempio è il Modello 2, quindi useremo quello.</p>
<div id="cell-41" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="21">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>pp_mod <span class="ot">&lt;-</span> <span class="fu">lmer</span>(</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>    Reaction <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> days_deprived <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> days_deprived <span class="sc">|</span> Subject), </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> sleep2</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pp_mod)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: Reaction ~ 1 + days_deprived + (1 + days_deprived | Subject)
   Data: sleep2

REML criterion at convergence: 1404.1

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-4.0157 -0.3541  0.0069  0.4681  5.0732 

Random effects:
 Groups   Name          Variance Std.Dev. Corr
 Subject  (Intercept)   958.35   30.957       
          days_deprived  45.78    6.766   0.18
 Residual               651.60   25.526       
Number of obs: 144, groups:  Subject, 18

Fixed effects:
              Estimate Std. Error t value
(Intercept)    267.967      8.266  32.418
days_deprived   11.435      1.845   6.197

Correlation of Fixed Effects:
            (Intr)
days_deprvd -0.062</code></pre>
</div>
</div>
<p>Prima di discutere come interpretare l’output, iniziamo col rappresentare graficamente i dati rispetto alle previsioni del nostro modello. Possiamo ottenere le previsioni del modello utilizzando la funzione <code>predict()</code> (vedi <code>?predict.merMod</code> per informazioni sull’uso con modelli a effetti misti).</p>
<p>Per prima cosa, creaiamo un nuovo dataframe con i valori dei predittori per <code>Subject</code> e <code>days_deprived</code>.</p>
<div id="cell-43" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="22">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sleep2)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>A data.frame: 6 x 4</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">Reaction</th>
<th data-quarto-table-cell-role="th" scope="col">Days</th>
<th data-quarto-table-cell-role="th" scope="col">Subject</th>
<th data-quarto-table-cell-role="th" scope="col">days_deprived</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;fct&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">1</td>
<td>250.8006</td>
<td>2</td>
<td>308</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">2</td>
<td>321.4398</td>
<td>3</td>
<td>308</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">3</td>
<td>356.8519</td>
<td>4</td>
<td>308</td>
<td>2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">4</td>
<td>414.6901</td>
<td>5</td>
<td>308</td>
<td>3</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">5</td>
<td>382.2038</td>
<td>6</td>
<td>308</td>
<td>4</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">6</td>
<td>290.1486</td>
<td>7</td>
<td>308</td>
<td>5</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="cell-44" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="23">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">crossing</span>(</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">Subject =</span> sleep2 <span class="sc">|&gt;</span> </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(Subject) <span class="sc">|&gt;</span> </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">levels</span>() <span class="sc">|&gt;</span> </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">factor</span>(),</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">days_deprived =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">7</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(newdata, <span class="dv">17</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>A tibble: 17 x 2</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" scope="col">Subject</th>
<th data-quarto-table-cell-role="th" scope="col">days_deprived</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th" scope="col">&lt;fct&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;int&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>308</td>
<td>0</td>
</tr>
<tr class="even">
<td>308</td>
<td>1</td>
</tr>
<tr class="odd">
<td>308</td>
<td>2</td>
</tr>
<tr class="even">
<td>308</td>
<td>3</td>
</tr>
<tr class="odd">
<td>308</td>
<td>4</td>
</tr>
<tr class="even">
<td>308</td>
<td>5</td>
</tr>
<tr class="odd">
<td>308</td>
<td>6</td>
</tr>
<tr class="even">
<td>308</td>
<td>7</td>
</tr>
<tr class="odd">
<td>309</td>
<td>0</td>
</tr>
<tr class="even">
<td>309</td>
<td>1</td>
</tr>
<tr class="odd">
<td>309</td>
<td>2</td>
</tr>
<tr class="even">
<td>309</td>
<td>3</td>
</tr>
<tr class="odd">
<td>309</td>
<td>4</td>
</tr>
<tr class="even">
<td>309</td>
<td>5</td>
</tr>
<tr class="odd">
<td>309</td>
<td>6</td>
</tr>
<tr class="even">
<td>309</td>
<td>7</td>
</tr>
<tr class="odd">
<td>310</td>
<td>0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Il codice precedente crea un nuovo data frame chiamato <code>newdata</code> utilizzando la funzione <code>crossing()</code> da <code>dplyr</code>.</p>
<p><code>Subject = sleep2 |&gt; pull(Subject) |&gt; levels() |&gt; factor()</code>: Questa parte del codice estrae la colonna “Subject” dal data frame “sleep2”, quindi applica una serie di operazioni successive utilizzando l’operatore <code>|&gt;</code> (pipe) per manipolare i dati nella colonna. - <code>sleep2 |&gt; pull(Subject)</code>: Inizia estraendo la colonna “Subject” dal data frame “sleep2”. - <code>levels()</code>: Successivamente, applica la funzione “levels()” per ottenere i livelli unici della colonna “Subject”. Questo è utile quando si ha a che fare con variabili categoriche (come un “factor”). - <code>factor()</code>: Infine, trasforma i livelli ottenuti in un “factor”. Questo è importante perché la funzione “crossing()” richiede che le variabili categoriche siano di tipo “factor”.</p>
<ol type="1">
<li><p><code>days_deprived = 0:7</code>: Questa parte del codice crea una nuova variabile chiamata “days_deprived” che contiene una sequenza da 0 a 7. Questo rappresenta i giorni di privazione.</p></li>
<li><p><code>crossing(...)</code>: Infine, la funzione “crossing()” viene utilizzata per creare un nuovo data frame chiamato “newdata” combinando tutte le possibili combinazioni di valori tra la variabile “Subject” (con i suoi livelli unici) e la variabile “days_deprived” (con i valori da 0 a 7).</p></li>
</ol>
<p>Utilizziamo <code>predict()</code> per trovare le rette di regressione per ciascun soggetto.</p>
<div id="cell-47" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="24">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>newdata2 <span class="ot">&lt;-</span> newdata <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Reaction =</span> <span class="fu">predict</span>(pp_mod, newdata))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-48" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="25">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(newdata2)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>A tibble: 6 x 3</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" scope="col">Subject</th>
<th data-quarto-table-cell-role="th" scope="col">days_deprived</th>
<th data-quarto-table-cell-role="th" scope="col">Reaction</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th" scope="col">&lt;fct&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;int&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>308</td>
<td>0</td>
<td>292.4667</td>
</tr>
<tr class="even">
<td>308</td>
<td>1</td>
<td>312.5041</td>
</tr>
<tr class="odd">
<td>308</td>
<td>2</td>
<td>332.5416</td>
</tr>
<tr class="even">
<td>308</td>
<td>3</td>
<td>352.5790</td>
</tr>
<tr class="odd">
<td>308</td>
<td>4</td>
<td>372.6164</td>
</tr>
<tr class="even">
<td>308</td>
<td>5</td>
<td>392.6539</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Ora possiamo creare il grafico con le predizioni del modello.</p>
<div id="cell-50" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="26">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sleep2, <span class="fu">aes</span>(<span class="at">x =</span> days_deprived, <span class="at">y =</span> Reaction)) <span class="sc">+</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> newdata2,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">color =</span> <span class="st">"blue"</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">7</span>) <span class="sc">+</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span>Subject) <span class="sc">+</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Reaction Time"</span>, <span class="at">x =</span> <span class="st">"Days deprived of sleep (0 = baseline)"</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_multilevel_files/figure-html/cell-27-output-1.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretare-loutput-di-lmer-ed-estrarre-le-stime" class="level2" data-number="11.6">
<h2 data-number="11.6" class="anchored" data-anchor-id="interpretare-loutput-di-lmer-ed-estrarre-le-stime"><span class="header-section-number">11.6</span> Interpretare l’output di <code>lmer()</code> ed estrarre le stime</h2>
<p>La chiamata a <code>lmer()</code> restituisce un oggetto della classe “lmerMod”.</p>
<section id="effetti-fissi" class="level3" data-number="11.6.1">
<h3 data-number="11.6.1" class="anchored" data-anchor-id="effetti-fissi"><span class="header-section-number">11.6.1</span> Effetti fissi</h3>
<p>La sezione dell’output chiamata “Effetti fissi:” è simile a ciò che si vede nell’output per un modello lineare semplice adattato con <code>lm()</code>.</p>
<pre><code>Fixed effects:
              Estimate Std. Error t value
(Intercept)    267.967      8.266  32.418
days_deprived   11.435      1.845   6.197</code></pre>
<p>L’output precedente indica che il tempo di reazione medio stimato per i partecipanti al Giorno 0 era di circa 268 millisecondi, con ogni giorno di privazione del sonno che aggiungeva mediamente ulteriori 11 millisecondi al tempo di risposta.</p>
<p>Se dobbiamo ottenere gli effetti fissi dal modello, possiamo estrarli utilizzando la funzione <code>fixef()</code>.</p>
<div id="cell-52" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="27">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fixef</span>(pp_mod) <span class="sc">|&gt;</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) days_deprived 
    267.96742      11.43543 </code></pre>
</div>
</div>
<p>Gli errori standard ci forniscono stime della variabilità di questi parametri dovuta all’errore di campionamento. Possiamo utilizzarli per calcolare i valori <span class="math inline">\(t\)</span> o derivare gli intervalli di confidenza. Per estrarli, utilizziamo <code>vcov(pp_mod)</code>, che restituirà una matrice di varianza-covarianza (non quella associata agli effetti casuali), quindi estraiamo la diagonale utilizzando <code>diag()</code> e calcoliamo infine la radice quadrata utilizzando <code>sqrt()</code>.</p>
<div id="cell-54" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="28">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vcov</span>(pp_mod)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>2 x 2 Matrix of class "dpoMatrix"
              (Intercept) days_deprived
(Intercept)     68.325030     -0.949732
days_deprived   -0.949732      3.405105</code></pre>
</div>
</div>
<div id="cell-55" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="29">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vcov</span>(pp_mod) <span class="sc">|&gt;</span> </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">diag</span>() <span class="sc">|&gt;</span> </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sqrt</span>() <span class="sc">|&gt;</span> </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) days_deprived 
     8.265896      1.845293 </code></pre>
</div>
</div>
<p>Si noti che, nell’output di <code>lmer</code>, i valori <span class="math inline">\(t\)</span> non sono accompagnati dai valori <span class="math inline">\(p\)</span>, come avviene di solito nei contesti di modellazione più semplici. Esistono molteplici approcci per ottenere i valori <span class="math inline">\(p\)</span> da modelli a effetti misti, ciascuno con vantaggi e svantaggi (si veda, ad esempio, Luke (2017) per un’analisi delle opzioni disponibili). I valori <span class="math inline">\(t\)</span> non vengono accompagnati dai gradi di libertà, poiché i gradi di libertà in un modello a effetti misti non sono ben definiti. Spesso i ricercatori trattano i valori <span class="math inline">\(t\)</span> come valori <span class="math inline">\(z\)</span> di Wald, ossia come osservazioni provenienti da una distribuzione normale standard. Poiché la distribuzione <span class="math inline">\(t\)</span> si avvicina alla distribuzione normale standard all’aumentare del numero di osservazioni, questa pratica “t-as-z” è legittima se il numero di osservazioni campionarie è sufficientemente grande.</p>
<p>Per calcolare i valori <span class="math inline">\(z\)</span> di Wald, basta dividere la stima dell’effetto fisso per il suo errore standard:</p>
<div id="cell-57" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="30">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>tvals <span class="ot">&lt;-</span> <span class="fu">fixef</span>(pp_mod) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcov</span>(pp_mod)))</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>tvals <span class="sc">|&gt;</span> </span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) days_deprived 
    32.418437      6.197082 </code></pre>
</div>
</div>
<p>I valori-<span class="math inline">\(p\)</span> si ottengono nel modo seguente:</p>
<div id="cell-59" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="31">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(tvals))))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) days_deprived 
  0.00000e+00   5.75197e-10 </code></pre>
</div>
</div>
<p>Questo fornisce una forte evidenza contro l’ipotesi nulla <span class="math inline">\(H_0: \gamma_1 = 0\)</span>. Sembra che la privazione del sonno aumenti effettivamente il tempo di risposta.</p>
<p>È possibile ottenere gli intervalli di confidenza per le stime utilizzando la funzione <code>confint()</code> (questa tecnica utilizza il bootstrap parametrico).</p>
<div id="cell-61" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="32">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(pp_mod) <span class="sc">|&gt;</span> </span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Computing profile confidence intervals ...
</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                    2.5 %      97.5 %
.sig01         19.0980993  46.3366669
.sig02         -0.4051075   0.8059258
.sig03          4.0079284  10.2487353
.sigma         22.4666029  29.3494508
(Intercept)   251.3443396 284.5904989
days_deprived   7.7245247  15.1463328</code></pre>
</div>
</div>
</section>
<section id="effetti-random" class="level3" data-number="11.6.2">
<h3 data-number="11.6.2" class="anchored" data-anchor-id="effetti-random"><span class="header-section-number">11.6.2</span> Effetti random</h3>
<pre><code>Random effects:
 Groups   Name          Variance Std.Dev. Corr
 Subject  (Intercept)   958.35   30.957       
          days_deprived  45.78    6.766   0.18
 Residual               651.60   25.526       
Number of obs: 144, groups:  Subject, 18</code></pre>
<p>La parte relativa agli effetti casuali dell’output di <code>summary()</code> ci fornisce una tabella con informazioni sulle diverse componenti della varianza: la matrice di varianza-covarianza (o matrici, se ci sono più fattori casuali) e la varianza residua.</p>
<p>Cominciamo con la riga <code>Residual</code>. Questo ci indica che la varianza residua, <span class="math inline">\(\sigma^2\)</span>, è stata stimata a circa 651.6. Il valore nella colonna successiva, 25.526, è la deviazione standard, <span class="math inline">\(\sigma\)</span>, che è la radice quadrata della varianza.</p>
<p>Estraiamo la deviazione standard dei residui utilizzando la funzione <code>sigma()</code>.</p>
<div id="cell-63" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="33">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sigma</span>(pp_mod) <span class="co"># residual</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
25.526404577851
</div>
</div>
<p>Le due righe sopra la riga Residual ci forniscono informazioni sulla matrice di varianza-covarianza per il fattore casuale “Subject”.</p>
<pre><code>Random effects:
 Groups   Name          Variance Std.Dev. Corr
 Subject  (Intercept)   958.35   30.957       
          days_deprived  45.78    6.766   0.18</code></pre>
<p>I valori nella colonna “Variance” ci forniscono la diagonale principale della matrice, mentre i valori nella colonna “Std.Dev.” rappresentano semplicemente le radici quadrate di questi valori. La colonna “Corr” indica la correlazione tra l’intercetta e la pendenza.</p>
<p>Possiamo estrarre questi valori dall’oggetto adattato <code>pp_mod</code> utilizzando la funzione <code>VarCorr()</code>. Questa funzione restituisce una lista nominata, con un elemento per ciascun fattore casuale. Nel nostro caso, “Subject” è l’unico fattore casuale, quindi la lista avrà lunghezza 1.</p>
<div id="cell-65" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="34">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># variance-covariance matrix for random factor Subject</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">VarCorr</span>(pp_mod)[[<span class="st">"Subject"</span>]] <span class="sc">|&gt;</span> </span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>() <span class="co"># oppure: VarCorr(pp_mod)[[1]]</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              (Intercept) days_deprived
(Intercept)      958.3517      37.20460
days_deprived     37.2046      45.77766
attr(,"stddev")
  (Intercept) days_deprived 
    30.957255      6.765919 
attr(,"correlation")
              (Intercept) days_deprived
(Intercept)     1.0000000     0.1776263
days_deprived   0.1776263     1.0000000</code></pre>
</div>
</div>
<p>Le prime righe rappresentano la matrice di varianza-covarianza. Le varianze sono riportate sulla diagonale principale. <code>correlation</code> indica la correlazione tra la stima della pendenza e la stima dell’intercetta.</p>
<p>Possiamo estrarre gli effetti casuali stimati (BLUPS) utilizzando la funzione <code>ranef()</code>.</p>
<div id="cell-67" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="35">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ranef</span>(pp_mod)[[<span class="st">"Subject"</span>]] <span class="sc">|&gt;</span> </span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    (Intercept) days_deprived
308  24.4992891     8.6020000
309 -59.3723102    -8.1277534
310 -39.4762764    -7.4292365
330   1.3500428    -2.3845976
331  18.4576169    -3.7477340
332  30.5270040    -4.8936899
333  13.3682027     0.2888639
334 -18.1583020     3.8436686
335 -16.9737887   -12.0702333
337  44.5850842    10.1760837
349 -26.6839022     2.1946699
350  -5.9657957     8.1758613
351  -5.5710355    -2.3718494
352  46.6347253    -0.5616377
369   0.9616395     1.7385130
370 -18.5216778     5.6317534
371  -7.3431320     0.2729282
372  17.6826159     0.6623897</code></pre>
</div>
</div>
<p>Possiamo ottenere i valori stimati dal modello utilizzando <code>fitted()</code> e i residui utilizzando <code>residuals()</code>.</p>
<div id="cell-69" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="36">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(sleep2,</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">fit =</span> <span class="fu">fitted</span>(pp_mod),</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">resid =</span> <span class="fu">residuals</span>(pp_mod)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(Subject) <span class="sc">%&gt;%</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">slice</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">10</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(<span class="at">n =</span> <span class="sc">+</span><span class="cn">Inf</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 x 6
# Groups:   Subject [18]
   Reaction  Days Subject days_deprived   fit  resid
      &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt;           &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
 1     251.     2 308                 0  292. -41.7 
 2     203.     2 309                 0  209.  -5.62
 3     234.     2 310                 0  228.   5.83
 4     284.     2 330                 0  269.  14.5 
 5     302.     2 331                 0  286.  15.4 
 6     273.     2 332                 0  298. -25.5 
 7     277.     2 333                 0  281.  -4.57
 8     243.     2 334                 0  250.  -6.44
 9     254.     2 335                 0  251.   3.50
10     292.     2 337                 0  313. -20.9 
11     239.     2 349                 0  241.  -2.36
12     256.     2 350                 0  262.  -5.80
13     270.     2 351                 0  262.   7.50
14     327.     2 352                 0  315.  12.3 
15     257.     2 369                 0  269. -11.7 
16     239.     2 370                 0  249. -10.5 
17     278.     2 371                 0  261.  17.3 
18     298.     2 372                 0  286.  11.9 </code></pre>
</div>
</div>
<p>Infine, possiamo ottenere previsioni per nuovi dati utilizzando <code>predict()</code>, come abbiamo fatto in precedenza.</p>
<div id="cell-71" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="37">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="do">## create the table with new predictor values</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>ndat <span class="ot">&lt;-</span> <span class="fu">crossing</span>(</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Subject =</span> sleep2 <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Subject) <span class="sc">%&gt;%</span> <span class="fu">levels</span>() <span class="sc">%&gt;%</span> <span class="fu">factor</span>(),</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">days_deprived =</span> <span class="dv">8</span><span class="sc">:</span><span class="dv">10</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Reaction =</span> <span class="fu">predict</span>(pp_mod, <span class="at">newdata =</span> .))</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>ndat <span class="sc">|&gt;</span> </span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>A tibble: 6 x 3</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" scope="col">Subject</th>
<th data-quarto-table-cell-role="th" scope="col">days_deprived</th>
<th data-quarto-table-cell-role="th" scope="col">Reaction</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th" scope="col">&lt;fct&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;int&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>308</td>
<td>8</td>
<td>452.7661</td>
</tr>
<tr class="even">
<td>308</td>
<td>9</td>
<td>472.8036</td>
</tr>
<tr class="odd">
<td>308</td>
<td>10</td>
<td>492.8410</td>
</tr>
<tr class="even">
<td>309</td>
<td>8</td>
<td>235.0565</td>
</tr>
<tr class="odd">
<td>309</td>
<td>9</td>
<td>238.3642</td>
</tr>
<tr class="even">
<td>309</td>
<td>10</td>
<td>241.6719</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="cell-72" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="38">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sleep2, <span class="fu">aes</span>(<span class="at">x =</span> days_deprived, <span class="at">y =</span> Reaction)) <span class="sc">+</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> <span class="fu">bind_rows</span>(newdata2, ndat),</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">color =</span> <span class="st">"blue"</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span>Subject) <span class="sc">+</span></span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Reaction Time"</span>, <span class="at">x =</span> <span class="st">"Days deprived of sleep (0 = baseline)"</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_multilevel_files/figure-html/cell-39-output-1.png" width="480" height="296" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="considerazioni-conclusive" class="level2" data-number="11.7">
<h2 data-number="11.7" class="anchored" data-anchor-id="considerazioni-conclusive"><span class="header-section-number">11.7</span> Considerazioni Conclusive</h2>
<p>Il presente capitolo presenta un’analisi approfondita dei modelli statistici multilivello discutendo l’esempio relativo all’effetto della deprivazione del sonno sulle prestazioni psicomotorie. Utilizzando il dataset <code>sleepstudy</code>, abbiamo introdotto concetti chiave quali “complete pooling”, “no pooling” e “partial pooling”. Questi approcci sono stati esplorati per evidenziare le loro implicazioni nella modellazione dei dati che contengono misure ripetute.</p>
<p>L’analisi si focalizza sull’applicazione pratica dei modelli multilivello, dettagliando le variabili fisse e casuali e la loro importanza nel contesto dei modelli. È stata posta particolare enfasi sulla matrice di varianza-covarianza, essenziale per comprendere le relazioni all’interno dei modelli multilivello.</p>
<p>I modelli multilivello sono di vitale importanza per l’assessment psicologico e la psicometria, in quanto permettono di analizzare dati complessi tenendo conto delle variazioni individuali e di gruppo. Questi modelli forniscono strumenti flessibili per esaminare l’influenza di fattori contestuali e individuali sul comportamento e le prestazioni psicologiche, un aspetto cruciale nell’assessment psicologico.</p>
<p>Il capitolo anticipa l’utilizzo dei modelli multilivello nel calcolo dell’affidabilità tra giudici, un tema che sarà approfondito nel capitolo successivo. Inoltre, i modelli multilivello sono presentati come un’introduzione o un’alternativa ai modelli di crescita latente, che verranno esplorati nei capitoli successivi. Questo collegamento sottolinea la continuità e l’importanza di tali modelli nell’ambito più ampio della ricerca psicologica e psicometrica.</p>
</section>
<section id="session-info" class="level2" data-number="11.8">
<h2 data-number="11.8" class="anchored" data-anchor-id="session-info"><span class="header-section-number">11.8</span> Session Info</h2>
<div id="cell-75" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="39">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>R version 4.4.1 (2024-06-14)
Platform: aarch64-apple-darwin20
Running under: macOS 15.0

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] C

time zone: Europe/Rome
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] kableExtra_1.4.0  repr_1.1.7        lme4_1.1-35.5     Matrix_1.7-0     
 [5] car_3.1-2         carData_3.0-5     ggokabeito_0.1.0  viridis_0.6.5    
 [9] viridisLite_0.4.2 ggpubr_0.6.0      ggExtra_0.10.1    bayesplot_1.11.1 
[13] gridExtra_2.3     patchwork_1.3.0   semTools_0.5-6    semPlot_1.1.6    
[17] lavaan_0.6-18     psych_2.4.6.26    scales_1.3.0      markdown_1.13    
[21] knitr_1.48        lubridate_1.9.3   forcats_1.0.0     stringr_1.5.1    
[25] dplyr_1.1.4       purrr_1.0.2       readr_2.1.5       tidyr_1.3.1      
[29] tibble_3.2.1      ggplot2_3.5.1     tidyverse_2.0.0   here_1.0.1       

loaded via a namespace (and not attached):
  [1] rstudioapi_0.16.0  jsonlite_1.8.9     magrittr_2.0.3    
  [4] TH.data_1.1-2      estimability_1.5.1 farver_2.1.2      
  [7] nloptr_2.1.1       rmarkdown_2.28     vctrs_0.6.5       
 [10] minqa_1.2.8        base64enc_0.1-3    rstatix_0.7.2     
 [13] htmltools_0.5.8.1  broom_1.0.6        Formula_1.2-5     
 [16] htmlwidgets_1.6.4  plyr_1.8.9         sandwich_3.1-1    
 [19] emmeans_1.10.4     zoo_1.8-12         uuid_1.2-1        
 [22] igraph_2.0.3       mime_0.12          lifecycle_1.0.4   
 [25] pkgconfig_2.0.3    R6_2.5.1           fastmap_1.2.0     
 [28] shiny_1.9.1        digest_0.6.37      OpenMx_2.21.12    
 [31] fdrtool_1.2.18     colorspace_2.1-1   rprojroot_2.0.4   
 [34] Hmisc_5.1-3        labeling_0.4.3     fansi_1.0.6       
 [37] timechange_0.3.0   abind_1.4-8        compiler_4.4.1    
 [40] withr_3.0.1        glasso_1.11        htmlTable_2.4.3   
 [43] backports_1.5.0    ggsignif_0.6.4     MASS_7.3-61       
 [46] corpcor_1.6.10     gtools_3.9.5       tools_4.4.1       
 [49] pbivnorm_0.6.0     foreign_0.8-87     zip_2.3.1         
 [52] httpuv_1.6.15      nnet_7.3-19        glue_1.7.0        
 [55] quadprog_1.5-8     promises_1.3.0     nlme_3.1-166      
 [58] lisrelToR_0.3      grid_4.4.1         pbdZMQ_0.3-13     
 [61] checkmate_2.3.2    cluster_2.1.6      reshape2_1.4.4    
 [64] generics_0.1.3     gtable_0.3.5       tzdb_0.4.0        
 [67] data.table_1.16.0  hms_1.1.3          xml2_1.3.6        
 [70] utf8_1.2.4         sem_3.1-16         pillar_1.9.0      
 [73] IRdisplay_1.1      rockchalk_1.8.157  later_1.3.2       
 [76] splines_4.4.1      lattice_0.22-6     survival_3.7-0    
 [79] kutils_1.73        tidyselect_1.2.1   miniUI_0.1.1.1    
 [82] pbapply_1.7-2      svglite_2.1.3      stats4_4.4.1      
 [85] xfun_0.47          qgraph_1.9.8       arm_1.14-4        
 [88] stringi_1.8.4      pacman_0.5.1       boot_1.3-31       
 [91] evaluate_1.0.0     codetools_0.2-20   mi_1.1            
 [94] cli_3.6.3          RcppParallel_5.1.9 IRkernel_1.3.2    
 [97] rpart_4.1.23       systemfonts_1.1.0  xtable_1.8-4      
[100] munsell_0.5.1      Rcpp_1.0.13        coda_0.19-4.1     
[103] png_0.1-8          XML_3.99-0.17      parallel_4.4.1    
[106] jpeg_0.1-10        mvtnorm_1.3-1      openxlsx_4.2.7.1  
[109] crayon_1.5.3       rlang_1.1.4        multcomp_1.4-26   
[112] mnormt_2.1.1      </code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiato!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiato!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ccaudek\.github\.io\/testing_psicologico\/intro\.html");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/ctt/06_ctt_applications.html" class="pagination-link" aria-label="Applicazioni della CTT">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Applicazioni della CTT</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/raters/02_interrater_reliability.html" class="pagination-link" aria-label="L'affidabilità tra giudici">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">L’affidabilità tra giudici</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Testing Psicologico è stato scritto da Corrado Caudek.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.dev/ccaudek/testing_psicologico/blob/main/chapters/raters/01_multilevel.ipynb" class="toc-action"><i class="bi bi-github"></i>Modifica questa pagina</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Questo libro è stato realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>