<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Corrado Caudek">
<title>23&nbsp; Riparazione affettiva post-infedeltà – Testing Psicologico</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/networks/01_networks.html" rel="next">
<link href="../../chapters/path_analysis/01_path_analysis.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9ac0fa60fcd2ae55f2ddd9f231fc218f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-d0edb45afdd5f5fd9663be5d5709df0d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/path_analysis/01_path_analysis.html">Analisi dei percorsi</a></li><li class="breadcrumb-item"><a href="../../chapters/path_analysis/02_clement_2022.html"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Riparazione affettiva post-infedeltà</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Testing Psicologico</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ccaudek/testing_psicologico/" title="Eseguire il codice" class="quarto-navigation-tool px-1" aria-label="Eseguire il codice"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Ricerca"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Informazioni Generali</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../prefazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefazione</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Calendario</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../cal_testing_psic_2025.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calendario Didattico e Programma del Corso</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Punteggi e scale</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/01_scores_scales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Punteggi e scale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E1_likert.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">✏ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E2_optimal_scoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E3_thurstone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">✏ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/02_development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sviluppo dello strumento</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/03_equating.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Equating nei Test Psicologici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E4_norming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">CTT</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/01_ctt_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Fondamenti teorici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/02_ctt_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">L’affidabilità del test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/03_ctt_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Metodi di stima dell’affidabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/04_err_std_mis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">L’errore standard della misurazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/05_err_std_stima.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">La stima del punteggio vero</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/06_ctt_applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Applicazioni della CTT</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Giudici</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/01_multilevel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Modelli multilivello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/02_interrater_reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">L’affidabilità tra giudici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/E1_irr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Validità</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/validity/01_validity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">La Validità del test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/validity/02_other_variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Relazioni test-criterio</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Generalizzabilità</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/gtheory/01_gtheory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Teoria della generalizzabilità</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Items</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/items/01_item_development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Lo sviluppo degli item</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/items/02_item_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Analisi degli item</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Analisi dei percorsi</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/path_analysis/01_path_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Analisi dei percorsi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/path_analysis/02_clement_2022.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Riparazione affettiva post-infedeltà</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Networks</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/networks/01_networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Network psicologici</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">PCA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/pca/01_linear_algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Elementi di algebra lineare</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/pca/02_pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Analisi delle componenti principali</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">FA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/01_intro_fa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Introduzione all’analisi fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/02_analisi_fattoriale_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Il modello unifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/03_analisi_fattoriale_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Il modello statistico dell’analisi fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/04_analisi_fattoriale_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Il modello multifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/05_factor_scores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">I punteggi fattoriali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/06_constraints_on_parms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Attendibilità e modello fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/07_total_score.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Punteggio totale e modello fattoriale</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false">
 <span class="menu-text">Costruzione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/01_val_matrici.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Valutazione della matrice di correlazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/02_estrazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">L’estrazione dei fattori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/03_numero_fattori.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Il numero dei fattori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/04_rotazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">La rotazione fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/05_val_soluzione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Valutare e rifinire la soluzione fattoriale</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">CFA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/01_cfa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Analisti Fattoriale Confermativa</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/02_meanstructure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">La struttura delle medie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/03_cat_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Dati non gaussiani e categoriali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/04_mmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">CFA per matrici multi-tratto multi-metodo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/05_bifactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Modello bifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/06_efa_lavaan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Exploratory Structural Equation Modeling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/07_fa_in_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Strategia Integrata per un’Analisi Fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/E_02_bifactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false">
 <span class="menu-text">SEM</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/01_sem_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Introduzione ai Modelli SEM</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/02_data_preparation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Preparazione dei Dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/03_gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Test del Modello e Indicizzazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/04_mod_comp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Confronto tra modelli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/05_cfa_mod_comp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">CFA: confronto tra modelli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/06_refine_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">La revisione del modello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/07_group_invariance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Invarianza di misura</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/08_multilevel_sem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Modelli di Equazioni Strutturali Multilivello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/09_structural_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Modelli di Regressione Strutturale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/10_missing_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Dati mancanti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/11_small_samples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Modellizzazione SEM in Piccoli Campioni</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/13_esem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Exploratory structural equation modelling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/14_sem_power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Dimensione Campionaria e Analisi della Potenza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/15_prior_pred_mod_check.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Prior Predictive Model Checking</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false">
 <span class="menu-text">Mokken</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/01_logistic_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Modello di Regressione Logistica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/02_core_issues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Analisi della Scala di Mokken</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/03_applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Applicazione Pratica</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false">
 <span class="menu-text">IRT</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/01_rasch_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">Modello di Rasch</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/02_assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">68</span>&nbsp; <span class="chapter-title">Assunzioni e Proprietà del Modello di Rasch</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/03_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title">Stima</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/04_1pl_2pl_3pl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Modelli 1PL, 2PL e 3PL</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/05_implementation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Implementazione</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false">
 <span class="menu-text">LGM</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/01_lgm_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">72</span>&nbsp; <span class="chapter-title">Curve di crescita latente</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/02_lgm_prelims.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">73</span>&nbsp; <span class="chapter-title">Considerazioni Preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/06_lgm_mixed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">74</span>&nbsp; <span class="chapter-title">LGM e modelli misti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/03_time_effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">75</span>&nbsp; <span class="chapter-title">Dati longitudinali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/05_intro_panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">76</span>&nbsp; <span class="chapter-title">Specificare e Interpretare un Modello Longitudinale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/07_growth_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">77</span>&nbsp; <span class="chapter-title">Curve di crescita latente</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/08_growth_cont.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">78</span>&nbsp; <span class="chapter-title">Il tempo su una metrica continua</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/09_time_inv_cov.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">79</span>&nbsp; <span class="chapter-title">Covariate indipendenti dal tempo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/10_growth_groups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">80</span>&nbsp; <span class="chapter-title">Modelli di crescita latenti a gruppi multipli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/11_lgm_wais.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">81</span>&nbsp; <span class="chapter-title">Lo Sviluppo dell’Intelligenza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/12_temp_reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">82</span>&nbsp; <span class="chapter-title">Affidabilità longitudinale</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false">
 <span class="menu-text">Predizione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/prediction/01_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">83</span>&nbsp; <span class="chapter-title">Predizione</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../99-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliografia</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendici</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a1_intro_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linguaggio R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a2_sums.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Simbolo di somma</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a3_calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Per liberarvi dai terrori preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false">
 <span class="menu-text">Soluzioni degli esercizi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/solutions_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Probabilità</span></span></a>
  </div>
</li>
      </ul>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Indice</h2>
   
  <ul>
<li><a href="#introduzione" id="toc-introduzione" class="nav-link active" data-scroll-target="#introduzione"><span class="header-section-number">23.1</span> Introduzione</a></li>
  <li><a href="#modello-di-mediazione-semplice" id="toc-modello-di-mediazione-semplice" class="nav-link" data-scroll-target="#modello-di-mediazione-semplice"><span class="header-section-number">23.2</span> Modello di Mediazione Semplice</a></li>
  <li><a href="#modello-di-moderazione" id="toc-modello-di-moderazione" class="nav-link" data-scroll-target="#modello-di-moderazione"><span class="header-section-number">23.3</span> Modello di Moderazione</a></li>
  <li><a href="#modello-di-mediazione-moderata" id="toc-modello-di-mediazione-moderata" class="nav-link" data-scroll-target="#modello-di-mediazione-moderata"><span class="header-section-number">23.4</span> Modello di Mediazione Moderata</a></li>
  <li>
<a href="#esempio-di-mediazione-moderata" id="toc-esempio-di-mediazione-moderata" class="nav-link" data-scroll-target="#esempio-di-mediazione-moderata"><span class="header-section-number">23.5</span> Esempio di Mediazione Moderata</a>
  <ul>
<li><a href="#indipendenza" id="toc-indipendenza" class="nav-link" data-scroll-target="#indipendenza"><span class="header-section-number">23.5.1</span> Indipendenza</a></li>
  <li><a href="#linearit%C3%A0" id="toc-linearità" class="nav-link" data-scroll-target="#linearit%C3%A0"><span class="header-section-number">23.5.2</span> Linearità</a></li>
  <li>
<a href="#omoschedasticit%C3%A0" id="toc-omoschedasticità" class="nav-link" data-scroll-target="#omoschedasticit%C3%A0"><span class="header-section-number">23.5.3</span> Omoschedasticità</a>
  <ul>
<li><a href="#verifica-visiva-dellomoschedasticit%C3%A0" id="toc-verifica-visiva-dellomoschedasticità" class="nav-link" data-scroll-target="#verifica-visiva-dellomoschedasticit%C3%A0"><span class="header-section-number">23.5.3.1</span> Verifica visiva dell’omoschedasticità</a></li>
  <li><a href="#test-statistico-per-lomoschedasticit%C3%A0" id="toc-test-statistico-per-lomoschedasticità" class="nav-link" data-scroll-target="#test-statistico-per-lomoschedasticit%C3%A0"><span class="header-section-number">23.5.3.2</span> Test statistico per l’omoschedasticità</a></li>
  <li><a href="#cosa-fare-in-caso-di-eteroschedasticit%C3%A0" id="toc-cosa-fare-in-caso-di-eteroschedasticità" class="nav-link" data-scroll-target="#cosa-fare-in-caso-di-eteroschedasticit%C3%A0"><span class="header-section-number">23.5.3.3</span> Cosa fare in caso di eteroschedasticità?</a></li>
  </ul>
</li>
  <li>
<a href="#multicollinearit%C3%A0" id="toc-multicollinearità" class="nav-link" data-scroll-target="#multicollinearit%C3%A0"><span class="header-section-number">23.5.4</span> Multicollinearità</a>
  <ul>
<li><a href="#come-verificare-la-multicollinearit%C3%A0" id="toc-come-verificare-la-multicollinearità" class="nav-link" data-scroll-target="#come-verificare-la-multicollinearit%C3%A0"><span class="header-section-number">23.5.4.1</span> Come verificare la multicollinearità</a></li>
  <li><a href="#calcolo-del-vif-in-r" id="toc-calcolo-del-vif-in-r" class="nav-link" data-scroll-target="#calcolo-del-vif-in-r"><span class="header-section-number">23.5.4.2</span> Calcolo del VIF in R</a></li>
  <li><a href="#interpretazione-dei-risultati" id="toc-interpretazione-dei-risultati" class="nav-link" data-scroll-target="#interpretazione-dei-risultati"><span class="header-section-number">23.5.4.3</span> Interpretazione dei risultati</a></li>
  <li><a href="#come-affrontare-la-multicollinearit%C3%A0" id="toc-come-affrontare-la-multicollinearità" class="nav-link" data-scroll-target="#come-affrontare-la-multicollinearit%C3%A0"><span class="header-section-number">23.5.4.4</span> Come affrontare la multicollinearità</a></li>
  </ul>
</li>
  <li>
<a href="#normalit%C3%A0" id="toc-normalità" class="nav-link" data-scroll-target="#normalit%C3%A0"><span class="header-section-number">23.5.5</span> Normalità</a>
  <ul>
<li>
<a href="#verifica-della-normalit%C3%A0" id="toc-verifica-della-normalità" class="nav-link" data-scroll-target="#verifica-della-normalit%C3%A0"><span class="header-section-number">23.5.5.1</span> Verifica della normalità</a>
  <ul class="collapse">
<li><a href="#verifiche-grafiche" id="toc-verifiche-grafiche" class="nav-link" data-scroll-target="#verifiche-grafiche"><span class="header-section-number">23.5.5.1.1</span> Verifiche grafiche</a></li>
  <li><a href="#verifica-con-listogramma" id="toc-verifica-con-listogramma" class="nav-link" data-scroll-target="#verifica-con-listogramma"><span class="header-section-number">23.5.5.1.2</span> Verifica con l’istogramma</a></li>
  <li><a href="#verifica-con-il-grafico-p-p" id="toc-verifica-con-il-grafico-p-p" class="nav-link" data-scroll-target="#verifica-con-il-grafico-p-p"><span class="header-section-number">23.5.5.1.3</span> Verifica con il grafico P-P</a></li>
  </ul>
</li>
  <li><a href="#test-statistici-per-la-normalit%C3%A0" id="toc-test-statistici-per-la-normalità" class="nav-link" data-scroll-target="#test-statistici-per-la-normalit%C3%A0"><span class="header-section-number">23.5.5.2</span> Test statistici per la normalità</a></li>
  </ul>
</li>
  </ul>
</li>
  <li>
<a href="#analisi-di-moderazione" id="toc-analisi-di-moderazione" class="nav-link" data-scroll-target="#analisi-di-moderazione"><span class="header-section-number">23.6</span> Analisi di Moderazione</a>
  <ul>
<li><a href="#modello-di-regressione-con-interazione" id="toc-modello-di-regressione-con-interazione" class="nav-link" data-scroll-target="#modello-di-regressione-con-interazione"><span class="header-section-number">23.6.1</span> Modello di Regressione con Interazione</a></li>
  <li>
<a href="#risultati-principali" id="toc-risultati-principali" class="nav-link" data-scroll-target="#risultati-principali"><span class="header-section-number">23.6.2</span> Risultati Principali</a>
  <ul>
<li><a href="#interpretazione-dellinterazione" id="toc-interpretazione-dellinterazione" class="nav-link" data-scroll-target="#interpretazione-dellinterazione"><span class="header-section-number">23.6.2.1</span> Interpretazione dell’Interazione</a></li>
  </ul>
</li>
  <li><a href="#visualizzazione-delle-pendenze-semplici" id="toc-visualizzazione-delle-pendenze-semplici" class="nav-link" data-scroll-target="#visualizzazione-delle-pendenze-semplici"><span class="header-section-number">23.6.3</span> Visualizzazione delle Pendenze Semplici</a></li>
  </ul>
</li>
  <li>
<a href="#analisi-della-mediazione" id="toc-analisi-della-mediazione" class="nav-link" data-scroll-target="#analisi-della-mediazione"><span class="header-section-number">23.7</span> Analisi della Mediazione</a>
  <ul>
<li><a href="#specifica-del-modello-in-lavaan" id="toc-specifica-del-modello-in-lavaan" class="nav-link" data-scroll-target="#specifica-del-modello-in-lavaan"><span class="header-section-number">23.7.1</span> Specifica del Modello in lavaan</a></li>
  <li><a href="#risultati-principali-1" id="toc-risultati-principali-1" class="nav-link" data-scroll-target="#risultati-principali-1"><span class="header-section-number">23.7.2</span> Risultati Principali</a></li>
  <li><a href="#varianza-spiegata-r%C2%B2" id="toc-varianza-spiegata-r²" class="nav-link" data-scroll-target="#varianza-spiegata-r%C2%B2"><span class="header-section-number">23.7.3</span> Varianza Spiegata (R²)</a></li>
  </ul>
</li>
  <li>
<a href="#mediazione-moderata" id="toc-mediazione-moderata" class="nav-link" data-scroll-target="#mediazione-moderata"><span class="header-section-number">23.8</span> Mediazione Moderata</a>
  <ul>
<li><a href="#specifica-del-modello-in-lavaan-1" id="toc-specifica-del-modello-in-lavaan-1" class="nav-link" data-scroll-target="#specifica-del-modello-in-lavaan-1"><span class="header-section-number">23.8.1</span> Specifica del Modello in lavaan</a></li>
  <li><a href="#risultati-principali-2" id="toc-risultati-principali-2" class="nav-link" data-scroll-target="#risultati-principali-2"><span class="header-section-number">23.8.2</span> Risultati Principali</a></li>
  <li><a href="#conclusioni-mediazione-moderata" id="toc-conclusioni-mediazione-moderata" class="nav-link" data-scroll-target="#conclusioni-mediazione-moderata"><span class="header-section-number">23.8.3</span> Conclusioni (Mediazione Moderata)</a></li>
  </ul>
</li>
  <li><a href="#sintesi-complessiva" id="toc-sintesi-complessiva" class="nav-link" data-scroll-target="#sintesi-complessiva"><span class="header-section-number">23.9</span> Sintesi Complessiva</a></li>
  <li><a href="#riflessioni-finali" id="toc-riflessioni-finali" class="nav-link" data-scroll-target="#riflessioni-finali"><span class="header-section-number">23.10</span> Riflessioni Finali</a></li>
  <li><a href="#session-info" id="toc-session-info" class="nav-link" data-scroll-target="#session-info"><span class="header-section-number">23.11</span> Session Info</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/path_analysis/01_path_analysis.html">Analisi dei percorsi</a></li><li class="breadcrumb-item"><a href="../../chapters/path_analysis/02_clement_2022.html"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Riparazione affettiva post-infedeltà</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-path-analysis-clement" class="quarto-section-identifier"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Riparazione affettiva post-infedeltà</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
In questo capitolo imparerai a
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>distinguere tra moderazione, mediazione e mediazione moderata.</li>
</ul>
</div>
</div>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prerequisiti
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Leggere <em>A step-by-step tutorial for performing a moderated mediation analysis using PROCESS</em> di <span class="citation" data-cites="clement2022step">Clement &amp; Bradley-Garcia (<a href="#ref-clement2022step" role="doc-biblioref">2022</a>)</span>
</li>
</ul>
</div>
</div>
<div class="callout callout-style-simple callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Preparazione del Notebook
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"code"</span>, <span class="st">"_common.R"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Load packages</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/ns-load.html">requireNamespace</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span></span>
<span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">lavaanExtra</span>, <span class="va">lavaanPlot</span>, <span class="va">semTools</span>, <span class="va">haven</span>, <span class="va">mediation</span>, <span class="va">semPlot</span>, </span>
<span>    <span class="va">performance</span>, <span class="va">car</span>, <span class="va">lmtest</span>, <span class="va">interactions</span>, <span class="va">sjPlot</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<section id="introduzione" class="level2" data-number="23.1"><h2 data-number="23.1" class="anchored" data-anchor-id="introduzione">
<span class="header-section-number">23.1</span> Introduzione</h2>
<p>Questo capitolo ha l’obiettivo di illustrare il tutorial proposto da <span class="citation" data-cites="clement2022step">Clement &amp; Bradley-Garcia (<a href="#ref-clement2022step" role="doc-biblioref">2022</a>)</span>, in cui l’analisi dei percorsi (path analysis) viene applicata a tre tipologie di analisi statistica: il modello di moderazione, il modello di mediazione semplice e il modello di mediazione moderata.</p>
</section><section id="modello-di-mediazione-semplice" class="level2" data-number="23.2"><h2 data-number="23.2" class="anchored" data-anchor-id="modello-di-mediazione-semplice">
<span class="header-section-number">23.2</span> Modello di Mediazione Semplice</h2>
<p>Il modello di mediazione analizza in che modo una variabile indipendente (IV o X) influisca su una variabile dipendente (DV o Y) attraverso una variabile intermediaria, definita variabile mediatrice (M). In questo schema, l’effetto della variabile indipendente sulla variabile dipendente si scompone in due componenti:</p>
<ol type="1">
<li>
<strong>Effetto diretto (c′)</strong>: l’influenza dell’IV sulla DV al netto del contributo di M.<br>
</li>
<li>
<strong>Effetto indiretto (a × b)</strong>: il percorso che passa attraverso M.</li>
</ol>
<p>Per esempio, nel contesto delle relazioni di coppia, si può ipotizzare che la fiducia nel partner trasgressore (IV) promuova il perdono (DV) grazie all’incremento di una variabile mediatrice come la comprensione o l’empatia (M) <span class="citation" data-cites="clement2022step hargrave2016restoration">(<a href="#ref-clement2022step" role="doc-biblioref">Clement &amp; Bradley-Garcia, 2022</a>; <a href="#ref-hargrave2016restoration" role="doc-biblioref">Hargrave &amp; Hammer, 2016</a>)</span>. L’analisi di tale dinamica mediante un modello di mediazione semplice permette di comprendere meglio quali elementi possano essere potenziati attraverso interventi mirati, come il rafforzamento della fiducia o il potenziamento dell’empatia, per favorire il perdono.</p>
<p>La struttura di un modello di mediazione semplice può essere così riassunta:</p>
<ol type="1">
<li>
<strong>IV → M</strong>: l’IV influenza direttamente la variabile mediatrice.<br>
</li>
<li>
<strong>M → DV</strong>: la variabile mediatrice influenza la DV.<br>
</li>
<li>
<strong>IV → DV (effetto diretto)</strong>: anche tenendo conto di M, l’IV esercita un’influenza residua sulla DV.</li>
</ol>
<p>L’obiettivo principale è stimare l’effetto indiretto, ovvero il contributo di M nella relazione fra IV e DV. Questo modello consente di individuare percorsi specifici di influenza e di stabilire se e in che misura una variabile intermediaria contribuisca a spiegare il legame fra IV e DV.</p>
<div id="fig-clement-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-clement-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../figures/clement_2022.png" class="img-fluid figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-clement-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;23.1: Pannello A: Mediazione semplice; Pannello B: Moderazione; Pannello C: Modelli di Mediazione Moderata. Nel Pannello A, le linee tratteggiate indicano il percorso indiretto (ab), mentre la linea continua indica il percorso diretto (c′) <span class="citation" data-cites="clement2022step">(Figura tratta da <a href="#ref-clement2022step" role="doc-biblioref">Clement &amp; Bradley-Garcia, 2022</a>)</span>.
</figcaption></figure>
</div>
<p>La letteratura evidenzia che la fiducia in un partner romantico è collegata alla compassione verso di esso (Salazar, 2015), e che la compassione, a sua volta, è uno dei principali predittori di perdono (Davis, 2017). Sulla base di questi risultati, si può ipotizzare che la fiducia favorisca il perdono attraverso la compassione provata per il partner romantico.</p>
<p>Per verificare questa ipotesi, si può strutturare un modello di mediazione in cui:<br>
- la fiducia nel partner romantico influisce sulla compassione (percorso “a”);<br>
- la compassione, a sua volta, influenza il perdono (percorso “b”).</p>
<p>In questo scenario, l’effetto indiretto (a × b) rappresenta il modo in cui la fiducia promuove il perdono grazie alla maggiore compassione. Se l’analisi statistica conferma la significatività dell’effetto indiretto, si può concludere che la compassione media l’associazione tra fiducia e perdono. Viceversa, se tale effetto non risulta significativo, non si possono trarre conclusioni circa un ruolo di mediazione della compassione.</p>
<p>Oltre all’effetto indiretto, il modello di mediazione consente di esaminare l’effetto diretto della fiducia sul perdono, controllando per la compassione. In altre parole, si valuta se la fiducia mantenga un’influenza significativa sul perdono anche quando la compassione è tenuta costante. L’effetto totale (c) del modello di mediazione è pertanto la somma dell’effetto diretto (c′) e dell’effetto indiretto (a × b), cioè (c = c’ + (a b)).</p>
<p>Secondo la letteratura (Meule, 2019), si parla di <strong>mediazione completa</strong> quando l’effetto indiretto risulta significativo mentre l’effetto diretto non lo è; si parla invece di <strong>mediazione parziale</strong> quando entrambi gli effetti (diretto e indiretto) risultano significativi.</p>
<p>In conclusione, un modello di mediazione semplice può gettare luce su come la compassione sia correlata alla fiducia nel partner romantico e al perdono. Tuttavia, per comprendere le circostanze in cui la fiducia e la compassione risultino più o meno associate, è necessario considerare anche un modello di moderazione.</p>
</section><section id="modello-di-moderazione" class="level2" data-number="23.3"><h2 data-number="23.3" class="anchored" data-anchor-id="modello-di-moderazione">
<span class="header-section-number">23.3</span> Modello di Moderazione</h2>
<p>In un modello di moderazione, l’obiettivo è stabilire se una terza variabile, detta <strong>variabile moderatrice</strong> (W), modifichi la forza o la direzione della relazione tra la variabile indipendente (IV) e la variabile dipendente (DV). Come evidenzia Hayes (2018, p.&nbsp;220):</p>
<blockquote class="blockquote">
<p>“Identificare un moderatore di un effetto aiuta a stabilire le condizioni limite di quell’effetto o le circostanze, gli stimoli o il tipo di persone per cui l’effetto è maggiore o minore, presente o assente, positivo o negativo, e così via.”</p>
</blockquote>
<p>Da un punto di vista statistico, verificare un modello di moderazione equivale a testare l’interazione tra le variabili, analogamente a quanto accade nell’analisi della varianza (ANOVA; Frazier, Tix, &amp; Barron, 2004). Si parla di <strong>effetto di interazione</strong> quando l’effetto dell’IV sulla DV cambia in funzione dei livelli di W (Hayes, 2018). In altri termini, il ricercatore si chiede se l’associazione tra IV e DV risulti più o meno intensa (o addirittura opposta nel segno) a seconda del valore assunto dal moderatore.</p>
<p>Come mostrato nel Pannello B della <a href="#fig-clement-1" class="quarto-xref">Figura&nbsp;<span class="quarto-unresolved-ref">fig-clement-1</span></a>, un modello di moderazione mette in luce le condizioni specifiche in cui una determinata relazione può risultare più o meno forte. Tornando all’esempio incentrato su fiducia, compassione e perdono, potremmo domandarci in quali situazioni la fiducia favorisca maggiormente la compassione. Nella letteratura sui comportamenti prosociali, l’umiltà è stata individuata come fattore essenziale per promuovere la compassione (Worthington &amp; Allison, 2018). Alcuni studi indicano che vedere il proprio partner romantico come umile è associato anche alla percezione di maggiore compassione (McDonald, Olson, Goddard, &amp; Marshall, 2018), e che la fiducia è positivamente correlata a livelli più elevati di umiltà (Wang, Edwards, &amp; Hill, 2017). Di conseguenza, è plausibile ipotizzare che l’effetto della fiducia sulla compassione vari a seconda di quanto il partner venga percepito come umile, configurando così un tipico esempio di moderazione.</p>
</section><section id="modello-di-mediazione-moderata" class="level2" data-number="23.4"><h2 data-number="23.4" class="anchored" data-anchor-id="modello-di-mediazione-moderata">
<span class="header-section-number">23.4</span> Modello di Mediazione Moderata</h2>
<p>Il concetto di <em>mediazione moderata</em>, introdotto da James e Brett (1984), descrive come una variabile moderatrice (W) possa influenzare l’ampiezza o la presenza di un <strong>effetto indiretto</strong> (Preacher, Rucker, &amp; Hayes, 2007). In altre parole, si parla di mediazione moderata quando l’intensità dell’effetto di mediazione varia in funzione dei livelli del moderatore (Preacher et al., 2007).</p>
<p>Come illustrato nel Pannello C della <a href="#fig-clement-1" class="quarto-xref">Figura&nbsp;<span class="quarto-unresolved-ref">fig-clement-1</span></a>, in un modello di mediazione moderata la relazione tra una variabile indipendente (X) e una variabile dipendente (Y), mediata da un’altra variabile (M), dipende dal valore assunto da W. Nel nostro esempio che include fiducia, umiltà, compassione e perdono, si potrebbe supporre che la fiducia nel partner romantico (X) agisca sul perdono (Y) attraverso la compassione (M), ma che la forza di tale mediazione sia potenziata o attenuata in base alla percezione del partner come umile (W). In pratica, se il partner è considerato molto umile, l’effetto indiretto di X su Y (mediato da M) potrebbe essere particolarmente marcato; al contrario, a livelli bassi di umiltà, il processo di mediazione potrebbe indebolirsi o persino scomparire.</p>
<p>L’analisi di mediazione moderata fornisce dunque un quadro più completo del fenomeno oggetto di studio, poiché chiarisce <strong>come</strong> (attraverso M) e <strong>in quali condizioni</strong> (valori di W) un effetto di X su Y si manifesti, offrendo indicazioni utili per interventi e ipotesi di ricerca più mirate.</p>
</section><section id="esempio-di-mediazione-moderata" class="level2" data-number="23.5"><h2 data-number="23.5" class="anchored" data-anchor-id="esempio-di-mediazione-moderata">
<span class="header-section-number">23.5</span> Esempio di Mediazione Moderata</h2>
<p>Nel tutorial di <span class="citation" data-cites="clement2022step">Clement &amp; Bradley-Garcia (<a href="#ref-clement2022step" role="doc-biblioref">2022</a>)</span> sono presentati i dati di uno studio che analizza l’associazione fra fiducia di coppia, compassione verso il partner responsabile di un’offesa, percezione di tale partner come umile e perdono in persone che avevano sperimentato una <strong>ferita da attaccamento</strong>. Secondo Johnson, Makinen e Millikin (2001), le ferite da attaccamento corrispondono a una violazione percepita della fiducia o a un abbandono verificatosi in un momento critico, durante il quale la persona ferita aveva bisogno del sostegno e della cura del partner.</p>
<p>All’interno dello studio, la <strong>fiducia di coppia</strong> è stata definita come il grado di onestà e di buona volontà che la persona ferita attribuisce al partner offensore (Larzelere &amp; Huston, 1980). Un elemento cruciale per superare le ferite da attaccamento e ristabilire la fiducia nella relazione è il perdono, concettualizzato come l’insieme di <strong>elevate motivazioni benevolenti</strong> (ad es. buona volontà) e <strong>basse motivazioni di evitamento o vendetta</strong> nei confronti del partner trasgressore.</p>
<p>Il campione era composto da 138 partecipanti che avevano vissuto una ferita da attaccamento nella loro attuale relazione romantica e che avevano scelto di perdonare il partner. I partecipanti hanno compilato questionari self-report online, descrivendo brevemente la ferita subita e indicando se avevano effettivamente perdonato (sì/no).</p>
<ul>
<li>
<strong>Fiducia di coppia</strong>: misurata con la <strong>Dyadic Trust Scale</strong> (DTS; Larzelere &amp; Huston, 1980), composta da 8 item valutati su una scala da 1 (“fortemente d’accordo”) a 7 (“fortemente in disaccordo”).<br>
</li>
<li>
<strong>Compassione verso il partner</strong>: misurata con una versione modificata della <strong>Compassion Scale</strong> (CS; Pommier, Neff, &amp; Tóth-Király, 2020), adattata per rilevare la compassione verso il partner offensore. La scala comprende 16 item, valutati da 1 (“quasi mai”) a 5 (“quasi sempre”).<br>
</li>
<li>
<strong>Percezione del partner come umile</strong>: misurata con la <strong>Relational Humility Scale</strong> (RHS; Davis et al., 2011), modificata per riflettere il sentimento del partecipante verso il partner che ha commesso l’offesa. Gli item sono valutati su una scala da 1 (“fortemente in disaccordo”) a 5 (“fortemente d’accordo”).<br>
</li>
<li>
<strong>Perdono del partner offensore</strong>: misurato tramite il <strong>Transgressions-related Interpersonal Motivations Inventory</strong> (TRIM; McCullough et al., 1998; McCullough, Fincham, &amp; Tsang, 2003). Il TRIM valuta:
<ol type="1">
<li>Motivazione ad evitare il partner.<br>
</li>
<li>Motivazione a cercare vendetta.<br>
</li>
<li>Motivazione a mostrare benevolenza verso il partner.</li>
</ol>
In questo caso, il perdono è stato definito come bassi livelli di motivazione all’evitamento o alla vendetta e alti livelli di benevolenza. Nel tutorial, è stata impiegata solo la sottoscala della <strong>benevolenza</strong> del TRIM-18.</li>
</ul>
<p>Di seguito un estratto del codice (in R) per il caricamento dei dati, l’esplorazione delle variabili e l’individuazione di eventuali outlier.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Caricamento dei dati da un file SPSS</span></span>
<span><span class="va">data</span> <span class="op">&lt;-</span> <span class="fu">read_sav</span><span class="op">(</span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"data"</span>, <span class="st">"clement_2022.sav"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Esplorazione della struttura del dataset</span></span>
<span><span class="fu">glimpse</span><span class="op">(</span><span class="va">data</span><span class="op">)</span></span>
<span><span class="co">#&gt; Rows: 138</span></span>
<span><span class="co">#&gt; Columns: 4</span></span>
<span><span class="co">#&gt; $ CS_TOT   &lt;dbl&gt; 58, 68, 66, 70, 70, 44, 66, 76, 67, 43, 66, 68, 68, 69, 7…</span></span>
<span><span class="co">#&gt; $ RHSTOT   &lt;dbl&gt; 59, 53, 52, 35, 55, 36, 53, 54, 49, 45, 27, 52, 34, 29, 4…</span></span>
<span><span class="co">#&gt; $ TRIM_Ben &lt;dbl&gt; 19, 22, 26, 24, 25, 12, 21, 29, 30, 6, 25, 17, 29, 22, 9,…</span></span>
<span><span class="co">#&gt; $ DTST     &lt;dbl&gt; 54, 51, 48, 34, 48, 32, 52, 52, 49, 47, 36, 34, 47, 56, 5…</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Statistiche descrittive</span></span>
<span><span class="fu">describe</span><span class="op">(</span><span class="va">data</span><span class="op">)</span></span>
<span><span class="co">#&gt;          vars   n  mean    sd median trimmed   mad min max range  skew</span></span>
<span><span class="co">#&gt; CS_TOT      1 138 64.19  8.53   66.0   65.04  8.15  35  76    41 -0.88</span></span>
<span><span class="co">#&gt; RHSTOT      2 138 42.92 10.19   44.5   43.34 11.12  17  60    43 -0.33</span></span>
<span><span class="co">#&gt; TRIM_Ben    3 138 21.86  5.68   22.0   22.35  5.93   6  30    24 -0.74</span></span>
<span><span class="co">#&gt; DTST        4 138 38.59 10.25   39.0   38.96 11.86  11  56    45 -0.26</span></span>
<span><span class="co">#&gt;          kurtosis   se</span></span>
<span><span class="co">#&gt; CS_TOT       0.50 0.73</span></span>
<span><span class="co">#&gt; RHSTOT      -0.57 0.87</span></span>
<span><span class="co">#&gt; TRIM_Ben     0.12 0.48</span></span>
<span><span class="co">#&gt; DTST        -0.64 0.87</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Identificazione degli outlier per ciascuna variabile</span></span>
<span><span class="va">outliers_results</span> <span class="op">&lt;-</span> <span class="fu">check_outliers</span><span class="op">(</span><span class="va">data</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Visualizzazione dei risultati sugli outlier</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">outliers_results</span><span class="op">)</span></span>
<span><span class="co">#&gt; OK: No outliers detected.</span></span>
<span><span class="co">#&gt; - Based on the following method and threshold: mahalanobis (20).</span></span>
<span><span class="co">#&gt; - For variables: CS_TOT, RHSTOT, TRIM_Ben, DTST</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># 1. Trasformiamo il dataset da wide a long</span></span>
<span><span class="va">data_long</span> <span class="op">&lt;-</span> <span class="va">data</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">pivot_longer</span><span class="op">(</span></span>
<span>    cols <span class="op">=</span> <span class="fu">everything</span><span class="op">(</span><span class="op">)</span>,       <span class="co"># Converte tutte le colonne</span></span>
<span>    names_to <span class="op">=</span> <span class="st">"Variabile"</span>,    <span class="co"># Nome della nuova colonna con i nomi delle variabili</span></span>
<span>    values_to <span class="op">=</span> <span class="st">"Valore"</span>       <span class="co"># Nome della nuova colonna con i valori</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="co"># 2. Creiamo il boxplot con ggplot2</span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">data_long</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">Variabile</span>, y <span class="op">=</span> <span class="va">Valore</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_boxplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Boxplot delle variabili"</span>, x <span class="op">=</span> <span class="cn">NULL</span>, y <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme</span><span class="op">(</span></span>
<span>    axis.text.x <span class="op">=</span> <span class="fu">element_text</span><span class="op">(</span>angle <span class="op">=</span> <span class="fl">90</span>, vjust <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span>  <span class="co"># Rotazione etichette asse X</span></span>
<span>  <span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="02_clement_2022_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>Questo esempio illustra come i dati possano essere preparati e ispezionati preliminarmente prima di condurre un’analisi di mediazione moderata. I passaggi successivi includono la costruzione di un modello di regressione lineare con interazioni (per testare la moderazione) e l’impiego di procedure specifiche (ad es. PROCESS di Hayes) per esaminare contemporaneamente la mediazione e la moderazione.</p>
<section id="indipendenza" class="level3" data-number="23.5.1"><h3 data-number="23.5.1" class="anchored" data-anchor-id="indipendenza">
<span class="header-section-number">23.5.1</span> Indipendenza</h3>
<p>Nella regressione lineare, l’assunzione di indipendenza richiede che i residui del modello siano indipendenti l’uno dall’altro. In altre parole, l’errore commesso nel predire il valore di un partecipante non deve influenzare l’errore commesso nel predire il valore di un altro partecipante. Nel nostro caso, ciò significa che l’errore nella stima del punteggio di benevolenza di una persona non dovrebbe influenzare l’errore nella stima del punteggio di un’altra.</p>
<p>Per verificare l’indipendenza dei residui, si utilizza la statistica di Durbin-Watson, che rileva la presenza di autocorrelazione nei termini di errore (Uyanto, 2020). Questa statistica varia da 0 a 4, e valori compresi tra <strong>1.5 e 2.5</strong> indicano che l’assunzione di indipendenza è plausibilmente soddisfatta (Glen, 2022).</p>
<p>In R, la funzione <code>durbinWatsonTest()</code> del pacchetto <strong>car</strong> permette di calcolare la statistica di Durbin-Watson. Dopo aver definito un modello di regressione (nell’esempio riportato, con <code>TRIM_Ben</code> come variabile dipendente e <code>DTST</code>, <code>CS_TOT</code>, <code>RHSTOT</code> come predittori)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Creazione del modello di regressione</span></span>
<span><span class="va">model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">TRIM_Ben</span> <span class="op">~</span> <span class="va">DTST</span> <span class="op">+</span> <span class="va">CS_TOT</span> <span class="op">+</span> <span class="va">RHSTOT</span>, data <span class="op">=</span> <span class="va">data</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>si esegue il test di Durbin-Watson nel seguente modo:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dw_test</span> <span class="op">&lt;-</span> <span class="fu">durbinWatsonTest</span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span>
<span><span class="va">dw_test</span></span>
<span><span class="co">#&gt;  lag Autocorrelation D-W Statistic p-value</span></span>
<span><span class="co">#&gt;    1        -0.03195         2.035   0.846</span></span>
<span><span class="co">#&gt;  Alternative hypothesis: rho != 0</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Se il valore della statistica rientra tra <strong>1.5 e 2.5</strong>, possiamo concludere che l’assunzione di indipendenza dei residui è rispettata. Una volta verificata questa condizione, è possibile procedere con il controllo della successiva assunzione di linearità.</p>
</section><section id="linearità" class="level3" data-number="23.5.2"><h3 data-number="23.5.2" class="anchored" data-anchor-id="linearità">
<span class="header-section-number">23.5.2</span> Linearità</h3>
<p>Un’ipotesi fondamentale nella regressione lineare è che esista una relazione lineare tra le variabili indipendenti (IV) e la variabile dipendente (DV). Questo significa che un cambiamento nelle IV comporta un cambiamento proporzionale nella DV. La verifica di questa assunzione è cruciale per garantire che il modello di regressione catturi correttamente la relazione tra le variabili.</p>
<p>Per valutare la linearità, si possono utilizzare grafici di dispersione che mettono in relazione le IV con la DV oppure grafici parziali per esaminare la relazione lineare tra ogni IV e la DV. Nel suo tutorial, <span class="citation" data-cites="clement2022step">Clement &amp; Bradley-Garcia (<a href="#ref-clement2022step" role="doc-biblioref">2022</a>)</span> verifica l’assunzione di linearità tracciando un grafico tra i residui studentizzati (SRE_1) e i valori previsti non standardizzati (PRE_1).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calcolare i residui studentizzati e i valori previsti</span></span>
<span><span class="va">SRE_1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/influence.measures.html">rstudent</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span>  <span class="co"># Residui studentizzati</span></span>
<span><span class="va">PRE_1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span>   <span class="co"># Valori previsti non standardizzati</span></span>
<span></span>
<span><span class="co"># Creare un data frame per ggplot</span></span>
<span><span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>PRE_1 <span class="op">=</span> <span class="va">PRE_1</span>, SRE_1 <span class="op">=</span> <span class="va">SRE_1</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Creare il grafico con ggplot2</span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">df</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">PRE_1</span>, y <span class="op">=</span> <span class="va">SRE_1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span>color <span class="op">=</span> <span class="st">"blue"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, color <span class="op">=</span> <span class="st">"red"</span>, linewidth <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Verifica della linearità: residui vs valori previsti"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Valori previsti (PRE_1)"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Residui studentizzati (SRE_1)"</span></span>
<span>  <span class="op">)</span> </span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="02_clement_2022_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretazione:</strong></p>
<ul>
<li>se i punti nel grafico sono distribuiti casualmente attorno alla linea orizzontale a residuo zero (linea rossa), l’assunzione di linearità è soddisfatta;</li>
<li>la presenza di pattern evidenti (come curve o trend sistematici) indica una possibile violazione della linearità, suggerendo che il modello di regressione potrebbe non essere adeguato.</li>
</ul></section><section id="omoschedasticità" class="level3" data-number="23.5.3"><h3 data-number="23.5.3" class="anchored" data-anchor-id="omoschedasticità">
<span class="header-section-number">23.5.3</span> Omoschedasticità</h3>
<p>L’assunzione di <strong>omoschedasticità</strong> richiede che la variabilità degli errori (residui) rimanga costante per tutti i valori delle variabili indipendenti (IV). In altre parole, l’errore nella relazione tra le IV e la variabile dipendente (DV) non dovrebbe aumentare o diminuire sistematicamente in funzione dei valori previsti della DV. Quando questa assunzione viene violata, si parla di <strong>eteroschedasticità</strong>, che si verifica quando la variabilità degli errori cambia al variare dei valori previsti (Osborne &amp; Waters, 2002).</p>
<section id="verifica-visiva-dellomoschedasticità" class="level4" data-number="23.5.3.1"><h4 data-number="23.5.3.1" class="anchored" data-anchor-id="verifica-visiva-dellomoschedasticità">
<span class="header-section-number">23.5.3.1</span> Verifica visiva dell’omoschedasticità</h4>
<p>Per valutare l’omoschedasticità, possiamo utilizzare un grafico di dispersione che rappresenta i residui rispetto ai valori previsti:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calcolo dei residui e dei valori previsti</span></span>
<span><span class="va">residuals</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">resid</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span>
<span><span class="va">predicted_values</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Creazione del data frame per ggplot</span></span>
<span><span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  predicted_values <span class="op">=</span> <span class="va">predicted_values</span>,</span>
<span>  residuals <span class="op">=</span> <span class="va">residuals</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Grafico con ggplot2</span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">df</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">predicted_values</span>, y <span class="op">=</span> <span class="va">residuals</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span>color <span class="op">=</span> <span class="st">"blue"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, color <span class="op">=</span> <span class="st">"red"</span>, linewidth <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Verifica dell'omoschedasticità: Residui vs Valori previsti"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Valori previsti"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Residui"</span></span>
<span>  <span class="op">)</span> </span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="02_clement_2022_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Se i punti nel grafico sono distribuiti casualmente attorno alla linea orizzontale (residui pari a 0) e formano una distribuzione rettangolare uniforme, l’assunzione di omoschedasticità è rispettata.</li>
<li>Se i punti mostrano una dispersione non uniforme (ad esempio, un cono che si allarga o si restringe, o una forma curva), è probabile che ci sia eteroschedasticità e che l’assunzione sia violata.</li>
</ul></section><section id="test-statistico-per-lomoschedasticità" class="level4" data-number="23.5.3.2"><h4 data-number="23.5.3.2" class="anchored" data-anchor-id="test-statistico-per-lomoschedasticità">
<span class="header-section-number">23.5.3.2</span> Test statistico per l’omoschedasticità</h4>
<p>Oltre al controllo visivo, è possibile eseguire un test formale, come il test di <strong>Breusch-Pagan</strong>, disponibile nel pacchetto <code>lmtest</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Esecuzione del test di Breusch-Pagan</span></span>
<span><span class="fu">bptest</span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  studentized Breusch-Pagan test</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; data:  model</span></span>
<span><span class="co">#&gt; BP = 3.4, df = 3, p-value = 0.3</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>
<p><strong>Interpretazione del p-value</strong>:</p>
<ul>
<li>Se il <strong>p-value</strong> è elevato (di solito &gt; 0.05), non ci sono evidenze di eteroschedasticità e l’assunzione di omoschedasticità è plausibilmente soddisfatta.</li>
<li>Se il <strong>p-value</strong> è basso (di solito &lt; 0.05), si rileva eteroschedasticità, indicando una violazione dell’assunzione.</li>
</ul>
</li>
</ul></section><section id="cosa-fare-in-caso-di-eteroschedasticità" class="level4" data-number="23.5.3.3"><h4 data-number="23.5.3.3" class="anchored" data-anchor-id="cosa-fare-in-caso-di-eteroschedasticità">
<span class="header-section-number">23.5.3.3</span> Cosa fare in caso di eteroschedasticità?</h4>
<p>Se l’assunzione di omoschedasticità è violata, ci sono diversi approcci per affrontare il problema:</p>
<ol type="1">
<li>
<strong>Trasformazione delle variabili</strong>: Applicare trasformazioni logaritmiche o di potenza alle variabili può ridurre l’eteroschedasticità.</li>
<li>
<strong>Stime robuste</strong>: Utilizzare errori standard robusti per ridurre l’impatto dell’eteroschedasticità sui risultati del modello.</li>
<li>
<strong>Modelli alternativi</strong>: Considerare modelli che tengano conto dell’eteroschedasticità, come la regressione ponderata.</li>
</ol>
<p>Questo tipo di analisi aiuta a garantire che le inferenze statistiche basate sul modello di regressione siano valide e affidabili.</p>
</section></section><section id="multicollinearità" class="level3" data-number="23.5.4"><h3 data-number="23.5.4" class="anchored" data-anchor-id="multicollinearità">
<span class="header-section-number">23.5.4</span> Multicollinearità</h3>
<p>La <strong>multicollinearità</strong> si verifica quando due o più variabili indipendenti (IV) sono fortemente correlate tra loro, rendendo difficile isolare gli effetti unici di ciascuna variabile sulla variabile dipendente (DV). Questo problema si manifesta quando i punteggi di una o più IV sono altamente prevedibili in base alle altre IV incluse nel modello (Kim, 2019). La presenza di multicollinearità può compromettere l’interpretazione dei coefficienti di regressione e ridurre l’affidabilità dei risultati.</p>
<section id="come-verificare-la-multicollinearità" class="level4" data-number="23.5.4.1"><h4 data-number="23.5.4.1" class="anchored" data-anchor-id="come-verificare-la-multicollinearità">
<span class="header-section-number">23.5.4.1</span> Come verificare la multicollinearità</h4>
<p>Per valutare la multicollinearità, possiamo utilizzare due metriche principali:</p>
<ol type="1">
<li>
<strong>Fattore di inflazione della varianza</strong> (VIF): Misura quanto la varianza stimata di un coefficiente di regressione è aumentata a causa della multicollinearità.</li>
<li>
<strong>Statistica di tolleranza</strong>: Rappresenta il reciproco del VIF ed esprime la proporzione della varianza di una variabile indipendente che non è spiegata dalle altre IV.</li>
</ol>
<p><strong>Criteri di riferimento:</strong></p>
<ul>
<li>La <strong>tolleranza</strong> dovrebbe essere superiore a <strong>0.1</strong> (valori più bassi indicano multicollinearità).</li>
<li>Il <strong>VIF</strong> dovrebbe essere inferiore a <strong>10</strong> (Miles, 2005).</li>
</ul></section><section id="calcolo-del-vif-in-r" class="level4" data-number="23.5.4.2"><h4 data-number="23.5.4.2" class="anchored" data-anchor-id="calcolo-del-vif-in-r">
<span class="header-section-number">23.5.4.2</span> Calcolo del VIF in R</h4>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calcolo del VIF per le variabili indipendenti</span></span>
<span><span class="va">vif_values</span> <span class="op">&lt;-</span> <span class="fu">vif</span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Visualizzazione dei valori VIF</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">vif_values</span><span class="op">)</span></span>
<span><span class="co">#&gt;   DTST CS_TOT RHSTOT </span></span>
<span><span class="co">#&gt;  1.557  1.090  1.585</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="interpretazione-dei-risultati" class="level4" data-number="23.5.4.3"><h4 data-number="23.5.4.3" class="anchored" data-anchor-id="interpretazione-dei-risultati">
<span class="header-section-number">23.5.4.3</span> Interpretazione dei risultati</h4>
<ul>
<li>
<strong>Valori di VIF inferiori a 10</strong>: Non ci sono problemi significativi di multicollinearità.</li>
<li>
<strong>Valori di VIF superiori a 10</strong>: È presente multicollinearità nel modello, e potrebbe essere necessario intervenire.</li>
</ul></section><section id="come-affrontare-la-multicollinearità" class="level4" data-number="23.5.4.4"><h4 data-number="23.5.4.4" class="anchored" data-anchor-id="come-affrontare-la-multicollinearità">
<span class="header-section-number">23.5.4.4</span> Come affrontare la multicollinearità</h4>
<p>Se si riscontra multicollinearità, è possibile considerare le seguenti strategie:</p>
<ol type="1">
<li>
<strong>Rimuovere variabili ridondanti</strong>: Identificare le IV che contribuiscono meno al modello o sono fortemente correlate tra loro, ed eliminarle.</li>
<li>
<strong>Combinare variabili correlate</strong>: Creare indici compositi o utilizzare tecniche di riduzione della dimensionalità come l’analisi delle componenti principali (PCA).</li>
<li>
<strong>Standardizzare le variabili</strong>: In alcuni casi, la standardizzazione può ridurre gli effetti della multicollinearità.</li>
<li>
<strong>Utilizzare modelli robusti</strong>: Considerare approcci come la regressione ridge o la regressione con penalizzazione (es. LASSO) che possono gestire la multicollinearità.</li>
</ol>
<p>Affrontare la multicollinearità è essenziale per garantire un’interpretazione affidabile dei coefficienti di regressione e la validità complessiva del modello.</p>
</section></section><section id="normalità" class="level3" data-number="23.5.5"><h3 data-number="23.5.5" class="anchored" data-anchor-id="normalità">
<span class="header-section-number">23.5.5</span> Normalità</h3>
<p>L’assunzione di <strong>normalità</strong> richiede che i residui, ossia gli errori nella stima del modello di regressione, siano distribuiti normalmente (Hayes, 2018). Questa assunzione è importante principalmente per garantire la validità dei test statistici utilizzati per valutare i coefficienti di regressione, poiché si basa sull’ipotesi di normalità degli errori.</p>
<section id="verifica-della-normalità" class="level4" data-number="23.5.5.1"><h4 data-number="23.5.5.1" class="anchored" data-anchor-id="verifica-della-normalità">
<span class="header-section-number">23.5.5.1</span> Verifica della normalità</h4>
<p>Per verificare questa assunzione, possiamo utilizzare strumenti grafici per un’ispezione visiva e, se necessario, test statistici.</p>
<section id="verifiche-grafiche" class="level5" data-number="23.5.5.1.1"><h5 data-number="23.5.5.1.1" class="anchored" data-anchor-id="verifiche-grafiche">
<span class="header-section-number">23.5.5.1.1</span> Verifiche grafiche</h5>
<ol type="1">
<li>
<strong>Istogramma dei residui</strong>: Visualizzare la distribuzione dei residui sovrapponendo una curva di densità normale per verificare se i residui seguono una forma a campana.</li>
<li>
<strong>Grafico P-P (Probability-Probability Plot)</strong>: Confrontare la distribuzione cumulativa dei residui con una distribuzione normale teorica. Se i punti si allineano lungo la diagonale, la normalità è rispettata.</li>
</ol>
<p>Anche se ci sono piccole deviazioni dalla normalità, la regressione è robusta a violazioni non gravi di questa assunzione, quindi l’analisi può essere comunque considerata valida.</p>
</section><section id="verifica-con-listogramma" class="level5" data-number="23.5.5.1.2"><h5 data-number="23.5.5.1.2" class="anchored" data-anchor-id="verifica-con-listogramma">
<span class="header-section-number">23.5.5.1.2</span> Verifica con l’istogramma</h5>
<p>Il seguente codice crea un istogramma dei residui con una curva di densità normale sovrapposta:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calcolo dei residui</span></span>
<span><span class="va">residuals</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">resid</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Creazione del data frame per ggplot</span></span>
<span><span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>residuals <span class="op">=</span> <span class="va">residuals</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Istogramma con curva di densità sovrapposta</span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">df</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">residuals</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="fu">after_stat</span><span class="op">(</span><span class="va">density</span><span class="op">)</span><span class="op">)</span>, </span>
<span>                 binwidth <span class="op">=</span> <span class="cn">NULL</span>,  </span>
<span>                 fill <span class="op">=</span> <span class="st">"lightblue"</span>, color <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_density</span><span class="op">(</span>color <span class="op">=</span> <span class="st">"red"</span>, linewidth <span class="op">=</span> <span class="fl">1.2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Istogramma dei residui"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Residui"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Densità"</span></span>
<span>  <span class="op">)</span> </span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="02_clement_2022_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretazione</strong>: Se la curva di densità (linea rossa) segue la forma dell’istogramma, possiamo concludere che i residui sono distribuiti normalmente.</p>
</section><section id="verifica-con-il-grafico-p-p" class="level5" data-number="23.5.5.1.3"><h5 data-number="23.5.5.1.3" class="anchored" data-anchor-id="verifica-con-il-grafico-p-p">
<span class="header-section-number">23.5.5.1.3</span> Verifica con il grafico P-P</h5>
<p>Il grafico P-P è un ulteriore strumento per verificare la normalità:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calcolo dei residui</span></span>
<span><span class="va">residuals</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">resid</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Creazione del Q-Q plot</span></span>
<span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>residuals <span class="op">=</span> <span class="va">residuals</span><span class="op">)</span>, <span class="fu">aes</span><span class="op">(</span>sample <span class="op">=</span> <span class="va">residuals</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_qq</span><span class="op">(</span>color <span class="op">=</span> <span class="st">"blue"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_qq_line</span><span class="op">(</span>color <span class="op">=</span> <span class="st">"red"</span>, linewidth <span class="op">=</span> <span class="fl">1.2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Q-Q plot dei residui"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Quantili teorici"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Quantili campionari"</span></span>
<span>  <span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="02_clement_2022_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretazione</strong>: Se i punti nel grafico si distribuiscono lungo la linea diagonale (linea rossa), i residui sono distribuiti normalmente. Deviazioni sistematiche dalla linea diagonale indicano violazioni della normalità.</p>
</section></section><section id="test-statistici-per-la-normalità" class="level4" data-number="23.5.5.2"><h4 data-number="23.5.5.2" class="anchored" data-anchor-id="test-statistici-per-la-normalità">
<span class="header-section-number">23.5.5.2</span> Test statistici per la normalità</h4>
<p>Se necessario, è possibile utilizzare test statistici come il <strong>test di Shapiro-Wilk</strong> o il <strong>test di Kolmogorov-Smirnov</strong> per valutare formalmente la normalità dei residui:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Test di Shapiro-Wilk</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test</a></span><span class="op">(</span><span class="va">residuals</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Shapiro-Wilk normality test</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; data:  residuals</span></span>
<span><span class="co">#&gt; W = 0.93, p-value = 5e-06</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Interpretazione del p-value</strong>:</p>
<ul>
<li>
<strong>p &gt; 0.05</strong>: Non ci sono evidenze di una deviazione significativa dalla normalità.</li>
<li>
<strong>p ≤ 0.05</strong>: I residui non seguono una distribuzione normale.</li>
</ul>
<p>In conclusione, se i residui mostrano piccole deviazioni dalla normalità, ciò potrebbe non compromettere significativamente l’analisi, poiché la regressione lineare è relativamente robusta a violazioni lievi di questa assunzione. Tuttavia, in caso di deviazioni gravi, si potrebbe considerare:</p>
<ul>
<li>
<strong>Trasformazioni delle variabili</strong> (ad esempio, logaritmica o radice quadrata).</li>
<li>
<strong>Modelli alternativi</strong> come modelli di regressione robusti o non parametrici.</li>
</ul>
<p>La verifica della normalità è una parte essenziale del controllo delle assunzioni, ma va interpretata nel contesto generale della robustezza del modello.</p>
</section></section></section><section id="analisi-di-moderazione" class="level2" data-number="23.6"><h2 data-number="23.6" class="anchored" data-anchor-id="analisi-di-moderazione">
<span class="header-section-number">23.6</span> Analisi di Moderazione</h2>
<p><strong>Obiettivo</strong><br>
Verificare se l’effetto di <em>DTST</em> (fiducia di coppia) su <em>CS_TOT</em> (compassione verso il partner che ha ferito) cambia in funzione di <em>RHSTOT</em> (umiltà percepita del partner). In altre parole, vogliamo vedere se <em>RHSTOT</em> modera la relazione tra <em>DTST</em> e <em>CS_TOT</em>.</p>
<section id="modello-di-regressione-con-interazione" class="level3" data-number="23.6.1"><h3 data-number="23.6.1" class="anchored" data-anchor-id="modello-di-regressione-con-interazione">
<span class="header-section-number">23.6.1</span> Modello di Regressione con Interazione</h3>
<p>Per analizzare l’interazione, stimiamo un modello di regressione lineare in cui la variabile dipendente è <em>CS_TOT</em>, e come predittori utilizziamo <em>DTST</em>, <em>RHSTOT</em> e il termine di interazione <em>DTST * RHSTOT</em>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">CS_TOT</span> <span class="op">~</span> <span class="va">DTST</span> <span class="op">*</span> <span class="va">RHSTOT</span>, data <span class="op">=</span> <span class="va">data</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; lm(formula = CS_TOT ~ DTST * RHSTOT, data = data)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residuals:</span></span>
<span><span class="co">#&gt;     Min      1Q  Median      3Q     Max </span></span>
<span><span class="co">#&gt; -25.859  -4.131   0.851   5.954  15.033 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt;             Estimate Std. Error t value Pr(&gt;|t|)</span></span>
<span><span class="co">#&gt; (Intercept) 74.85822    9.90301    7.56  5.7e-12</span></span>
<span><span class="co">#&gt; DTST        -0.51699    0.27916   -1.85    0.066</span></span>
<span><span class="co">#&gt; RHSTOT      -0.35486    0.24140   -1.47    0.144</span></span>
<span><span class="co">#&gt; DTST:RHSTOT  0.01427    0.00618    2.31    0.022</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residual standard error: 8.1 on 134 degrees of freedom</span></span>
<span><span class="co">#&gt; Multiple R-squared:  0.117,  Adjusted R-squared:  0.0976 </span></span>
<span><span class="co">#&gt; F-statistic: 5.94 on 3 and 134 DF,  p-value: 0.000781</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="risultati-principali" class="level3" data-number="23.6.2"><h3 data-number="23.6.2" class="anchored" data-anchor-id="risultati-principali">
<span class="header-section-number">23.6.2</span> Risultati Principali</h3>
<p>Dall’output di regressione (coefficiente, errore standard, valore p) possiamo estrapolare i seguenti punti:</p>
<ol type="1">
<li>
<strong>Intercetta</strong>:
<ul>
<li>Valore stimato = 74.86 (SE = 9.90), p &lt; 0.001<br>
</li>
<li>L’intercetta indica il livello atteso di compassione (<em>CS_TOT</em>) quando sia <em>DTST</em> che <em>RHSTOT</em> sono pari a zero (o al loro valore di riferimento se centrati).</li>
</ul>
</li>
<li>
<strong>Effetto principale di DTST</strong> (fiducia di coppia):
<ul>
<li>Coefficiente = -0.517, p = 0.0662<br>
</li>
<li>Sebbene tenda a un valore negativo, non è significativo al 5%. Significa che, preso da solo, <em>DTST</em> non predice con sufficiente forza il livello di compassione (almeno ai livelli di significatività più comuni).</li>
</ul>
</li>
<li>
<strong>Effetto principale di RHSTOT</strong> (umiltà percepita):
<ul>
<li>Coefficiente = -0.355, p = 0.1439<br>
</li>
<li>Anch’esso non significativo. Significa che, in media, <em>RHSTOT</em> da sola non predice la compassione a un livello di p &lt; 0.05.</li>
</ul>
</li>
<li>
<strong>Interazione (DTST * RHSTOT)</strong>
<ul>
<li>Coefficiente = 0.0143, p = 0.0224<br>
</li>
<li>L’interazione risulta invece significativa. Questo indica che l’effetto di <em>DTST</em> sulla compassione (<em>CS_TOT</em>) dipende dai livelli di umiltà percepita (<em>RHSTOT</em>).</li>
</ul>
</li>
</ol>
<section id="interpretazione-dellinterazione" class="level4" data-number="23.6.2.1"><h4 data-number="23.6.2.1" class="anchored" data-anchor-id="interpretazione-dellinterazione">
<span class="header-section-number">23.6.2.1</span> Interpretazione dell’Interazione</h4>
<p>La significatività dell’interazione suggerisce che:</p>
<ul>
<li>Se l’umiltà percepita (<em>RHSTOT</em>) è <strong>alta</strong>, l’effetto di <em>DTST</em> (fiducia) sulla compassione (<em>CS_TOT</em>) aumenta.<br>
</li>
<li>Se l’umiltà percepita è <strong>bassa</strong>, l’effetto di <em>DTST</em> sulla compassione diminuisce o si annulla.</li>
</ul></section></section><section id="visualizzazione-delle-pendenze-semplici" class="level3" data-number="23.6.3"><h3 data-number="23.6.3" class="anchored" data-anchor-id="visualizzazione-delle-pendenze-semplici">
<span class="header-section-number">23.6.3</span> Visualizzazione delle Pendenze Semplici</h3>
<p>Per comprendere meglio l’interazione, è utile tracciare l’effetto di <em>DTST</em> su <em>CS_TOT</em> a diversi livelli di <em>RHSTOT</em> (in genere: valore medio, ±1 deviazione standard):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calcolo della media e della deviazione standard di RHSTOT</span></span>
<span><span class="va">mean_RHSTOT</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">data</span><span class="op">$</span><span class="va">RHSTOT</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">sd_RHSTOT</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">data</span><span class="op">$</span><span class="va">RHSTOT</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Visualizzazione (ad es. usando 'interact_plot' di un pacchetto come 'interactions')</span></span>
<span><span class="fu">interact_plot</span><span class="op">(</span></span>
<span>  <span class="va">model</span>,</span>
<span>  pred <span class="op">=</span> <span class="va">DTST</span>, </span>
<span>  modx <span class="op">=</span> <span class="va">RHSTOT</span>,</span>
<span>  modx.values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">mean_RHSTOT</span> <span class="op">-</span> <span class="va">sd_RHSTOT</span>, <span class="va">mean_RHSTOT</span>, <span class="va">mean_RHSTOT</span> <span class="op">+</span> <span class="va">sd_RHSTOT</span><span class="op">)</span>,</span>
<span>  plot.points <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>  main.title <span class="op">=</span> <span class="st">"Interazione tra DTST e RHSTOT su CS_TOT"</span>,</span>
<span>  x.label <span class="op">=</span> <span class="st">"Fiducia di coppia (DTST)"</span>,</span>
<span>  y.label <span class="op">=</span> <span class="st">"Compassione (CS_TOT)"</span>,</span>
<span>  legend.main <span class="op">=</span> <span class="st">"Livelli di umiltà percepita (RHSTOT)"</span></span>
<span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="02_clement_2022_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Dal grafico</strong> (non mostrato qui ma ottenibile con il codice sopra), si nota:</p>
<ul>
<li>A livelli <strong>elevati</strong> di <em>RHSTOT</em>, la relazione <em>DTST → CS_TOT</em> è più ripida e positiva.<br>
</li>
<li>A livelli <strong>bassi</strong> di <em>RHSTOT</em>, la pendenza della retta si appiattisce: l’effetto di <em>DTST</em> sulla compassione risulta più debole.</li>
</ul></section></section><section id="analisi-della-mediazione" class="level2" data-number="23.7"><h2 data-number="23.7" class="anchored" data-anchor-id="analisi-della-mediazione">
<span class="header-section-number">23.7</span> Analisi della Mediazione</h2>
<p><strong>Obiettivo</strong><br>
Esaminare come la variabile <em>DTST</em> (fiducia di coppia) influenzi <em>TRIM_Ben</em> (perdono) attraverso una variabile mediatrice, <em>CS_TOT</em> (compassione). Seguendo la notazione comunemente utilizzata (ad es. in un modello di mediazione semplice):</p>
<ul>
<li>
<em>X</em> = DTST (fiducia)</li>
<li>
<em>M</em> = CS_TOT (compassione)</li>
<li>
<em>Y</em> = TRIM_Ben (perdono)</li>
</ul>
<p>Un modello di mediazione tipicamente analizza:<br>
1. <strong>Effetto diretto</strong> (<em>c’</em>): influenza di <em>X</em> su <em>Y</em> senza passare per <em>M</em>.<br>
2. <strong>Effetto mediato</strong> (<em>ab</em>): influenza indiretta di <em>X</em> su <em>Y</em> che passa attraverso <em>M</em>.<br>
3. <strong>Effetto totale</strong> (<em>c</em>): somma di effetto diretto e mediato.</p>
<section id="specifica-del-modello-in-lavaan" class="level3" data-number="23.7.1"><h3 data-number="23.7.1" class="anchored" data-anchor-id="specifica-del-modello-in-lavaan">
<span class="header-section-number">23.7.1</span> Specifica del Modello in lavaan</h3>
<p>Utilizzando il pacchetto <code>lavaan</code> in R, si può costruire il seguente modello:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model</span> <span class="op">&lt;-</span> <span class="st">"</span></span>
<span><span class="st">  # Effetto diretto di DTST su TRIM_Ben</span></span>
<span><span class="st">  TRIM_Ben ~ c_prime*DTST</span></span>
<span><span class="st"></span></span>
<span><span class="st">  # Effetto di DTST su CS_TOT</span></span>
<span><span class="st">  CS_TOT ~ a*DTST</span></span>
<span><span class="st"></span></span>
<span><span class="st">  # Effetto di CS_TOT su TRIM_Ben</span></span>
<span><span class="st">  TRIM_Ben ~ b*CS_TOT</span></span>
<span><span class="st"></span></span>
<span><span class="st">  # Effetto indiretto</span></span>
<span><span class="st">  ab := a*b</span></span>
<span><span class="st"></span></span>
<span><span class="st">  # Effetto totale</span></span>
<span><span class="st">  total := c_prime + ab</span></span>
<span><span class="st">"</span></span>
<span></span>
<span><span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu">sem</span><span class="op">(</span><span class="va">model</span>, data <span class="op">=</span> <span class="va">data</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit</span>, fit.measures <span class="op">=</span> <span class="cn">TRUE</span>, standardized <span class="op">=</span> <span class="cn">TRUE</span>, rsquare <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="co">#&gt; lavaan 0.6-19 ended normally after 1 iteration</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Estimator                                         ML</span></span>
<span><span class="co">#&gt;   Optimization method                           NLMINB</span></span>
<span><span class="co">#&gt;   Number of model parameters                         5</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Number of observations                           138</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Model Test User Model:</span></span>
<span><span class="co">#&gt;                                                       </span></span>
<span><span class="co">#&gt;   Test statistic                                 0.000</span></span>
<span><span class="co">#&gt;   Degrees of freedom                                 0</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Model Test Baseline Model:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Test statistic                                60.916</span></span>
<span><span class="co">#&gt;   Degrees of freedom                                 3</span></span>
<span><span class="co">#&gt;   P-value                                        0.000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; User Model versus Baseline Model:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Comparative Fit Index (CFI)                    1.000</span></span>
<span><span class="co">#&gt;   Tucker-Lewis Index (TLI)                       1.000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Loglikelihood and Information Criteria:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Loglikelihood user model (H0)               -895.673</span></span>
<span><span class="co">#&gt;   Loglikelihood unrestricted model (H1)       -895.673</span></span>
<span><span class="co">#&gt;                                                       </span></span>
<span><span class="co">#&gt;   Akaike (AIC)                                1801.345</span></span>
<span><span class="co">#&gt;   Bayesian (BIC)                              1815.981</span></span>
<span><span class="co">#&gt;   Sample-size adjusted Bayesian (SABIC)       1800.163</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Root Mean Square Error of Approximation:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   RMSEA                                          0.000</span></span>
<span><span class="co">#&gt;   90 Percent confidence interval - lower         0.000</span></span>
<span><span class="co">#&gt;   90 Percent confidence interval - upper         0.000</span></span>
<span><span class="co">#&gt;   P-value H_0: RMSEA &lt;= 0.050                       NA</span></span>
<span><span class="co">#&gt;   P-value H_0: RMSEA &gt;= 0.080                       NA</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Standardized Root Mean Square Residual:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   SRMR                                           0.000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Parameter Estimates:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Standard errors                             Standard</span></span>
<span><span class="co">#&gt;   Information                                 Expected</span></span>
<span><span class="co">#&gt;   Information saturated (h1) model          Structured</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Regressions:</span></span>
<span><span class="co">#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all</span></span>
<span><span class="co">#&gt;   TRIM_Ben ~                                                            </span></span>
<span><span class="co">#&gt;     DTST    (c_pr)    0.148    0.040    3.691    0.000    0.148    0.267</span></span>
<span><span class="co">#&gt;   CS_TOT ~                                                              </span></span>
<span><span class="co">#&gt;     DTST       (a)    0.197    0.069    2.864    0.004    0.197    0.237</span></span>
<span><span class="co">#&gt;   TRIM_Ben ~                                                            </span></span>
<span><span class="co">#&gt;     CS_TOT     (b)    0.292    0.048    6.058    0.000    0.292    0.438</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Variances:</span></span>
<span><span class="co">#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all</span></span>
<span><span class="co">#&gt;    .TRIM_Ben         21.819    2.627    8.307    0.000   21.819    0.681</span></span>
<span><span class="co">#&gt;    .CS_TOT           68.186    8.209    8.307    0.000   68.186    0.944</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; R-Square:</span></span>
<span><span class="co">#&gt;                    Estimate</span></span>
<span><span class="co">#&gt;     TRIM_Ben          0.319</span></span>
<span><span class="co">#&gt;     CS_TOT            0.056</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Defined Parameters:</span></span>
<span><span class="co">#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all</span></span>
<span><span class="co">#&gt;     ab                0.058    0.022    2.589    0.010    0.058    0.104</span></span>
<span><span class="co">#&gt;     total             0.205    0.044    4.690    0.000    0.205    0.371</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="risultati-principali-1" class="level3" data-number="23.7.2"><h3 data-number="23.7.2" class="anchored" data-anchor-id="risultati-principali-1">
<span class="header-section-number">23.7.2</span> Risultati Principali</h3>
<ol type="1">
<li>
<strong>Effetto Diretto (<span class="math inline">\(c’\)</span>)</strong>
<ul>
<li>Coefficiente standardizzato = 0.267<br>
</li>
<li>Coefficiente non standardizzato = 0.148 (SE = 0.040, z = 3.691, p &lt; 0.001)<br>
</li>
<li>Indica un effetto positivo e significativo di <em>DTST</em> sul perdono (<em>TRIM_Ben</em>), al netto di <em>CS_TOT</em>.</li>
</ul>
</li>
<li>
<strong>Effetto Indiretto (<span class="math inline">\(ab\)</span>)</strong>
<ul>
<li>Coefficiente standardizzato = 0.104<br>
</li>
<li>Coefficiente non standardizzato = 0.058 (SE = 0.022, z = 2.589, p = 0.010)<br>
</li>
<li>
<em>DTST</em> influenza anche il perdono (<em>TRIM_Ben</em>) <strong>attraverso</strong> la compassione (<em>CS_TOT</em>): maggiore fiducia favorisce la compassione, che a sua volta incrementa la propensione al perdono.</li>
</ul>
</li>
<li>
<strong>Effetto Totale (<span class="math inline">\(c\)</span>)</strong>
<ul>
<li>Coefficiente standardizzato = 0.371<br>
</li>
<li>Coefficiente non standardizzato = 0.205 (SE = 0.044, z = 4.690, p &lt; 0.001)<br>
</li>
<li>Sommando effetto diretto e indiretto, l’influenza globale di <em>DTST</em> sul perdono è positiva e significativa.</li>
</ul>
</li>
</ol></section><section id="varianza-spiegata-r²" class="level3" data-number="23.7.3"><h3 data-number="23.7.3" class="anchored" data-anchor-id="varianza-spiegata-r²">
<span class="header-section-number">23.7.3</span> Varianza Spiegata (R²)</h3>
<ul>
<li>
<em>TRIM_Ben (perdono)</em>: Il modello spiega circa il <strong>31.9%</strong> della varianza.<br>
</li>
<li>
<em>CS_TOT (compassione)</em>: <em>DTST</em> spiega circa il <strong>5.6%</strong> della varianza in <em>CS_TOT</em>.</li>
</ul>
<p><strong>Conclusione (Mediazione)</strong><br>
La fiducia di coppia (<em>DTST</em>) contribuisce al perdono sia direttamente sia tramite la compassione (<em>CS_TOT</em>). Questa evidenza sottolinea che coltivare la fiducia e la compassione può promuovere la capacità di perdonare nelle relazioni.</p>
</section></section><section id="mediazione-moderata" class="level2" data-number="23.8"><h2 data-number="23.8" class="anchored" data-anchor-id="mediazione-moderata">
<span class="header-section-number">23.8</span> Mediazione Moderata</h2>
<p><strong>Obiettivo</strong><br>
Integrare contemporaneamente mediazione e moderazione. Si analizza se <em>RHSTOT</em> (umiltà percepita) modera i percorsi chiave, ossia:<br>
1. Il percorso diretto tra <em>DTST</em> e <em>TRIM_Ben</em>.<br>
2. Il percorso mediato attraverso <em>CS_TOT</em> (quindi anche la relazione tra <em>DTST</em> e <em>CS_TOT</em>).</p>
<section id="specifica-del-modello-in-lavaan-1" class="level3" data-number="23.8.1"><h3 data-number="23.8.1" class="anchored" data-anchor-id="specifica-del-modello-in-lavaan-1">
<span class="header-section-number">23.8.1</span> Specifica del Modello in lavaan</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model</span> <span class="op">&lt;-</span> <span class="st">"</span></span>
<span><span class="st">  # Effetti su TRIM_Ben (Y)</span></span>
<span><span class="st">  TRIM_Ben ~ c*DTST + b*CS_TOT + d*RHSTOT + e*DTST:RHSTOT</span></span>
<span><span class="st"></span></span>
<span><span class="st">  # Effetti su CS_TOT (M)</span></span>
<span><span class="st">  CS_TOT ~ a*DTST + f*RHSTOT + g*DTST:RHSTOT</span></span>
<span><span class="st"></span></span>
<span><span class="st">  # Definizioni di effetti</span></span>
<span><span class="st">  indirect := a*b</span></span>
<span><span class="st">  direct   := c</span></span>
<span><span class="st">  total    := indirect + direct</span></span>
<span><span class="st">"</span></span>
<span></span>
<span><span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu">sem</span><span class="op">(</span><span class="va">model</span>, data <span class="op">=</span> <span class="va">data</span>, se <span class="op">=</span> <span class="st">"bootstrap"</span>, bootstrap <span class="op">=</span> <span class="fl">100</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit</span>, fit.measures <span class="op">=</span> <span class="cn">TRUE</span>, standardized <span class="op">=</span> <span class="cn">TRUE</span>, rsquare <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="co">#&gt; lavaan 0.6-19 ended normally after 1 iteration</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Estimator                                         ML</span></span>
<span><span class="co">#&gt;   Optimization method                           NLMINB</span></span>
<span><span class="co">#&gt;   Number of model parameters                         9</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Number of observations                           138</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Model Test User Model:</span></span>
<span><span class="co">#&gt;                                                       </span></span>
<span><span class="co">#&gt;   Test statistic                                 0.000</span></span>
<span><span class="co">#&gt;   Degrees of freedom                                 0</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Model Test Baseline Model:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Test statistic                                71.556</span></span>
<span><span class="co">#&gt;   Degrees of freedom                                 7</span></span>
<span><span class="co">#&gt;   P-value                                        0.000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; User Model versus Baseline Model:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Comparative Fit Index (CFI)                    1.000</span></span>
<span><span class="co">#&gt;   Tucker-Lewis Index (TLI)                       1.000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Loglikelihood and Information Criteria:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Loglikelihood user model (H0)               -890.353</span></span>
<span><span class="co">#&gt;   Loglikelihood unrestricted model (H1)       -890.353</span></span>
<span><span class="co">#&gt;                                                       </span></span>
<span><span class="co">#&gt;   Akaike (AIC)                                1798.705</span></span>
<span><span class="co">#&gt;   Bayesian (BIC)                              1825.050</span></span>
<span><span class="co">#&gt;   Sample-size adjusted Bayesian (SABIC)       1796.577</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Root Mean Square Error of Approximation:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   RMSEA                                          0.000</span></span>
<span><span class="co">#&gt;   90 Percent confidence interval - lower         0.000</span></span>
<span><span class="co">#&gt;   90 Percent confidence interval - upper         0.000</span></span>
<span><span class="co">#&gt;   P-value H_0: RMSEA &lt;= 0.050                       NA</span></span>
<span><span class="co">#&gt;   P-value H_0: RMSEA &gt;= 0.080                       NA</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Standardized Root Mean Square Residual:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   SRMR                                           0.000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Parameter Estimates:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Standard errors                            Bootstrap</span></span>
<span><span class="co">#&gt;   Number of requested bootstrap draws              100</span></span>
<span><span class="co">#&gt;   Number of successful bootstrap draws             100</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Regressions:</span></span>
<span><span class="co">#&gt;                    Estimate    Std.Err  z-value  P(&gt;|z|)   Std.lv  </span></span>
<span><span class="co">#&gt;   TRIM_Ben ~                                                       </span></span>
<span><span class="co">#&gt;     DTST       (c)      0.203    0.165    1.234    0.217      0.203</span></span>
<span><span class="co">#&gt;     CS_TOT     (b)      0.289    0.052    5.559    0.000      0.289</span></span>
<span><span class="co">#&gt;     RHSTOT     (d)      0.122    0.131    0.930    0.353      0.122</span></span>
<span><span class="co">#&gt;     DTST:RHSTO (e)     -0.002    0.003   -0.576    0.565     -0.002</span></span>
<span><span class="co">#&gt;   CS_TOT ~                                                         </span></span>
<span><span class="co">#&gt;     DTST       (a)     -0.517    0.300   -1.722    0.085     -0.517</span></span>
<span><span class="co">#&gt;     RHSTOT     (f)     -0.355    0.233   -1.525    0.127     -0.355</span></span>
<span><span class="co">#&gt;     DTST:RHSTO (g)      0.014    0.006    2.280    0.023      0.014</span></span>
<span><span class="co">#&gt;   Std.all</span></span>
<span><span class="co">#&gt;          </span></span>
<span><span class="co">#&gt;     0.367</span></span>
<span><span class="co">#&gt;     0.433</span></span>
<span><span class="co">#&gt;     0.219</span></span>
<span><span class="co">#&gt;    -0.254</span></span>
<span><span class="co">#&gt;          </span></span>
<span><span class="co">#&gt;    -0.621</span></span>
<span><span class="co">#&gt;    -0.424</span></span>
<span><span class="co">#&gt;     1.232</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Variances:</span></span>
<span><span class="co">#&gt;                    Estimate    Std.Err  z-value  P(&gt;|z|)   Std.lv  </span></span>
<span><span class="co">#&gt;    .TRIM_Ben           21.601    3.470    6.225    0.000     21.601</span></span>
<span><span class="co">#&gt;    .CS_TOT             63.762    8.915    7.152    0.000     63.762</span></span>
<span><span class="co">#&gt;   Std.all</span></span>
<span><span class="co">#&gt;     0.675</span></span>
<span><span class="co">#&gt;     0.883</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; R-Square:</span></span>
<span><span class="co">#&gt;                    Estimate  </span></span>
<span><span class="co">#&gt;     TRIM_Ben            0.325</span></span>
<span><span class="co">#&gt;     CS_TOT              0.117</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Defined Parameters:</span></span>
<span><span class="co">#&gt;                    Estimate    Std.Err  z-value  P(&gt;|z|)   Std.lv  </span></span>
<span><span class="co">#&gt;     indirect           -0.149    0.101   -1.481    0.139     -0.149</span></span>
<span><span class="co">#&gt;     direct              0.203    0.165    1.228    0.219      0.203</span></span>
<span><span class="co">#&gt;     total               0.054    0.183    0.295    0.768      0.054</span></span>
<span><span class="co">#&gt;   Std.all</span></span>
<span><span class="co">#&gt;    -0.269</span></span>
<span><span class="co">#&gt;     0.367</span></span>
<span><span class="co">#&gt;     0.097</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>
<em>DTST:RHSTOT</em> rappresenta il termine di interazione che cattura se e come l’umiltà percepita modula l’effetto della fiducia di coppia sia su <em>TRIM_Ben</em> sia su <em>CS_TOT</em>.</li>
</ul></section><section id="risultati-principali-2" class="level3" data-number="23.8.2"><h3 data-number="23.8.2" class="anchored" data-anchor-id="risultati-principali-2">
<span class="header-section-number">23.8.2</span> Risultati Principali</h3>
<ol type="1">
<li>
<strong>Effetto Diretto</strong>
<ul>
<li>Coefficiente = 0.203 (z = 1.378, p = 0.168)<br>
</li>
<li>Non è significativo al 5%, ma suggerisce una lieve relazione positiva.</li>
</ul>
</li>
<li>**Effetto Indiretto (a*b)**
<ul>
<li>Coefficiente = -0.149 (z = -1.435, p = 0.151)<br>
</li>
<li>Non significativo.</li>
</ul>
</li>
<li>
<strong>Interazione su CS_TOT</strong>
<ul>
<li>Coefficiente = 0.014 (z = 2.162, p = 0.031)<br>
</li>
<li>Indica che l’effetto di <em>DTST</em> sulla compassione (<em>CS_TOT</em>) è più forte quando l’umiltà percepita (<em>RHSTOT</em>) è alta.</li>
</ul>
</li>
<li>
<strong>Effetto Totale</strong>
<ul>
<li>Coefficiente = 0.054 (z = 0.380, p = 0.704)<br>
</li>
<li>Complessivamente, l’effetto di <em>DTST</em> sul perdono risulta piuttosto debole in questo modello.</li>
</ul>
</li>
<li>
<strong>Varianza Spiegata</strong>
<ul>
<li>Circa <strong>32.5%</strong> della varianza in <em>TRIM_Ben</em>.<br>
</li>
<li>Circa <strong>11.7%</strong> della varianza in <em>CS_TOT</em>.</li>
</ul>
</li>
</ol></section><section id="conclusioni-mediazione-moderata" class="level3" data-number="23.8.3"><h3 data-number="23.8.3" class="anchored" data-anchor-id="conclusioni-mediazione-moderata">
<span class="header-section-number">23.8.3</span> Conclusioni (Mediazione Moderata)</h3>
<ul>
<li>L’umiltà percepita (<em>RHSTOT</em>) modera il legame tra fiducia e compassione: se il partner è percepito come umile, la fiducia ha un impatto più robusto nel favorire la compassione.<br>
</li>
<li>Non emergono invece prove convincenti di un effetto mediato significativo di <em>DTST</em> su <em>TRIM_Ben</em> attraverso <em>CS_TOT</em> in presenza della moderazione di <em>RHSTOT</em>.<br>
</li>
<li>Nonostante ciò, la componente di moderazione sottolinea l’importanza delle percezioni interpersonali (umiltà percepita) per comprendere come la fiducia possa trasformarsi in atteggiamenti prosociali (compassione) e, potenzialmente, in perdono.</li>
</ul></section></section><section id="sintesi-complessiva" class="level2" data-number="23.9"><h2 data-number="23.9" class="anchored" data-anchor-id="sintesi-complessiva">
<span class="header-section-number">23.9</span> Sintesi Complessiva</h2>
<ol type="1">
<li>
<strong>Moderazione</strong>:
<ul>
<li>
<em>DTST</em> (fiducia di coppia) e <em>RHSTOT</em> (umiltà percepita) interagiscono nel predire <em>CS_TOT</em> (compassione). In particolare, la fiducia esercita un effetto più intenso se il partner è percepito come umile.</li>
</ul>
</li>
<li>
<strong>Mediazione</strong>:
<ul>
<li>Quando guardiamo alla relazione tra <em>DTST</em> (fiducia) e <em>TRIM_Ben</em> (perdono), <em>CS_TOT</em> (compassione) funge da mediatore significativo: una maggiore fiducia incrementa la compassione, che a sua volta aumenta la propensione a perdonare.</li>
</ul>
</li>
<li>
<strong>Mediazione Moderata</strong>:
<ul>
<li>La moderazione di <em>RHSTOT</em> è rilevante soprattutto sul percorso <em>DTST → CS_TOT</em>. Non si osservano effetti mediati significativi sul perdono (<em>TRIM_Ben</em>) una volta introdotto l’effetto interattivo.</li>
</ul>
</li>
</ol>
<p><strong>Implicazioni</strong><br>
- Per favorire il perdono in coppia, è utile agire su più fronti: consolidare la fiducia, coltivare la compassione e, ove possibile, promuovere percezioni positive di umiltà.<br>
- Gli interventi di sostegno psicologico che mirano a rafforzare sia la fiducia sia l’umiltà percepita possono potenziare l’effetto pro-compassione, rendendo il perdono più probabile.</p>
<p><strong>In sintesi</strong>, i risultati evidenziano come l’umiltà percepita del partner (<em>RHSTOT</em>) rappresenti un elemento chiave per modulare l’effetto della fiducia di coppia (<em>DTST</em>) sulla compassione (<em>CS_TOT</em>) e, in misura più limitata, sul perdono (<em>TRIM_Ben</em>). In particolare:</p>
<ul>
<li>Sebbene l’effetto diretto di <em>DTST</em> sul perdono non risulti significativo, la percezione positiva del partner come umile (RHSTOT) potenzia la relazione tra fiducia e compassione, promuovendo atteggiamenti più empatici.</li>
<li>Non vi sono tuttavia evidenze solide di un effetto indiretto di <em>DTST</em> su <em>TRIM_Ben</em> mediato unicamente da <em>CS_TOT</em>.</li>
</ul>
<p>Il modello suggerisce che, pur avendo un impatto limitato sul perdono, le percezioni interpersonali (come l’umiltà del partner) rivestono un ruolo importante nell’aumentare la capacità di provare compassione.</p>
</section><section id="riflessioni-finali" class="level2" data-number="23.10"><h2 data-number="23.10" class="anchored" data-anchor-id="riflessioni-finali">
<span class="header-section-number">23.10</span> Riflessioni Finali</h2>
<p>Le tre analisi prese in esame delineano un quadro complesso delle dinamiche tra fiducia di coppia (<em>DTST</em>), compassione (<em>CS_TOT</em>) e perdono (<em>TRIM_Ben</em>).</p>
<ol type="1">
<li>
<strong>Fiducia di coppia</strong>
<ul>
<li>Influisce in modo diretto sul perdono, anche se la forza di questo legame varia a seconda dei modelli presi in considerazione.<br>
</li>
<li>Svolge una funzione rilevante nel promuovere la compassione, la quale a sua volta facilita il perdono (effetto mediato).</li>
</ul>
</li>
<li>
<strong>Umiltà percepita del partner</strong>
<ul>
<li>Modera la relazione tra fiducia e compassione, amplificando l’effetto della prima sullo sviluppo di sentimenti compassionevoli.<br>
</li>
<li>Quando il partner è percepito come più umile, la fiducia di coppia si traduce in maniera più incisiva in compassione, e potenzialmente in comportamenti più orientati al perdono.</li>
</ul>
</li>
<li>
<strong>Perdono</strong>
<ul>
<li>Risulta influenzato dalla fiducia, specialmente attraverso la compassione come meccanismo di mediazione.<br>
</li>
<li>È ulteriormente sostenuto da un contesto relazionale in cui vi sia un riconoscimento reciproco di umiltà e responsabilità.</li>
</ul>
</li>
</ol>
<p><strong>Prospettive Applicative</strong><br>
Interventi mirati a promuovere la fiducia reciproca nelle relazioni di coppia, a potenziare i sentimenti di compassione e ad accrescere la percezione di umiltà possono contribuire a un miglioramento nella propensione al perdono. Lavorare su queste tre dimensioni (fiducia, compassione, umiltà) potrebbe dunque rivelarsi essenziale per favorire un clima relazionale più empatico e cooperativo, utile in contesti sia clinici sia di prevenzione.</p>
</section><section id="session-info" class="level2" data-number="23.11"><h2 data-number="23.11" class="anchored" data-anchor-id="session-info">
<span class="header-section-number">23.11</span> Session Info</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; R version 4.4.2 (2024-10-31)</span></span>
<span><span class="co">#&gt; Platform: aarch64-apple-darwin20</span></span>
<span><span class="co">#&gt; Running under: macOS Sequoia 15.3.2</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Matrix products: default</span></span>
<span><span class="co">#&gt; BLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib </span></span>
<span><span class="co">#&gt; LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; locale:</span></span>
<span><span class="co">#&gt; [1] C/UTF-8/C/C/C/C</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; time zone: Europe/Rome</span></span>
<span><span class="co">#&gt; tzcode source: internal</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; attached base packages:</span></span>
<span><span class="co">#&gt; [1] stats     graphics  grDevices utils     datasets  methods   base     </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; other attached packages:</span></span>
<span><span class="co">#&gt;  [1] sjPlot_2.8.17      interactions_1.2.0 lmtest_0.9-40     </span></span>
<span><span class="co">#&gt;  [4] zoo_1.8-13         car_3.1-3          carData_3.0-5     </span></span>
<span><span class="co">#&gt;  [7] performance_0.13.0 mediation_4.5.0    sandwich_3.1-1    </span></span>
<span><span class="co">#&gt; [10] mvtnorm_1.3-3      Matrix_1.7-3       haven_2.5.4       </span></span>
<span><span class="co">#&gt; [13] lavaanPlot_0.8.1   lavaanExtra_0.2.1  ggokabeito_0.1.0  </span></span>
<span><span class="co">#&gt; [16] see_0.11.0         MASS_7.3-65        viridis_0.6.5     </span></span>
<span><span class="co">#&gt; [19] viridisLite_0.4.2  ggpubr_0.6.0       ggExtra_0.10.1    </span></span>
<span><span class="co">#&gt; [22] gridExtra_2.3      patchwork_1.3.0    bayesplot_1.11.1  </span></span>
<span><span class="co">#&gt; [25] semTools_0.5-6     semPlot_1.1.6      lavaan_0.6-19     </span></span>
<span><span class="co">#&gt; [28] psych_2.4.12       scales_1.3.0       markdown_1.13     </span></span>
<span><span class="co">#&gt; [31] knitr_1.50         lubridate_1.9.4    forcats_1.0.0     </span></span>
<span><span class="co">#&gt; [34] stringr_1.5.1      dplyr_1.1.4        purrr_1.0.4       </span></span>
<span><span class="co">#&gt; [37] readr_2.1.5        tidyr_1.3.1        tibble_3.2.1      </span></span>
<span><span class="co">#&gt; [40] ggplot2_3.5.1      tidyverse_2.0.0    here_1.0.1        </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; loaded via a namespace (and not attached):</span></span>
<span><span class="co">#&gt;   [1] splines_4.4.2       later_1.4.1         datawizard_1.0.1   </span></span>
<span><span class="co">#&gt;   [4] XML_3.99-0.18       rpart_4.1.24        lifecycle_1.0.4    </span></span>
<span><span class="co">#&gt;   [7] Rdpack_2.6.3        rstatix_0.7.2       rprojroot_2.0.4    </span></span>
<span><span class="co">#&gt;  [10] globals_0.16.3      lattice_0.22-6      insight_1.1.0      </span></span>
<span><span class="co">#&gt;  [13] rockchalk_1.8.157   backports_1.5.0     magrittr_2.0.3     </span></span>
<span><span class="co">#&gt;  [16] openxlsx_4.2.8      Hmisc_5.2-3         rmarkdown_2.29     </span></span>
<span><span class="co">#&gt;  [19] httpuv_1.6.15       qgraph_1.9.8        zip_2.3.2          </span></span>
<span><span class="co">#&gt;  [22] pbapply_1.7-2       minqa_1.2.8         RColorBrewer_1.1-3 </span></span>
<span><span class="co">#&gt;  [25] multcomp_1.4-28     abind_1.4-8         quadprog_1.5-8     </span></span>
<span><span class="co">#&gt;  [28] nnet_7.3-20         TH.data_1.1-3       jtools_2.3.0       </span></span>
<span><span class="co">#&gt;  [31] listenv_0.9.1       arm_1.14-4          parallelly_1.42.0  </span></span>
<span><span class="co">#&gt;  [34] codetools_0.2-20    tidyselect_1.2.1    ggeffects_2.2.1    </span></span>
<span><span class="co">#&gt;  [37] farver_2.1.2        lme4_1.1-36         broom.mixed_0.2.9.6</span></span>
<span><span class="co">#&gt;  [40] stats4_4.4.2        base64enc_0.1-3     jsonlite_1.9.1     </span></span>
<span><span class="co">#&gt;  [43] Formula_1.2-5       survival_3.8-3      emmeans_1.10.7     </span></span>
<span><span class="co">#&gt;  [46] tools_4.4.2         Rcpp_1.0.14         glue_1.8.0         </span></span>
<span><span class="co">#&gt;  [49] mnormt_2.1.1        xfun_0.51           withr_3.0.2        </span></span>
<span><span class="co">#&gt;  [52] fastmap_1.2.0       boot_1.3-31         digest_0.6.37      </span></span>
<span><span class="co">#&gt;  [55] mi_1.1              timechange_0.3.0    R6_2.6.1           </span></span>
<span><span class="co">#&gt;  [58] mime_0.13           estimability_1.5.1  colorspace_2.1-1   </span></span>
<span><span class="co">#&gt;  [61] lpSolve_5.6.23      gtools_3.9.5        jpeg_0.1-10        </span></span>
<span><span class="co">#&gt;  [64] DiagrammeR_1.0.11   generics_0.1.3      data.table_1.17.0  </span></span>
<span><span class="co">#&gt;  [67] corpcor_1.6.10      htmlwidgets_1.6.4   pkgconfig_2.0.3    </span></span>
<span><span class="co">#&gt;  [70] sem_3.1-16          gtable_0.3.6        furrr_0.3.1        </span></span>
<span><span class="co">#&gt;  [73] htmltools_0.5.8.1   png_0.1-8           reformulas_0.4.0   </span></span>
<span><span class="co">#&gt;  [76] rstudioapi_0.17.1   tzdb_0.5.0          reshape2_1.4.4     </span></span>
<span><span class="co">#&gt;  [79] coda_0.19-4.1       visNetwork_2.1.2    checkmate_2.3.2    </span></span>
<span><span class="co">#&gt;  [82] nlme_3.1-167        nloptr_2.2.1        sjlabelled_1.2.0   </span></span>
<span><span class="co">#&gt;  [85] parallel_4.4.2      miniUI_0.1.1.1      foreign_0.8-88     </span></span>
<span><span class="co">#&gt;  [88] pillar_1.10.1       grid_4.4.2          vctrs_0.6.5        </span></span>
<span><span class="co">#&gt;  [91] promises_1.3.2      OpenMx_2.21.13      xtable_1.8-4       </span></span>
<span><span class="co">#&gt;  [94] cluster_2.1.8.1     htmlTable_2.4.3     evaluate_1.0.3     </span></span>
<span><span class="co">#&gt;  [97] pbivnorm_0.6.0      cli_3.6.4           kutils_1.73        </span></span>
<span><span class="co">#&gt; [100] compiler_4.4.2      rlang_1.1.5         ggsignif_0.6.4     </span></span>
<span><span class="co">#&gt; [103] labeling_0.4.3      fdrtool_1.2.18      sjmisc_2.8.10      </span></span>
<span><span class="co">#&gt; [106] plyr_1.8.9          stringi_1.8.4       pander_0.6.6       </span></span>
<span><span class="co">#&gt; [109] munsell_0.5.1       lisrelToR_0.3       pacman_0.5.1       </span></span>
<span><span class="co">#&gt; [112] sjstats_0.19.0      hms_1.1.3           glasso_1.11        </span></span>
<span><span class="co">#&gt; [115] future_1.34.0       shiny_1.10.0        rbibutils_2.3      </span></span>
<span><span class="co">#&gt; [118] igraph_2.1.4        broom_1.0.7         RcppParallel_5.1.10</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-clement2022step" class="csl-entry" role="listitem">
Clement, L. M., &amp; Bradley-Garcia, M. (2022). A step-by-step tutorial for performing a moderated mediation analysis using PROCESS. <em>The Quantitative Methods for Psychology</em>, <em>18</em>(3), 258–271.
</div>
<div id="ref-hargrave2016restoration" class="csl-entry" role="listitem">
Hargrave, T. D., &amp; Hammer, M. Y. (2016). Restoration of Relationships After Affairs. In <em>Techniques for the Couple Therapist</em> (pp. 190–193). Routledge.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiato!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiato!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ccaudek\.github\.io\/testing_psicologico\/intro\.html");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../chapters/path_analysis/01_path_analysis.html" class="pagination-link" aria-label="Analisi dei percorsi">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Analisi dei percorsi</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/networks/01_networks.html" class="pagination-link" aria-label="Network psicologici">
        <span class="nav-page-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Network psicologici</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Testing Psicologico</strong> è una dispensa scritta da Corrado Caudek.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


</body></html>