<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Corrado Caudek">
<title>83&nbsp; Predizione – Testing Psicologico</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../99-references.html" rel="next">
<link href="../../chapters/lgm/12_temp_reliability.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-2363a7b1713459e3bb7e05f1febbb7c9.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-6160eebdccf729e88acfdd1d92726e70.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-62e4b2809dfb41b5160f340e7c383cce.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-d5b1b7f210f9f8712579e048ed54cd39.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script><script type="application/json" class="js-hypothesis-config">
{
  "theme": "clean"
}
</script><script async="" src="https://hypothes.is/embed.js"></script><script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/prediction/01_prediction.html">Predizione</a></li><li class="breadcrumb-item"><a href="../../chapters/prediction/01_prediction.html"><span class="chapter-number">83</span>&nbsp; <span class="chapter-title">Predizione</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Testing Psicologico</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ccaudek/testing_psicologico/" title="Eseguire il codice" class="quarto-navigation-tool px-1" aria-label="Eseguire il codice"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Attiva/disattiva la modalità oscura"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Ricerca"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Benvenuti</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../prefazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefazione</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Calendario</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../cal_testing_psic_2025.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calendario Didattico e Programma del Corso</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Punteggi e scale</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/01_scores_scales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Punteggi e scale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E1_likert.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E2_optimal_scoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E3_thurstone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/02_development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sviluppo dello strumento</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/03_equating.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Equating nei Test Psicologici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E4_norming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">CTT</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/01_ctt_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Fondamenti teorici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/02_ctt_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">L’affidabilità del test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/03_ctt_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Metodi di stima dell’affidabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/04_err_std_mis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">L’errore standard della misurazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/05_err_std_stima.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">La stima del punteggio vero</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/06_ctt_applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Applicazioni della CTT</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Giudici</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/01_multilevel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Modelli multilivello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/02_interrater_reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">L’affidabilità tra giudici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/E1_irr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Validità</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/validity/01_validity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">La Validità del test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/validity/02_other_variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Relazioni test-criterio</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Generalizzabilità</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/gtheory/01_gtheory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Teoria della generalizzabilità</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Items</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/items/01_item_development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Lo sviluppo degli item</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/items/02_item_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Analisi degli item</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Analisi dei percorsi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/path_analysis/01_path_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Analisi dei percorsi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/path_analysis/02_clement_2022.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Riparazione affettiva post-infedeltà</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Networks</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/networks/01_networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Network psicologici</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">PCA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/pca/01_linear_algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Elementi di algebra lineare</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/pca/02_pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Analisi delle componenti principali</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">FA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/01_intro_fa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Introduzione all’analisi fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/02_analisi_fattoriale_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Il modello unifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/03_analisi_fattoriale_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Il modello statistico dell’analisi fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/04_analisi_fattoriale_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Il modello multifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/05_factor_scores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">I punteggi fattoriali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/06_constraints_on_parms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Attendibilità e modello fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/07_total_score.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Punteggio totale e modello fattoriale</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false">
 <span class="menu-text">Costruzione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/01_val_matrici.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Valutazione della matrice di correlazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/02_estrazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">L’estrazione dei fattori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/03_numero_fattori.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Il numero dei fattori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/04_rotazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">La rotazione fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/05_val_soluzione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Valutare e rifinire la soluzione fattoriale</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">CFA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/01_cfa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Analisti Fattoriale Confermativa</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/02_meanstructure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">La struttura delle medie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/03_cat_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Dati non gaussiani e categoriali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/04_mmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">CFA per matrici multi-tratto multi-metodo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/05_bifactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Modello bifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/06_efa_lavaan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Exploratory Structural Equation Modeling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/07_fa_in_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Strategia Integrata per un’Analisi Fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/E_02_bifactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false">
 <span class="menu-text">SEM</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/01_sem_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Introduzione ai Modelli SEM</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/02_data_preparation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Preparazione dei Dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/03_gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Test del Modello e Indicizzazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/04_mod_comp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Confronto tra modelli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/05_cfa_mod_comp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">CFA: confronto tra modelli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/06_refine_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">La revisione del modello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/07_group_invariance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Invarianza di misura</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/08_multilevel_sem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Modelli di Equazioni Strutturali Multilivello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/09_structural_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Modelli di Regressione Strutturale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/10_missing_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Dati mancanti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/11_small_samples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Modellizzazione SEM in Piccoli Campioni</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/13_esem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Exploratory structural equation modelling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/14_sem_power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Dimensione Campionaria e Analisi della Potenza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/15_prior_pred_mod_check.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Prior Predictive Model Checking</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false">
 <span class="menu-text">Mokken</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/01_logistic_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Modello di Regressione Logistica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/02_core_issues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Analisi della Scala di Mokken</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/03_applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Applicazione Pratica</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false">
 <span class="menu-text">IRT</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/01_rasch_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">Modello di Rasch</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/02_assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">68</span>&nbsp; <span class="chapter-title">Assunzioni e Proprietà del Modello di Rasch</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/03_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title">Stima</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/04_1pl_2pl_3pl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Modelli 1PL, 2PL e 3PL</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/05_implementation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Implementazione</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false">
 <span class="menu-text">LGM</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/01_lgm_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">72</span>&nbsp; <span class="chapter-title">Curve di crescita latente</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/02_lgm_prelims.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">73</span>&nbsp; <span class="chapter-title">Considerazioni Preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/06_lgm_mixed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">74</span>&nbsp; <span class="chapter-title">LGM e modelli misti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/03_time_effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">75</span>&nbsp; <span class="chapter-title">Dati longitudinali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/05_intro_panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">76</span>&nbsp; <span class="chapter-title">Specificare e Interpretare un Modello Longitudinale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/07_growth_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">77</span>&nbsp; <span class="chapter-title">Curve di crescita latente</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/08_growth_cont.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">78</span>&nbsp; <span class="chapter-title">Il tempo su una metrica continua</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/09_time_inv_cov.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">79</span>&nbsp; <span class="chapter-title">Covariate indipendenti dal tempo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/10_growth_groups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">80</span>&nbsp; <span class="chapter-title">Modelli di crescita latenti a gruppi multipli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/11_lgm_wais.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">81</span>&nbsp; <span class="chapter-title">Lo Sviluppo dell’Intelligenza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/12_temp_reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">82</span>&nbsp; <span class="chapter-title">Affidabilità longitudinale</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="true">
 <span class="menu-text">Predizione</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/prediction/01_prediction.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">83</span>&nbsp; <span class="chapter-title">Predizione</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../99-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliografia</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendici</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a1_intro_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linguaggio R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a2_sums.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Simbolo di somma</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a3_calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Per liberarvi dai terrori preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false">
 <span class="menu-text">Soluzioni degli esercizi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/solutions_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Probabilità</span></span></a>
  </div>
</li>
      </ul>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Indice</h2>
   
  <ul>
<li><a href="#introduzione" id="toc-introduzione" class="nav-link active" data-scroll-target="#introduzione"><span class="header-section-number">83.1</span> Introduzione</a></li>
  <li><a href="#probabilit%C3%A0-di-una-condizione-medica" id="toc-probabilità-di-una-condizione-medica" class="nav-link" data-scroll-target="#probabilit%C3%A0-di-una-condizione-medica"><span class="header-section-number">83.2</span> Probabilità di una condizione medica</a></li>
  <li>
<a href="#accuratezza-delle-predizioni" id="toc-accuratezza-delle-predizioni" class="nav-link" data-scroll-target="#accuratezza-delle-predizioni"><span class="header-section-number">83.3</span> Accuratezza delle Predizioni</a>
  <ul>
<li><a href="#la-matrice-di-confusione" id="toc-la-matrice-di-confusione" class="nav-link" data-scroll-target="#la-matrice-di-confusione"><span class="header-section-number">83.3.1</span> La Matrice di Confusione</a></li>
  <li><a href="#tassi-marginali-e-indicatori-chiave" id="toc-tassi-marginali-e-indicatori-chiave" class="nav-link" data-scroll-target="#tassi-marginali-e-indicatori-chiave"><span class="header-section-number">83.3.2</span> Tassi Marginali e Indicatori Chiave</a></li>
  <li><a href="#limportanza-del-tasso-di-base" id="toc-limportanza-del-tasso-di-base" class="nav-link" data-scroll-target="#limportanza-del-tasso-di-base"><span class="header-section-number">83.3.3</span> L’Importanza del Tasso di Base</a></li>
  <li><a href="#diversi-tipi-di-errori-e-i-loro-costi" id="toc-diversi-tipi-di-errori-e-i-loro-costi" class="nav-link" data-scroll-target="#diversi-tipi-di-errori-e-i-loro-costi"><span class="header-section-number">83.3.4</span> Diversi Tipi di Errori e i loro Costi</a></li>
  <li><a href="#importanza-del-rapporto-di-selezione-e-del-tasso-di-base" id="toc-importanza-del-rapporto-di-selezione-e-del-tasso-di-base" class="nav-link" data-scroll-target="#importanza-del-rapporto-di-selezione-e-del-tasso-di-base"><span class="header-section-number">83.3.5</span> Importanza del Rapporto di Selezione e del Tasso di Base</a></li>
  <li><a href="#predizioni-e-affidabilit%C3%A0-in-condizioni-di-basso-tasso-di-base" id="toc-predizioni-e-affidabilità-in-condizioni-di-basso-tasso-di-base" class="nav-link" data-scroll-target="#predizioni-e-affidabilit%C3%A0-in-condizioni-di-basso-tasso-di-base"><span class="header-section-number">83.3.6</span> Predizioni e Affidabilità in Condizioni di Basso Tasso di Base</a></li>
  <li><a href="#sensibilit%C3%A0-specificit%C3%A0-ppv-e-npv" id="toc-sensibilità-specificità-ppv-e-npv" class="nav-link" data-scroll-target="#sensibilit%C3%A0-specificit%C3%A0-ppv-e-npv"><span class="header-section-number">83.3.7</span> Sensibilità, Specificità, PPV e NPV</a></li>
  </ul>
</li>
  <li><a href="#stime-di-accuratezza-e-cutoff" id="toc-stime-di-accuratezza-e-cutoff" class="nav-link" data-scroll-target="#stime-di-accuratezza-e-cutoff"><span class="header-section-number">83.4</span> Stime di Accuratezza e Cutoff</a></li>
  <li><a href="#teoria-della-detezione-del-segnale" id="toc-teoria-della-detezione-del-segnale" class="nav-link" data-scroll-target="#teoria-della-detezione-del-segnale"><span class="header-section-number">83.5</span> Teoria della Detezione del Segnale</a></li>
  <li><a href="#curva-roc-receiver-operating-characteristic" id="toc-curva-roc-receiver-operating-characteristic" class="nav-link" data-scroll-target="#curva-roc-receiver-operating-characteristic"><span class="header-section-number">83.6</span> Curva ROC (Receiver Operating Characteristic)</a></li>
  <li><a href="#auc-area-under-the-curve" id="toc-auc-area-under-the-curve" class="nav-link" data-scroll-target="#auc-area-under-the-curve"><span class="header-section-number">83.7</span> AUC (Area Under the Curve)</a></li>
  <li><a href="#riflessioni-conclusive" id="toc-riflessioni-conclusive" class="nav-link" data-scroll-target="#riflessioni-conclusive"><span class="header-section-number">83.8</span> Riflessioni Conclusive</a></li>
  <li><a href="#informazioni-sullambiente-di-sviluppo" id="toc-informazioni-sullambiente-di-sviluppo" class="nav-link" data-scroll-target="#informazioni-sullambiente-di-sviluppo">Informazioni sull’Ambiente di Sviluppo</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/prediction/01_prediction.html">Predizione</a></li><li class="breadcrumb-item"><a href="../../chapters/prediction/01_prediction.html"><span class="chapter-number">83</span>&nbsp; <span class="chapter-title">Predizione</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-prediction-roc" class="quarto-section-identifier"><span class="chapter-number">83</span>&nbsp; <span class="chapter-title">Predizione</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
In questo capitolo imparerai a
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>conoscere le problematiche di base della predizione statistica;</li>
<li>calcolare e interpretare la curva ROC e la statistica AUC.</li>
</ul>
</div>
</div>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prerequisiti
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Leggere il capitolo 9 <em>Prediction</em> del testo di <span class="citation" data-cites="petersen2024principles">Petersen (<a href="../../99-references.html#ref-petersen2024principles" role="doc-biblioref">2024</a>)</span>.</li>
</ul>
</div>
</div>
<div class="callout callout-style-simple callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Preparazione del Notebook
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"code"</span>, <span class="st">"_common.R"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Load packages</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/ns-load.html">requireNamespace</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span></span>
<span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span></span>
<span>    <span class="va">petersenlab</span>, <span class="va">magrittr</span>, <span class="va">viridis</span>, <span class="va">pROC</span>, <span class="va">ROCR</span>, <span class="va">rms</span>, <span class="va">ResourceSelection</span>,</span>
<span>    <span class="va">gridExtra</span>, <span class="va">grid</span>, <span class="va">ggpubr</span>, <span class="va">msir</span>, <span class="va">car</span>, <span class="va">ggrepel</span>, <span class="va">MOTE</span>,</span>
<span>    <span class="va">tinytex</span></span>
<span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<section id="introduzione" class="level2" data-number="83.1"><h2 data-number="83.1" class="anchored" data-anchor-id="introduzione">
<span class="header-section-number">83.1</span> Introduzione</h2>
<p>Le predizioni rappresentano un aspetto cruciale in numerosi ambiti. Possono riguardare sia dati categoriali, valutabili attraverso strumenti come matrici di confusione e modelli di regressione logistica, sia dati continui, analizzabili tramite regressioni multiple o modelli più complessi come quelli misti o a equazioni strutturali.</p>
<p>Il capitolo si concentra sulla valutazione delle predizioni in contesti categoriali, approfondendo l’utilizzo della curva ROC e dell’AUC (Area Under the Curve) per misurare la qualità dei modelli predittivi.</p>
</section><section id="probabilità-di-una-condizione-medica" class="level2" data-number="83.2"><h2 data-number="83.2" class="anchored" data-anchor-id="probabilità-di-una-condizione-medica">
<span class="header-section-number">83.2</span> Probabilità di una condizione medica</h2>
<p>Un esempio classico, discusso da <span class="citation" data-cites="petersen2024principles">Petersen (<a href="../../99-references.html#ref-petersen2024principles" role="doc-biblioref">2024</a>)</span>, illustra il problema di calcolare la probabilità di avere l’HIV (<span class="math inline">\(P(HIV \mid Test+)\)</span>) partendo da un risultato positivo a un test diagnostico. Le informazioni di base sono:</p>
<ul>
<li>
<strong>Tasso di base dell’HIV</strong> (<span class="math inline">\(P(HIV)\)</span>): 0.3% (0.003), ovvero la probabilità che una persona nella popolazione generale abbia l’HIV.</li>
<li>
<strong>Sensibilità del test</strong> (<span class="math inline">\(P(Test+ \mid HIV)\)</span>): 95% (0.95), ovvero la probabilità che il test sia positivo quando la persona ha l’HIV.</li>
<li>
<strong>Specificità del test</strong> (<span class="math inline">\(P(Test- \mid \neg HIV)\)</span>): 99.28% (0.9928), ovvero la probabilità che il test sia negativo quando la persona non ha l’HIV.</li>
</ul>
<p>Utilizziamo il <strong>teorema di Bayes</strong> per calcolare <span class="math inline">\(P(HIV \mid Test+)\)</span>:</p>
<p><span class="math display">\[
P(HIV \mid Test+) = \frac{P(Test+ \mid HIV) \cdot P(HIV)}{P(Test+)},
\]</span></p>
<p>dove il denominatore <span class="math inline">\(P(Test+)\)</span> rappresenta la probabilità complessiva di un test positivo, somma di:</p>
<ul>
<li>
<strong>Veri positivi</strong>: <span class="math inline">\(P(Test+ \mid HIV) \cdot P(HIV)\)</span>,</li>
<li>
<strong>Falsi positivi</strong>: <span class="math inline">\(P(Test+ \mid \neg HIV) \cdot P(\neg HIV)\)</span>.</li>
</ul>
<p>Con <span class="math inline">\(P(Test+ \mid \neg HIV) = 1 - P(Test- \mid \neg HIV) = 1 - 0.9928 = 0.0072\)</span>, e <span class="math inline">\(P(\neg HIV) = 1 - P(HIV) = 0.997\)</span>, possiamo calcolare:</p>
<p><span class="math display">\[
P(Test+) = (0.95 \cdot 0.003) + (0.0072 \cdot 0.997) \approx 0.010027.
\]</span></p>
<p>Inserendo i valori nella formula di Bayes:</p>
<p><span class="math display">\[
P(HIV \mid Test+) = \frac{0.95 \cdot 0.003}{0.010027} \approx 0.2844 \quad (28.44\%).
\]</span></p>
<p>Un primo test positivo aumenta quindi la probabilità di avere l’HIV al <strong>28.44%</strong>.</p>
<p>Dopo un primo test positivo, la probabilità di avere l’HIV è aumentata al 28.44%. Consideriamo ora l’effetto di un <strong>secondo test positivo</strong> e calcoliamo la probabilità aggiornata di avere l’HIV.</p>
<p>La probabilità di ottenere un secondo test positivo (<span class="math inline">\(P(\text{Secondo Test+})\)</span>) si calcola considerando due scenari:</p>
<ol type="1">
<li>
<strong>La persona ha l’HIV</strong>:
<ul>
<li>Probabilità: <span class="math inline">\(P(HIV \mid Test+) = 0.2844\)</span>,</li>
<li>Sensibilità del test: <span class="math inline">\(P(Test+ \mid HIV) = 0.95\)</span>.</li>
</ul>
</li>
<li>
<strong>La persona non ha l’HIV</strong>:
<ul>
<li>Probabilità: <span class="math inline">\(P(\neg HIV \mid Test+) = 1 - P(HIV \mid Test+) = 0.7156\)</span>,</li>
<li>Tasso di falsi positivi: <span class="math inline">\(P(Test+ \mid \neg HIV) = 0.0072\)</span>.</li>
</ul>
</li>
</ol>
<p>La probabilità totale è data da:</p>
<p><span class="math display">\[
P(\text{Secondo Test+}) = P(Test+ \mid HIV) \cdot P(HIV \mid Test+) + P(Test+ \mid \neg HIV) \cdot P(\neg HIV \mid Test+).
\]</span></p>
<p>Sostituendo i valori:</p>
<p><span class="math display">\[
P(\text{Secondo Test+}) = (0.95 \cdot 0.2844) + (0.0072 \cdot 0.7156) \approx 0.2753.
\]</span></p>
<p>Aggiorniamo la probabilità di avere l’HIV dopo un secondo test positivo usando nuovamente il teorema di Bayes:</p>
<p><span class="math display">\[
P(HIV \mid \text{Secondo Test+}) = \frac{P(Test+ \mid HIV) \cdot P(HIV \mid Test+)}{P(\text{Secondo Test+})}.
\]</span></p>
<p>Sostituendo i valori:</p>
<p><span class="math display">\[
P(HIV \mid \text{Secondo Test+}) = \frac{0.95 \cdot 0.2844}{0.2753} \approx 0.981 \quad (98.1\%).
\]</span></p>
<p>L’esempio presentato da <span class="citation" data-cites="petersen2024principles">Petersen (<a href="../../99-references.html#ref-petersen2024principles" role="doc-biblioref">2024</a>)</span> è rilevante per il problema generale della predizione, in quanto illustra come il ragionamento bayesiano consenta di integrare informazioni iniziali e successive per migliorare la precisione delle stime. In particolare, i risultati evidenziano tre aspetti fondamentali:</p>
<ol type="1">
<li><p><strong>Tasso di base come punto di partenza cruciale</strong>: La probabilità iniziale (prior) di avere l’HIV, pari allo 0.3%, sottolinea quanto sia importante considerare il contesto epidemiologico e demografico nella fase iniziale della predizione. Questo valore guida l’intero processo di aggiornamento e mostra che una condizione rara richiede prove forti per modificarne la probabilità.</p></li>
<li><p><strong>Aggiornamento incrementale delle probabilità</strong>: Il passaggio da una probabilità del 28.44% dopo un primo test positivo a una probabilità del 98.1% dopo un secondo test positivo evidenzia la potenza del teorema di Bayes nel combinare evidenze successive. Ogni risultato positivo aggiunge informazioni che riducono l’incertezza iniziale, migliorando progressivamente la qualità della predizione.</p></li>
<li><p><strong>Valore aggiunto dei test ripetuti</strong>: L’analisi dimostra che l’efficacia diagnostica cresce con l’accumularsi di evidenze. Test ripetuti consentono di discriminare meglio tra casi veri positivi e falsi positivi, fornendo stime più affidabili e utili per decisioni cliniche.</p></li>
</ol>
<p>Questi risultati mettono in luce l’importanza del ragionamento bayesiano non solo per valutare la probabilità di una condizione medica, ma anche per affrontare una vasta gamma di problemi di predizione in cui l’incertezza iniziale può essere ridotta integrando dati nuovi. L’approccio evidenzia come sia possibile arrivare a conclusioni robuste anche in contesti caratterizzati da bassi tassi di base e test diagnostici non perfetti.</p>
</section><section id="accuratezza-delle-predizioni" class="level2" data-number="83.3"><h2 data-number="83.3" class="anchored" data-anchor-id="accuratezza-delle-predizioni">
<span class="header-section-number">83.3</span> Accuratezza delle Predizioni</h2>
<p>Dopo l’introduzione sull’uso del teorema di Bayes per la predizione, <span class="citation" data-cites="petersen2024principles">Petersen (<a href="../../99-references.html#ref-petersen2024principles" role="doc-biblioref">2024</a>)</span> affronta il tema delle predizioni con una tabella 2 × 2. Per spiegare questo caso, <span class="citation" data-cites="petersen2024principles">Petersen (<a href="../../99-references.html#ref-petersen2024principles" role="doc-biblioref">2024</a>)</span> presenta un esempio adattato da Meehl &amp; Rosen (1955).</p>
<p>Immaginiamo che l’esercito americano utilizzi un test per escludere i candidati con basse probabilità di completare l’addestramento di base. Per analizzare l’accuratezza delle predizioni effettuate, possiamo utilizzare una <strong>matrice di confusione</strong>, che confronta le predizioni del test con i risultati reali.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 14%">
<col style="width: 20%">
</colgroup>
<thead><tr class="header">
<th><strong>Decisione (Predizione)</strong></th>
<th><strong>Adattamento Effettivo (Scarso)</strong></th>
<th><strong>Adattamento Effettivo (Buono)</strong></th>
<th><strong>Totale Predetto</strong></th>
<th><strong>Rapporto di Selezione (SR)</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Escludere</strong></td>
<td>TP = 86 (0.043)</td>
<td>FP = 422 (0.211)</td>
<td>508</td>
<td>SR = 0.254</td>
</tr>
<tr class="even">
<td><strong>Trattenere</strong></td>
<td>FN = 14 (0.007)</td>
<td>TN = 1.478 (0.739)</td>
<td>1,492</td>
<td>1 − SR = 0.746</td>
</tr>
<tr class="odd">
<td><strong>Totale Effettivo</strong></td>
<td>100</td>
<td>1,900</td>
<td>N = 2,000</td>
<td></td>
</tr>
<tr class="even">
<td><strong>Tasso di Base (BR)</strong></td>
<td>BR = 0.05</td>
<td>1 − BR = 0.95</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<section id="la-matrice-di-confusione" class="level3" data-number="83.3.1"><h3 data-number="83.3.1" class="anchored" data-anchor-id="la-matrice-di-confusione">
<span class="header-section-number">83.3.1</span> La Matrice di Confusione</h3>
<p>La <strong>matrice di confusione</strong> è uno strumento che mette in relazione le predizioni di un modello con i risultati osservati. Nel caso di una predizione binaria (es. sì/no o positivo/negativo), la matrice è organizzata in quattro categorie:</p>
<ol type="1">
<li>
<strong>Vero Positivo (TP)</strong>: La predizione corretta che identifica una persona con la caratteristica (es. cattivo adattamento).</li>
<li>
<strong>Vero Negativo (TN)</strong>: La predizione corretta che identifica una persona senza la caratteristica.</li>
<li>
<strong>Falso Positivo (FP)</strong>: L’errore in cui si predice la presenza della caratteristica quando in realtà non è presente.</li>
<li>
<strong>Falso Negativo (FN)</strong>: L’errore in cui si predice l’assenza della caratteristica quando in realtà è presente.</li>
</ol>
<p>Questi quattro risultati consentono di valutare l’accuratezza di un modello.</p>
</section><section id="tassi-marginali-e-indicatori-chiave" class="level3" data-number="83.3.2"><h3 data-number="83.3.2" class="anchored" data-anchor-id="tassi-marginali-e-indicatori-chiave">
<span class="header-section-number">83.3.2</span> Tassi Marginali e Indicatori Chiave</h3>
<p>Dalla matrice di confusione possiamo calcolare alcuni tassi e indicatori utili:</p>
<ol type="1">
<li><p><strong>Tasso di Base (BR)</strong>: La probabilità che una persona abbia la caratteristica di interesse. Ad esempio: <span class="math display">\[
BR = \frac{FN + TP}{N} = \frac{100}{2000} = 0.05
\]</span> Ciò significa che solo il 5% dei candidati ha un cattivo adattamento.</p></li>
<li><p><strong>Rapporto di Selezione (SR)</strong>: La probabilità di essere esclusi dal programma: <span class="math display">\[
SR = \frac{TP + FP}{N} = \frac{508}{2000} = 0.254
\]</span> In questo caso, il 25,4% dei candidati è stato escluso.</p></li>
<li><p><strong>Percentuale di Accuratezza</strong>: Rappresenta la proporzione di predizioni corrette sul totale: <span class="math display">\[
\text{Accuratezza} = 100 \times \frac{TP + TN}{N} = 100 \times \frac{86 + 1478}{2000} = 78\%
\]</span></p></li>
<li><p><strong>Accuratezza per Caso</strong>: Misura la precisione che si otterrebbe effettuando predizioni casuali basate solo sulle probabilità marginali (BR e SR). Per esempio: <span class="math display">\[
P(TP) = BR \times SR = 0.05 \times 0.254 = 0.0127
\]</span> <span class="math display">\[
P(TN) = (1 − BR) \times (1 − SR) = 0.95 \times 0.746 = 0.7087
\]</span> <span class="math display">\[
\text{Accuratezza per Caso} = P(TP) + P(TN) = 0.0127 + 0.7087 = 0.7214 \, (72,14\%)
\]</span></p></li>
</ol>
<p>Confrontando il 78% di accuratezza del modello con il 72.14% ottenibile per caso, il modello fornisce un miglioramento del 6%.</p>
</section><section id="limportanza-del-tasso-di-base" class="level3" data-number="83.3.3"><h3 data-number="83.3.3" class="anchored" data-anchor-id="limportanza-del-tasso-di-base">
<span class="header-section-number">83.3.3</span> L’Importanza del Tasso di Base</h3>
<p>Quando il <strong>tasso di base</strong> è molto basso (come in questo caso, BR = 0.05), l’accuratezza complessiva può essere ingannevole. Se predicessimo che nessuno ha un cattivo adattamento, otterremmo un’accuratezza del 95%, ma il modello non identificherebbe alcun caso di cattivo adattamento.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 29%">
<col style="width: 29%">
<col style="width: 17%">
</colgroup>
<thead><tr class="header">
<th><strong>Decisione (Predizione)</strong></th>
<th><strong>Adattamento Effettivo (Scarso)</strong></th>
<th><strong>Adattamento Effettivo (Buono)</strong></th>
<th><strong>Totale Predetto</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Escludere</strong></td>
<td>TP = 0</td>
<td>FP = 0</td>
<td>0</td>
</tr>
<tr class="even">
<td><strong>Trattenere</strong></td>
<td>FN = 100</td>
<td>TN = 1,900</td>
<td>2,000</td>
</tr>
<tr class="odd">
<td><strong>Totale Effettivo</strong></td>
<td>100</td>
<td>1,900</td>
<td>N = 2,000</td>
</tr>
</tbody>
</table>
<p>In questo caso, l’accuratezza complessiva sarebbe: <span class="math display">\[
P(\text{Accuratezza}) = \frac{TP + TN}{N} = \frac{0 + 1900}{2000} = 95\%.
\]</span></p>
<p>Questo esempio evidenzia che un’elevata accuratezza complessiva non garantisce un buon modello, specialmente quando il tasso di base è sbilanciato.</p>
<p>In conclusione, l’analisi di una matrice di confusione richiede attenzione ai tassi di base e agli errori, poiché l’accuratezza globale può essere fuorviante. È essenziale confrontare il valore del modello con ciò che si otterrebbe per caso o con strategie alternative, come basarsi solo sul tasso di base. Inoltre, occorre considerare il peso relativo degli errori (falsi positivi e falsi negativi) in base al contesto applicativo. Questi aspetti saranno discussi nel prossimo paragrafo.</p>
</section><section id="diversi-tipi-di-errori-e-i-loro-costi" class="level3" data-number="83.3.4"><h3 data-number="83.3.4" class="anchored" data-anchor-id="diversi-tipi-di-errori-e-i-loro-costi">
<span class="header-section-number">83.3.4</span> Diversi Tipi di Errori e i loro Costi</h3>
<p>In un processo di classificazione, non tutti gli errori hanno lo stesso costo. Esistono due tipi principali di errori: i <em>falsi positivi</em> e i <em>falsi negativi</em>, ciascuno con implicazioni diverse che dipendono dal contesto della predizione.</p>
<p>Spesso, l’accuratezza complessiva può essere aumentata affidandosi semplicemente al <em>tasso di base</em>, ma in molte situazioni può essere preferibile utilizzare uno strumento di screening, anche a costo di una minore <em>accuratezza complessiva</em>, se ciò consente di minimizzare errori specifici che hanno costi elevati. Ad esempio:</p>
<ol type="1">
<li><p><strong>Screening medico</strong>: Consideriamo uno strumento di screening per l’HIV. I <em>falsi positivi</em> (classificare erroneamente una persona come a rischio) comportano costi come la necessità di test di conferma e, talvolta, ansia temporanea per l’individuo. Tuttavia, un <em>falso negativo</em> (non identificare una persona effettivamente a rischio) ha costi molto più alti, poiché potrebbe portare a un mancato intervento precoce, con conseguenze gravi per la salute. In questo caso, i costi associati ai falsi negativi superano di gran lunga quelli dei falsi positivi, rendendo lo screening preferibile nonostante una diminuzione dell’accuratezza complessiva.</p></li>
<li><p><strong>Selezione del personale in situazioni di rischio</strong>: La CIA, ad esempio, ha utilizzato strumenti di selezione per identificare potenziali spie durante periodi di guerra. Un <em>falso positivo</em> in questo contesto (considerare erroneamente una persona come una spia) potrebbe risultare nell’esclusione di un candidato innocente. Un <em>falso negativo</em> (assumere una persona che è effettivamente una spia) comporta rischi molto più gravi, rendendo cruciale l’identificazione corretta delle spie, anche a costo di più <em>falsi positivi</em>.</p></li>
</ol>
<p>Il modo in cui i costi degli errori vengono valutati dipende fortemente dal contesto. Alcuni potenziali costi dei <em>falsi positivi</em> includono trattamenti medici non necessari o il rischio di incarcerare una persona innocente. Al contrario, i <em>falsi negativi</em> possono portare al rilascio di una persona pericolosa, alla mancata individuazione di una malattia grave, o al mancato riconoscimento di un rischio imminente.</p>
</section><section id="importanza-del-rapporto-di-selezione-e-del-tasso-di-base" class="level3" data-number="83.3.5"><h3 data-number="83.3.5" class="anchored" data-anchor-id="importanza-del-rapporto-di-selezione-e-del-tasso-di-base">
<span class="header-section-number">83.3.5</span> Importanza del Rapporto di Selezione e del Tasso di Base</h3>
<p>Il costo degli errori può variare a seconda di come si imposta il <em>rapporto di selezione</em> (cioè, quanto rigorosamente si applica il criterio per accettare o escludere un individuo). La scelta di un rapporto di selezione meno restrittivo o più restrittivo influisce sulla probabilità di incorrere in <em>falsi positivi</em> e <em>falsi negativi</em> e può dipendere dal contesto e dai costi associati agli errori.</p>
<ul>
<li>
<strong>Criterio meno rigido</strong>: Se escludere candidati è costoso, ad esempio quando si ha la necessità di assumere molte persone, potrebbe essere più utile un criterio di selezione permissivo, che accetta anche persone con un rischio potenziale.</li>
<li>
<strong>Criterio più rigido</strong>: In contesti in cui non è necessario accettare molti individui, si può adottare un criterio di selezione più rigido per ridurre i rischi, scartando un numero maggiore di candidati sospetti.</li>
</ul>
<p>Quando il <em>rapporto di selezione</em> differisce dal <em>tasso di base</em> degli esiti negativi effettivi, inevitabilmente si generano errori:</p>
<ul>
<li>Se, ad esempio, il rapporto di selezione prevede di escludere il 25% dei candidati, ma solo il 5% risulta effettivamente “non idoneo,” il risultato sarà un numero elevato di <em>falsi positivi</em>.</li>
<li>D’altro canto, se si esclude solo l’1% dei candidati mentre il tasso di non idoneità è del 5%, si finirà per includere molti <em>falsi negativi</em>.</li>
</ul></section><section id="predizioni-e-affidabilità-in-condizioni-di-basso-tasso-di-base" class="level3" data-number="83.3.6"><h3 data-number="83.3.6" class="anchored" data-anchor-id="predizioni-e-affidabilità-in-condizioni-di-basso-tasso-di-base">
<span class="header-section-number">83.3.6</span> Predizioni e Affidabilità in Condizioni di Basso Tasso di Base</h3>
<p>Fare predizioni accurate diventa particolarmente complesso quando il tasso di base è basso, come nel caso di eventi rari (ad esempio, il suicidio). In questi casi, il numero di casi positivi reali è molto ridotto, rendendo difficile identificare correttamente i pochi eventi positivi senza generare numerosi falsi positivi o falsi negativi.</p>
<p>Questa difficoltà può essere compresa in relazione alla teoria classica dei test, che definisce l’affidabilità come il rapporto tra la varianza del punteggio vero e la varianza del punteggio osservato. Con un tasso di base molto basso, la varianza del punteggio vero è ridotta, il che abbassa l’affidabilità della misura e rende più complessa una predizione accurata.</p>
</section><section id="sensibilità-specificità-ppv-e-npv" class="level3" data-number="83.3.7"><h3 data-number="83.3.7" class="anchored" data-anchor-id="sensibilità-specificità-ppv-e-npv">
<span class="header-section-number">83.3.7</span> Sensibilità, Specificità, PPV e NPV</h3>
<p>Come abbiamo visto, la <em>percentuale di accuratezza</em> da sola non è sufficiente per valutare l’efficacia di un modello, poiché è molto influenzata dai <em>tassi di base</em>. Ad esempio, se il tasso di base è basso, potremmo ottenere un’alta percentuale di accuratezza semplicemente affermando che nessuno ha la condizione; se è alto, affermando che tutti ce l’hanno. Perciò, è essenziale considerare altre metriche di accuratezza, come <em>sensibilità</em> (SN), <em>specificità</em> (SP), <em>valore predittivo positivo</em> (PPV) e <em>valore predittivo negativo</em> (NPV).</p>
<p>Queste metriche, che si possono calcolare dalla <em>matrice di confusione</em>, ci aiutano a valutare se il modello è efficace nel rilevare la condizione senza includere erroneamente i casi negativi. Analizziamole in dettaglio:</p>
<ul>
<li>
<p><strong>Sensibilità</strong> (SN): indica la capacità del test di identificare correttamente i veri positivi, cioè le persone con la condizione. Si calcola come la proporzione di veri positivi (<span class="math inline">\(\text{TP}\)</span>) rispetto al totale di persone con la condizione (<span class="math inline">\(\text{TP} + \text{FN}\)</span>):</p>
<p><span class="math display">\[
\frac{\text{TP}}{\text{TP} + \text{FN}} = \frac{86}{86 + 14} = 0.86
\]</span></p>
</li>
<li>
<p><strong>Specificità</strong> (SP): misura la capacità del test di identificare correttamente i veri negativi, ossia le persone senza la condizione. Si calcola come la proporzione di veri negativi (<span class="math inline">\(\text{TN}\)</span>) rispetto al totale di persone senza la condizione (<span class="math inline">\(\text{TN} + \text{FP}\)</span>):</p>
<p><span class="math display">\[
\frac{\text{TN}}{\text{TN} + \text{FP}} = \frac{1,478}{1,478 + 422} = 0.78
\]</span></p>
</li>
<li>
<p><strong>Valore Predittivo Positivo</strong> (PPV): indica la probabilità che una persona classificata come positiva abbia effettivamente la condizione. Si calcola come la proporzione di veri positivi (<span class="math inline">\(\text{TP}\)</span>) sul totale dei positivi stimati (<span class="math inline">\(\text{TP} + \text{FP}\)</span>):</p>
<p><span class="math display">\[
\frac{\text{TP}}{\text{TP} + \text{FP}} = \frac{86}{86 + 422} = 0.17
\]</span></p>
</li>
<li>
<p><strong>Valore Predittivo Negativo</strong> (NPV): rappresenta la probabilità che una persona classificata come negativa non abbia effettivamente la condizione. Si calcola come la proporzione di veri negativi (<span class="math inline">\(\text{TN}\)</span>) sul totale dei negativi stimati (<span class="math inline">\(\text{TN} + \text{FN}\)</span>):</p>
<p><span class="math display">\[
\frac{\text{TN}}{\text{TN} + \text{FN}} = \frac{1,478}{1,478 + 14} = 0.99
\]</span></p>
</li>
</ul>
<p>Ogni misura è espressa come una proporzione, variando da 0 a 1, dove valori più alti indicano una maggiore accuratezza per ciascun aspetto specifico. Usando queste metriche otteniamo un quadro dettagliato dell’efficacia dello strumento a un determinato cutoff.</p>
<p>In questo caso, il nostro strumento mostra:</p>
<ul>
<li>
<strong>Alta sensibilità</strong> (0.86): è efficace nel rilevare chi ha la condizione.</li>
<li>
<strong>Bassa specificità</strong> (0.78): classifica erroneamente come positivi molti casi che non hanno la condizione.</li>
<li>
<strong>Basso PPV</strong> (0.17): la maggior parte dei casi classificati come positivi sono in realtà negativi, indicando una frequenza elevata di falsi positivi.</li>
<li>
<strong>Alto NPV</strong> (0.99): quasi tutti i casi classificati come negativi non hanno la condizione.</li>
</ul>
<p>Quindi, pur avendo una buona capacità di rilevare i positivi (alta sensibilità), il modello è meno efficace nel limitare i falsi positivi (basso PPV). Questo potrebbe essere accettabile se l’obiettivo è identificare tutti i potenziali casi positivi, anche a costo di includere molti falsi positivi, ma potrebbe non essere ideale se il costo degli errori di falsa positività è elevato.</p>
</section></section><section id="stime-di-accuratezza-e-cutoff" class="level2" data-number="83.4"><h2 data-number="83.4" class="anchored" data-anchor-id="stime-di-accuratezza-e-cutoff">
<span class="header-section-number">83.4</span> Stime di Accuratezza e Cutoff</h2>
<p>Sensibilità, specificità, PPV e NPV variano in base al cutoff (ovvero, la soglia) per la classificazione. Consideriamo il seguente esempio. Degli alieni visitano la Terra e sviluppano un test per determinare se una bacca è commestibile o non commestibile.</p>
<div class="cell" data-layout-align="center" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sampleSize</span> <span class="op">&lt;-</span> <span class="fl">1000</span></span>
<span></span>
<span><span class="va">edibleScores</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">sampleSize</span>, <span class="fl">50</span>, <span class="fl">15</span><span class="op">)</span></span>
<span><span class="va">inedibleScores</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">sampleSize</span>, <span class="fl">100</span>, <span class="fl">15</span><span class="op">)</span></span>
<span></span>
<span><span class="va">edibleData</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>score <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">edibleScores</span>, <span class="va">inedibleScores</span><span class="op">)</span>, type <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"edible"</span>, <span class="va">sampleSize</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"inedible"</span>, <span class="va">sampleSize</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">cutoff</span> <span class="op">&lt;-</span> <span class="fl">75</span></span>
<span></span>
<span><span class="va">hist_edible</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/density.html">density</a></span><span class="op">(</span><span class="va">edibleScores</span>, from <span class="op">=</span> <span class="fl">0</span>, to <span class="op">=</span> <span class="fl">150</span><span class="op">)</span> <span class="op">%$%</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, y <span class="op">=</span> <span class="va">y</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>    <span class="fu">mutate</span><span class="op">(</span>area <span class="op">=</span> <span class="va">x</span> <span class="op">&gt;=</span> <span class="va">cutoff</span><span class="op">)</span></span>
<span></span>
<span><span class="va">hist_edible</span><span class="op">$</span><span class="va">type</span><span class="op">[</span><span class="va">hist_edible</span><span class="op">$</span><span class="va">area</span> <span class="op">==</span> <span class="cn">TRUE</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="st">"edible_FP"</span></span>
<span><span class="va">hist_edible</span><span class="op">$</span><span class="va">type</span><span class="op">[</span><span class="va">hist_edible</span><span class="op">$</span><span class="va">area</span> <span class="op">==</span> <span class="cn">FALSE</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="st">"edible_TN"</span></span>
<span></span>
<span><span class="va">hist_inedible</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/density.html">density</a></span><span class="op">(</span><span class="va">inedibleScores</span>, from <span class="op">=</span> <span class="fl">0</span>, to <span class="op">=</span> <span class="fl">150</span><span class="op">)</span> <span class="op">%$%</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, y <span class="op">=</span> <span class="va">y</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>    <span class="fu">mutate</span><span class="op">(</span>area <span class="op">=</span> <span class="va">x</span> <span class="op">&lt;</span> <span class="va">cutoff</span><span class="op">)</span></span>
<span></span>
<span><span class="va">hist_inedible</span><span class="op">$</span><span class="va">type</span><span class="op">[</span><span class="va">hist_inedible</span><span class="op">$</span><span class="va">area</span> <span class="op">==</span> <span class="cn">TRUE</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="st">"inedible_FN"</span></span>
<span><span class="va">hist_inedible</span><span class="op">$</span><span class="va">type</span><span class="op">[</span><span class="va">hist_inedible</span><span class="op">$</span><span class="va">area</span> <span class="op">==</span> <span class="cn">FALSE</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="st">"inedible_TP"</span></span>
<span></span>
<span><span class="va">density_data</span> <span class="op">&lt;-</span> <span class="fu">bind_rows</span><span class="op">(</span><span class="va">hist_edible</span>, <span class="va">hist_inedible</span><span class="op">)</span></span>
<span></span>
<span><span class="va">density_data</span><span class="op">$</span><span class="va">type</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">density_data</span><span class="op">$</span><span class="va">type</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"edible_TN"</span>, <span class="st">"inedible_TP"</span>, <span class="st">"edible_FP"</span>, <span class="st">"inedible_FN"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>La figura successiva mostra le distribuzioni dei punteggi in base al tipo di bacca. Si può notare come ci sono due distribuzioni distinte, ma con una certa sovrapposizione. Pertanto, qualsiasi cutoff selezionato comporterà almeno alcune classificazioni errate. L’entità della sovrapposizione delle distribuzioni riflette la quantità di errore di misurazione dello strumento rispetto alla caratteristica di interesse.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">edibleData</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">score</span>, ymin <span class="op">=</span> <span class="fl">0</span>, fill <span class="op">=</span> <span class="va">type</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_density</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">scale_fill_manual</span><span class="op">(</span></span>
<span>      name <span class="op">=</span> <span class="st">"Tipo di Bacca"</span>, values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu">viridis</span><span class="op">(</span><span class="fl">2</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="fu">viridis</span><span class="op">(</span><span class="fl">2</span><span class="op">)</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span></span>
<span>    <span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">scale_y_continuous</span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Frequenza"</span><span class="op">)</span> </span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="01_prediction_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>La figura successiva mostra le distribuzioni dei punteggi in base al tipo di bacca con un cutoff. La linea rossa indica il cutoff: il livello al di sopra del quale le bacche vengono classificate come non commestibili. Ci sono errori su entrambi i lati del cutoff. Sotto il cutoff, ci sono dei falsi negativi (blu): bacche non commestibili erroneamente classificate come commestibili. Sopra il cutoff, ci sono dei falsi positivi (verde): bacche commestibili erroneamente classificate come non commestibili. I costi dei falsi negativi potrebbero includere malattia o morte derivanti dal consumo di bacche non commestibili, mentre i costi dei falsi positivi potrebbero includere maggiore tempo per trovare cibo, insufficienza di cibo e fame.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">density_data</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, ymin <span class="op">=</span> <span class="fl">0</span>, ymax <span class="op">=</span> <span class="va">y</span>, fill <span class="op">=</span> <span class="va">type</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_ribbon</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">scale_fill_manual</span><span class="op">(</span></span>
<span>        name <span class="op">=</span> <span class="st">"Tipo di Bacca"</span>,</span>
<span>        values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu">viridis</span><span class="op">(</span><span class="fl">4</span><span class="op">)</span><span class="op">[</span><span class="fl">4</span><span class="op">]</span>, <span class="fu">viridis</span><span class="op">(</span><span class="fl">4</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="fu">viridis</span><span class="op">(</span><span class="fl">4</span><span class="op">)</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span>, <span class="fu">viridis</span><span class="op">(</span><span class="fl">4</span><span class="op">)</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span>,</span>
<span>        breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"edible_TN"</span>, <span class="st">"inedible_TP"</span>, <span class="st">"edible_FP"</span>, <span class="st">"inedible_FN"</span><span class="op">)</span>,</span>
<span>        labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>          <span class="st">"Commestibile: TN"</span>, <span class="st">"Non Commestibile: TP"</span>, </span>
<span>          <span class="st">"Commestibile: FP"</span>, <span class="st">"Non Commestibile: FN"</span><span class="op">)</span></span>
<span>    <span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_line</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="va">y</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_vline</span><span class="op">(</span>xintercept <span class="op">=</span> <span class="va">cutoff</span>, color <span class="op">=</span> <span class="st">"red"</span>, linewidth <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">scale_x_continuous</span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Punteggio"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">scale_y_continuous</span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Frequenza"</span><span class="op">)</span> </span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="01_prediction_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>A seconda dei nostri obiettivi di valutazione, potremmo voler usare un diverso rapporto di selezione modificando il cutoff. La Figura mostra le distribuzioni dei punteggi quando si aumenta il cutoff. Ora ci sono più falsi negativi (blu) e meno falsi positivi (verde). Se alziamo il cutoff per essere più conservativi, il numero di falsi negativi aumenta, mentre il numero di falsi positivi diminuisce. Di conseguenza, aumentando il cutoff, la sensibilità e il valore predittivo negativo (NPV) diminuiscono, mentre la specificità e il valore predittivo positivo (PPV) aumentano. Un cutoff più alto potrebbe essere ottimale se i costi dei falsi positivi sono considerati superiori a quelli dei falsi negativi. Ad esempio, se gli alieni non possono rischiare di mangiare bacche non commestibili perché sono fatali, e ci sono abbastanza bacche commestibili per nutrire la colonia aliena.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Raise the cutoff</span></span>
<span><span class="va">cutoff</span> <span class="op">&lt;-</span> <span class="fl">85</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">density_data</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, ymin <span class="op">=</span> <span class="fl">0</span>, ymax <span class="op">=</span> <span class="va">y</span>, fill <span class="op">=</span> <span class="va">type</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_ribbon</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">scale_fill_manual</span><span class="op">(</span></span>
<span>        name <span class="op">=</span> <span class="st">"Tipo di Bacca"</span>,</span>
<span>        values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu">viridis</span><span class="op">(</span><span class="fl">4</span><span class="op">)</span><span class="op">[</span><span class="fl">4</span><span class="op">]</span>, <span class="fu">viridis</span><span class="op">(</span><span class="fl">4</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="fu">viridis</span><span class="op">(</span><span class="fl">4</span><span class="op">)</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span>, <span class="fu">viridis</span><span class="op">(</span><span class="fl">4</span><span class="op">)</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span>,</span>
<span>        breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"edible_TN"</span>, <span class="st">"inedible_TP"</span>, <span class="st">"edible_FP"</span>, <span class="st">"inedible_FN"</span><span class="op">)</span>,</span>
<span>        labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>          <span class="st">"Commestibile: TN"</span>, <span class="st">"Non Commestibile: TP"</span>, </span>
<span>          <span class="st">"Commestibile: FP"</span>, <span class="st">"Non Commestibile: FN"</span><span class="op">)</span></span>
<span>    <span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_line</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="va">y</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_vline</span><span class="op">(</span>xintercept <span class="op">=</span> <span class="va">cutoff</span>, color <span class="op">=</span> <span class="st">"red"</span>, linewidth <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">scale_x_continuous</span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Punteggio"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">scale_y_continuous</span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Frequenza"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">theme</span><span class="op">(</span></span>
<span>        axis.text.y <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,</span>
<span>        axis.ticks.y <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="01_prediction_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>In alternativa, possiamo abbassare il cutoff per essere più liberali. La Figura seguente mostra le distribuzioni dei punteggi quando abbassiamo il cutoff. Ora ci sono meno falsi negativi (blu) e più falsi positivi (verde). Abbassando il cutoff, la sensibilità e il NPV aumentano, mentre la specificità e il PPV diminuiscono. Un cutoff più basso potrebbe essere ottimale se i costi dei falsi negativi sono considerati superiori a quelli dei falsi positivi. Ad esempio, se gli alieni non possono rischiare di perdere bacche commestibili perché sono scarse, e mangiare bacche non commestibili comporta solo disagi temporanei.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Lower the cutoff</span></span>
<span><span class="va">cutoff</span> <span class="op">&lt;-</span> <span class="fl">65</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">density_data</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, ymin <span class="op">=</span> <span class="fl">0</span>, ymax <span class="op">=</span> <span class="va">y</span>, fill <span class="op">=</span> <span class="va">type</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_ribbon</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">scale_fill_manual</span><span class="op">(</span></span>
<span>        name <span class="op">=</span> <span class="st">"Tipo di Bacca"</span>,</span>
<span>        values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu">viridis</span><span class="op">(</span><span class="fl">4</span><span class="op">)</span><span class="op">[</span><span class="fl">4</span><span class="op">]</span>, <span class="fu">viridis</span><span class="op">(</span><span class="fl">4</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="fu">viridis</span><span class="op">(</span><span class="fl">4</span><span class="op">)</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span>, <span class="fu">viridis</span><span class="op">(</span><span class="fl">4</span><span class="op">)</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span>,</span>
<span>        breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"edible_TN"</span>, <span class="st">"inedible_TP"</span>, <span class="st">"edible_FP"</span>, <span class="st">"inedible_FN"</span><span class="op">)</span>,</span>
<span>        labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>          <span class="st">"Commestibile: TN"</span>, <span class="st">"Non Commestibile: TP"</span>, </span>
<span>          <span class="st">"Commestibile: FP"</span>, <span class="st">"Non Commestibile: FN"</span><span class="op">)</span></span>
<span>    <span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_line</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="va">y</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_vline</span><span class="op">(</span>xintercept <span class="op">=</span> <span class="va">cutoff</span>, color <span class="op">=</span> <span class="st">"red"</span>, linewidth <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">scale_x_continuous</span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Punteggio"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">scale_y_continuous</span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Frequenza"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">theme</span><span class="op">(</span></span>
<span>        axis.text.y <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,</span>
<span>        axis.ticks.y <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="01_prediction_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>In sintesi, sensibilità e specificità variano in base al cutoff utilizzato per la classificazione. Se aumentiamo il cutoff, la specificità e il PPV aumentano, mentre la sensibilità e il NPV diminuiscono. Se abbassiamo il cutoff, la sensibilità e il NPV aumentano, mentre la specificità e il PPV diminuiscono. Pertanto, il cutoff ottimale dipende dai costi associati ai falsi negativi e ai falsi positivi. Se i falsi negativi sono più costosi, dovremmo impostare un cutoff basso; se i falsi positivi sono più costosi, dovremmo impostare un cutoff alto.</p>
</section><section id="teoria-della-detezione-del-segnale" class="level2" data-number="83.5"><h2 data-number="83.5" class="anchored" data-anchor-id="teoria-della-detezione-del-segnale">
<span class="header-section-number">83.5</span> Teoria della Detezione del Segnale</h2>
<p>La <em>teoria della detezione del segnale</em> (Signal Detection Theory, SDT) è un approccio probabilistico che descrive la capacità di rilevare uno stimolo target (segnale) in mezzo a stimoli non target (rumore). Sviluppata durante la Seconda Guerra Mondiale per migliorare le prestazioni di radar e sonar, distingue tra due concetti fondamentali: <strong>sensibilità</strong> e <strong>bias</strong>.</p>
<ul>
<li>
<strong>Sensibilità</strong>: misura la capacità di distinguere tra segnale e rumore.</li>
<li>
<strong>Bias</strong>: rappresenta la tendenza a sovrastimare o sottostimare la probabilità di un segnale.</li>
</ul>
<p>Originariamente utilizzata per selezionare e addestrare operatori radar, la SDT trova oggi applicazione in vari campi, come la medicina (es. rilevamento di tumori) e la psicologia. In quest’ultima, è stata utilizzata per studiare percezioni sociali, evidenziando differenze sistematiche nella sensibilità e nel bias.</p>
<p>Le principali metriche della SDT includono <strong><span class="math inline">\(d'\)</span></strong> per la sensibilità e <strong><span class="math inline">\(\beta\)</span></strong>, <strong><span class="math inline">\(c\)</span></strong>, e <strong><span class="math inline">\(b\)</span></strong> per il bias, utili per quantificare precisione e tendenze decisionali.</p>
</section><section id="curva-roc-receiver-operating-characteristic" class="level2" data-number="83.6"><h2 data-number="83.6" class="anchored" data-anchor-id="curva-roc-receiver-operating-characteristic">
<span class="header-section-number">83.6</span> Curva ROC (Receiver Operating Characteristic)</h2>
<p>La curva ROC è un grafico che rappresenta la capacità di un test o modello di discriminare tra due classi (es. positivi e negativi). È costruita tracciando il <strong>tasso di veri positivi (sensibilità)</strong> sull’asse y e il <strong>tasso di falsi positivi (1-specificità)</strong> sull’asse x, per ogni possibile valore di cutoff.</p>
<ul>
<li>
<strong>Interpretazione della curva</strong>:
<ul>
<li>Una curva che si avvicina al lato superiore sinistro del grafico rappresenta un test con alta sensibilità e specificità.</li>
<li>Una curva vicino alla diagonale indica una discriminazione casuale, non utile per classificare.</li>
</ul>
</li>
<li>
<strong>Generazione della curva</strong>:
<ol type="1">
<li>Calcola la sensibilità e 1-specificità per vari valori di cutoff.</li>
<li>Traccia i punti corrispondenti sul grafico e collegali per formare la curva.</li>
</ol>
</li>
</ul>
<p>Esaminiamo un esempio in R utilizzando il pacchetto <code>pROC</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Dati di esempio</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">aSAH</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Generazione della curva ROC</span></span>
<span><span class="va">rocCurve</span> <span class="op">&lt;-</span> <span class="fu">roc</span><span class="op">(</span><span class="va">aSAH</span><span class="op">$</span><span class="va">outcome</span>, <span class="va">aSAH</span><span class="op">$</span><span class="va">s100b</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Visualizzazione della curva</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">rocCurve</span>, legacy.axes <span class="op">=</span> <span class="cn">TRUE</span>, print.auc <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="01_prediction_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
</section><section id="auc-area-under-the-curve" class="level2" data-number="83.7"><h2 data-number="83.7" class="anchored" data-anchor-id="auc-area-under-the-curve">
<span class="header-section-number">83.7</span> AUC (Area Under the Curve)</h2>
<p>L’AUC è l’area sotto la curva ROC e fornisce una misura sintetica della capacità discriminativa del test.</p>
<ul>
<li>
<strong>Interpretazione dell’AUC</strong>:
<ul>
<li>
<strong>0.5</strong>: Discriminazione casuale (linea diagonale).</li>
<li>
<strong>0.7–0.8</strong>: Discriminazione accettabile.</li>
<li>
<strong>0.8–0.9</strong>: Buona discriminazione.</li>
<li>
<strong>&gt;0.9</strong>: Eccellente discriminazione.</li>
</ul>
</li>
<li>
<strong>Significato dell’AUC</strong>:
<ul>
<li>Rappresenta la probabilità che, selezionando casualmente un esito positivo e uno negativo, il test classifichi correttamente l’esito positivo.</li>
<li>Ad esempio, un’AUC di 0.75 significa che il test classifica correttamente il 75% delle coppie positivo-negativo.</li>
</ul>
</li>
</ul>
<p>Esempio in R per una curva ROC lisciata e AUC:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Curva ROC lisciata</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu">roc</span><span class="op">(</span><span class="va">aSAH</span><span class="op">$</span><span class="va">outcome</span>, <span class="va">aSAH</span><span class="op">$</span><span class="va">s100b</span>, smooth <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>, </span>
<span>     legacy.axes <span class="op">=</span> <span class="cn">TRUE</span>, print.auc <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="01_prediction_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Vantaggi dell’analisi ROC e AUC</strong></p>
<ol type="1">
<li>
<strong>Indipendenza dal cutoff</strong>: La curva ROC consente di valutare un test senza fissare una soglia specifica.</li>
<li>
<strong>Robustezza</strong>: L’AUC è meno influenzata da fattori come il tasso di base nella popolazione o lo sbilanciamento tra classi.</li>
<li>
<strong>Comparabilità</strong>: Permette di confrontare l’efficacia di diversi test o modelli.</li>
</ol></section><section id="riflessioni-conclusive" class="level2" data-number="83.8"><h2 data-number="83.8" class="anchored" data-anchor-id="riflessioni-conclusive">
<span class="header-section-number">83.8</span> Riflessioni Conclusive</h2>
<p>La curva ROC (<em>Receiver Operating Characteristic</em>) e l’AUC (<em>Area Under the Curve</em>) rappresentano strumenti tra i più efficaci per valutare l’accuratezza predittiva di modelli e test diagnostici. La loro forza risiede nella capacità di fornire una valutazione complessiva della discriminabilità del modello, tenendo conto dei bias introdotti da tassi di base e dalla scelta delle soglie decisionali.</p>
<p>La curva ROC traccia la relazione tra il tasso di veri positivi (<em>True Positive Rate</em>, o sensibilità) e il tasso di falsi positivi (<em>False Positive Rate</em>, o 1-specificità) per ogni possibile valore di cutoff. Questo approccio consente di:</p>
<ul>
<li>
<strong>Visualizzare le prestazioni complessive</strong>: La curva illustra come varia il compromesso tra sensibilità e specificità al variare della soglia, rendendo evidente il trade-off tra errori di tipo I (falsi positivi) ed errori di tipo II (falsi negativi).</li>
<li>
<strong>Superare la limitazione di un singolo cutoff</strong>: Piuttosto che valutare il modello su una soglia arbitraria, la curva ROC considera tutte le possibili soglie, offrendo un quadro più completo.</li>
</ul>
<p>L’AUC, o area sotto la curva ROC, sintetizza la capacità del modello di distinguere tra classi in un singolo valore. Un’AUC pari a 1 indica una classificazione perfetta, mentre un valore di 0.5 rappresenta un modello che non ha capacità discriminativa migliore di una scelta casuale. Le caratteristiche principali dell’AUC includono:</p>
<ul>
<li>
<strong>Indipendenza dai tassi di base</strong>: L’AUC misura la capacità discriminativa del modello senza essere influenzata dalla prevalenza delle classi, rendendola particolarmente utile in contesti con distribuzioni sbilanciate.</li>
<li>
<strong>Comparabilità</strong>: L’AUC consente di confrontare modelli diversi in modo standardizzato, indipendentemente dalla soglia di classificazione scelta.</li>
</ul>
<p>Un aspetto critico nella valutazione di modelli predittivi è che i tassi di base (la proporzione della classe positiva nella popolazione) possono influenzare fortemente le metriche di performance, come accuratezza e precisione. La curva ROC e l’AUC affrontano questo problema:</p>
<ul>
<li>
<strong>Separazione tra sensibilità e bias</strong>: La curva ROC evidenzia le capacità discriminative indipendentemente dal bias introdotto da tassi di base o scelte di cutoff.</li>
<li>
<strong>Supporto alla scelta del cutoff ottimale</strong>: Valutando il compromesso tra veri positivi e falsi positivi per ogni soglia, è possibile identificare il punto che bilancia meglio sensibilità e specificità in base ai costi associati agli errori.</li>
</ul>
<p>Strumenti come ROC e AUC sono particolarmente utili in campi come la psicologia, la medicina e l’intelligenza artificiale, dove:</p>
<ul>
<li>
<strong>Errori hanno costi variabili</strong>: Ad esempio, nel rilevamento di malattie, un falso negativo può essere più grave di un falso positivo. La curva ROC aiuta a scegliere soglie che minimizzano l’impatto di tali errori.</li>
<li>
<strong>Gestione di distribuzioni sbilanciate</strong>: In scenari dove la classe positiva è rara (es. diagnosi di malattie gravi), l’AUC permette di valutare le prestazioni senza essere distorto dalla prevalenza.</li>
</ul>
<p>In conclusione, la curva ROC e l’AUC offrono una rappresentazione completa della capacità predittiva di un modello, permettendo di considerare molteplici cutoff e di ridurre l’influenza di bias legati ai tassi di base. Questo approccio consente decisioni informate su soglie ottimali, rendendoli strumenti indispensabili in ogni analisi che coinvolga la predizione e la classificazione.</p>
</section><section id="informazioni-sullambiente-di-sviluppo" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="informazioni-sullambiente-di-sviluppo">Informazioni sull’Ambiente di Sviluppo</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; R version 4.4.2 (2024-10-31)</span></span>
<span><span class="co">#&gt; Platform: aarch64-apple-darwin20</span></span>
<span><span class="co">#&gt; Running under: macOS Sequoia 15.2</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Matrix products: default</span></span>
<span><span class="co">#&gt; BLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib </span></span>
<span><span class="co">#&gt; LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; locale:</span></span>
<span><span class="co">#&gt; [1] C/UTF-8/C/C/C/C</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; time zone: Europe/Rome</span></span>
<span><span class="co">#&gt; tzcode source: internal</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; attached base packages:</span></span>
<span><span class="co">#&gt; [1] grid      stats     graphics  grDevices utils     datasets  methods  </span></span>
<span><span class="co">#&gt; [8] base     </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; other attached packages:</span></span>
<span><span class="co">#&gt;  [1] tinytex_0.54            MOTE_1.0.2              ggrepel_0.9.6          </span></span>
<span><span class="co">#&gt;  [4] car_3.1-3               carData_3.0-5           msir_1.3.3             </span></span>
<span><span class="co">#&gt;  [7] ResourceSelection_0.3-6 rms_6.9-0               Hmisc_5.2-2            </span></span>
<span><span class="co">#&gt; [10] ROCR_1.0-11             pROC_1.18.5             magrittr_2.0.3         </span></span>
<span><span class="co">#&gt; [13] petersenlab_1.0.0       ggokabeito_0.1.0        see_0.9.0              </span></span>
<span><span class="co">#&gt; [16] MASS_7.3-64             viridis_0.6.5           viridisLite_0.4.2      </span></span>
<span><span class="co">#&gt; [19] ggpubr_0.6.0            ggExtra_0.10.1          gridExtra_2.3          </span></span>
<span><span class="co">#&gt; [22] patchwork_1.3.0         bayesplot_1.11.1        semTools_0.5-6         </span></span>
<span><span class="co">#&gt; [25] semPlot_1.1.6           lavaan_0.6-19           psych_2.4.12           </span></span>
<span><span class="co">#&gt; [28] scales_1.3.0            markdown_1.13           knitr_1.49             </span></span>
<span><span class="co">#&gt; [31] lubridate_1.9.4         forcats_1.0.0           stringr_1.5.1          </span></span>
<span><span class="co">#&gt; [34] dplyr_1.1.4             purrr_1.0.2             readr_2.1.5            </span></span>
<span><span class="co">#&gt; [37] tidyr_1.3.1             tibble_3.2.1            ggplot2_3.5.1          </span></span>
<span><span class="co">#&gt; [40] tidyverse_2.0.0         here_1.0.1             </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; loaded via a namespace (and not attached):</span></span>
<span><span class="co">#&gt;   [1] splines_4.4.2      later_1.4.1        polspline_1.1.25  </span></span>
<span><span class="co">#&gt;   [4] XML_3.99-0.18      rpart_4.1.24       lifecycle_1.0.4   </span></span>
<span><span class="co">#&gt;   [7] Rdpack_2.6.2       rstatix_0.7.2      rprojroot_2.0.4   </span></span>
<span><span class="co">#&gt;  [10] lattice_0.22-6     rockchalk_1.8.157  backports_1.5.0   </span></span>
<span><span class="co">#&gt;  [13] openxlsx_4.2.7.1   rmarkdown_2.29     yaml_2.3.10       </span></span>
<span><span class="co">#&gt;  [16] httpuv_1.6.15      qgraph_1.9.8       zip_2.3.1         </span></span>
<span><span class="co">#&gt;  [19] pbapply_1.7-2      DBI_1.2.3          minqa_1.2.8       </span></span>
<span><span class="co">#&gt;  [22] RColorBrewer_1.1-3 multcomp_1.4-26    abind_1.4-8       </span></span>
<span><span class="co">#&gt;  [25] quadprog_1.5-8     nnet_7.3-20        TH.data_1.1-2     </span></span>
<span><span class="co">#&gt;  [28] sandwich_3.1-1     arm_1.14-4         MatrixModels_0.5-3</span></span>
<span><span class="co">#&gt;  [31] codetools_0.2-20   tidyselect_1.2.1   farver_2.1.2      </span></span>
<span><span class="co">#&gt;  [34] lme4_1.1-36        stats4_4.4.2       base64enc_0.1-3   </span></span>
<span><span class="co">#&gt;  [37] jsonlite_1.8.9     Formula_1.2-5      survival_3.8-3    </span></span>
<span><span class="co">#&gt;  [40] emmeans_1.10.6     tools_4.4.2        Rcpp_1.0.14       </span></span>
<span><span class="co">#&gt;  [43] glue_1.8.0         mnormt_2.1.1       xfun_0.50         </span></span>
<span><span class="co">#&gt;  [46] mgcv_1.9-1         withr_3.0.2        fastmap_1.2.0     </span></span>
<span><span class="co">#&gt;  [49] mitools_2.4        boot_1.3-31        SparseM_1.84-2    </span></span>
<span><span class="co">#&gt;  [52] digest_0.6.37      mi_1.1             timechange_0.3.0  </span></span>
<span><span class="co">#&gt;  [55] R6_2.5.1           mime_0.12          estimability_1.5.1</span></span>
<span><span class="co">#&gt;  [58] colorspace_2.1-1   mix_1.0-13         gtools_3.9.5      </span></span>
<span><span class="co">#&gt;  [61] jpeg_0.1-10        generics_0.1.3     data.table_1.16.4 </span></span>
<span><span class="co">#&gt;  [64] corpcor_1.6.10     htmlwidgets_1.6.4  pkgconfig_2.0.3   </span></span>
<span><span class="co">#&gt;  [67] sem_3.1-16         gtable_0.3.6       htmltools_0.5.8.1 </span></span>
<span><span class="co">#&gt;  [70] png_0.1-8          reformulas_0.4.0   rstudioapi_0.17.1 </span></span>
<span><span class="co">#&gt;  [73] tzdb_0.4.0         reshape2_1.4.4     coda_0.19-4.1     </span></span>
<span><span class="co">#&gt;  [76] checkmate_2.3.2    nlme_3.1-166       nloptr_2.1.1      </span></span>
<span><span class="co">#&gt;  [79] zoo_1.8-12         parallel_4.4.2     miniUI_0.1.1.1    </span></span>
<span><span class="co">#&gt;  [82] foreign_0.8-88     pillar_1.10.1      reshape_0.8.9     </span></span>
<span><span class="co">#&gt;  [85] vctrs_0.6.5        promises_1.3.2     OpenMx_2.21.13    </span></span>
<span><span class="co">#&gt;  [88] xtable_1.8-4       cluster_2.1.8      htmlTable_2.4.3   </span></span>
<span><span class="co">#&gt;  [91] evaluate_1.0.3     pbivnorm_0.6.0     ez_4.4-0          </span></span>
<span><span class="co">#&gt;  [94] mvtnorm_1.3-3      cli_3.6.3          kutils_1.73       </span></span>
<span><span class="co">#&gt;  [97] compiler_4.4.2     rlang_1.1.4        ggsignif_0.6.4    </span></span>
<span><span class="co">#&gt; [100] labeling_0.4.3     fdrtool_1.2.18     mclust_6.1.1      </span></span>
<span><span class="co">#&gt; [103] plyr_1.8.9         stringi_1.8.4      munsell_0.5.1     </span></span>
<span><span class="co">#&gt; [106] MBESS_4.9.3        lisrelToR_0.3      pacman_0.5.1      </span></span>
<span><span class="co">#&gt; [109] quantreg_5.99.1    Matrix_1.7-1       hms_1.1.3         </span></span>
<span><span class="co">#&gt; [112] glasso_1.11        shiny_1.10.0       rbibutils_2.3     </span></span>
<span><span class="co">#&gt; [115] igraph_2.1.2       broom_1.0.7        RcppParallel_5.1.9</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-petersen2024principles" class="csl-entry" role="listitem">
Petersen, I. T. (2024). <em>Principles of psychological assessment: With applied examples in R</em>. CRC Press.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiato!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiato!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ccaudek\.github\.io\/testing_psicologico\/intro\.html");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../chapters/lgm/12_temp_reliability.html" class="pagination-link" aria-label="Affidabilità longitudinale">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">82</span>&nbsp; <span class="chapter-title">Affidabilità longitudinale</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../99-references.html" class="pagination-link" aria-label="Bibliografia">
        <span class="nav-page-text">Bibliografia</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Testing Psicologico</strong> è una dispensa scritta da Corrado Caudek.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


</body></html>