<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Corrado Caudek">
<title>21&nbsp; Il modello statistico dell’analisi fattoriale – Testing Psicologico</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/fa/04_analisi_fattoriale_3.html" rel="next">
<link href="../../chapters/fa/02_analisi_fattoriale_1.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9ac0fa60fcd2ae55f2ddd9f231fc218f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c18f9378377a5e466bf47441f75951d3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/fa/01_intro_fa.html">FA</a></li><li class="breadcrumb-item"><a href="../../chapters/fa/03_analisi_fattoriale_2.html"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Il modello statistico dell’analisi fattoriale</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Testing Psicologico</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ccaudek/testing_psicologico/" title="Eseguire il codice" class="quarto-navigation-tool px-1" aria-label="Eseguire il codice"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Ricerca"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Informazioni Generali</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../prefazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefazione</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Calendario</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../cal_testing_psic_2025.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calendario Didattico e Programma del Corso</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Punteggi e scale</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/01_scores_scales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Punteggi e scale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E1_likert.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">✏ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E2_optimal_scoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E3_thurstone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">✏ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/02_development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sviluppo dello strumento</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/03_equating.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Equating nei Test Psicologici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E4_norming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">CTT</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/01_ctt_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Fondamenti teorici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/02_ctt_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">L’affidabilità del test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/03_ctt_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Metodi di stima dell’affidabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/04_err_std_mis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">L’errore standard della misurazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/05_err_std_stima.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">La stima del punteggio vero</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/06_ctt_applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Applicazioni della CTT</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Analisi dei percorsi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/path_analysis/01_path_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Analisi dei percorsi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/path_analysis/02_clement_2022.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Riparazione affettiva post-infedeltà</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Networks</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/networks/01_networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Network psicologici</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">PCA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/pca/01_linear_algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Elementi di algebra lineare</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/pca/02_pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Analisi delle componenti principali</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">FA</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/01_intro_fa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Introduzione all’analisi fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/02_analisi_fattoriale_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Il modello unifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/03_analisi_fattoriale_2.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Il modello statistico dell’analisi fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/04_analisi_fattoriale_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Il modello multifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/05_factor_scores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">I punteggi fattoriali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/06_constraints_on_parms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Attendibilità e modello fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/07_total_score.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Punteggio totale e modello fattoriale</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Costruzione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/01_val_matrici.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Valutazione della matrice di correlazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/02_estrazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">L’estrazione dei fattori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/03_numero_fattori.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Determinare il numero dei fattori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/04_rotazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">La rotazione fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/05_val_soluzione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Valutare e rifinire la soluzione fattoriale</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">CFA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/01_cfa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Analisti Fattoriale Confermativa</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/02_meanstructure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">La struttura delle medie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/03_cat_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Dati non gaussiani e categoriali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/04_mmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">CFA per matrici multi-tratto multi-metodo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/05_bifactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Modello bifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/06_efa_lavaan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Exploratory Structural Equation Modeling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/07_fa_in_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Strategia Integrata per un’Analisi Fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/E_02_bifactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">SEM</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/01_sem_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Introduzione ai Modelli SEM</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/02_data_preparation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Preparazione dei Dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/03_gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Test del Modello e Indicizzazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/04_mod_comp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Confronto tra modelli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/05_cfa_mod_comp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">CFA: confronto tra modelli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/06_refine_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">La revisione del modello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/07_group_invariance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Invarianza di misura</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/08_multilevel_sem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Modelli di Equazioni Strutturali Multilivello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/09_structural_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Modelli di Regressione Strutturale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/10_missing_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Dati mancanti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/11_small_samples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Modellizzazione SEM in Piccoli Campioni</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/13_esem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Exploratory structural equation modelling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/14_sem_power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Dimensione Campionaria e Analisi della Potenza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/15_prior_pred_mod_check.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Prior Predictive Model Checking</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">Giudici</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/01_multilevel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Modelli multilivello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/02_interrater_reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">L’affidabilità tra giudici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/E1_irr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false">
 <span class="menu-text">Validità</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/validity/01_validity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">La Validità del test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/validity/02_other_variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Relazioni test-criterio</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Generalizzabilità</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/gtheory/01_gtheory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Teoria della generalizzabilità</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false">
 <span class="menu-text">Items</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/items/01_item_development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">Lo sviluppo degli item</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/items/02_item_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Analisi degli item</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false">
 <span class="menu-text">Mokken</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/01_logistic_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Modello di Regressione Logistica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/02_core_issues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Analisi della Scala di Mokken</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/03_applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Applicazione Pratica</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false">
 <span class="menu-text">IRT</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/01_rasch_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">Modello di Rasch</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/02_assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">68</span>&nbsp; <span class="chapter-title">Assunzioni e Proprietà del Modello di Rasch</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/03_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title">Stima</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/04_1pl_2pl_3pl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Modelli 1PL, 2PL e 3PL</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/05_implementation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Implementazione</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false">
 <span class="menu-text">LGM</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/01_lgm_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">72</span>&nbsp; <span class="chapter-title">Curve di crescita latente</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/02_lgm_prelims.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">73</span>&nbsp; <span class="chapter-title">Considerazioni Preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/06_lgm_mixed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">74</span>&nbsp; <span class="chapter-title">LGM e modelli misti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/03_time_effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">75</span>&nbsp; <span class="chapter-title">Dati longitudinali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/05_intro_panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">76</span>&nbsp; <span class="chapter-title">Specificare e Interpretare un Modello Longitudinale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/07_growth_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">77</span>&nbsp; <span class="chapter-title">Curve di crescita latente</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/08_growth_cont.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">78</span>&nbsp; <span class="chapter-title">Il tempo su una metrica continua</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/09_time_inv_cov.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">79</span>&nbsp; <span class="chapter-title">Covariate indipendenti dal tempo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/10_growth_groups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">80</span>&nbsp; <span class="chapter-title">Modelli di crescita latenti a gruppi multipli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/11_lgm_wais.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">81</span>&nbsp; <span class="chapter-title">Lo Sviluppo dell’Intelligenza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/12_temp_reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">82</span>&nbsp; <span class="chapter-title">Affidabilità longitudinale</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false">
 <span class="menu-text">Predizione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/prediction/01_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">83</span>&nbsp; <span class="chapter-title">Predizione</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../99-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliografia</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendici</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a1_intro_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linguaggio R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a2_sums.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Simbolo di somma</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a3_calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Per liberarvi dai terrori preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false">
 <span class="menu-text">Soluzioni degli esercizi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/solutions_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Probabilità</span></span></a>
  </div>
</li>
      </ul>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Indice</h2>
   
  <ul>
<li><a href="#modello-monofattoriale" id="toc-modello-monofattoriale" class="nav-link active" data-scroll-target="#modello-monofattoriale"><span class="header-section-number">21.1</span> Modello monofattoriale</a></li>
  <li><a href="#covarianza-tra-un-indicatore-e-il-fattore-comune" id="toc-covarianza-tra-un-indicatore-e-il-fattore-comune" class="nav-link" data-scroll-target="#covarianza-tra-un-indicatore-e-il-fattore-comune"><span class="header-section-number">21.2</span> Covarianza tra un indicatore e il fattore comune</a></li>
  <li><a href="#espressione-fattoriale-della-varianza" id="toc-espressione-fattoriale-della-varianza" class="nav-link" data-scroll-target="#espressione-fattoriale-della-varianza"><span class="header-section-number">21.3</span> Espressione fattoriale della varianza</a></li>
  <li><a href="#covarianza-tra-due-variabili-manifeste" id="toc-covarianza-tra-due-variabili-manifeste" class="nav-link" data-scroll-target="#covarianza-tra-due-variabili-manifeste"><span class="header-section-number">21.4</span> Covarianza tra due variabili manifeste</a></li>
  <li><a href="#correlazioni-osservate-e-correlazioni-riprodotte-dal-modello" id="toc-correlazioni-osservate-e-correlazioni-riprodotte-dal-modello" class="nav-link" data-scroll-target="#correlazioni-osservate-e-correlazioni-riprodotte-dal-modello"><span class="header-section-number">21.5</span> Correlazioni osservate e correlazioni riprodotte dal modello</a></li>
  <li>
<a href="#bont%C3%A0-di-adattamento-del-modello-ai-dati" id="toc-bontà-di-adattamento-del-modello-ai-dati" class="nav-link" data-scroll-target="#bont%C3%A0-di-adattamento-del-modello-ai-dati"><span class="header-section-number">21.6</span> Bontà di adattamento del modello ai dati</a>
  <ul>
<li><a href="#lipotesi-nulla-del-test" id="toc-lipotesi-nulla-del-test" class="nav-link" data-scroll-target="#lipotesi-nulla-del-test"><span class="header-section-number">21.6.1</span> L’ipotesi nulla del test</a></li>
  <li><a href="#la-statistica-chi2" id="toc-la-statistica-chi2" class="nav-link" data-scroll-target="#la-statistica-chi2"><span class="header-section-number">21.6.2</span> La statistica <span class="math inline">\(\chi^2\)</span></a></li>
  <li><a href="#interpretazione-del-test" id="toc-interpretazione-del-test" class="nav-link" data-scroll-target="#interpretazione-del-test"><span class="header-section-number">21.6.3</span> Interpretazione del test</a></li>
  <li><a href="#assunzioni-e-limiti" id="toc-assunzioni-e-limiti" class="nav-link" data-scroll-target="#assunzioni-e-limiti"><span class="header-section-number">21.6.4</span> Assunzioni e limiti</a></li>
  </ul>
</li>
  <li>
<a href="#lerrore-standard-della-misurazione-nel-modello-fattoriale" id="toc-lerrore-standard-della-misurazione-nel-modello-fattoriale" class="nav-link" data-scroll-target="#lerrore-standard-della-misurazione-nel-modello-fattoriale"><span class="header-section-number">21.7</span> L’errore standard della misurazione nel modello fattoriale</a>
  <ul>
<li><a href="#collegamento-tra-ctt-e-analisi-fattoriale" id="toc-collegamento-tra-ctt-e-analisi-fattoriale" class="nav-link" data-scroll-target="#collegamento-tra-ctt-e-analisi-fattoriale"><span class="header-section-number">21.7.1</span> Collegamento tra CTT e analisi fattoriale</a></li>
  <li><a href="#decomposizione-della-varianza" id="toc-decomposizione-della-varianza" class="nav-link" data-scroll-target="#decomposizione-della-varianza"><span class="header-section-number">21.7.2</span> Decomposizione della varianza</a></li>
  <li><a href="#errore-standard-di-misurazione" id="toc-errore-standard-di-misurazione" class="nav-link" data-scroll-target="#errore-standard-di-misurazione"><span class="header-section-number">21.7.3</span> Errore standard di misurazione</a></li>
  </ul>
</li>
  <li>
<a href="#un-esempio-concreto" id="toc-un-esempio-concreto" class="nav-link" data-scroll-target="#un-esempio-concreto"><span class="header-section-number">21.8</span> Un esempio concreto</a>
  <ul>
<li><a href="#lettura-e-ispezione-preliminare-dei-dati" id="toc-lettura-e-ispezione-preliminare-dei-dati" class="nav-link" data-scroll-target="#lettura-e-ispezione-preliminare-dei-dati"><span class="header-section-number">21.8.1</span> Lettura e ispezione preliminare dei dati</a></li>
  <li><a href="#specifica-e-stima-di-un-modello-unifattoriale" id="toc-specifica-e-stima-di-un-modello-unifattoriale" class="nav-link" data-scroll-target="#specifica-e-stima-di-un-modello-unifattoriale"><span class="header-section-number">21.8.2</span> Specifica e stima di un modello unifattoriale</a></li>
  <li><a href="#stima-dellerrore-standard-di-misurazione-tramite-il-modello-fattoriale" id="toc-stima-dellerrore-standard-di-misurazione-tramite-il-modello-fattoriale" class="nav-link" data-scroll-target="#stima-dellerrore-standard-di-misurazione-tramite-il-modello-fattoriale"><span class="header-section-number">21.8.3</span> Stima dell’errore standard di misurazione tramite il modello fattoriale</a></li>
  <li><a href="#confronto-con-la-formula-della-ctt" id="toc-confronto-con-la-formula-della-ctt" class="nav-link" data-scroll-target="#confronto-con-la-formula-della-ctt"><span class="header-section-number">21.8.4</span> Confronto con la formula della CTT</a></li>
  <li><a href="#correlazioni-riprodotte-dal-modello" id="toc-correlazioni-riprodotte-dal-modello" class="nav-link" data-scroll-target="#correlazioni-riprodotte-dal-modello"><span class="header-section-number">21.8.5</span> Correlazioni riprodotte dal modello</a></li>
  <li><a href="#varianza-riprodotta-di-una-variabile" id="toc-varianza-riprodotta-di-una-variabile" class="nav-link" data-scroll-target="#varianza-riprodotta-di-una-variabile"><span class="header-section-number">21.8.6</span> Varianza riprodotta di una variabile</a></li>
  </ul>
</li>
  <li><a href="#correlazione-tra-variabili-manifeste-e-fattore-comune" id="toc-correlazione-tra-variabili-manifeste-e-fattore-comune" class="nav-link" data-scroll-target="#correlazione-tra-variabili-manifeste-e-fattore-comune"><span class="header-section-number">21.9</span> Correlazione tra variabili manifeste e fattore comune</a></li>
  <li><a href="#session-info" id="toc-session-info" class="nav-link" data-scroll-target="#session-info"><span class="header-section-number">21.10</span> Session Info</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/fa/01_intro_fa.html">FA</a></li><li class="breadcrumb-item"><a href="../../chapters/fa/03_analisi_fattoriale_2.html"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Il modello statistico dell’analisi fattoriale</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-fa-statistical-model-fa" class="quarto-section-identifier"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Il modello statistico dell’analisi fattoriale</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
In questo capitolo imparerai a
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Comprendere il modello statistico monofattoriale.</li>
<li>Eseguire l’analisi statistica per il modello monofattoriale con <code>lavaan</code>.</li>
</ul>
</div>
</div>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prerequisiti
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Leggere il capitolo 6, <em>Factor Analysis and Principal Component Analysis</em>, del testo <em>Principles of psychological assessment</em> di <span class="citation" data-cites="petersen2024principles">Petersen (<a href="../../99-references.html#ref-petersen2024principles" role="doc-biblioref">2024</a>)</span>.</li>
</ul>
</div>
</div>
<div class="callout callout-style-simple callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Preparazione del Notebook
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"code"</span>, <span class="st">"_common.R"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/ns-load.html">requireNamespace</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span></span>
<span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">lavaan</span>, <span class="va">semPlot</span>, <span class="va">tidyr</span>, <span class="va">ggdag</span>, <span class="va">dagitty</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<section id="modello-monofattoriale" class="level2" data-number="21.1"><h2 data-number="21.1" class="anchored" data-anchor-id="modello-monofattoriale">
<span class="header-section-number">21.1</span> Modello monofattoriale</h2>
<p>L’analisi fattoriale esplorativa (AFE) parte da una matrice di dimensioni <span class="math inline">\(p \times p\)</span> (dove <span class="math inline">\(p\)</span> è il numero di variabili osservate) che contiene i coefficienti di correlazione (o, in alternativa, di covarianza) fra tali variabili. L’obiettivo dell’AFE è ottenere una matrice di dimensioni <span class="math inline">\(p \times k\)</span> (dove <span class="math inline">\(k\)</span> è il numero di fattori comuni) i cui elementi – chiamati <em>saturazioni fattoriali</em> – descrivono la relazione tra ciascun fattore comune e ogni variabile osservata.</p>
<p>Nel caso più semplice, quello <em>monofattoriale</em>, si ipotizza l’esistenza di un unico fattore latente, <span class="math inline">\(\xi\)</span>. In presenza di <span class="math inline">\(p\)</span> variabili manifeste <span class="math inline">\(Y_i\)</span>, il modello matematico di un solo fattore comune si può esprimere nel modo seguente:</p>
<p><span id="eq-fa-model-1f"><span class="math display">\[
Y_i = \mu_i + \lambda_{i} \,\xi + \delta_i ,
\quad\text{per}\quad
i=1, \dots, p,
\tag{21.1}\]</span></span></p>
<p>dove:</p>
<ul>
<li>
<span class="math inline">\(\xi\)</span> è il fattore comune (o <em>fattore latente</em>), condiviso da tutte le variabili <span class="math inline">\(Y_i\)</span>;</li>
<li>
<span class="math inline">\(\delta_i\)</span> è il <em>fattore specifico</em> (o <em>fattore unico</em>) associato alla <span class="math inline">\(i\)</span>-esima variabile osservata, cioè una componente di varianza che non è condivisa con le altre variabili;</li>
<li>
<span class="math inline">\(\lambda_i\)</span> è la <em>saturazione fattoriale</em> (o <em>peso</em>) della <span class="math inline">\(i\)</span>-esima variabile, ossia il coefficiente che quantifica il peso esercitato dal fattore comune <span class="math inline">\(\xi\)</span> su <span class="math inline">\(Y_i\)</span>.</li>
</ul>
<p>Per semplificare l’analisi, si assume spesso che <span class="math inline">\(\mu_i = 0\)</span>, considerando le <span class="math inline">\(Y_i\)</span> già centrate (cioè prive della loro media). Questa convenzione rende possibile riscrivere il modello come:</p>
<p><span id="eq-fa-model-1f-noint"><span class="math display">\[
Y_i = \lambda_i \,\xi + \delta_i.
\tag{21.2}\]</span></span></p>
<p>In aggiunta a questa ipotesi di centratura, si stabilisce che:</p>
<ol type="1">
<li>il fattore comune <span class="math inline">\(\xi\)</span> abbia media nulla, <span class="math inline">\(\mathbb{E}(\xi) = 0\)</span>, e varianza unitaria, <span class="math inline">\(\mathbb{V}(\xi) = 1\)</span>;</li>
<li>i fattori specifici <span class="math inline">\(\delta_i\)</span> abbiano media nulla, <span class="math inline">\(\mathbb{E}(\delta_i)=0\)</span>, e varianza <span class="math inline">\(\psi_i\)</span>, cioè <span class="math inline">\(\mathbb{V}(\delta_i) = \psi_i\)</span>;</li>
<li>i fattori specifici siano tra loro incorrelati: <span class="math inline">\(\mathbb{E}(\delta_i \,\delta_k) = 0\)</span> per <span class="math inline">\(i \neq k\)</span>;</li>
<li>i fattori specifici siano incorrelati con il fattore comune: <span class="math inline">\(\mathbb{E}(\delta_i\,\xi) = 0\)</span> per ogni <span class="math inline">\(i\)</span>.</li>
</ol>
<p>Date queste ipotesi, l’interdipendenza (cioè le correlazioni) fra le variabili osservate <span class="math inline">\(Y_i\)</span> e <span class="math inline">\(Y_k\)</span> è interamente spiegata dal singolo fattore comune <span class="math inline">\(\xi\)</span>. I termini <span class="math inline">\(\delta_i\)</span> riguardano solo la varianza <em>non condivisa</em> di ciascuna variabile.</p>
<p>Sulla base di queste assunzioni, è possibile:</p>
<ul>
<li>calcolare la <em>covarianza</em> tra <span class="math inline">\(Y_i\)</span> e il fattore comune <span class="math inline">\(\xi\)</span>;</li>
<li>determinare la <em>varianza</em> di ciascuna variabile <span class="math inline">\(Y_i\)</span>;</li>
<li>ottenere la <em>covarianza</em> tra due variabili manifeste <span class="math inline">\(Y_i\)</span> e <span class="math inline">\(Y_k\)</span>.</li>
</ul>
<p>Tali derivazioni consentono di comprendere a fondo come il fattore latente <span class="math inline">\(\xi\)</span> contribuisca a spiegare le relazioni fra le variabili osservate e quanta parte della varianza di ciascuna variabile sia invece imputabile a fattori specifici (non condivisi). Questo concetto è alla base di tutte le procedure di stima e di interpretazione nell’analisi fattoriale esplorativa con un solo fattore.</p>
</section><section id="covarianza-tra-un-indicatore-e-il-fattore-comune" class="level2" data-number="21.2"><h2 data-number="21.2" class="anchored" data-anchor-id="covarianza-tra-un-indicatore-e-il-fattore-comune">
<span class="header-section-number">21.2</span> Covarianza tra un indicatore e il fattore comune</h2>
<p>Nel modello monofattoriale, vogliamo determinare la covarianza teorica tra una variabile manifesta <span class="math inline">\(Y_i\)</span> e il fattore comune <span class="math inline">\(\xi\)</span>. La definizione di covarianza è:</p>
<p><span class="math display">\[
\mathrm{Cov}(Y_i, \xi)
= \mathbb{E}(Y_i \, \xi)
  - \mathbb{E}(Y_i)\,\mathbb{E}(\xi).
\]</span></p>
<p>Poiché per semplicità assumiamo <span class="math inline">\(\mathbb{E}(\xi) = 0\)</span>, la formula si riduce a:</p>
<p><span class="math display">\[
\mathrm{Cov}(Y_i, \xi)
= \mathbb{E}(Y_i \,\xi).
\]</span></p>
<p>Usando il modello monofattoriale <span class="math inline">\(Y_i = \lambda_i \xi + \delta_i\)</span>, si ottiene:</p>
<p><span class="math display">\[
\mathrm{Cov}(Y_i, \xi)
= \mathbb{E}\bigl((\lambda_i \,\xi + \delta_i)\xi\bigr)
= \mathbb{E}(\lambda_i\,\xi^2 + \delta_i\,\xi).
\]</span></p>
<p>Il termine <span class="math inline">\(\lambda_i\)</span> è una costante (la <em>saturazione fattoriale</em>), perciò si può portare fuori dall’aspettazione:</p>
<p><span class="math display">\[
= \lambda_i \,\mathbb{E}(\xi^2) + \mathbb{E}(\delta_i \,\xi).
\]</span></p>
<p>A questo punto, valgono due ipotesi fondamentali:</p>
<ol type="1">
<li>
<span class="math inline">\(\mathbb{E}(\xi^2) = \mathbb{V}(\xi) = 1\)</span>, cioè il fattore comune ha varianza unitaria.</li>
<li>
<span class="math inline">\(\mathrm{Cov}(\delta_i,\xi) = \mathbb{E}(\delta_i \,\xi) = 0\)</span>, poiché il fattore specifico <span class="math inline">\(\delta_i\)</span> è incorrelato con il fattore comune <span class="math inline">\(\xi\)</span>.</li>
</ol>
<p>Applicando queste ipotesi si ha:</p>
<p><span class="math display">\[
\mathrm{Cov}(Y_i, \xi)
= \lambda_i \cdot 1 + 0
= \lambda_i.
\]</span></p>
<p><strong>In sintesi</strong>: in un modello a singolo fattore, la <em>saturazione</em> <span class="math inline">\(\lambda_i\)</span> coincide con la covarianza tra la variabile manifesta <span class="math inline">\(Y_i\)</span> e il fattore comune <span class="math inline">\(\xi\)</span>. Inoltre, se ogni variabile <span class="math inline">\(Y_i\)</span> è stata <em>standardizzata</em>, ossia ha varianza pari a 1, allora <span class="math inline">\(\lambda_i = \mathrm{Corr}(Y_i,\xi)\)</span>. In tal caso, <span class="math inline">\(\lambda_i\)</span> esprime direttamente la <em>correlazione</em> tra la variabile <span class="math inline">\(Y_i\)</span> e il fattore comune <span class="math inline">\(\xi\)</span>.</p>
</section><section id="espressione-fattoriale-della-varianza" class="level2" data-number="21.3"><h2 data-number="21.3" class="anchored" data-anchor-id="espressione-fattoriale-della-varianza">
<span class="header-section-number">21.3</span> Espressione fattoriale della varianza</h2>
<p>Sotto l’ipotesi che <span class="math inline">\(\mathbb{E}(Y_i) = 0\)</span>, la varianza di <span class="math inline">\(Y_i\)</span> è:</p>
<p><span class="math display">\[
\mathbb{V}(Y_i) = \mathbb{E}(Y_i^2) - [\mathbb{E}(Y_i)]^2
                = \mathbb{E}(Y_i^2).
\]</span></p>
<p>Usando di nuovo il modello monofattoriale <span class="math inline">\(Y_i = \lambda_i \xi + \delta_i\)</span>:</p>
<p><span class="math display">\[
\mathbb{V}(Y_i)
= \mathbb{E}\bigl((\lambda_i \,\xi + \delta_i)^2\bigr).
\]</span></p>
<p>Sviluppando il quadrato:</p>
<p><span class="math display">\[
= \mathbb{E}\bigl(\lambda_i^2 \,\xi^2
                  + 2\,\lambda_i\,\xi\,\delta_i
                  + \delta_i^2\bigr).
\]</span></p>
<p>Distinguiamo i tre termini all’interno dell’aspettazione:</p>
<ol type="1">
<li>
<span class="math inline">\(\mathbb{E}(\lambda_i^2 \,\xi^2) = \lambda_i^2 \,\mathbb{E}(\xi^2)\)</span> poiché <span class="math inline">\(\lambda_i^2\)</span> è costante e <span class="math inline">\(\mathbb{E}(\xi^2) = \mathbb{V}(\xi) = 1\)</span>. Pertanto questo termine diventa <span class="math inline">\(\lambda_i^2\)</span>.</li>
<li>
<span class="math inline">\(\mathbb{E}(2\,\lambda_i\,\xi\,\delta_i) = 2\,\lambda_i\,\mathbb{E}(\xi\,\delta_i)\)</span>. Ma <span class="math inline">\(\mathrm{Cov}(\xi, \delta_i) = 0\)</span>, dunque <span class="math inline">\(\mathbb{E}(\xi\,\delta_i) = 0\)</span>. Di conseguenza questo termine è nullo.</li>
<li>
<span class="math inline">\(\mathbb{E}(\delta_i^2) = \mathbb{V}(\delta_i) = \psi_i\)</span>, dato che il fattore specifico <span class="math inline">\(\delta_i\)</span> ha varianza <span class="math inline">\(\psi_i\)</span>.</li>
</ol>
<p>Mettendo insieme questi risultati, otteniamo:</p>
<p><span class="math display">\[
\mathbb{V}(Y_i)
= \lambda_i^2 + \psi_i.
\]</span></p>
<ul>
<li>
<span class="math inline">\(\lambda_i^2\)</span> è detta <em>comunalità</em> della variabile <span class="math inline">\(Y_i\)</span> e indica la parte di varianza spiegata dal fattore comune <span class="math inline">\(\xi\)</span>.</li>
<li>
<span class="math inline">\(\psi_i\)</span> rappresenta la parte di varianza non spiegata dal fattore comune, detta <em>unicità</em> di <span class="math inline">\(Y_i\)</span>.</li>
</ul>
<p>Nel caso in cui le <span class="math inline">\(Y_i\)</span> siano state <em>standardizzate</em> (quindi abbiano <span class="math inline">\(\mathbb{V}(Y_i) = 1\)</span>), si ottiene:</p>
<p><span class="math display">\[
1 = \lambda_i^2 + \psi_i,
\]</span></p>
<p>da cui</p>
<p><span class="math display">\[
\psi_i = 1 - \lambda_i^2.
\]</span></p>
<p>In questo scenario, la comunalità <span class="math inline">\(\lambda_i^2\)</span> indica esattamente la percentuale di varianza di <span class="math inline">\(Y_i\)</span> spiegata dal fattore comune, mentre <span class="math inline">\(\psi_i\)</span> indica la percentuale rimanente, legata a fattori specifici o ad altri errori di misura.</p>
<p><strong>In sintesi</strong>, la varianza di una variabile osservata <span class="math inline">\(Y_i\)</span> può essere scomposta in:</p>
<ul>
<li>
<span class="math inline">\(\lambda_i^2\)</span>, la parte <em>comune</em> che la variabile condivide con tutte le altre (ossia la porzione di varianza attribuibile al fattore comune <span class="math inline">\(\xi\)</span>, chiamata <em>comunalità</em>);</li>
<li>
<span class="math inline">\(\psi_i\)</span>, la parte <em>specifica</em> o <em>residua</em>, non spiegata dal fattore comune (chiamata <em>unicità</em>).</li>
</ul>
<p>Nei modelli fattoriali, l’obiettivo principale è proprio stimare correttamente <span class="math inline">\(\lambda_i\)</span> e <span class="math inline">\(\psi_i\)</span> per capire in che misura un fattore latente unico (<span class="math inline">\(\xi\)</span>) spiega le relazioni tra le diverse variabili manifeste <span class="math inline">\(Y_1, Y_2, \dots, Y_p\)</span>.</p>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Esempio 21.1</strong></span> Riprendiamo l’analisi della matrice di correlazioni di Spearman.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">Spearman</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  <span class="fl">1.0</span>, <span class="fl">.78</span>, <span class="fl">.70</span>, <span class="fl">.66</span>,</span>
<span>  <span class="fl">.78</span>, <span class="fl">1.0</span>, <span class="fl">.64</span>, <span class="fl">.54</span>,</span>
<span>  <span class="fl">.70</span>, <span class="fl">.64</span>, <span class="fl">1.0</span>, <span class="fl">.45</span>,</span>
<span>  <span class="fl">.66</span>, <span class="fl">.54</span>, <span class="fl">.45</span>, <span class="fl">1.0</span></span>
<span><span class="op">)</span>,</span>
<span>byrow <span class="op">=</span> <span class="cn">TRUE</span>, ncol <span class="op">=</span> <span class="fl">4</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">Spearman</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"C"</span>, <span class="st">"E"</span>, <span class="st">"M"</span>, <span class="st">"P"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">Spearman</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"C"</span>, <span class="st">"E"</span>, <span class="st">"M"</span>, <span class="st">"P"</span><span class="op">)</span></span>
<span><span class="va">Spearman</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt;      C    E    M    P</span></span>
<span><span class="co">#&gt; C 1.00 0.78 0.70 0.66</span></span>
<span><span class="co">#&gt; E 0.78 1.00 0.64 0.54</span></span>
<span><span class="co">#&gt; M 0.70 0.64 1.00 0.45</span></span>
<span><span class="co">#&gt; P 0.66 0.54 0.45 1.00</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Quando eseguiamo una <em>analisi fattoriale</em> con la funzione <code><a href="https://rdrr.io/r/stats/factanal.html">factanal()</a></code>, nello stesso output compare la quantità denominata <code>SS loadings</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/factanal.html">factanal</a></span><span class="op">(</span>covmat <span class="op">=</span> <span class="va">Spearman</span>, factors <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">fm</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; factanal(factors = 1, covmat = Spearman)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Uniquenesses:</span></span>
<span><span class="co">#&gt;     C     E     M     P </span></span>
<span><span class="co">#&gt; 0.086 0.329 0.460 0.539 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Loadings:</span></span>
<span><span class="co">#&gt;   Factor1</span></span>
<span><span class="co">#&gt; C 0.956  </span></span>
<span><span class="co">#&gt; E 0.819  </span></span>
<span><span class="co">#&gt; M 0.735  </span></span>
<span><span class="co">#&gt; P 0.679  </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;                Factor1</span></span>
<span><span class="co">#&gt; SS loadings      2.587</span></span>
<span><span class="co">#&gt; Proportion Var   0.647</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; The degrees of freedom for the model is 2 and the fit was 0.023</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Questa quantità indica quanta parte della <em>varianza totale</em> delle quattro variabili manifeste è spiegata dal fattore comune.</p>
<p>Ricordiamo che, per <em>varianza totale</em> in statistica multivariata, si intende la somma delle varianze delle variabili osservate (cioè la <em>traccia</em> della matrice di covarianza). Se le variabili sono standardizzate, ciascuna contribuisce con 1 alla varianza complessiva, quindi, con quattro variabili, la varianza totale risulta 4.</p>
<p>La <em>quota</em> della varianza totale spiegata dal modello fattoriale a un fattore è data dalla somma delle comunalità di ogni variabile, ossia dalle saturazioni fattoriali (loadings) <em>al quadrato</em>, sommate tra loro. Nell’esempio, il valore ottenuto è 2.587; perciò la proporzione di varianza spiegata è</p>
<p><span class="math display">\[
\frac{2.587}{4} \approx 0.647,
\]</span></p>
<p>che <code><a href="https://rdrr.io/r/stats/factanal.html">factanal()</a></code> riporta come <code>Proportion Var</code>.</p>
<p>La parte di varianza di ciascuna variabile <em>non</em> spiegata dal fattore comune prende il nome di <em>unicità</em> (in inglese <em>uniqueness</em>). Nel risultato di <code><a href="https://rdrr.io/r/stats/factanal.html">factanal()</a></code>, l’unicità di ogni variabile si ottiene con <code>fm$uniqueness</code>. La <em>comunalità</em> (ovvero la quota di varianza spiegata dal fattore comune) si ricava da <code>1 - fm$uniqueness</code>, oppure calcolando direttamente il quadrato di ogni saturazione fattoriale.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">L</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">fm</span><span class="op">$</span><span class="va">load</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="va">fm</span><span class="op">$</span><span class="va">load</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>, <span class="va">fm</span><span class="op">$</span><span class="va">load</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span>, <span class="va">fm</span><span class="op">$</span><span class="va">load</span><span class="op">[</span><span class="fl">4</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">L</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 0.9563 0.8194 0.7350 0.6790</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Eseguendo il prodotto interno <code>t(L) %*% L</code>, infatti, si ottiene la somma dei quadrati delle saturazioni (le cosiddette <em>squared loadings</em>), che fornisce la comunalità totale spiegata dal fattore per l’insieme delle variabili.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">L</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">L</span> </span>
<span><span class="co">#&gt;       [,1]</span></span>
<span><span class="co">#&gt; [1,] 2.587</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section><section id="covarianza-tra-due-variabili-manifeste" class="level2" data-number="21.4"><h2 data-number="21.4" class="anchored" data-anchor-id="covarianza-tra-due-variabili-manifeste">
<span class="header-section-number">21.4</span> Covarianza tra due variabili manifeste</h2>
<p>Consideriamo due variabili manifeste <span class="math inline">\(Y_i\)</span> e <span class="math inline">\(Y_k\)</span> con media nulla, ossia <span class="math inline">\(\mathbb{E}(Y_i) = \mathbb{E}(Y_k) = 0\)</span>. In questa ipotesi, la loro covarianza è data da:</p>
<p><span class="math display">\[
\mathrm{Cov}(Y_i, Y_k)
= \mathbb{E}(Y_i \, Y_k)
  - \mathbb{E}(Y_i)\,\mathbb{E}(Y_k)
= \mathbb{E}(Y_i \, Y_k).
\]</span></p>
<p>Nel <em>modello monofattoriale</em>, ogni variabile si esprime come <span class="math inline">\(Y_i = \lambda_i \,\xi + \delta_i\)</span>, dove <span class="math inline">\(\xi\)</span> è il fattore comune e <span class="math inline">\(\delta_i\)</span> è il fattore specifico. Sostituendo queste espressioni nella formula della covarianza, otteniamo:</p>
<p><span class="math display">\[
\mathrm{Cov}(Y_i, Y_k)
= \mathbb{E}\bigl((\lambda_i \,\xi + \delta_i)
                  (\lambda_k \,\xi + \delta_k)\bigr).
\]</span></p>
<p>Espandendo il prodotto dentro l’aspettazione:</p>
<p><span class="math display">\[
= \mathbb{E}\bigl(\lambda_i\,\lambda_k \,\xi^2
                + \lambda_i\,\xi\,\delta_k
                + \lambda_k\,\delta_i\,\xi
                + \delta_i\,\delta_k\bigr).
\]</span></p>
<p>A questo punto, si applicano le ipotesi del modello:</p>
<ol type="1">
<li>
<span class="math inline">\(\mathbb{E}(\xi^2) = \mathbb{V}(\xi) = 1\)</span>.</li>
<li>
<span class="math inline">\(\mathrm{Cov}(\xi, \delta_i) = 0\)</span>, dunque <span class="math inline">\(\mathbb{E}(\xi \,\delta_i) = 0\)</span>.</li>
<li>
<span class="math inline">\(\mathrm{Cov}(\delta_i, \delta_k) = 0\)</span>, cioè <span class="math inline">\(\mathbb{E}(\delta_i \,\delta_k) = 0\)</span>.</li>
</ol>
<p>Applicandole ai termini sopra, abbiamo:</p>
<p><span class="math display">\[
\mathrm{Cov}(Y_i, Y_k)
= \lambda_i\,\lambda_k\,\underbrace{\mathbb{E}(\xi^2)}_{=1}
  + \lambda_i \,\underbrace{\mathbb{E}(\xi\,\delta_k)}_{=0}
  + \lambda_k \,\underbrace{\mathbb{E}(\delta_i\,\xi)}_{=0}
  + \underbrace{\mathbb{E}(\delta_i\,\delta_k)}_{=0}
= \lambda_i \,\lambda_k.
\]</span></p>
<p><strong>In sintesi</strong>, in un modello a singolo fattore, la covarianza tra due variabili manifeste <span class="math inline">\(Y_i\)</span> e <span class="math inline">\(Y_k\)</span> è interamente spiegata dal fattore comune <span class="math inline">\(\xi\)</span> e risulta pari al prodotto delle rispettive saturazioni fattoriali <span class="math inline">\(\lambda_i\)</span> e <span class="math inline">\(\lambda_k\)</span>.</p>
</section><section id="correlazioni-osservate-e-correlazioni-riprodotte-dal-modello" class="level2" data-number="21.5"><h2 data-number="21.5" class="anchored" data-anchor-id="correlazioni-osservate-e-correlazioni-riprodotte-dal-modello">
<span class="header-section-number">21.5</span> Correlazioni osservate e correlazioni riprodotte dal modello</h2>
<p>Nel modello monofattoriale, l’ipotesi di base è che il <em>fattore comune</em> spieghi <em>tutta</em> la covarianza tra le variabili osservate. In altre parole, ci aspettiamo che, una volta noto il valore del fattore comune <span class="math inline">\(\xi\)</span>, ogni variabile <span class="math inline">\(Y_i\)</span> sia incorrelata con le altre <span class="math inline">\((Y_k)\)</span>. Formalmente, ciò si traduce nell’uguaglianza:</p>
<p><span class="math display">\[
\mathrm{Cov}(Y_i, Y_k \,\mid\, \xi) = 0
\quad\text{per}\quad
i \neq k.
\]</span></p>
<p>Se questa condizione risulta soddisfatta, il modello monofattoriale riproduce correttamente le <em>correlazioni</em> osservate fra le variabili. Con il termine <span class="math inline">\(\boldsymbol{\Sigma}\)</span> si indica la <em>matrice di correlazioni riprodotte</em> dal modello, che in forma matriciale si esprime come:</p>
<p><span class="math display">\[
\boldsymbol{\Sigma}
= \boldsymbol{\Lambda}\,\boldsymbol{\Lambda}^{\prime}
  + \boldsymbol{\Psi},
\]</span></p>
<p>dove <span class="math inline">\(\boldsymbol{\Lambda}\)</span> è la matrice delle <em>saturazioni fattoriali</em> (loadings) e <span class="math inline">\(\boldsymbol{\Psi}\)</span> è la matrice delle <em>unicità</em> (cioè le varianze specifiche non spiegate dal fattore comune).</p>
<p>Il modello monofattoriale si considera <em>adeguato</em> se la differenza tra la matrice di correlazioni empiricamente osservate e la matrice <span class="math inline">\(\boldsymbol{\Sigma}\)</span> prodotta dal modello risulta trascurabile. Quando tale differenza (chiamata spesso <em>misura di scostamento</em> o <em>misfit</em>) è prossima allo zero, possiamo concludere che il fattore comune riesce a spiegare in modo soddisfacente i rapporti di correlazione tra le variabili del nostro insieme di dati.</p>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Esempio 21.2</strong></span> Per i dati di Spearman, le correlazioni riprodotte dal modello ad un fattore sono</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">L</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">L</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="va">fm</span><span class="op">$</span><span class="va">uniq</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span></span>
<span><span class="co">#&gt;       [,1]  [,2]  [,3]  [,4]</span></span>
<span><span class="co">#&gt; [1,] 1.000 0.784 0.703 0.649</span></span>
<span><span class="co">#&gt; [2,] 0.784 1.000 0.602 0.556</span></span>
<span><span class="co">#&gt; [3,] 0.703 0.602 1.000 0.499</span></span>
<span><span class="co">#&gt; [4,] 0.649 0.556 0.499 1.000</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>La matrice delle differenze tra le correlazioni campionarie e quelle riprodotte è</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">Spearman</span> <span class="op">-</span> <span class="op">(</span><span class="va">L</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">L</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="va">fm</span><span class="op">$</span><span class="va">uniq</span><span class="op">)</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span> </span>
<span><span class="co">#&gt;        C      E      M      P</span></span>
<span><span class="co">#&gt; C  0.000 -0.004 -0.003  0.011</span></span>
<span><span class="co">#&gt; E -0.004  0.000  0.038 -0.016</span></span>
<span><span class="co">#&gt; M -0.003  0.038  0.000 -0.049</span></span>
<span><span class="co">#&gt; P  0.011 -0.016 -0.049  0.000</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Lo scarto maggiore tra le correlazioni campionarie e quelle riprodotte è uguale a 0.049. Si può dunque concludere che il modello monofattoriale spiega in maniera ragionevole i dati di Spearman.</p>
</div>
</section><section id="bontà-di-adattamento-del-modello-ai-dati" class="level2" data-number="21.6"><h2 data-number="21.6" class="anchored" data-anchor-id="bontà-di-adattamento-del-modello-ai-dati">
<span class="header-section-number">21.6</span> Bontà di adattamento del modello ai dati</h2>
<p>Un aspetto fondamentale nell’analisi fattoriale è valutare se la <em>matrice di correlazioni</em> (o <em>covarianze</em>) prevista dal modello rispecchia adeguatamente i dati empirici. A tal scopo, si conduce un test statistico che confronta la matrice di correlazioni/covarianze <em>osservata</em> con quella <em>predetta</em> dal modello fattoriale.</p>
<section id="lipotesi-nulla-del-test" class="level3" data-number="21.6.1"><h3 data-number="21.6.1" class="anchored" data-anchor-id="lipotesi-nulla-del-test">
<span class="header-section-number">21.6.1</span> L’ipotesi nulla del test</h3>
<p>L’ipotesi nulla (<span class="math inline">\(H_0\)</span>) afferma che le differenze tra le correlazioni osservate e quelle riprodotte dal modello siano dovute soltanto agli errori di campionamento. In altre parole, il modello è considerato “corretto” a livello di popolazione, ossia <span class="math inline">\(\boldsymbol{\Sigma}(\theta) = \boldsymbol{\Sigma}\)</span>, dove:</p>
<ul>
<li>
<span class="math inline">\(\boldsymbol{\Sigma}\)</span> è la matrice di correlazioni (o covarianze) nella <em>popolazione</em>;</li>
<li>
<span class="math inline">\(\boldsymbol{\Sigma}(\theta)\)</span> è la matrice di correlazioni (o covarianze) riprodotta dal modello in base ai parametri <span class="math inline">\(\theta\)</span>.</li>
</ul></section><section id="la-statistica-chi2" class="level3" data-number="21.6.2"><h3 data-number="21.6.2" class="anchored" data-anchor-id="la-statistica-chi2">
<span class="header-section-number">21.6.2</span> La statistica <span class="math inline">\(\chi^2\)</span>
</h3>
<p>La statistica usata per il test, indicata come <span class="math inline">\(v\)</span> (o più comunemente <span class="math inline">\(\chi^2\)</span>), è funzione della differenza tra <span class="math inline">\(\boldsymbol{S}\)</span> (la matrice osservata) e <span class="math inline">\(\boldsymbol{S}(\theta)\)</span> (la matrice riprodotta dal modello):</p>
<p><span id="eq-chisq-gof"><span class="math display">\[
v = f\bigl[\boldsymbol{S}(\theta) - \boldsymbol{S}\bigr].
\tag{21.3}\]</span></span></p>
<p>Quando l’ipotesi nulla è vera (cioè la <em>discrepanza</em> tra le due matrici è solo casuale), <span class="math inline">\(v\)</span> si distribuisce approssimativamente come una <span class="math inline">\(\chi^2\)</span> con <span class="math inline">\(\nu\)</span> gradi di libertà, dove</p>
<p><span id="eq-chisq-gof-nu"><span class="math display">\[
\nu = \frac{p(p+1)}{2} \;-\; q.
\tag{21.4}\]</span></span></p>
<ul>
<li>
<span class="math inline">\(p\)</span> è il numero di variabili manifeste;</li>
<li>
<span class="math inline">\(q\)</span> è il numero di parametri stimati dal modello (ad esempio, <span class="math inline">\(\lambda\)</span> e <span class="math inline">\(\psi\)</span> nel modello monofattoriale).</li>
</ul>
<p>Il valore di <span class="math inline">\(v\)</span> è <em>tanto maggiore quanto più le correlazioni/covarianze previste dal modello differiscono da quelle effettivamente osservate</em>. Se <span class="math inline">\(v=0\)</span>, i parametri del modello ricostruiscono <em>esattamente</em> la matrice di correlazioni della popolazione.</p>
</section><section id="interpretazione-del-test" class="level3" data-number="21.6.3"><h3 data-number="21.6.3" class="anchored" data-anchor-id="interpretazione-del-test">
<span class="header-section-number">21.6.3</span> Interpretazione del test</h3>
<p>Il test <span class="math inline">\(\chi^2\)</span> di adattamento del modello fattoriale segue la logica inversa rispetto ai test più comuni (dove un risultato significativo indica evidenza per l’ipotesi alternativa):</p>
<ul>
<li>se il test <em>non</em> è significativo (es., <span class="math inline">\(p\geq 0{,}05\)</span>), non si può escludere che la discrepanza tra matrice osservata e matrice stimata sia dovuta al caso: in tal caso, il modello è considerato adeguato;</li>
<li>al contrario, un risultato <em>significativo</em> (es., <span class="math inline">\(p &lt; 0{,}05\)</span>) indica che la differenza non si spiega solo con l’errore di campionamento e che il modello presenta <em>carenze di adattamento</em> ai dati.</li>
</ul></section><section id="assunzioni-e-limiti" class="level3" data-number="21.6.4"><h3 data-number="21.6.4" class="anchored" data-anchor-id="assunzioni-e-limiti">
<span class="header-section-number">21.6.4</span> Assunzioni e limiti</h3>
<ol type="1">
<li>
<strong>Normalità multivariata</strong>: il test <span class="math inline">\(\chi^2\)</span> richiede che le variabili siano distribuite (almeno approssimativamente) come un campione casuale tratto da una distribuzione normale multivariata. Nella pratica, non sempre questa condizione è soddisfatta.</li>
<li>
<strong>Dimensioni campionarie</strong>: la statistica <span class="math inline">\(\chi^2\)</span> è <em>sensibile</em> al numero di osservazioni. Con campioni di grandi dimensioni, anche piccole discrepanze tra il modello e i dati tendono a produrre risultati statisticamente significativi, suggerendo un <em>falso</em> cattivo adattamento.</li>
</ol>
<p>Per questi motivi, la bontà di adattamento del modello non si giudica solo in base alla significatività del test <span class="math inline">\(\chi^2\)</span>. Un criterio alternativo è ad esempio valutare il <strong>rapporto <span class="math inline">\(\chi^2/\nu\)</span></strong>, dove <span class="math inline">\(\nu\)</span> sono i gradi di libertà del test. Valori di <span class="math inline">\(\chi^2/\nu \leq 3\)</span> (o talvolta <span class="math inline">\(\leq 4\)</span>) sono spesso considerati indicativi di un adattamento accettabile. Inoltre, in letteratura esistono molti altri indici (<em>fit indices</em>) che completano la valutazione della bontà di adattamento del modello fattoriale.</p>
</section></section><section id="lerrore-standard-della-misurazione-nel-modello-fattoriale" class="level2" data-number="21.7"><h2 data-number="21.7" class="anchored" data-anchor-id="lerrore-standard-della-misurazione-nel-modello-fattoriale">
<span class="header-section-number">21.7</span> L’errore standard della misurazione nel modello fattoriale</h2>
<p>In questa sezione, mostriamo come il <em>concetto di errore standard di misurazione</em>, tipico della CTT, possa essere reinterpretato tramite il <em>modello fattoriale</em>.</p>
<section id="collegamento-tra-ctt-e-analisi-fattoriale" class="level3" data-number="21.7.1"><h3 data-number="21.7.1" class="anchored" data-anchor-id="collegamento-tra-ctt-e-analisi-fattoriale">
<span class="header-section-number">21.7.1</span> Collegamento tra CTT e analisi fattoriale</h3>
<p>Secondo la CTT, il punteggio osservato <span class="math inline">\(X\)</span> di un test si scompone in due parti:</p>
<p><span class="math display">\[
X = T + E,
\]</span></p>
<p>dove:</p>
<ul>
<li>
<span class="math inline">\(T\)</span> è il <em>valore vero</em> del soggetto,</li>
<li>
<span class="math inline">\(E\)</span> è l’<em>errore di misurazione</em>, considerato una variabile casuale con media zero, indipendente da <span class="math inline">\(T\)</span>.</li>
</ul>
<p>Se consideriamo un modello fattoriale <em>monofattoriale</em> con <span class="math inline">\(p\)</span> item (variabili osservate), la relazione che descrive ciascun item <span class="math inline">\(j\)</span> per il soggetto <span class="math inline">\(i\)</span> è:</p>
<p><span class="math display">\[
Y_{ji} = \lambda_j \,\xi_i + \delta_{ji},
\]</span></p>
<p>dove:</p>
<ul>
<li>
<span class="math inline">\(Y_{ji}\)</span> è il punteggio osservato nell’item <span class="math inline">\(j\)</span>,</li>
<li>
<span class="math inline">\(\xi_i\)</span> è il fattore comune (latente) per il soggetto <span class="math inline">\(i\)</span>,</li>
<li>
<span class="math inline">\(\lambda_j\)</span> è il <em>carico fattoriale</em> dell’item <span class="math inline">\(j\)</span> sul fattore <span class="math inline">\(\xi\)</span>,</li>
<li>
<span class="math inline">\(\delta_{ji}\)</span> è l’errore unico (o fattore specifico) relativo all’item <span class="math inline">\(j\)</span>.</li>
</ul>
<p>Il <strong>punteggio totale</strong> <span class="math inline">\(X_i\)</span> del soggetto <span class="math inline">\(i\)</span> si ottiene sommando i punteggi dei singoli item:</p>
<p><span class="math display">\[
X_i
= \sum_{j=1}^p Y_{ji}
= \sum_{j=1}^p (\lambda_j \,\xi_i + \delta_{ji})
= \biggl(\sum_{j=1}^p \lambda_j\biggr)\,\xi_i
  + \sum_{j=1}^p \delta_{ji}.
\]</span></p>
<p>Notiamo che questa formula rispecchia la struttura della CTT <span class="citation" data-cites="mcdonald2013test">(<a href="../../99-references.html#ref-mcdonald2013test" role="doc-biblioref">McDonald, 2013</a>)</span>:</p>
<p><span class="math display">\[
X_i = T_i + E_i,
\]</span></p>
<p>dove il <em>valore vero</em> <span class="math inline">\(T_i\)</span> è <span class="math inline">\(\bigl(\sum_{j=1}^p \lambda_j\bigr)\,\xi_i\)</span> (la parte del punteggio dovuta al fattore comune) e l’<em>errore</em> <span class="math inline">\(E_i\)</span> è <span class="math inline">\(\sum_{j=1}^p \delta_{ji}\)</span> (la somma degli errori unici).</p>
</section><section id="decomposizione-della-varianza" class="level3" data-number="21.7.2"><h3 data-number="21.7.2" class="anchored" data-anchor-id="decomposizione-della-varianza">
<span class="header-section-number">21.7.2</span> Decomposizione della varianza</h3>
<p>Nella CTT, la varianza del punteggio osservato <span class="math inline">\(\sigma^2_{X_i}\)</span> si scompone nella varianza del valore vero (<span class="math inline">\(\sigma^2_{T_i}\)</span>) e nella varianza dell’errore (<span class="math inline">\(\sigma^2_{E_i}\)</span>):</p>
<p><span class="math display">\[
\sigma^2_{X_i}
= \sigma^2_{T_i} + \sigma^2_{E_i}.
\]</span></p>
<p>All’interno del modello fattoriale, la <em>varianza del valore vero</em> (<span class="math inline">\(\sigma^2_{T_i}\)</span>) corrisponde alla varianza del termine <span class="math inline">\(\bigl(\sum_{j=1}^p \lambda_j\bigr)\,\xi_i\)</span>. Poiché <span class="math inline">\(\xi_i\)</span> ha varianza unitaria (<span class="math inline">\(\mathbb{V}(\xi_i)=1\)</span>), si ha:</p>
<p><span class="math display">\[
\sigma^2_{T_i}
= \mathbb{V}\Biggl[\biggl(\sum_{j=1}^p \lambda_j\biggr)\,\xi_i\Biggr]
= \biggl(\sum_{j=1}^p \lambda_j\biggr)^2 \,\mathbb{V}(\xi_i)
= \biggl(\sum_{j=1}^p \lambda_j\biggr)^2.
\]</span></p>
<p>La <em>varianza dell’errore</em> (<span class="math inline">\(\sigma^2_{E_i}\)</span>), invece, è la varianza della somma degli errori unici <span class="math inline">\(\sum_{j=1}^p \delta_{ji}\)</span>. Nel modello fattoriale, si assume che gli errori <span class="math inline">\(\delta_{ji}\)</span> siano incorrelati tra loro, per cui:</p>
<p><span class="math display">\[
\sigma^2_{E_i}
= \mathbb{V}\Biggl(\sum_{j=1}^p \delta_{ji}\Biggr)
= \sum_{j=1}^p \mathbb{V}(\delta_{ji})
= \sum_{j=1}^p \Psi_j,
\]</span></p>
<p>dove <span class="math inline">\(\Psi_j\)</span> è la varianza (unicità) associata all’errore dell’item <span class="math inline">\(j\)</span>.</p>
</section><section id="errore-standard-di-misurazione" class="level3" data-number="21.7.3"><h3 data-number="21.7.3" class="anchored" data-anchor-id="errore-standard-di-misurazione">
<span class="header-section-number">21.7.3</span> Errore standard di misurazione</h3>
<p>Nella CTT, <em>l’errore standard di misurazione</em> di un test quantifica, in media, quanto il punteggio osservato può differire dal valore vero <span class="math inline">\(T_i\)</span>. Nel modello fattoriale, <strong>l’errore standard di misurazione del punteggio totale</strong> è la radice quadrata della somma delle varianze degli errori unici:</p>
<p><span class="math display">\[
\sigma_E
= \sqrt{\sigma^2_{E_i}}
= \sqrt{\sum_{j=1}^p \Psi_j}.
\]</span></p>
<p>Questo fornisce una visione fattoriale dell’errore di misurazione: la precisione di un test (intesa come minore ampiezza dell’errore) aumenta al diminuire della somma delle unicità dei singoli item.</p>
<p><strong>In sintesi</strong>, il modello fattoriale arricchisce il tradizionale concetto di errore standard di misurazione della CTT, mostrando che l’errore (<em>specifico</em> o <em>unico</em>) di ciascun item influisce cumulativamente sulla precisione del punteggio totale. In altre parole, <strong>gli item che presentano carichi fattoriali elevati</strong> contribuiscono a ridurre l’errore complessivo di misurazione, mentre <strong>le loro corrispettive unicità</strong> (varianze specifiche non spiegate dal fattore comune) aumentano l’incertezza del punteggio totale. Questo legame tra CTT e analisi fattoriale offre <em>un’ottica ulteriore</em> per comprendere e quantificare la precisione dei test psicometrici.</p>
</section></section><section id="un-esempio-concreto" class="level2" data-number="21.8"><h2 data-number="21.8" class="anchored" data-anchor-id="un-esempio-concreto">
<span class="header-section-number">21.8</span> Un esempio concreto</h2>
<p>Vediamo ora come applicare i concetti del modello monofattoriale e dell’errore standard di misurazione a un caso reale. Utilizzeremo i dati raccolti per la validazione italiana del <em>Cognitive Style Questionnaire – Short Form</em> (CSQ-SF, Meins et al.&nbsp;2012). Questo questionario, volto a misurare la vulnerabilità all’ansia e alla depressione, comprende cinque sottoscale: <em>Internality</em> (<code>I</code>), <em>Globality</em> (<code>G</code>), <em>Stability</em> (<code>S</code>), <em>Negative consequences</em> (<code>N</code>) e <em>Self-worth</em> (<code>W</code>). Sebbene la sottoscala di <em>Internality</em> risulti problematica, la includiamo nell’analisi per illustrare la procedura completa.</p>
<section id="lettura-e-ispezione-preliminare-dei-dati" class="level3" data-number="21.8.1"><h3 data-number="21.8.1" class="anchored" data-anchor-id="lettura-e-ispezione-preliminare-dei-dati">
<span class="header-section-number">21.8.1</span> Lettura e ispezione preliminare dei dati</h3>
<p>In <span class="math inline">\(\textsf{R}\)</span>, carichiamo il dataset e ne verifichiamo la dimensione (<span class="math inline">\(n\)</span>, numero di partecipanti). Per una prima esplorazione, calcoliamo le statistiche descrittive (<code>psych::describe(...)</code>) e visualizziamo la matrice di correlazione con <code>psych::pairs.panels(...)</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">csq</span> <span class="op">&lt;-</span> <span class="fu">rio</span><span class="fu">::</span><span class="fu"><a href="http://gesistsa.github.io/rio/reference/import.html">import</a></span><span class="op">(</span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"data"</span>, <span class="st">"csq540.csv"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">csq</span><span class="op">)</span>                 <span class="co"># Numero di partecipanti</span></span>
<span><span class="fu">psych</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/describe.html">describe</a></span><span class="op">(</span><span class="va">csq</span>, type <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="co"># Statistiche descrittive</span></span>
<span><span class="co">#&gt;   vars   n  mean    sd median trimmed   mad min max range  skew kurtosis</span></span>
<span><span class="co">#&gt; I    1 540 47.76  5.78     48   47.87  4.45  21  64    43 -0.31     1.07</span></span>
<span><span class="co">#&gt; G    2 540 45.00 11.94     42   44.55 11.86  16  78    62  0.34    -0.70</span></span>
<span><span class="co">#&gt; S    3 540 44.60 12.18     42   44.24 13.34  16  77    61  0.27    -0.77</span></span>
<span><span class="co">#&gt; N    4 540 22.01  6.92     21   21.86  7.41   8  39    31  0.21    -0.74</span></span>
<span><span class="co">#&gt; W    5 540 44.05 13.10     43   43.66 13.34  16  79    63  0.31    -0.53</span></span>
<span><span class="co">#&gt;     se</span></span>
<span><span class="co">#&gt; I 0.25</span></span>
<span><span class="co">#&gt; G 0.51</span></span>
<span><span class="co">#&gt; S 0.52</span></span>
<span><span class="co">#&gt; N 0.30</span></span>
<span><span class="co">#&gt; W 0.56</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">psych</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/pairs.panels.html">pairs.panels</a></span><span class="op">(</span><span class="va">csq</span><span class="op">)</span>       <span class="co"># Matrice di correlazione</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="03_analisi_fattoriale_2_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>Ne emerge che la sottoscala <em>Internality</em> (<code>I</code>) presenta alcune criticità — aspetto già segnalato in letteratura.</p>
</section><section id="specifica-e-stima-di-un-modello-unifattoriale" class="level3" data-number="21.8.2"><h3 data-number="21.8.2" class="anchored" data-anchor-id="specifica-e-stima-di-un-modello-unifattoriale">
<span class="header-section-number">21.8.2</span> Specifica e stima di un modello unifattoriale</h3>
<p>Per analizzare i dati secondo un modello fattoriale a un solo fattore, usiamo la sintassi del pacchetto <code>lavaan</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mod_csq</span> <span class="op">&lt;-</span> <span class="st">"</span></span>
<span><span class="st">  F =~ NA*I + G + S + N + W</span></span>
<span><span class="st">  F ~~ 1*F</span></span>
<span><span class="st">"</span></span>
<span><span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu">lavaan</span><span class="fu">:::</span><span class="fu"><a href="https://rdrr.io/pkg/lavaan/man/cfa.html">cfa</a></span><span class="op">(</span><span class="va">mod_csq</span>, data <span class="op">=</span> <span class="va">csq</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Nella prima riga, <code>F =~ NA*I + G + S + N + W</code> indichiamo che il fattore <code>F</code> è definito dai cinque item/sottoscale (<code>I, G, S, N, W</code>), con parametro <code>NA</code> per lasciare libera la stima della prima saturazione.</li>
<li>Nella seconda riga, <code>F ~~ 1*F</code> impone varianza unitaria per il fattore <code>F</code>.</li>
</ul>
<p>Otteniamo il resoconto completo con:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit</span>, standardized <span class="op">=</span> <span class="cn">TRUE</span>, fit.measures <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="co">#&gt; lavaan 0.6-19 ended normally after 26 iterations</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Estimator                                         ML</span></span>
<span><span class="co">#&gt;   Optimization method                           NLMINB</span></span>
<span><span class="co">#&gt;   Number of model parameters                        10</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Number of observations                           540</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Model Test User Model:</span></span>
<span><span class="co">#&gt;                                                       </span></span>
<span><span class="co">#&gt;   Test statistic                                46.716</span></span>
<span><span class="co">#&gt;   Degrees of freedom                                 5</span></span>
<span><span class="co">#&gt;   P-value (Chi-square)                           0.000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Model Test Baseline Model:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Test statistic                              2361.816</span></span>
<span><span class="co">#&gt;   Degrees of freedom                                10</span></span>
<span><span class="co">#&gt;   P-value                                        0.000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; User Model versus Baseline Model:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Comparative Fit Index (CFI)                    0.982</span></span>
<span><span class="co">#&gt;   Tucker-Lewis Index (TLI)                       0.965</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Loglikelihood and Information Criteria:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Loglikelihood user model (H0)              -8741.781</span></span>
<span><span class="co">#&gt;   Loglikelihood unrestricted model (H1)      -8718.423</span></span>
<span><span class="co">#&gt;                                                       </span></span>
<span><span class="co">#&gt;   Akaike (AIC)                               17503.562</span></span>
<span><span class="co">#&gt;   Bayesian (BIC)                             17546.478</span></span>
<span><span class="co">#&gt;   Sample-size adjusted Bayesian (SABIC)      17514.734</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Root Mean Square Error of Approximation:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   RMSEA                                          0.124</span></span>
<span><span class="co">#&gt;   90 Percent confidence interval - lower         0.093</span></span>
<span><span class="co">#&gt;   90 Percent confidence interval - upper         0.158</span></span>
<span><span class="co">#&gt;   P-value H_0: RMSEA &lt;= 0.050                    0.000</span></span>
<span><span class="co">#&gt;   P-value H_0: RMSEA &gt;= 0.080                    0.989</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Standardized Root Mean Square Residual:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   SRMR                                           0.033</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Parameter Estimates:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Standard errors                             Standard</span></span>
<span><span class="co">#&gt;   Information                                 Expected</span></span>
<span><span class="co">#&gt;   Information saturated (h1) model          Structured</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Latent Variables:</span></span>
<span><span class="co">#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all</span></span>
<span><span class="co">#&gt;   F =~                                                                  </span></span>
<span><span class="co">#&gt;     I                 0.725    0.253    2.867    0.004    0.725    0.126</span></span>
<span><span class="co">#&gt;     G               -11.322    0.384  -29.481    0.000  -11.322   -0.949</span></span>
<span><span class="co">#&gt;     S               -11.342    0.398  -28.513    0.000  -11.342   -0.932</span></span>
<span><span class="co">#&gt;     N                -6.163    0.233  -26.398    0.000   -6.163   -0.891</span></span>
<span><span class="co">#&gt;     W               -11.598    0.444  -26.137    0.000  -11.598   -0.886</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Variances:</span></span>
<span><span class="co">#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all</span></span>
<span><span class="co">#&gt;     F                 1.000                               1.000    1.000</span></span>
<span><span class="co">#&gt;    .I                32.840    2.000   16.420    0.000   32.840    0.984</span></span>
<span><span class="co">#&gt;    .G                14.038    1.473    9.532    0.000   14.038    0.099</span></span>
<span><span class="co">#&gt;    .S                19.508    1.718   11.353    0.000   19.508    0.132</span></span>
<span><span class="co">#&gt;    .N                 9.847    0.725   13.573    0.000    9.847    0.206</span></span>
<span><span class="co">#&gt;    .W                36.892    2.685   13.737    0.000   36.892    0.215</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>e le stime dei parametri con:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">parameterEstimates</span><span class="op">(</span><span class="va">fit</span><span class="op">)</span></span>
<span><span class="co">#&gt;    lhs op rhs     est    se       z pvalue ci.lower ci.upper</span></span>
<span><span class="co">#&gt; 1    F =~   I   0.725 0.253   2.867  0.004    0.229    1.220</span></span>
<span><span class="co">#&gt; 2    F =~   G -11.322 0.384 -29.481  0.000  -12.075  -10.569</span></span>
<span><span class="co">#&gt; 3    F =~   S -11.342 0.398 -28.513  0.000  -12.122  -10.563</span></span>
<span><span class="co">#&gt; 4    F =~   N  -6.163 0.233 -26.398  0.000   -6.621   -5.705</span></span>
<span><span class="co">#&gt; 5    F =~   W -11.598 0.444 -26.137  0.000  -12.467  -10.728</span></span>
<span><span class="co">#&gt; 6    F ~~   F   1.000 0.000      NA     NA    1.000    1.000</span></span>
<span><span class="co">#&gt; 7    I ~~   I  32.840 2.000  16.420  0.000   28.920   36.759</span></span>
<span><span class="co">#&gt; 8    G ~~   G  14.038 1.473   9.532  0.000   11.151   16.924</span></span>
<span><span class="co">#&gt; 9    S ~~   S  19.508 1.718  11.353  0.000   16.140   22.876</span></span>
<span><span class="co">#&gt; 10   N ~~   N   9.847 0.725  13.573  0.000    8.425   11.269</span></span>
<span><span class="co">#&gt; 11   W ~~   W  36.892 2.685  13.737  0.000   31.628   42.155</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In particolare, ci soffermiamo sulle <em>unicità</em> (varianze specifiche di ciascuna sottoscala), accessibili da:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">psi</span> <span class="op">&lt;-</span> <span class="fu">parameterEstimates</span><span class="op">(</span><span class="va">fit</span><span class="op">)</span><span class="op">$</span><span class="va">est</span><span class="op">[</span><span class="fl">7</span><span class="op">:</span><span class="fl">11</span><span class="op">]</span></span>
<span><span class="va">psi</span></span>
<span><span class="co">#&gt; [1] 32.840 14.038 19.508  9.847 36.892</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="stima-dellerrore-standard-di-misurazione-tramite-il-modello-fattoriale" class="level3" data-number="21.8.3"><h3 data-number="21.8.3" class="anchored" data-anchor-id="stima-dellerrore-standard-di-misurazione-tramite-il-modello-fattoriale">
<span class="header-section-number">21.8.3</span> Stima dell’errore standard di misurazione tramite il modello fattoriale</h3>
<p>Nel modello fattoriale monofattoriale, <em>l’errore standard di misurazione</em> di un punteggio totale è la radice quadrata della somma delle varianze specifiche (unicità). Con le stime ottenute da lavaan, basta sommare i valori <span class="math inline">\(\psi_j\)</span> e prenderne la radice quadrata:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">psi</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 10.64</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Questo valore rappresenta l’errore standard complessivo del <em>punteggio totale</em> calcolato sui cinque item (sottoscale).</p>
</section><section id="confronto-con-la-formula-della-ctt" class="level3" data-number="21.8.4"><h3 data-number="21.8.4" class="anchored" data-anchor-id="confronto-con-la-formula-della-ctt">
<span class="header-section-number">21.8.4</span> Confronto con la formula della CTT</h3>
<p>Ricordiamo la <em>formula classica</em> per l’errore standard di misurazione nella <strong>Classical Test Theory (CTT)</strong>:</p>
<p><span class="math display">\[
\sigma_E = \sigma_X \sqrt{1 - \rho_{XX'}},
\]</span></p>
<p>dove <span class="math inline">\(\sigma_X\)</span> è la <em>deviazione standard del punteggio totale</em> e <span class="math inline">\(\rho_{XX'}\)</span> è l’<em>attendibilità</em> (affidabilità) del test.</p>
<ol type="1">
<li>
<p>Calcoliamo il <strong>punteggio totale</strong> come somma delle sottoscale:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">tot_score</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowSums</a></span><span class="op">(</span><span class="va">csq</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</li>
<li>
<p>Otteniamo la <strong>deviazione standard</strong> di <code>tot_score</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sigma</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">tot_score</span><span class="op">)</span></span>
<span><span class="va">sigma</span></span>
<span><span class="co">#&gt; [1] 41.26</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</li>
<li>
<p>Stimiamo l’<strong>attendibilità</strong> <span class="math inline">\(\rho_{XX'}\)</span> (qui indicata da <span class="math inline">\(\Omega\)</span>) con la funzione <code><a href="https://rdrr.io/pkg/semTools/man/semTools-deprecated.html">semTools::reliability()</a></code> applicata all’oggetto <code>fit</code> prodotto da <code>lavaan</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">rel</span> <span class="op">&lt;-</span> <span class="fu">semTools</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/semTools/man/semTools-deprecated.html">reliability</a></span><span class="op">(</span><span class="va">fit</span><span class="op">)</span></span>
<span><span class="va">rel</span></span>
<span><span class="co">#&gt;             F</span></span>
<span><span class="co">#&gt; alpha  0.8507</span></span>
<span><span class="co">#&gt; omega  0.9330</span></span>
<span><span class="co">#&gt; omega2 0.9330</span></span>
<span><span class="co">#&gt; omega3 0.9273</span></span>
<span><span class="co">#&gt; avevar 0.7917</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Il valore di <span class="math inline">\(\Omega\)</span> è tipicamente riportato nella seconda riga di <code>rel</code>.</p>
</li>
<li>
<p>Applichiamo la formula:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sigma</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">rel</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 10.68</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</li>
</ol>
<p>Il valore ottenuto risulta molto simile all’errore standard di misurazione calcolato con la formula di derivazione fattoriale <span class="math inline">\(\sqrt{\sum_{j=1}^p \Psi_j}\)</span>, a conferma della coerenza tra il modello fattoriale e la CTT.</p>
</section><section id="correlazioni-riprodotte-dal-modello" class="level3" data-number="21.8.5"><h3 data-number="21.8.5" class="anchored" data-anchor-id="correlazioni-riprodotte-dal-modello">
<span class="header-section-number">21.8.5</span> Correlazioni riprodotte dal modello</h3>
<p>Per ispezionare <em>come</em> il modello unifattoriale “ricostruisce” le correlazioni tra le variabili, possiamo estrarre:</p>
<ul>
<li>
<p>La <strong>matrice di correlazione riprodotta</strong>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cor_mat</span> <span class="op">&lt;-</span> <span class="fu">lavInspect</span><span class="op">(</span><span class="va">fit</span>, <span class="st">"cor.ov"</span><span class="op">)</span></span>
<span><span class="va">cor_mat</span></span>
<span><span class="co">#&gt;        I      G      S      N      W</span></span>
<span><span class="co">#&gt; I  1.000                            </span></span>
<span><span class="co">#&gt; G -0.119  1.000                     </span></span>
<span><span class="co">#&gt; S -0.117  0.885  1.000              </span></span>
<span><span class="co">#&gt; N -0.112  0.846  0.830  1.000       </span></span>
<span><span class="co">#&gt; W -0.111  0.841  0.825  0.789  1.000</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</li>
<li>
<p>Le <strong>saturazioni fattoriali standardizzate</strong> (loadings):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">l</span> <span class="op">&lt;-</span> <span class="fu">inspect</span><span class="op">(</span><span class="va">fit</span>, what<span class="op">=</span><span class="st">"std"</span><span class="op">)</span><span class="op">$</span><span class="va">lambda</span></span>
<span><span class="va">l</span></span>
<span><span class="co">#&gt;        F</span></span>
<span><span class="co">#&gt; I  0.126</span></span>
<span><span class="co">#&gt; G -0.949</span></span>
<span><span class="co">#&gt; S -0.932</span></span>
<span><span class="co">#&gt; N -0.891</span></span>
<span><span class="co">#&gt; W -0.886</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</li>
</ul>
<p>Nel modello monofattoriale, la <strong>correlazione predetta</strong> tra due variabili manifeste (ad esempio <code>I</code> e <code>G</code>) è data dal <em>prodotto</em> delle loro saturazioni. Se <code>l[1]</code> è la saturazione di <code>I</code> e <code>l[2]</code> quella di <code>G</code>, allora:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">l</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">*</span> <span class="va">l</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span></span>
<span><span class="co">#&gt; [1] -0.1192</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>restituisce la correlazione stimata per queste due sottoscale. Per visualizzare la <em>matrice completa</em> delle correlazioni riprodotte dal modello, calcoliamo:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">l</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">l</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span></span>
<span><span class="co">#&gt;        I      G      S      N      W</span></span>
<span><span class="co">#&gt; I  0.016 -0.119 -0.117 -0.112 -0.111</span></span>
<span><span class="co">#&gt; G -0.119  0.901  0.885  0.846  0.841</span></span>
<span><span class="co">#&gt; S -0.117  0.885  0.868  0.830  0.825</span></span>
<span><span class="co">#&gt; N -0.112  0.846  0.830  0.794  0.789</span></span>
<span><span class="co">#&gt; W -0.111  0.841  0.825  0.789  0.785</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="varianza-riprodotta-di-una-variabile" class="level3" data-number="21.8.6"><h3 data-number="21.8.6" class="anchored" data-anchor-id="varianza-riprodotta-di-una-variabile">
<span class="header-section-number">21.8.6</span> Varianza riprodotta di una variabile</h3>
<p>Prendiamo a esempio la variabile <span class="math inline">\(`W`\)</span> e confrontiamo:</p>
<ul>
<li>
<p>La <strong>varianza osservata</strong>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">var</a></span><span class="op">(</span><span class="va">csq</span><span class="op">$</span><span class="va">W</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 171.7</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</li>
<li>
<p>La <strong>varianza riprodotta</strong> dal modello: somma della varianza spiegata dal fattore e della varianza residua. Poiché il caricamento fattoriale standardizzato per <code>W</code> (ad esempio <code>-11.598</code> nel caso di non standardizzazione, o un valore <span class="math inline">\(\lambda_W\)</span> in quello standardizzato) misura l’effetto di <code>F</code> su <code>W</code>, la parte spiegata è <span class="math inline">\(\lambda_W^2\)</span>. Sommando poi la specificità (residuo), ricostruiamo la varianza totale. Se prendiamo la proporzione di varianza residua rispetto a quella osservata:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fl">1</span> <span class="op">-</span> <span class="op">(</span><span class="va">l</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">var</a></span><span class="op">(</span><span class="va">csq</span><span class="op">$</span><span class="va">W</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt;       F</span></span>
<span><span class="co">#&gt; I 1.000</span></span>
<span><span class="co">#&gt; G 0.995</span></span>
<span><span class="co">#&gt; S 0.995</span></span>
<span><span class="co">#&gt; N 0.995</span></span>
<span><span class="co">#&gt; W 0.995</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>otteniamo un valore simile all’unicità stimata per <code>W</code>.</p>
</li>
</ul>
<p>Procedendo nello stesso modo per le altre sottoscale (<code>G</code>, <code>I</code>, ecc.) possiamo verificare la corrispondenza fra la varianza empirica e la varianza spiegata dal modello unifattoriale.</p>
<p><strong>In sintesi</strong>, questo esempio illustra come, in un modello unifattoriale, sia possibile collegare:</p>
<ol type="1">
<li>
<strong>errori standard di misurazione</strong> (CTT) e <strong>somme di unicità</strong> degli item (analisi fattoriale);</li>
<li>
<strong>correlazioni osservate</strong> e <strong>correlazioni riprodotte</strong> dal modello mediante il prodotto dei carichi fattoriali;</li>
<li>
<strong>varianza osservata</strong> e <strong>varianza ricostruita</strong> come somma di varianza comune (fattore) e varianza residua (unicità).</li>
</ol>
<p>La coerenza dei risultati fra CTT e analisi fattoriale ribadisce la loro stretta complementarità nello studio dell’affidabilità e della struttura latente di un test psicometrico.</p>
</section></section><section id="correlazione-tra-variabili-manifeste-e-fattore-comune" class="level2" data-number="21.9"><h2 data-number="21.9" class="anchored" data-anchor-id="correlazione-tra-variabili-manifeste-e-fattore-comune">
<span class="header-section-number">21.9</span> Correlazione tra variabili manifeste e fattore comune</h2>
<p>Nel <em>modello unifattoriale</em>, la <em>saturazione fattoriale</em> <span class="math inline">\(\lambda_i\)</span> della variabile manifesta <span class="math inline">\(Y_i\)</span> corrisponde teoricamente alla <em>correlazione</em> tra <span class="math inline">\(Y_i\)</span> e il <em>fattore comune</em> <span class="math inline">\(\xi\)</span>. Tuttavia, perché ciò risulti evidente in un’applicazione reale, è necessario poter disporre di una <em>stima</em> dei punteggi fattoriali per ciascun partecipante, cioè i valori (stimati) del fattore comune <span class="math inline">\(\xi_i\)</span>. In <span class="math inline">\(\textsf{R}\)</span>, con <code>lavaan</code> possiamo ricavare i <strong>punteggi fattoriali</strong> usando la funzione <code>lavPredict(fit)</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fu">lavPredict</span><span class="op">(</span><span class="va">fit</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt;            F</span></span>
<span><span class="co">#&gt; [1,]  0.2694</span></span>
<span><span class="co">#&gt; [2,] -0.9111</span></span>
<span><span class="co">#&gt; [3,]  0.1871</span></span>
<span><span class="co">#&gt; [4,] -0.3316</span></span>
<span><span class="co">#&gt; [5,]  0.8307</span></span>
<span><span class="co">#&gt; [6,]  1.1535</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="fu">lavPredict</span><span class="op">(</span><span class="va">fit</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 540   1</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>
<code>head(lavPredict(fit))</code> mostra le prime righe dei punteggi fattoriali stimati per i soggetti.</li>
<li>
<code>dim(lavPredict(fit))</code> conferma che abbiamo un punteggio per ognuno dei 540 soggetti nel dataset.</li>
</ul>
<p>Per verificare in concreto la relazione tra <span class="math inline">\(\lambda_i\)</span> e la correlazione di <span class="math inline">\(Y_i\)</span> con il fattore comune, calcoliamo la <em>correlazione</em> tra i valori osservati su ciascuna sottoscala del CSQ e le stime dei punteggi fattoriali (ossia <span class="math inline">\(\hat{\xi}\)</span>):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">csq</span><span class="op">$</span><span class="va">I</span>, <span class="fu">lavPredict</span><span class="op">(</span><span class="va">fit</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">csq</span><span class="op">$</span><span class="va">G</span>, <span class="fu">lavPredict</span><span class="op">(</span><span class="va">fit</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">csq</span><span class="op">$</span><span class="va">S</span>, <span class="fu">lavPredict</span><span class="op">(</span><span class="va">fit</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">csq</span><span class="op">$</span><span class="va">N</span>, <span class="fu">lavPredict</span><span class="op">(</span><span class="va">fit</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">csq</span><span class="op">$</span><span class="va">W</span>, <span class="fu">lavPredict</span><span class="op">(</span><span class="va">fit</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1]  0.128 -0.970 -0.952 -0.910 -0.905</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I risultati ottenuti sono molto <em>simili</em> (ma non necessariamente identici) alle saturazioni fattoriali riportate in:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">inspect</span><span class="op">(</span><span class="va">fit</span>, what<span class="op">=</span><span class="st">"std"</span><span class="op">)</span><span class="op">$</span><span class="va">lambda</span></span>
<span><span class="co">#&gt;        F</span></span>
<span><span class="co">#&gt; I  0.126</span></span>
<span><span class="co">#&gt; G -0.949</span></span>
<span><span class="co">#&gt; S -0.932</span></span>
<span><span class="co">#&gt; N -0.891</span></span>
<span><span class="co">#&gt; W -0.886</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>La piccola differenza riscontrata è dovuta al fatto che i punteggi fattoriali <span class="math inline">\(\hat{\xi}_i\)</span> sono <em>stime</em> e non i valori reali del fattore latente, quindi non coincidono esattamente con <span class="math inline">\(\xi_i\)</span>. Ciò nonostante, se il modello è ben specificato e i dati si adattano in modo soddisfacente, le correlazioni tra punteggi osservati e fattore stimato risulteranno prossime alle saturazioni fattoriali teoriche.</p>
</section><section id="session-info" class="level2" data-number="21.10"><h2 data-number="21.10" class="anchored" data-anchor-id="session-info">
<span class="header-section-number">21.10</span> Session Info</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; R version 4.4.2 (2024-10-31)</span></span>
<span><span class="co">#&gt; Platform: aarch64-apple-darwin20</span></span>
<span><span class="co">#&gt; Running under: macOS Sequoia 15.3.2</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Matrix products: default</span></span>
<span><span class="co">#&gt; BLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib </span></span>
<span><span class="co">#&gt; LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; locale:</span></span>
<span><span class="co">#&gt; [1] C/UTF-8/C/C/C/C</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; time zone: Europe/Rome</span></span>
<span><span class="co">#&gt; tzcode source: internal</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; attached base packages:</span></span>
<span><span class="co">#&gt; [1] stats     graphics  grDevices utils     datasets  methods   base     </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; other attached packages:</span></span>
<span><span class="co">#&gt;  [1] dagitty_0.3-4     ggdag_0.2.13      ggokabeito_0.1.0  see_0.11.0       </span></span>
<span><span class="co">#&gt;  [5] MASS_7.3-65       viridis_0.6.5     viridisLite_0.4.2 ggpubr_0.6.0     </span></span>
<span><span class="co">#&gt;  [9] ggExtra_0.10.1    gridExtra_2.3     patchwork_1.3.0   bayesplot_1.11.1 </span></span>
<span><span class="co">#&gt; [13] semTools_0.5-6    semPlot_1.1.6     lavaan_0.6-19     psych_2.4.12     </span></span>
<span><span class="co">#&gt; [17] scales_1.3.0      markdown_1.13     knitr_1.50        lubridate_1.9.4  </span></span>
<span><span class="co">#&gt; [21] forcats_1.0.0     stringr_1.5.1     dplyr_1.1.4       purrr_1.0.4      </span></span>
<span><span class="co">#&gt; [25] readr_2.1.5       tidyr_1.3.1       tibble_3.2.1      ggplot2_3.5.1    </span></span>
<span><span class="co">#&gt; [29] tidyverse_2.0.0   here_1.0.1       </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; loaded via a namespace (and not attached):</span></span>
<span><span class="co">#&gt;   [1] rstudioapi_0.17.1   jsonlite_1.9.1      magrittr_2.0.3     </span></span>
<span><span class="co">#&gt;   [4] TH.data_1.1-3       estimability_1.5.1  farver_2.1.2       </span></span>
<span><span class="co">#&gt;   [7] nloptr_2.2.1        rmarkdown_2.29      vctrs_0.6.5        </span></span>
<span><span class="co">#&gt;  [10] minqa_1.2.8         base64enc_0.1-3     rstatix_0.7.2      </span></span>
<span><span class="co">#&gt;  [13] htmltools_0.5.8.1   curl_6.2.1          broom_1.0.7        </span></span>
<span><span class="co">#&gt;  [16] Formula_1.2-5       htmlwidgets_1.6.4   plyr_1.8.9         </span></span>
<span><span class="co">#&gt;  [19] sandwich_3.1-1      rio_1.2.3           emmeans_1.10.7     </span></span>
<span><span class="co">#&gt;  [22] zoo_1.8-13          igraph_2.1.4        mime_0.13          </span></span>
<span><span class="co">#&gt;  [25] lifecycle_1.0.4     pkgconfig_2.0.3     Matrix_1.7-3       </span></span>
<span><span class="co">#&gt;  [28] R6_2.6.1            fastmap_1.2.0       rbibutils_2.3      </span></span>
<span><span class="co">#&gt;  [31] shiny_1.10.0        digest_0.6.37       OpenMx_2.21.13     </span></span>
<span><span class="co">#&gt;  [34] fdrtool_1.2.18      colorspace_2.1-1    rprojroot_2.0.4    </span></span>
<span><span class="co">#&gt;  [37] Hmisc_5.2-3         timechange_0.3.0    abind_1.4-8        </span></span>
<span><span class="co">#&gt;  [40] compiler_4.4.2      withr_3.0.2         glasso_1.11        </span></span>
<span><span class="co">#&gt;  [43] htmlTable_2.4.3     backports_1.5.0     carData_3.0-5      </span></span>
<span><span class="co">#&gt;  [46] R.utils_2.13.0      ggsignif_0.6.4      corpcor_1.6.10     </span></span>
<span><span class="co">#&gt;  [49] gtools_3.9.5        tools_4.4.2         pbivnorm_0.6.0     </span></span>
<span><span class="co">#&gt;  [52] foreign_0.8-88      zip_2.3.2           httpuv_1.6.15      </span></span>
<span><span class="co">#&gt;  [55] nnet_7.3-20         R.oo_1.27.0         glue_1.8.0         </span></span>
<span><span class="co">#&gt;  [58] quadprog_1.5-8      nlme_3.1-167        promises_1.3.2     </span></span>
<span><span class="co">#&gt;  [61] lisrelToR_0.3       grid_4.4.2          checkmate_2.3.2    </span></span>
<span><span class="co">#&gt;  [64] cluster_2.1.8.1     reshape2_1.4.4      generics_0.1.3     </span></span>
<span><span class="co">#&gt;  [67] gtable_0.3.6        tzdb_0.5.0          R.methodsS3_1.8.2  </span></span>
<span><span class="co">#&gt;  [70] data.table_1.17.0   hms_1.1.3           tidygraph_1.3.1    </span></span>
<span><span class="co">#&gt;  [73] car_3.1-3           sem_3.1-16          pillar_1.10.1      </span></span>
<span><span class="co">#&gt;  [76] rockchalk_1.8.157   later_1.4.1         splines_4.4.2      </span></span>
<span><span class="co">#&gt;  [79] lattice_0.22-6      survival_3.8-3      kutils_1.73        </span></span>
<span><span class="co">#&gt;  [82] tidyselect_1.2.1    miniUI_0.1.1.1      pbapply_1.7-2      </span></span>
<span><span class="co">#&gt;  [85] reformulas_0.4.0    V8_6.0.2            stats4_4.4.2       </span></span>
<span><span class="co">#&gt;  [88] xfun_0.51           qgraph_1.9.8        arm_1.14-4         </span></span>
<span><span class="co">#&gt;  [91] stringi_1.8.4       yaml_2.3.10         pacman_0.5.1       </span></span>
<span><span class="co">#&gt;  [94] boot_1.3-31         evaluate_1.0.3      codetools_0.2-20   </span></span>
<span><span class="co">#&gt;  [97] mi_1.1              cli_3.6.4           RcppParallel_5.1.10</span></span>
<span><span class="co">#&gt; [100] rpart_4.1.24        xtable_1.8-4        Rdpack_2.6.3       </span></span>
<span><span class="co">#&gt; [103] munsell_0.5.1       Rcpp_1.0.14         coda_0.19-4.1      </span></span>
<span><span class="co">#&gt; [106] png_0.1-8           XML_3.99-0.18       parallel_4.4.2     </span></span>
<span><span class="co">#&gt; [109] jpeg_0.1-10         lme4_1.1-36         mvtnorm_1.3-3      </span></span>
<span><span class="co">#&gt; [112] openxlsx_4.2.8      rlang_1.1.5         multcomp_1.4-28    </span></span>
<span><span class="co">#&gt; [115] mnormt_2.1.1</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-mcdonald2013test" class="csl-entry" role="listitem">
McDonald, R. P. (2013). <em>Test theory: A unified treatment</em>. <span>Psychology Press</span>.
</div>
<div id="ref-petersen2024principles" class="csl-entry" role="listitem">
Petersen, I. T. (2024). <em>Principles of psychological assessment: With applied examples in R</em>. CRC Press.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiato!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiato!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ccaudek\.github\.io\/testing_psicologico\/intro\.html");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../chapters/fa/02_analisi_fattoriale_1.html" class="pagination-link" aria-label="Il modello unifattoriale">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Il modello unifattoriale</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/fa/04_analisi_fattoriale_3.html" class="pagination-link" aria-label="Il modello multifattoriale">
        <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Il modello multifattoriale</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Testing Psicologico</strong> è una dispensa scritta da Corrado Caudek.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


</body></html>