# Preparazione dei Dati {#sec-sem-data-prep}


::: callout-important
## In questo capitolo imparerai a 

- conoscere le manipolazioni di base dei dati necessarie per le analisi SEM.
:::

::: callout-tip
## Prerequisiti

- Leggere il capitolo *Structural Equation Modeling* del testo di @petersen2024principles.
:::

## Introduzione

Questo capitolo breve ma essenziale esplora diversi aspetti fondamentali della gestione dei dati nell'ambito della modellazione con Modelli di Equazioni Strutturali (SEM).

## Formati dei Dati di Input

I ricercatori spesso analizzano file di dati grezzi. Tuttavia, alcune analisi SEM possono essere eseguite anche con matrici di covarianze e medie. Se si utilizzano dati grezzi, il software SEM crea una propria matrice di covarianza per l'analisi. Talvolta, è necessario usare dati grezzi, come in casi di distribuzioni non normali, dati mancanti o variabili categoriali.

## Definitezza Positiva
È fondamentale che la matrice di dati, sia quella inizialmente fornita come input che quella calcolata dal computer durante l'analisi, soddisfi i criteri di essere positiva definita. Questo concetto implica diverse proprietà chiave: innanzitutto, la matrice deve avere un inverso, il che significa che non è singolare e può essere invertita matematicamente. Inoltre, è necessario che tutti gli autovalori della matrice siano positivi, indicando che non esistono autovalori negativi che potrebbero causare problemi durante l'analisi. Inoltre, la matrice deve essere priva di correlazioni o covarianze al di fuori limite. 

## Dati Mancanti
Questo è un argomento complesso che richiede l'uso di metodi statistici moderni e sarà approfondito in un capitolo successivo.

## Screening dei Dati
- **Collinearità Estrema, Valori Anomali e Violazioni delle Assunzioni Distribuzionali**: È importante gestire questi problemi per assicurare l'affidabilità dei risultati SEM. La collinearità estrema può essere rilevata tramite il fattore di inflazione della varianza (VIF), mentre i valori anomali e le violazioni delle ipotesi distribuzionali richiedono metodi specifici per essere identificati e gestiti.

## Varianze Relative
- **Gestione delle Varianze**: La differenza eccessiva tra le varianze può complicare l'iterazione dei metodi di stima in SEM. Per mitigare questo aspetto, i dati con varianze molto basse o alte possono essere riscalati.

In sintesi, prima di procedere a qualunque analisi statistica è necessario affrontare diversi problemi relativi alla corretta preparazione e gestione dei dati. Questi aspetti sono fondamentali per assicurare l'accuratezza e l'affidabilità dei risultati delle analisi SEM.

