<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Corrado Caudek">
<title>51&nbsp; Confronto tra modelli – Testing Psicologico</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/sem/05_cfa_mod_comp.html" rel="next">
<link href="../../chapters/sem/03_gof.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-86daaaaad7353f9cc0c554efc1dd6d94.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-dde6bd6f26623a10457909d7338dd2ac.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script><script type="application/json" class="js-hypothesis-config">
{
  "theme": "clean"
}
</script><script async="" src="https://hypothes.is/embed.js"></script><script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/sem/01_sem_intro.html">SEM</a></li><li class="breadcrumb-item"><a href="../../chapters/sem/04_mod_comp.html"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Confronto tra modelli</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Testing Psicologico</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ccaudek/testing_psicologico/" title="Eseguire il codice" class="quarto-navigation-tool px-1" aria-label="Eseguire il codice"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Ricerca"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Benvenuti</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../prefazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefazione</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Calendario</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../cal_testing_psic_2025.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calendario Didattico e Programma del Corso</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Punteggi e scale</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/01_scores_scales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Punteggi e scale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E1_likert.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E2_optimal_scoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E3_thurstone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/02_development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sviluppo dello strumento</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/03_equating.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Equating nei Test Psicologici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E4_norming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">CTT</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/01_ctt_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Fondamenti teorici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/02_ctt_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">L’affidabilità del test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/03_ctt_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Metodi di stima dell’affidabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/04_err_std_mis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">L’errore standard della misurazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/05_err_std_stima.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">La stima del punteggio vero</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/06_ctt_applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Applicazioni della CTT</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Giudici</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/01_multilevel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Modelli multilivello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/02_interrater_reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">L’affidabilità tra giudici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/E1_irr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Validità</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/validity/01_validity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">La Validità del test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/validity/02_other_variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Relazioni test-criterio</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Generalizzabilità</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/gtheory/01_gtheory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Teoria della generalizzabilità</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Items</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/items/01_item_development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Lo sviluppo degli item</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/items/02_item_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Analisi degli item</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Analisi dei percorsi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/path_analysis/01_path_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Analisi dei percorsi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/path_analysis/02_clement_2022.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Riparazione affettiva post-infedeltà</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Networks</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/networks/01_networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Network psicologici</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">PCA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/pca/01_linear_algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Elementi di algebra lineare</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/pca/02_pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Analisi delle componenti principali</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">FA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/01_intro_fa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Introduzione all’analisi fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/02_analisi_fattoriale_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Il modello unifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/03_analisi_fattoriale_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Il modello statistico dell’analisi fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/04_analisi_fattoriale_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Il modello multifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/05_factor_scores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">I punteggi fattoriali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/06_constraints_on_parms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Attendibilità e modello fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/07_total_score.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Punteggio totale e modello fattoriale</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false">
 <span class="menu-text">Costruzione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/01_val_matrici.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Valutazione della matrice di correlazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/02_estrazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">L’estrazione dei fattori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/03_numero_fattori.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Il numero dei fattori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/04_rotazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">La rotazione fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/05_val_soluzione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Valutare e rifinire la soluzione fattoriale</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">CFA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/01_cfa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Analisti Fattoriale Confermativa</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/02_meanstructure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">La struttura delle medie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/03_cat_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Dati non gaussiani e categoriali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/04_mmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">CFA per matrici multi-tratto multi-metodo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/05_bifactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Modello bifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/06_efa_lavaan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Exploratory Structural Equation Modeling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/07_fa_in_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Strategia Integrata per un’Analisi Fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/E_02_bifactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="true">
 <span class="menu-text">SEM</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/01_sem_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Introduzione ai Modelli SEM</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/02_data_preparation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Preparazione dei Dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/03_gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Test del Modello e Indicizzazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/04_mod_comp.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Confronto tra modelli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/05_cfa_mod_comp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">CFA: confronto tra modelli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/06_refine_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">La revisione del modello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/07_group_invariance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Invarianza di misura</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/08_multilevel_sem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Modelli di Equazioni Strutturali Multilivello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/09_structural_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Modelli di Regressione Strutturale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/10_missing_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Dati mancanti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/11_small_samples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Modellizzazione SEM in Piccoli Campioni</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/13_esem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Exploratory structural equation modelling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/14_sem_power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Dimensione Campionaria e Analisi della Potenza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/15_prior_pred_mod_check.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Prior Predictive Model Checking</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false">
 <span class="menu-text">Mokken</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/01_logistic_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Modello di Regressione Logistica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/02_core_issues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Analisi della Scala di Mokken</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/03_applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Applicazione Pratica</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false">
 <span class="menu-text">IRT</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/01_rasch_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">Modello di Rasch</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/02_assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">68</span>&nbsp; <span class="chapter-title">Assunzioni e Proprietà del Modello di Rasch</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/03_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title">Stima</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/04_1pl_2pl_3pl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Modelli 1PL, 2PL e 3PL</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/05_implementation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Implementazione</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false">
 <span class="menu-text">LGM</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/01_lgm_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">72</span>&nbsp; <span class="chapter-title">Curve di crescita latente</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/02_lgm_prelims.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">73</span>&nbsp; <span class="chapter-title">Considerazioni Preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/06_lgm_mixed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">74</span>&nbsp; <span class="chapter-title">LGM e modelli misti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/03_time_effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">75</span>&nbsp; <span class="chapter-title">Dati longitudinali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/05_intro_panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">76</span>&nbsp; <span class="chapter-title">Specificare e Interpretare un Modello Longitudinale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/07_growth_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">77</span>&nbsp; <span class="chapter-title">Curve di crescita latente</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/08_growth_cont.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">78</span>&nbsp; <span class="chapter-title">Il tempo su una metrica continua</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/09_time_inv_cov.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">79</span>&nbsp; <span class="chapter-title">Covariate indipendenti dal tempo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/10_growth_groups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">80</span>&nbsp; <span class="chapter-title">Modelli di crescita latenti a gruppi multipli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/11_lgm_wais.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">81</span>&nbsp; <span class="chapter-title">Lo Sviluppo dell’Intelligenza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/12_temp_reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">82</span>&nbsp; <span class="chapter-title">Affidabilità longitudinale</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false">
 <span class="menu-text">Predizione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/prediction/01_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">83</span>&nbsp; <span class="chapter-title">Predizione</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../99-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliografia</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendici</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a1_intro_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linguaggio R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a2_sums.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Simbolo di somma</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a3_calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Per liberarvi dai terrori preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false">
 <span class="menu-text">Soluzioni degli esercizi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/solutions_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Probabilità</span></span></a>
  </div>
</li>
      </ul>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Indice</h2>
   
  <ul>
<li><a href="#introduzione" id="toc-introduzione" class="nav-link active" data-scroll-target="#introduzione"><span class="header-section-number">51.1</span> Introduzione</a></li>
  <li><a href="#confrontare-modelli-nel-sem" id="toc-confrontare-modelli-nel-sem" class="nav-link" data-scroll-target="#confrontare-modelli-nel-sem"><span class="header-section-number">51.2</span> Confrontare Modelli nel SEM</a></li>
  <li><a href="#analisi-dei-modelli-nidificati" id="toc-analisi-dei-modelli-nidificati" class="nav-link" data-scroll-target="#analisi-dei-modelli-nidificati"><span class="header-section-number">51.3</span> Analisi dei Modelli Nidificati</a></li>
  <li>
<a href="#strategie-di-costruzione-e-potatura-nei-modelli-sem" id="toc-strategie-di-costruzione-e-potatura-nei-modelli-sem" class="nav-link" data-scroll-target="#strategie-di-costruzione-e-potatura-nei-modelli-sem"><span class="header-section-number">51.4</span> Strategie di Costruzione e Potatura nei Modelli SEM</a>
  <ul>
<li><a href="#costruzione-progressiva-del-modello" id="toc-costruzione-progressiva-del-modello" class="nav-link" data-scroll-target="#costruzione-progressiva-del-modello"><span class="header-section-number">51.4.1</span> Costruzione Progressiva del Modello</a></li>
  <li><a href="#potatura-retrograda-del-modello" id="toc-potatura-retrograda-del-modello" class="nav-link" data-scroll-target="#potatura-retrograda-del-modello"><span class="header-section-number">51.4.2</span> Potatura Retrograda del Modello</a></li>
  <li><a href="#obiettivi-e-considerazioni" id="toc-obiettivi-e-considerazioni" class="nav-link" data-scroll-target="#obiettivi-e-considerazioni"><span class="header-section-number">51.4.3</span> Obiettivi e Considerazioni</a></li>
  <li><a href="#punti-di-forza-relativi" id="toc-punti-di-forza-relativi" class="nav-link" data-scroll-target="#punti-di-forza-relativi"><span class="header-section-number">51.4.4</span> Punti di Forza Relativi</a></li>
  </ul>
</li>
  <li>
<a href="#strategie-di-ridefinizione-dei-modelli-sem-approcci-teorici-ed-empirici" id="toc-strategie-di-ridefinizione-dei-modelli-sem-approcci-teorici-ed-empirici" class="nav-link" data-scroll-target="#strategie-di-ridefinizione-dei-modelli-sem-approcci-teorici-ed-empirici"><span class="header-section-number">51.5</span> Strategie di Ridefinizione dei Modelli SEM: Approcci Teorici ed Empirici</a>
  <ul>
<li><a href="#approccio-teorico-nella-ridefinizione-dei-modelli" id="toc-approccio-teorico-nella-ridefinizione-dei-modelli" class="nav-link" data-scroll-target="#approccio-teorico-nella-ridefinizione-dei-modelli"><span class="header-section-number">51.5.1</span> Approccio Teorico nella Ridefinizione dei Modelli</a></li>
  <li><a href="#approccio-empirico-nella-ridefinizione-dei-modelli" id="toc-approccio-empirico-nella-ridefinizione-dei-modelli" class="nav-link" data-scroll-target="#approccio-empirico-nella-ridefinizione-dei-modelli"><span class="header-section-number">51.5.2</span> Approccio Empirico nella Ridefinizione dei Modelli</a></li>
  <li><a href="#implicazioni-per-linterpretazione-dei-modelli" id="toc-implicazioni-per-linterpretazione-dei-modelli" class="nav-link" data-scroll-target="#implicazioni-per-linterpretazione-dei-modelli"><span class="header-section-number">51.5.3</span> Implicazioni per l’Interpretazione dei Modelli</a></li>
  </ul>
</li>
  <li>
<a href="#test-della-differenza-chi-quadro-nel-sem" id="toc-test-della-differenza-chi-quadro-nel-sem" class="nav-link" data-scroll-target="#test-della-differenza-chi-quadro-nel-sem"><span class="header-section-number">51.6</span> Test della Differenza Chi-Quadro nel SEM</a>
  <ul>
<li><a href="#principi-fondamentali" id="toc-principi-fondamentali" class="nav-link" data-scroll-target="#principi-fondamentali"><span class="header-section-number">51.6.1</span> Principi Fondamentali</a></li>
  <li><a href="#applicazione-del-test" id="toc-applicazione-del-test" class="nav-link" data-scroll-target="#applicazione-del-test"><span class="header-section-number">51.6.2</span> Applicazione del Test</a></li>
  <li><a href="#interpretazione-dei-risultati" id="toc-interpretazione-dei-risultati" class="nav-link" data-scroll-target="#interpretazione-dei-risultati"><span class="header-section-number">51.6.3</span> Interpretazione dei Risultati</a></li>
  <li><a href="#considerazioni-nella-stima-ml-robusta" id="toc-considerazioni-nella-stima-ml-robusta" class="nav-link" data-scroll-target="#considerazioni-nella-stima-ml-robusta"><span class="header-section-number">51.6.4</span> Considerazioni nella Stima ML Robusta</a></li>
  <li><a href="#implicazioni-teoriche-ed-empiriche" id="toc-implicazioni-teoriche-ed-empiriche" class="nav-link" data-scroll-target="#implicazioni-teoriche-ed-empiriche"><span class="header-section-number">51.6.5</span> Implicazioni Teoriche ed Empiriche</a></li>
  </ul>
</li>
  <li>
<a href="#test-della-differenza-chi-quadro-scalato" id="toc-test-della-differenza-chi-quadro-scalato" class="nav-link" data-scroll-target="#test-della-differenza-chi-quadro-scalato"><span class="header-section-number">51.7</span> Test della Differenza Chi-Quadro Scalato</a>
  <ul>
<li><a href="#esempio" id="toc-esempio" class="nav-link" data-scroll-target="#esempio"><span class="header-section-number">51.7.1</span> Esempio</a></li>
  </ul>
</li>
  <li><a href="#confronto-di-modelli-non-annidati" id="toc-confronto-di-modelli-non-annidati" class="nav-link" data-scroll-target="#confronto-di-modelli-non-annidati"><span class="header-section-number">51.8</span> Confronto di Modelli Non Annidati</a></li>
  <li><a href="#aic-e-bic" id="toc-aic-e-bic" class="nav-link" data-scroll-target="#aic-e-bic"><span class="header-section-number">51.9</span> AIC e BIC</a></li>
  <li><a href="#indici-di-modifica-e-statistiche-correlate-nel-sem" id="toc-indici-di-modifica-e-statistiche-correlate-nel-sem" class="nav-link" data-scroll-target="#indici-di-modifica-e-statistiche-correlate-nel-sem"><span class="header-section-number">51.10</span> Indici di Modifica e Statistiche Correlate nel SEM</a></li>
  <li><a href="#riflessioni-conclusive" id="toc-riflessioni-conclusive" class="nav-link" data-scroll-target="#riflessioni-conclusive"><span class="header-section-number">51.11</span> Riflessioni Conclusive</a></li>
  <li><a href="#session-info" id="toc-session-info" class="nav-link" data-scroll-target="#session-info"><span class="header-section-number">51.12</span> Session Info</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/sem/01_sem_intro.html">SEM</a></li><li class="breadcrumb-item"><a href="../../chapters/sem/04_mod_comp.html"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Confronto tra modelli</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-sem-model-comparison" class="quarto-section-identifier"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Confronto tra modelli</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
In questo capitolo imparerai a:
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>
</li></ul>
</div>
</div>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prerequisiti
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Leggere il capitolo <em>Structural Equation Modeling</em> del testo di <span class="citation" data-cites="petersen2024principles">Petersen (<a href="../../99-references.html#ref-petersen2024principles" role="doc-biblioref">2024</a>)</span>.</li>
</ul>
</div>
</div>
<div class="callout callout-style-simple callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Preparazione del Notebook
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"code"</span>, <span class="st">"_common.R"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Load packages</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/ns-load.html">requireNamespace</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span></span>
<span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span></span>
<span>  <span class="va">lavaan</span>, <span class="va">lavaanExtra</span>, <span class="va">lavaanPlot</span>, <span class="va">lavaan</span>, <span class="va">psych</span>, <span class="va">mvnormalTest</span>, <span class="va">semPlot</span>, </span>
<span>    <span class="va">DiagrammeRsvg</span>, <span class="va">rsvg</span>, <span class="va">effectsize</span></span>
<span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<section id="introduzione" class="level2" data-number="51.1"><h2 data-number="51.1" class="anchored" data-anchor-id="introduzione">
<span class="header-section-number">51.1</span> Introduzione</h2>
<p>I ricercatori spesso confrontano modelli alternativi di equazioni strutturali che includono le stesse variabili e sono adattati agli stessi dati. Il contesto più frequente si verifica quando un singolo modello iniziale viene testato attraverso una serie di passaggi. Ad ogni passaggio, il modello iniziale viene ridefinito aggiungendo uno o più parametri liberi, il che generalmente migliora l’adattamento, oppure eliminando (fissando a zero) uno o più parametri liberi, il che generalmente peggiora l’adattamento. Una coppia di modelli alternativi così specificata viene definita “modelli nidificati”, poiché il modello più semplice dei due, o modello vincolato, è un sottoinsieme proprio del modello più complesso, o modello non vincolato. Un contesto diverso si verifica quando ci sono due o più modelli iniziali tali che (1) ogni modello si basa su una teoria diversa e (2) i modelli alternativi non sono nidificati nella loro relazione l’uno con l’altro. In entrambi i contesti, la scelta tra modelli concorrenti dovrebbe essere guidata tanto da basi concettuali quanto da considerazioni statistiche.</p>
</section><section id="confrontare-modelli-nel-sem" class="level2" data-number="51.2"><h2 data-number="51.2" class="anchored" data-anchor-id="confrontare-modelli-nel-sem">
<span class="header-section-number">51.2</span> Confrontare Modelli nel SEM</h2>
<p>Nel contesto dei Modelli di Equazioni Strutturali (SEM), un aspetto critico è il confronto tra diversi modelli per determinare quale sia il più adeguato. Questo confronto si presenta frequentemente nella forma di analisi di modelli nidificati. In tale contesto, si confronta un modello considerato “pieno” o “meno restrittivo” con un altro modello che è “ridotto” o “più restrittivo”.</p>
<p>Il modello pieno include un insieme più ampio di parametri e ipotesi, offrendo una rappresentazione più complessa delle relazioni tra le variabili. Al contrario, il modello ridotto è una versione più semplificata, con meno parametri e ipotesi, risultando in una struttura più contenuta e potenzialmente più parsimoniosa.</p>
<p>Questo tipo di confronto è cruciale per valutare l’adeguatezza dei modelli SEM, permettendo ai ricercatori di decidere se la complessità aggiuntiva del modello pieno sia giustificata rispetto al modello ridotto in termini di adattamento ai dati e coerenza con la teoria sottostante.</p>
</section><section id="analisi-dei-modelli-nidificati" class="level2" data-number="51.3"><h2 data-number="51.3" class="anchored" data-anchor-id="analisi-dei-modelli-nidificati">
<span class="header-section-number">51.3</span> Analisi dei Modelli Nidificati</h2>
<p>Nell’ambito dei Modelli di Equazioni Strutturali (SEM), i modelli nidificati occupano un ruolo centrale. Due modelli sono definiti come nidificati quando soddisfano specifici criteri gerarchici, delineati come segue:</p>
<ol type="1">
<li>
<strong>Formazione del Modello Vincolato:</strong>
<ul>
<li>Si crea un modello vincolato applicando una o più restrizioni a un modello non vincolato esistente. Questo processo aumenta i gradi di libertà del modello vincolato (C) rispetto a quelli del modello non vincolato (U), risultando in <span class="math inline">\(\text{df}_C &gt; \text{df}_U\)</span>.</li>
</ul>
</li>
<li>
<strong>Differenze nei Gradi di Libertà:</strong>
<ul>
<li>La differenza <span class="math inline">\(\text{df}_C - \text{df}_U\)</span> rappresenta il numero di restrizioni imposte al modello non vincolato per creare il modello vincolato, che equivale alla variazione nel numero di parametri liberi tra i due modelli.</li>
</ul>
</li>
<li>
<strong>Parametri Liberi e Vincolati:</strong>
<ul>
<li>I parametri liberi nel modello vincolato costituiscono un sottoinsieme di quelli presenti nel modello non vincolato. Allo stesso modo, i parametri fissi nel modello non vincolato formano un sottoinsieme di quelli nel modello vincolato.</li>
</ul>
</li>
<li>
<strong>Confronto dei Valori di Chi-Quadro:</strong>
<ul>
<li>Tra i due modelli, il valore di <span class="math inline">\(\chi^2\)</span> è minore o uguale nel modello non vincolato rispetto a quello nel modello vincolato, ovvero <span class="math inline">\(\chi^2_U \leq \chi^2_C\)</span>. Questo implica che le distribuzioni di probabilità possibili nel modello vincolato sono comprese anche nel modello non vincolato, che può tuttavia suggerire ulteriori distribuzioni non coerenti con il modello vincolato.</li>
</ul>
</li>
</ol>
<p>Questo tipo di relazione gerarchica, conosciuta come annidamento dei parametri, permette di valutare l’impatto di specifiche restrizioni o aggiunte di parametri. Ad esempio, un parametro libero in un modello non vincolato può essere fissato a zero, eliminando di conseguenza l’effetto corrispondente nel modello vincolato, oppure può essere sottoposto a un vincolo specificato dal ricercatore, riducendo così il numero di parametri liberi ma mantenendo l’effetto nel modello vincolato.</p>
<p>Consideriamo, per esempio, un modello di percorso non vincolato U con effetti diretti: <span class="math inline">\(X \rightarrow Y_1 \rightarrow Y_2\)</span> e <span class="math inline">\(X \rightarrow Y_2\)</span>. Ridefinendo il percorso <span class="math inline">\(X \rightarrow Y_2 = 0\)</span>, eliminiamo questa connessione dal modello U, generando così il modello vincolato C1, nidificato sotto U. Un’alternativa potrebbe essere imporre un vincolo di uguaglianza tra <span class="math inline">\(X\rightarrow Y_2\)</span> e <span class="math inline">\(Y_1 \rightarrow Y_2\)</span>, indicando che gli effetti diretti non standardizzati di <span class="math inline">\(X\)</span> e <span class="math inline">\(Y_1\)</span> su <span class="math inline">\(Y_2\)</span> sono identici. Questo produce un modello vincolato, C2, con un parametro libero in meno rispetto a U ma che include tutti i percorsi di U.</p>
<p>Nelle prossime sezioni, esamineremo come testare le ipotesi inerenti a questi modelli nidificati e come valutare la loro adeguatezza nel contesto SEM.</p>
</section><section id="strategie-di-costruzione-e-potatura-nei-modelli-sem" class="level2" data-number="51.4"><h2 data-number="51.4" class="anchored" data-anchor-id="strategie-di-costruzione-e-potatura-nei-modelli-sem">
<span class="header-section-number">51.4</span> Strategie di Costruzione e Potatura nei Modelli SEM</h2>
<section id="costruzione-progressiva-del-modello" class="level3" data-number="51.4.1"><h3 data-number="51.4.1" class="anchored" data-anchor-id="costruzione-progressiva-del-modello">
<span class="header-section-number">51.4.1</span> Costruzione Progressiva del Modello</h3>
<p>La costruzione di modelli SEM inizia tipicamente con un modello iniziale semplice e vincolato, che riflette le ipotesi fondamentali basate su teorie sostanziali. Questo approccio, detto anche ricerca in avanti, implica l’aggiunta progressiva di parametri liberi che rappresentano ipotesi precedentemente escluse, in base alla loro importanza. Sebbene questo processo possa generalmente migliorare l’adattamento del modello (riduzione di chiML), un adattamento migliore non è necessariamente indicativo di una maggiore correttezza del modello. La costruzione del modello può teoricamente proseguire fino a quando non si raggiunge un modello perfettamente adatto ai dati (dfM = 0), ma è essenziale valutare la validità teorica e la parsimonia del modello in ogni passaggio.</p>
</section><section id="potatura-retrograda-del-modello" class="level3" data-number="51.4.2"><h3 data-number="51.4.2" class="anchored" data-anchor-id="potatura-retrograda-del-modello">
<span class="header-section-number">51.4.2</span> Potatura Retrograda del Modello</h3>
<p>In contrasto, la potatura del modello, o ricerca all’indietro, inizia con un modello più complesso e non vincolato. In questa fase, il ricercatore semplifica il modello eliminando parametri liberi (fissandoli a zero) o imponendo vincoli di stima. Questo processo richiede di dare priorità alle ipotesi in ordine inverso di importanza. Il modello iniziale dovrebbe essere congruente con i dati, altrimenti non ha senso restringerlo ulteriormente. Tipicamente, come si procede con la potatura, l’adattamento complessivo del modello ai dati tende a peggiorare (aumento di chiML). Il criterio per arrestare la potatura si basa sull’adattamento del modello: si ferma quando ulteriori restrizioni peggiorerebbero significativamente l’adattamento ai dati.</p>
</section><section id="obiettivi-e-considerazioni" class="level3" data-number="51.4.3"><h3 data-number="51.4.3" class="anchored" data-anchor-id="obiettivi-e-considerazioni">
<span class="header-section-number">51.4.3</span> Obiettivi e Considerazioni</h3>
<p>L’obiettivo sia nella costruzione che nella potatura di modelli è identificare un modello con una struttura di covarianza (e, se presente, anche di media) correttamente specificata e teoricamente giustificata. Idealmente, entrambi gli approcci dovrebbero convergere verso lo stesso modello ottimale, benché ciò non sia garantito. È importante evitare il rischio di formulare ipotesi post hoc (HARKing), presentando modelli scoperti in modo esplorativo come se fossero stati ipotizzati a priori. Una soluzione a questo problema è la preregistrazione del piano di analisi.</p>
</section><section id="punti-di-forza-relativi" class="level3" data-number="51.4.4"><h3 data-number="51.4.4" class="anchored" data-anchor-id="punti-di-forza-relativi">
<span class="header-section-number">51.4.4</span> Punti di Forza Relativi</h3>
<ol type="1">
<li>
<strong>Costruzione del Modello:</strong> Partire da un modello più semplice può essere vantaggioso, soprattutto per i neofiti del SEM, poiché facilita l’identificazione statistica e riduce il rischio di errori nella specificazione del modello.</li>
<li>
<strong>Potatura del Modello:</strong> Questo approccio può essere particolarmente efficace per i modelli di misurazione, dove le variabili osservate sono usate come indicatori di un numero limitato di fattori comuni. Un modello di misurazione correttamente specificato inizialmente può rendere la potatura più efficace rispetto alla costruzione.</li>
</ol>
<p>In entrambi i casi, è cruciale basare le decisioni su solide basi teoriche oltre che su considerazioni statistiche, per assicurare che il modello finale sia non solo adatto ai dati ma anche coerente con il quadro teorico sottostante.</p>
</section></section><section id="strategie-di-ridefinizione-dei-modelli-sem-approcci-teorici-ed-empirici" class="level2" data-number="51.5"><h2 data-number="51.5" class="anchored" data-anchor-id="strategie-di-ridefinizione-dei-modelli-sem-approcci-teorici-ed-empirici">
<span class="header-section-number">51.5</span> Strategie di Ridefinizione dei Modelli SEM: Approcci Teorici ed Empirici</h2>
<section id="approccio-teorico-nella-ridefinizione-dei-modelli" class="level3" data-number="51.5.1"><h3 data-number="51.5.1" class="anchored" data-anchor-id="approccio-teorico-nella-ridefinizione-dei-modelli">
<span class="header-section-number">51.5.1</span> Approccio Teorico nella Ridefinizione dei Modelli</h3>
<p>Nel processo di costruzione o potatura dei Modelli di Equazioni Strutturali (SEM), l’approccio teorico gioca un ruolo fondamentale. Qui, le modifiche al modello sono guidate da ipotesi teoriche predefinite e specifiche. Ad esempio, considerando un modello di percorso non vincolato U con le relazioni <span class="math inline">\(X \rightarrow Y_1 \rightarrow Y_2\)</span> e <span class="math inline">\(X \rightarrow Y_2\)</span>, un ricercatore potrebbe ipotizzare che l’effetto di X su Y2 sia esclusivamente indiretto attraverso Y1. Questa ipotesi può essere testata vincolando il coefficiente di <span class="math inline">\(X \rightarrow Y_2\)</span> a zero. Se l’adattamento del modello così modificato non è significativamente inferiore rispetto al modello non vincolato, l’ipotesi di un effetto indiretto viene supportata, a patto che la direzionalità delle relazioni sia corretta.</p>
<p>Questo approccio enfatizza che le modifiche al modello dovrebbero essere effettuate sulla base di solide basi teoriche e concettuali, piuttosto che su criteri puramente statistici, come evidenziato da Jöreskog (1969): “La decisione di smettere di aggiungere parametri non può basarsi solo su una base statistica; ciò dipende in gran parte dall’interpretazione dei dati da parte del ricercatore, basata su considerazioni teoriche e concettuali sostanziali.”</p>
</section><section id="approccio-empirico-nella-ridefinizione-dei-modelli" class="level3" data-number="51.5.2"><h3 data-number="51.5.2" class="anchored" data-anchor-id="approccio-empirico-nella-ridefinizione-dei-modelli">
<span class="header-section-number">51.5.2</span> Approccio Empirico nella Ridefinizione dei Modelli</h3>
<p>Al contrario, l’approccio empirico nella costruzione o potatura dei modelli SEM si basa su criteri statistici. In questo scenario, i parametri liberi vengono aggiunti o eliminati a seconda della loro significatività statistica o di altri indicatori empirici. Per esempio, se i percorsi sono eliminati solo perché i loro coefficienti non sono statisticamente significativi, la ridefinizione del modello è guidata da considerazioni puramente empiriche. Questo approccio è analogo alla tecnica di eliminazione all’indietro nella regressione multipla, dove il software sceglie quali predittori rimuovere in base a criteri di significatività statistica.</p>
</section><section id="implicazioni-per-linterpretazione-dei-modelli" class="level3" data-number="51.5.3"><h3 data-number="51.5.3" class="anchored" data-anchor-id="implicazioni-per-linterpretazione-dei-modelli">
<span class="header-section-number">51.5.3</span> Implicazioni per l’Interpretazione dei Modelli</h3>
<p>La scelta tra un approccio teorico o empirico nella ridefinizione dei modelli SEM ha implicazioni significative per come interpretiamo i risultati. Un modello modificato in base a criteri teorici forti offre una maggiore fiducia nella validità delle sue conclusioni, mentre un modello costruito o potato basandosi principalmente su criteri empirici può essere soggetto a errori di Tipo I o II e può non essere replicabile in campioni diversi.</p>
<p>È fondamentale che i ricercatori si avvicinino alla costruzione e alla potatura dei modelli SEM con un equilibrio tra intuizioni teoriche e risultati empirici, per assicurare che i modelli finali siano non solo statisticamente validi ma anche teoricamente giustificati e interpretativamente significativi.</p>
</section></section><section id="test-della-differenza-chi-quadro-nel-sem" class="level2" data-number="51.6"><h2 data-number="51.6" class="anchored" data-anchor-id="test-della-differenza-chi-quadro-nel-sem">
<span class="header-section-number">51.6</span> Test della Differenza Chi-Quadro nel SEM</h2>
<section id="principi-fondamentali" class="level3" data-number="51.6.1"><h3 data-number="51.6.1" class="anchored" data-anchor-id="principi-fondamentali">
<span class="header-section-number">51.6.1</span> Principi Fondamentali</h3>
<p>Il test della differenza Chi-Quadro (chiD) è una tecnica statistica essenziale nel contesto dei Modelli di Equazioni Strutturali (SEM) per valutare l’effetto delle modifiche ai parametri sui modelli. Questo test viene utilizzato sia nella potatura (restrizione dei parametri) che nella costruzione (aggiunta di parametri) dei modelli. Il valore chiD rappresenta la differenza tra i valori di chi-quadro (chi-quadro massima verosimiglianza, chiML) di due modelli nidificati. I gradi di libertà associati, dfD, sono determinati dalla differenza nei gradi di libertà dei due modelli (<span class="math inline">\(\text{df}_C - \text{df}_U\)</span>).</p>
</section><section id="applicazione-del-test" class="level3" data-number="51.6.2"><h3 data-number="51.6.2" class="anchored" data-anchor-id="applicazione-del-test">
<span class="header-section-number">51.6.2</span> Applicazione del Test</h3>
<p>Per applicare il test della differenza chi-quadro, si seguono questi passaggi:</p>
<ol type="1">
<li>
<strong>Definizione dei Modelli:</strong> Identificare il modello pieno (con tutti i parametri ritenuti rilevanti) e il modello ridotto (una versione semplificata del modello pieno con alcune restrizioni).</li>
<li>
<strong>Stima dei Modelli:</strong> Utilizzare metodi di massima verosimiglianza per stimare entrambi i modelli.</li>
<li>
<strong>Calcolo del Rapporto di Verosimiglianze:</strong> Calcolare la differenza tra i logaritmi delle funzioni di verosimiglianza dei due modelli (<span class="math inline">\(D = -2(\ln(L_r) - \ln(L_f))\)</span>).</li>
<li>
<strong>Test Statistico:</strong> Utilizzare la distribuzione chi-quadrato per determinare il p-value. Un p-value basso indica che il modello ridotto non si adatta ai dati così come il modello pieno.</li>
</ol></section><section id="interpretazione-dei-risultati" class="level3" data-number="51.6.3"><h3 data-number="51.6.3" class="anchored" data-anchor-id="interpretazione-dei-risultati">
<span class="header-section-number">51.6.3</span> Interpretazione dei Risultati</h3>
<p>Un valore piccolo di chiD suggerisce che non c’è una differenza significativa nell’adattamento tra i due modelli, mentre un valore grande indica una differenza significativa. In termini di potatura, un grande chiD implica che il modello è stato eccessivamente vincolato. Nella costruzione, un grande chiD supporta la conservazione del parametro libero aggiunto. Tuttavia, prima di trarre conclusioni definitive, è cruciale considerare l’adattamento complessivo del modello, sia a livello globale che locale.</p>
</section><section id="considerazioni-nella-stima-ml-robusta" class="level3" data-number="51.6.4"><h3 data-number="51.6.4" class="anchored" data-anchor-id="considerazioni-nella-stima-ml-robusta">
<span class="header-section-number">51.6.4</span> Considerazioni nella Stima ML Robusta</h3>
<p>Nel caso di stima ML robusta, la differenza tra i chi-quadri scalati non può essere interpretata come un test dell’ipotesi di adattamento uguale a causa delle distribuzioni non centrali in condizioni di non normalità. Sono disponibili metodi specifici per calcolare una statistica di differenza chi-quadro scalata che segue approssimativamente le distribuzioni chi-quadro.</p>
</section><section id="implicazioni-teoriche-ed-empiriche" class="level3" data-number="51.6.5"><h3 data-number="51.6.5" class="anchored" data-anchor-id="implicazioni-teoriche-ed-empiriche">
<span class="header-section-number">51.6.5</span> Implicazioni Teoriche ed Empiriche</h3>
<p>La decisione di modificare un modello basandosi su un approccio teorico o empirico ha implicazioni significative. Ad esempio, l’eliminazione di percorsi non significativi su base puramente statistica può portare a conclusioni errate se non supportate da una solida base teorica. Inoltre, è importante essere consapevoli dei rischi associati alla capitalizzazione sul caso, come errori di Tipo I e II, e del pericolo di seguire “sentieri che si biforcano” nelle decisioni analitiche, che possono rendere i risultati specifici del campione e difficili da replicare. Per mitigare questi rischi, è consigliabile basare le modifiche del modello più su orientamenti teorici che sui risultati dei test di significatività.</p>
</section></section><section id="test-della-differenza-chi-quadro-scalato" class="level2" data-number="51.7"><h2 data-number="51.7" class="anchored" data-anchor-id="test-della-differenza-chi-quadro-scalato">
<span class="header-section-number">51.7</span> Test della Differenza Chi-Quadro Scalato</h2>
<p>Il metodo di Satorra e Bentler (2001) permette di calcolare manualmente una statistica di differenza chi-quadro scalata quando si confrontano due modelli gerarchici nella stima ML robusta. Si presume che il modello 1 sia più vincolato rispetto al modello 2 (cioè, dfM1 &gt; dfM2), i chi-quadri non scalati siano chiML e i chi-quadri scalati siano chiSB. La statistica di test Satorra-Bentler è definita come segue:</p>
<ol type="1">
<li><strong>Calcolare la Statistica di Differenza Chi-Quadro non Scalata e i suoi Gradi di Libertà:</strong></li>
</ol>
<ul>
<li>chiD = chiML1 - chiML2 e dfD = dfM1 - dfM2.</li>
</ul>
<ol start="2" type="1">
<li><strong>Recuperare il Fattore di Correzione di Scala, c, per Ogni Modello:</strong></li>
</ol>
<ul>
<li>c1 = chiML1 / chiSB1 e c2 = chiML2 / chiSB2.</li>
</ul>
<ol start="3" type="1">
<li><strong>Calcolare la Statistica di Differenza Chi-Quadro Scalata, chiSD:</strong></li>
</ol>
<ul>
<li>chiSD = chiD / ((c1 / dfM1 - c2 / dfM2) / dfD).</li>
<li>La probabilità per chiSD (dfD) in una distribuzione chi-quadro centrale rappresenta il p-value per il test di differenza chi-quadro scalato.</li>
</ul>
<p>In campioni piccoli o quando il modello più vincolato è molto errato, il denominatore di chiSD può essere &lt; 0, invalidando il test. Questo test è implementato nella funzione <code>lavTestLRT()</code> in <code>lavaan</code> (Rosseel et al., 2023).</p>
<section id="esempio" class="level3" data-number="51.7.1"><h3 data-number="51.7.1" class="anchored" data-anchor-id="esempio">
<span class="header-section-number">51.7.1</span> Esempio</h3>
<p>Consideriamo nuovamente i dati discussi da <span class="citation" data-cites="brown2015confirmatory">Brown (<a href="../../99-references.html#ref-brown2015confirmatory" role="doc-biblioref">2015</a>)</span> relativi al modello di misurazione per la depressione maggiore così come è definita nel DSM-IV. Ignoriamo qui le differenze di genere. Leggiamo i dati in <span class="math inline">\(\mathsf{R}\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">d_mdd</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html">readRDS</a></span><span class="op">(</span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"data"</span>, <span class="st">"mdd_sex.RDS"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Consideriamo il seguente modello:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model_mdd</span> <span class="op">&lt;-</span> <span class="st">"</span></span>
<span><span class="st">  MDD =~ mdd1 + mdd2 + mdd3 + mdd4 + mdd5 + mdd6 + mdd7 + mdd8 + mdd9</span></span>
<span><span class="st">"</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Adattiamo il modello ai dati.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_mdd</span> <span class="op">&lt;-</span> <span class="fu">cfa</span><span class="op">(</span></span>
<span>    <span class="va">model_mdd</span>,</span>
<span>    data <span class="op">=</span> <span class="va">d_mdd</span></span>
<span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">semPaths</span><span class="op">(</span><span class="va">fit_mdd</span>,</span>
<span>    whatLabels <span class="op">=</span> <span class="st">"std"</span>,</span>
<span>    sizeMan <span class="op">=</span> <span class="fl">8</span>,</span>
<span>    edge.label.cex <span class="op">=</span> <span class="fl">0.7</span>,</span>
<span>    style <span class="op">=</span> <span class="st">"mx"</span>,</span>
<span>    nCharNodes <span class="op">=</span> <span class="fl">0</span>, nCharEdges <span class="op">=</span> <span class="fl">0</span></span>
<span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04_mod_comp_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">fitMeasures</span><span class="op">(</span><span class="va">fit_mdd</span><span class="op">)</span> </span>
<span><span class="co">#&gt;                  npar                  fmin                 chisq </span></span>
<span><span class="co">#&gt;              1.80e+01              7.40e-02              1.10e+02 </span></span>
<span><span class="co">#&gt;                    df                pvalue        baseline.chisq </span></span>
<span><span class="co">#&gt;              2.70e+01              0.00e+00              1.30e+03 </span></span>
<span><span class="co">#&gt;           baseline.df       baseline.pvalue                   cfi </span></span>
<span><span class="co">#&gt;              3.60e+01              0.00e+00              9.34e-01 </span></span>
<span><span class="co">#&gt;                   tli                  nnfi                   rfi </span></span>
<span><span class="co">#&gt;              9.12e-01              9.12e-01              8.87e-01 </span></span>
<span><span class="co">#&gt;                   nfi                  pnfi                   ifi </span></span>
<span><span class="co">#&gt;              9.15e-01              6.86e-01              9.34e-01 </span></span>
<span><span class="co">#&gt;                   rni                  logl     unrestricted.logl </span></span>
<span><span class="co">#&gt;              9.34e-01             -1.37e+04             -1.37e+04 </span></span>
<span><span class="co">#&gt;                   aic                   bic                ntotal </span></span>
<span><span class="co">#&gt;              2.75e+04              2.76e+04              7.50e+02 </span></span>
<span><span class="co">#&gt;                  bic2                 rmsea        rmsea.ci.lower </span></span>
<span><span class="co">#&gt;              2.76e+04              6.40e-02              5.20e-02 </span></span>
<span><span class="co">#&gt;        rmsea.ci.upper        rmsea.ci.level          rmsea.pvalue </span></span>
<span><span class="co">#&gt;              7.70e-02              9.00e-01              2.90e-02 </span></span>
<span><span class="co">#&gt;        rmsea.close.h0 rmsea.notclose.pvalue     rmsea.notclose.h0 </span></span>
<span><span class="co">#&gt;              5.00e-02              1.90e-02              8.00e-02 </span></span>
<span><span class="co">#&gt;                   rmr            rmr_nomean                  srmr </span></span>
<span><span class="co">#&gt;              1.91e-01              1.91e-01              4.40e-02 </span></span>
<span><span class="co">#&gt;          srmr_bentler   srmr_bentler_nomean                  crmr </span></span>
<span><span class="co">#&gt;              4.40e-02              4.40e-02              5.00e-02 </span></span>
<span><span class="co">#&gt;           crmr_nomean            srmr_mplus     srmr_mplus_nomean </span></span>
<span><span class="co">#&gt;              5.00e-02              4.40e-02              4.40e-02 </span></span>
<span><span class="co">#&gt;                 cn_05                 cn_01                   gfi </span></span>
<span><span class="co">#&gt;              2.74e+02              3.20e+02              9.64e-01 </span></span>
<span><span class="co">#&gt;                  agfi                  pgfi                   mfi </span></span>
<span><span class="co">#&gt;              9.40e-01              5.78e-01              9.46e-01 </span></span>
<span><span class="co">#&gt;                  ecvi </span></span>
<span><span class="co">#&gt;              1.95e-01</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Gli indici Comparative Fit Index (CFI) = 0.934 e Tucker-Lewis Index (TLI) = 0.912 sono superiori a 0.9, dunque sono almeno sufficienti per gli standard correnti. L’indice RMSEA = 0.064 è appena superiore alla soglia di 0.06. L’indice SRMR = 0.044 è inferiore alla soglia 0.05. Dunque, complessivamente, il modello sembra adeguato.</p>
<p>Adattiamo ora il modello con la modifica proposta da {cite:t}<code>brown2015confirmatory</code>, ovvero</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model2_mdd</span> <span class="op">&lt;-</span> <span class="st">"</span></span>
<span><span class="st">  MDD =~ mdd1 + mdd2 + mdd3 + mdd4 + mdd5 + mdd6 + mdd7 + mdd8 +  mdd9</span></span>
<span><span class="st">  mdd1 ~~ mdd2</span></span>
<span><span class="st">"</span></span>
<span></span>
<span><span class="va">fit2_mdd</span> <span class="op">&lt;-</span> <span class="fu">cfa</span><span class="op">(</span></span>
<span>    <span class="va">model2_mdd</span>,</span>
<span>    data <span class="op">=</span> <span class="va">d_mdd</span></span>
<span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Eseguiamo il test del rapporto di verosimiglianze:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">lavTestLRT</span><span class="op">(</span><span class="va">fit_mdd</span>, <span class="va">fit2_mdd</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Chi-Squared Difference Test</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;          Df   AIC   BIC Chisq Chisq diff RMSEA Df diff Pr(&gt;Chisq)</span></span>
<span><span class="co">#&gt; fit2_mdd 26 27490 27577  67.6                                    </span></span>
<span><span class="co">#&gt; fit_mdd  27 27530 27614 110.3       42.7 0.236       1    6.3e-11</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Il test indica che il modello alternativo si adatta meglio ai dati del modello originale.</p>
<p>Esaminiamo gli indici di bontà di adattamento.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">effectsize</span><span class="fu">::</span><span class="fu"><a href="https://easystats.github.io/effectsize/reference/interpret.html">interpret</a></span><span class="op">(</span><span class="va">fit2_mdd</span><span class="op">)</span></span>
<span><span class="co">#&gt;     Name  Value Threshold Interpretation</span></span>
<span><span class="co">#&gt; 1    GFI 0.9781      0.95   satisfactory</span></span>
<span><span class="co">#&gt; 2   AGFI 0.9620      0.90   satisfactory</span></span>
<span><span class="co">#&gt; 3    NFI 0.9479      0.90   satisfactory</span></span>
<span><span class="co">#&gt; 4   NNFI 0.9544      0.90   satisfactory</span></span>
<span><span class="co">#&gt; 5    CFI 0.9671      0.90   satisfactory</span></span>
<span><span class="co">#&gt; 6  RMSEA 0.0462      0.05   satisfactory</span></span>
<span><span class="co">#&gt; 7   SRMR 0.0368      0.08   satisfactory</span></span>
<span><span class="co">#&gt; 8    RFI 0.9279      0.90   satisfactory</span></span>
<span><span class="co">#&gt; 9   PNFI 0.6846      0.50   satisfactory</span></span>
<span><span class="co">#&gt; 10   IFI 0.9673      0.90   satisfactory</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Gli indici Comparative Fit Index (CFI) = 0.967 e Tucker-Lewis Index (TLI) = 0.954 sono superiori a 0.95. L’indice RMSEA = 0.046. L’indice SRMR = 0.037.</p>
<p>Il “costo” che si paga per questo miglioramento dell’adattamento è che indici di adattamento così buoni, probabilmente, non si replicheranno in un altro campione di dati, a meno che venga introdotto un qualche altro aggiustamento che, sicuramente, sarà diverso da quello usato nel campione corrente. Personalmente, non avrei introdotto il “miglioramento” proposto da {cite:t}<code>brown2015confirmatory</code> in quanto, anche senza un tale aggiustamento post-hoc, il modello produce un adattamento accettabile.</p>
</section></section><section id="confronto-di-modelli-non-annidati" class="level2" data-number="51.8"><h2 data-number="51.8" class="anchored" data-anchor-id="confronto-di-modelli-non-annidati">
<span class="header-section-number">51.8</span> Confronto di Modelli Non Annidati</h2>
<p>Proseguendo, analizzeremo l’adattamento di due modelli distinti, entrambi costituiti dalle stesse variabili e applicati agli stessi dati. Tuttavia, a differenza di quanto precedentemente delineato, questi modelli non sono collegati gerarchicamente, ma si configurano come modelli non annidati. Questa situazione si presenta comunemente quando i ricercatori mettono a confronto modelli basati su teorie divergenti. È possibile effettuare un confronto informale dei valori del chi-quadrato derivanti da modelli non annidati, ma la loro differenza non va interpretata come una statistica di test valida. In altre parole, i test di differenza del chi-quadrato, sia in forma scalata che non, non sono appropriati in questo contesto. La ragione risiede nel fatto che la differenza tra le statistiche di test di modelli non annidati non segue una distribuzione chi-quadrato centrale. Sebbene siano stati compiuti sforzi per elaborare test di significatività adatti al confronto di modelli non annidati, questi metodi non hanno trovato un ampio utilizzo e spesso portano a complicazioni interpretative (Levy &amp; Hancock, 2007).</p>
<p>Una soluzione più pragmatica è rappresentata dalla famiglia degli indici di adattamento predittivo, conosciuti anche come criteri teorico-informativi. Questi indici non sono test di significatività, poiché le loro distribuzioni di probabilità variano ampiamente a seconda del tipo di modello e dei dati considerati e, pertanto, rimangono generalmente ignote. Piuttosto, essi riflettono sia la qualità dell’adattamento del modello sia la sua complessità, bilanciando questi due aspetti. Ciò implica l’applicazione di una penalità per la complessità del modello, che consente di regolare l’adattamento in funzione del numero di parametri liberi. Per esempio, nel caso di due modelli non annidati che mostrano un adattamento simile agli stessi dati, verrà privilegiato il modello meno complesso, in quanto considerato più probabile nella generalizzazione su campioni replicati. In questo scenario, il valore del criterio informativo sarà inferiore per il modello più semplice, dato che una penalità maggiore per la complessità viene applicata all’adattamento del modello più complesso. Di conseguenza, il modello con il criterio informativo più basso è da preferire. In questo capitolo, dopo aver introdotto un problema di ricerca, esploreremo due indici di adattamento predittivo ampiamente usati (AIC e BIC).</p>
<div id="fig-romney" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-romney-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../figures/romney.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-romney-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;51.1: Modelli alternativi non annidati di percorso ricorsivo per l’adattamento dopo un intervento chirurgico cardiaco. (Figura tratta da <span class="citation" data-cites="kline2023principles">Kline (<a href="../../99-references.html#ref-kline2023principles" role="doc-biblioref">2023</a>)</span>.)
</figcaption></figure>
</div>
<p>Nella figura sono presentati due modelli di percorso che descrivono il recupero dei pazienti dopo un intervento chirurgico cardiaco (Romney et al., 1992) – si veda <span class="citation" data-cites="kline2023principles">Kline (<a href="../../99-references.html#ref-kline2023principles" role="doc-biblioref">2023</a>)</span>, cap. 11. Il modello psicosomatico rappresenta le ipotesi che il morale del paziente trasmetta gli effetti della disfunzione neurologica e dello stato socioeconomico ridotto (SES) su sintomi della malattia e scarse relazioni sociali. Il modello medico rappresenta un diverso schema di relazioni causali tra le stesse variabili. In particolare, sia i sintomi della malattia sia la disfunzione neurologica sono specificati come variabili esogene con effetti diretti sul SES ridotto, basso morale e scarse relazioni. Tra queste tre variabili endogene, si ipotizza che il SES ridotto influenzi indirettamente le scarse relazioni attraverso il suo impatto precedente sul basso morale. Ci sono ulteriori effetti indiretti nel modello medico convenzionale dalle variabili esogene a quelle endogene. I due modelli nella figura non sono annidati, quindi il test della differenza del chi-quadro non può essere utilizzato per confrontarli direttamente. È dunque necessario seguire un altro approccio.</p>
</section><section id="aic-e-bic" class="level2" data-number="51.9"><h2 data-number="51.9" class="anchored" data-anchor-id="aic-e-bic">
<span class="header-section-number">51.9</span> AIC e BIC</h2>
<p>Uno degli indici di adattamento predittivo più noti basato sulla stima di massima verosimiglianza (ML) è il Criterio di Informazione di Akaike (AIC), che prende il nome dallo statistico Hirotugu Akaike. La formula per l’AIC di Akaike (1974, p.&nbsp;719) è:</p>
<p><span class="math display">\[ \text{AIC} = -2 \ln L_0 + 2q \]</span></p>
<p>dove <span class="math inline">\(L_0\)</span> è la funzione di verosimiglianza massimizzata nella stima ML per il modello del ricercatore e <span class="math inline">\(q\)</span> è il numero di parametri liberi del modello. Si noti che la penalità per la complessità nell’equazione precedente, <span class="math inline">\(2q\)</span>, diventa relativamente più piccola all’aumentare della dimensione del campione (Mulaik, 2009b).</p>
<p>Un diverso indice teorico-informativo che tiene direttamente conto della dimensione del campione è il Criterio di Informazione Bayesiano (BIC) (Raftery, 1993; Schwarz, 1978). La formula è</p>
<p><span class="math display">\[ \text{BIC} = -2 \ln L_0 + q \ln N \]</span></p>
<p>Confrontato con l’AIC, il BIC impone una penalità relativa maggiore per la complessità del modello.</p>
<p>Supponiamo che il numero di parametri stimati liberamente sia <span class="math inline">\(q = 10\)</span> e che <span class="math inline">\(N = 300\)</span>. La penalità AIC equivale a <span class="math inline">\(2(10)\)</span>, ovvero 20.000 (Equazione 11.4), ma la penalità BIC per lo stesso modello è <span class="math inline">\(10 (\ln 300)\)</span>, ovvero 50.038, più del doppio rispetto all’AIC. I valori relativi delle penalità BIC aumentano più lentamente all’aumentare della dimensione del campione; in altre parole, la sua penalità è asintotica su campioni sempre più grandi (Mulaik, 2009b).</p>
<p>In sostanza, sia l’AIC che il BIC sono strumenti per bilanciare l’adattamento del modello con la sua complessità, ma differiscono nel modo in cui valutano e penalizzano questa complessità, soprattutto in relazione alla dimensione del campione.</p>
<p>Utilizzando lo script fornito da <span class="citation" data-cites="kline2023principles">Kline (<a href="../../99-references.html#ref-kline2023principles" role="doc-biblioref">2023</a>)</span>, iniziamo a importare i dati in <code>R</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># input the correlations in lower diagnonal form</span></span>
<span><span class="va">romneyLower.cor</span> <span class="op">&lt;-</span> <span class="st">"</span></span>
<span><span class="st"> 1.00</span></span>
<span><span class="st">  .53 1.00</span></span>
<span><span class="st">  .15  .18 1.00</span></span>
<span><span class="st">  .52  .29 -.05 1.00</span></span>
<span><span class="st">  .30  .34  .23  .09 1.00 "</span></span>
<span></span>
<span><span class="co"># name the variables and convert to full correlation matrix</span></span>
<span><span class="va">romney.cor</span> <span class="op">&lt;-</span> <span class="fu">lavaan</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lavaan/man/getCov.html">getCov</a></span><span class="op">(</span><span class="va">romneyLower.cor</span>, names <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>    <span class="st">"morale"</span>, <span class="st">"symptoms"</span>,</span>
<span>    <span class="st">"dysfunction"</span>, <span class="st">"relations"</span>, <span class="st">"ses"</span></span>
<span><span class="op">)</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Esaminiamo le matrici di correlazioni e covarianze:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># display the correlations</span></span>
<span><span class="va">romney.cor</span></span>
<span><span class="co">#&gt;             morale symptoms dysfunction relations  ses</span></span>
<span><span class="co">#&gt; morale        1.00     0.53        0.15      0.52 0.30</span></span>
<span><span class="co">#&gt; symptoms      0.53     1.00        0.18      0.29 0.34</span></span>
<span><span class="co">#&gt; dysfunction   0.15     0.18        1.00     -0.05 0.23</span></span>
<span><span class="co">#&gt; relations     0.52     0.29       -0.05      1.00 0.09</span></span>
<span><span class="co">#&gt; ses           0.30     0.34        0.23      0.09 1.00</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># add the standard deviations and convert to covariances</span></span>
<span><span class="va">romney.cov</span> <span class="op">&lt;-</span> <span class="fu">lavaan</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lavaan/man/getCov.html">cor2cov</a></span><span class="op">(</span><span class="va">romney.cor</span>, sds <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>    <span class="fl">3.75</span>, <span class="fl">17.00</span>, <span class="fl">19.50</span>,</span>
<span>    <span class="fl">3.50</span>, <span class="fl">24.70</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># display the covariances</span></span>
<span><span class="va">romney.cov</span></span>
<span><span class="co">#&gt;             morale symptoms dysfunction relations    ses</span></span>
<span><span class="co">#&gt; morale       14.06     33.8       10.97      6.83  27.79</span></span>
<span><span class="co">#&gt; symptoms     33.79    289.0       59.67     17.25 142.77</span></span>
<span><span class="co">#&gt; dysfunction  10.97     59.7      380.25     -3.41 110.78</span></span>
<span><span class="co">#&gt; relations     6.83     17.3       -3.41     12.25   7.78</span></span>
<span><span class="co">#&gt; ses          27.79    142.8      110.78      7.78 610.09</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Specifichiamo il modello psicosomatico.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">somatic.model</span> <span class="op">&lt;-</span> <span class="st">"</span></span>
<span><span class="st">    # regressions</span></span>
<span><span class="st">    morale ~ ses + dysfunction</span></span>
<span><span class="st">    relations ~ morale</span></span>
<span><span class="st">    symptoms ~ morale</span></span>
<span><span class="st">    # without the zero constraint listed next,</span></span>
<span><span class="st">    # lavaan automatically specifies correlated</span></span>
<span><span class="st">    # disturbances for symptoms and relations,</span></span>
<span><span class="st">    # but their disturbances are independent in</span></span>
<span><span class="st">    # figure 11.1</span></span>
<span><span class="st">    symptoms ~~ 0*relations</span></span>
<span><span class="st">    # unanalyzed association between ses and dysfunction</span></span>
<span><span class="st">    # automatically specified </span></span>
<span><span class="st">"</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Specifichiamo il modello medico convenzionale.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">medical.model</span> <span class="op">&lt;-</span> <span class="st">"</span></span>
<span><span class="st">    # regressions</span></span>
<span><span class="st">    ses ~ symptoms + dysfunction</span></span>
<span><span class="st">    morale ~ symptoms + ses</span></span>
<span><span class="st">    relations ~ dysfunction + morale</span></span>
<span><span class="st">    # unanalyzed association between symptoms and dysfunction</span></span>
<span><span class="st">    # automatically specified </span></span>
<span><span class="st">"</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Adattiamo ai dati il modello psicosomatico.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">somatic</span> <span class="op">&lt;-</span> <span class="fu">lavaan</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lavaan/man/sem.html">sem</a></span><span class="op">(</span><span class="va">somatic.model</span>,</span>
<span>    sample.cov <span class="op">=</span> <span class="va">romney.cov</span>,</span>
<span>    sample.nobs <span class="op">=</span> <span class="fl">469</span>, fixed.x <span class="op">=</span> <span class="cn">FALSE</span>, sample.cov.rescale <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">semPaths</span><span class="op">(</span><span class="va">somatic</span>,</span>
<span>    whatLabels <span class="op">=</span> <span class="st">"std"</span>,</span>
<span>    sizeMan <span class="op">=</span> <span class="fl">10</span>,</span>
<span>    edge.label.cex <span class="op">=</span> <span class="fl">1.0</span>,</span>
<span>    style <span class="op">=</span> <span class="st">"mx"</span>,</span>
<span>    nCharNodes <span class="op">=</span> <span class="fl">0</span>, nCharEdges <span class="op">=</span> <span class="fl">0</span></span>
<span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04_mod_comp_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">lavaan</span><span class="fu">::</span><span class="fu">summary</span><span class="op">(</span><span class="va">somatic</span>, fit.measures <span class="op">=</span> <span class="cn">TRUE</span>, rsquare <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> </span>
<span><span class="co">#&gt; lavaan 0.6-19 ended normally after 1 iteration</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Estimator                                         ML</span></span>
<span><span class="co">#&gt;   Optimization method                           NLMINB</span></span>
<span><span class="co">#&gt;   Number of model parameters                        10</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Number of observations                           469</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Model Test User Model:</span></span>
<span><span class="co">#&gt;                                                       </span></span>
<span><span class="co">#&gt;   Test statistic                                40.488</span></span>
<span><span class="co">#&gt;   Degrees of freedom                                 5</span></span>
<span><span class="co">#&gt;   P-value (Chi-square)                           0.000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Model Test Baseline Model:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Test statistic                               390.816</span></span>
<span><span class="co">#&gt;   Degrees of freedom                                 9</span></span>
<span><span class="co">#&gt;   P-value                                        0.000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; User Model versus Baseline Model:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Comparative Fit Index (CFI)                    0.907</span></span>
<span><span class="co">#&gt;   Tucker-Lewis Index (TLI)                       0.833</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Loglikelihood and Information Criteria:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Loglikelihood user model (H0)              -8572.844</span></span>
<span><span class="co">#&gt;   Loglikelihood unrestricted model (H1)      -8552.599</span></span>
<span><span class="co">#&gt;                                                       </span></span>
<span><span class="co">#&gt;   Akaike (AIC)                               17165.687</span></span>
<span><span class="co">#&gt;   Bayesian (BIC)                             17207.193</span></span>
<span><span class="co">#&gt;   Sample-size adjusted Bayesian (SABIC)      17175.455</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Root Mean Square Error of Approximation:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   RMSEA                                          0.123</span></span>
<span><span class="co">#&gt;   90 Percent confidence interval - lower         0.090</span></span>
<span><span class="co">#&gt;   90 Percent confidence interval - upper         0.159</span></span>
<span><span class="co">#&gt;   P-value H_0: RMSEA &lt;= 0.050                    0.000</span></span>
<span><span class="co">#&gt;   P-value H_0: RMSEA &gt;= 0.080                    0.982</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Standardized Root Mean Square Residual:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   SRMR                                           0.065</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Parameter Estimates:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Standard errors                             Standard</span></span>
<span><span class="co">#&gt;   Information                                 Expected</span></span>
<span><span class="co">#&gt;   Information saturated (h1) model          Structured</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Regressions:</span></span>
<span><span class="co">#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)</span></span>
<span><span class="co">#&gt;   morale ~                                            </span></span>
<span><span class="co">#&gt;     ses               0.043    0.007    6.217    0.000</span></span>
<span><span class="co">#&gt;     dysfunction       0.016    0.009    1.897    0.058</span></span>
<span><span class="co">#&gt;   relations ~                                         </span></span>
<span><span class="co">#&gt;     morale            0.485    0.037   13.184    0.000</span></span>
<span><span class="co">#&gt;   symptoms ~                                          </span></span>
<span><span class="co">#&gt;     morale            2.403    0.178   13.535    0.000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Covariances:</span></span>
<span><span class="co">#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)</span></span>
<span><span class="co">#&gt;  .relations ~~                                        </span></span>
<span><span class="co">#&gt;    .symptoms          0.000                           </span></span>
<span><span class="co">#&gt;   ses ~~                                              </span></span>
<span><span class="co">#&gt;     dysfunction     110.779   22.821    4.854    0.000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Variances:</span></span>
<span><span class="co">#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)</span></span>
<span><span class="co">#&gt;    .morale           12.699    0.829   15.313    0.000</span></span>
<span><span class="co">#&gt;    .relations         8.938    0.584   15.313    0.000</span></span>
<span><span class="co">#&gt;    .symptoms        207.820   13.571   15.313    0.000</span></span>
<span><span class="co">#&gt;     ses             610.090   39.840   15.313    0.000</span></span>
<span><span class="co">#&gt;     dysfunction     380.250   24.831   15.313    0.000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; R-Square:</span></span>
<span><span class="co">#&gt;                    Estimate</span></span>
<span><span class="co">#&gt;     morale            0.097</span></span>
<span><span class="co">#&gt;     relations         0.270</span></span>
<span><span class="co">#&gt;     symptoms          0.281</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ora approfondiamo l’analisi dei residui. Nel contesto di un modello SEM, i residui sono derivati dalle differenze tra la matrice di correlazioni (o covarianze) osservata e quella prevista dal modello. Queste differenze sono elaborate attraverso specifiche funzioni per generare i residui. Utilizzando il pacchetto <code>lavaan</code> in R, possiamo accedere a tre principali tipi di residui: <code>standardized.mplus</code>, <code>normalized</code>, e <code>cor.bollen</code>.</p>
<ol type="1">
<li><p><strong>Residui Standardizzati (Standardized.mplus)</strong>: Questo tipo di residuo è una versione standardizzata dei residui. I residui standardizzati sono ottenuti calcolando la differenza tra i valori osservati e quelli previsti dal modello, e dividendo questa differenza per uno stimatore della deviazione standard del residuo. Questo processo trasforma i residui in una scala in cui hanno una varianza approssimativamente uguale. I residui standardizzati sono utili per identificare punti dati che il modello non riesce a spiegare bene. In <code>lavaan</code>, <code>type = "standardized.mplus"</code> si riferisce a una particolare forma di standardizzazione dei residui, simile a quella utilizzata nel software Mplus.</p></li>
<li><p><strong>Residui Normalizzati (Normalized)</strong>: I residui normalizzati sono un altro tipo di residui standardizzati. Sono calcolati come i residui standardizzati ma poi vengono normalizzati. La normalizzazione qui significa che i residui vengono ulteriormente trasformati in modo che la loro distribuzione si avvicini a una distribuzione normale. Questo è utile per verificare se i residui seguono una distribuzione normale, il che è un’assunzione comune in molti modelli statistici, inclusi quelli SEM.</p></li>
<li><p><strong>Correlazione dei Residui secondo Bollen (Cor.bollen)</strong>: Questo tipo di residuo si riferisce alla correlazione tra i residui di due variabili diverse nel modello. Il metodo <code>cor.bollen</code> calcola la correlazione tra i residui dopo che il modello è stato adattato ai dati. Questo tipo di analisi è utile per rilevare se ci sono correlazioni non modellate tra le variabili che potrebbero influenzare la validità del modello.</p></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">lavaan</span><span class="fu">::</span><span class="fu">residuals</span><span class="op">(</span><span class="va">somatic</span>, type <span class="op">=</span> <span class="st">"standardized.mplus"</span><span class="op">)</span> </span>
<span><span class="co">#&gt; $type</span></span>
<span><span class="co">#&gt; [1] "standardized.mplus"</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $cov</span></span>
<span><span class="co">#&gt;             morale reltns symptm    ses dysfnc</span></span>
<span><span class="co">#&gt; morale       0.000                            </span></span>
<span><span class="co">#&gt; relations    0.000  0.000                     </span></span>
<span><span class="co">#&gt; symptoms     0.000  0.427  0.000              </span></span>
<span><span class="co">#&gt; ses          0.000 -1.776  4.542  0.000       </span></span>
<span><span class="co">#&gt; dysfunction  0.000 -3.291  2.549  0.000  0.000</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">lavaan</span><span class="fu">::</span><span class="fu">residuals</span><span class="op">(</span><span class="va">somatic</span>, type <span class="op">=</span> <span class="st">"normalized"</span><span class="op">)</span> </span>
<span><span class="co">#&gt; $type</span></span>
<span><span class="co">#&gt; [1] "normalized"</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $cov</span></span>
<span><span class="co">#&gt;             morale reltns symptm   ses dysfnc</span></span>
<span><span class="co">#&gt; morale        0.00                           </span></span>
<span><span class="co">#&gt; relations     0.00   0.00                    </span></span>
<span><span class="co">#&gt; symptoms      0.00   0.30   0.00             </span></span>
<span><span class="co">#&gt; ses           0.00  -1.42   3.71  0.00       </span></span>
<span><span class="co">#&gt; dysfunction   0.00  -2.77   2.14  0.00   0.00</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">lavaan</span><span class="fu">::</span><span class="fu">residuals</span><span class="op">(</span><span class="va">somatic</span>, type <span class="op">=</span> <span class="st">"cor.bollen"</span><span class="op">)</span></span>
<span><span class="co">#&gt; $type</span></span>
<span><span class="co">#&gt; [1] "cor.bollen"</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $cov</span></span>
<span><span class="co">#&gt;             morale reltns symptm    ses dysfnc</span></span>
<span><span class="co">#&gt; morale       0.000                            </span></span>
<span><span class="co">#&gt; relations    0.000  0.000                     </span></span>
<span><span class="co">#&gt; symptoms     0.000  0.014  0.000              </span></span>
<span><span class="co">#&gt; ses          0.000 -0.066  0.181  0.000       </span></span>
<span><span class="co">#&gt; dysfunction  0.000 -0.128  0.100  0.000  0.000</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Adattiamo ai dati il modello medico convenzionale.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">medical</span> <span class="op">&lt;-</span> <span class="fu">lavaan</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lavaan/man/sem.html">sem</a></span><span class="op">(</span><span class="va">medical.model</span>,</span>
<span>    sample.cov <span class="op">=</span> <span class="va">romney.cov</span>,</span>
<span>    sample.nobs <span class="op">=</span> <span class="fl">469</span>, fixed.x <span class="op">=</span> <span class="cn">FALSE</span>, sample.cov.rescale <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">semPaths</span><span class="op">(</span><span class="va">medical</span>,</span>
<span>    whatLabels <span class="op">=</span> <span class="st">"std"</span>,</span>
<span>    sizeMan <span class="op">=</span> <span class="fl">10</span>,</span>
<span>    edge.label.cex <span class="op">=</span> <span class="fl">1.15</span>,</span>
<span>    style <span class="op">=</span> <span class="st">"mx"</span>,</span>
<span>    nCharNodes <span class="op">=</span> <span class="fl">0</span>, nCharEdges <span class="op">=</span> <span class="fl">0</span></span>
<span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04_mod_comp_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">lavaan</span><span class="fu">::</span><span class="fu">summary</span><span class="op">(</span><span class="va">medical</span>, fit.measures <span class="op">=</span> <span class="cn">TRUE</span>, rsquare <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>  </span>
<span><span class="co">#&gt; lavaan 0.6-19 ended normally after 1 iteration</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Estimator                                         ML</span></span>
<span><span class="co">#&gt;   Optimization method                           NLMINB</span></span>
<span><span class="co">#&gt;   Number of model parameters                        12</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Number of observations                           469</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Model Test User Model:</span></span>
<span><span class="co">#&gt;                                                       </span></span>
<span><span class="co">#&gt;   Test statistic                                 3.245</span></span>
<span><span class="co">#&gt;   Degrees of freedom                                 3</span></span>
<span><span class="co">#&gt;   P-value (Chi-square)                           0.355</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Model Test Baseline Model:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Test statistic                               400.859</span></span>
<span><span class="co">#&gt;   Degrees of freedom                                 9</span></span>
<span><span class="co">#&gt;   P-value                                        0.000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; User Model versus Baseline Model:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Comparative Fit Index (CFI)                    0.999</span></span>
<span><span class="co">#&gt;   Tucker-Lewis Index (TLI)                       0.998</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Loglikelihood and Information Criteria:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Loglikelihood user model (H0)              -8554.222</span></span>
<span><span class="co">#&gt;   Loglikelihood unrestricted model (H1)      -8552.599</span></span>
<span><span class="co">#&gt;                                                       </span></span>
<span><span class="co">#&gt;   Akaike (AIC)                               17132.444</span></span>
<span><span class="co">#&gt;   Bayesian (BIC)                             17182.251</span></span>
<span><span class="co">#&gt;   Sample-size adjusted Bayesian (SABIC)      17144.166</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Root Mean Square Error of Approximation:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   RMSEA                                          0.013</span></span>
<span><span class="co">#&gt;   90 Percent confidence interval - lower         0.000</span></span>
<span><span class="co">#&gt;   90 Percent confidence interval - upper         0.080</span></span>
<span><span class="co">#&gt;   P-value H_0: RMSEA &lt;= 0.050                    0.742</span></span>
<span><span class="co">#&gt;   P-value H_0: RMSEA &gt;= 0.080                    0.050</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Standardized Root Mean Square Residual:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   SRMR                                           0.016</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Parameter Estimates:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   Standard errors                             Standard</span></span>
<span><span class="co">#&gt;   Information                                 Expected</span></span>
<span><span class="co">#&gt;   Information saturated (h1) model          Structured</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Regressions:</span></span>
<span><span class="co">#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)</span></span>
<span><span class="co">#&gt;   ses ~                                               </span></span>
<span><span class="co">#&gt;     symptoms          0.448    0.063    7.110    0.000</span></span>
<span><span class="co">#&gt;     dysfunction       0.221    0.055    4.019    0.000</span></span>
<span><span class="co">#&gt;   morale ~                                            </span></span>
<span><span class="co">#&gt;     symptoms          0.107    0.009   11.756    0.000</span></span>
<span><span class="co">#&gt;     ses               0.021    0.006    3.291    0.001</span></span>
<span><span class="co">#&gt;   relations ~                                         </span></span>
<span><span class="co">#&gt;     dysfunction      -0.024    0.007   -3.335    0.001</span></span>
<span><span class="co">#&gt;     morale            0.504    0.037   13.745    0.000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Covariances:</span></span>
<span><span class="co">#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)</span></span>
<span><span class="co">#&gt;   symptoms ~~                                         </span></span>
<span><span class="co">#&gt;     dysfunction      59.670   15.553    3.836    0.000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Variances:</span></span>
<span><span class="co">#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)</span></span>
<span><span class="co">#&gt;    .ses             521.598   34.062   15.313    0.000</span></span>
<span><span class="co">#&gt;    .morale            9.884    0.645   15.313    0.000</span></span>
<span><span class="co">#&gt;    .relations         8.732    0.570   15.313    0.000</span></span>
<span><span class="co">#&gt;     symptoms        289.000   18.872   15.313    0.000</span></span>
<span><span class="co">#&gt;     dysfunction     380.250   24.831   15.313    0.000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; R-Square:</span></span>
<span><span class="co">#&gt;                    Estimate</span></span>
<span><span class="co">#&gt;     ses               0.145</span></span>
<span><span class="co">#&gt;     morale            0.297</span></span>
<span><span class="co">#&gt;     relations         0.290</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">lavaan</span><span class="fu">::</span><span class="fu">residuals</span><span class="op">(</span><span class="va">medical</span>, type <span class="op">=</span> <span class="st">"standardized.mplus"</span><span class="op">)</span></span>
<span><span class="co">#&gt; $type</span></span>
<span><span class="co">#&gt; [1] "standardized.mplus"</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $cov</span></span>
<span><span class="co">#&gt;                ses morale reltns symptm dysfnc</span></span>
<span><span class="co">#&gt; ses          0.000                            </span></span>
<span><span class="co">#&gt; morale       0.000  0.000                     </span></span>
<span><span class="co">#&gt; relations   -1.161 -1.818     NA              </span></span>
<span><span class="co">#&gt; symptoms     0.000  0.000  0.833  0.000       </span></span>
<span><span class="co">#&gt; dysfunction  0.000  0.842  0.862  0.000  0.000</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">lavaan</span><span class="fu">::</span><span class="fu">residuals</span><span class="op">(</span><span class="va">medical</span>, type <span class="op">=</span> <span class="st">"normalized"</span><span class="op">)</span> </span>
<span><span class="co">#&gt; $type</span></span>
<span><span class="co">#&gt; [1] "normalized"</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $cov</span></span>
<span><span class="co">#&gt;                ses morale reltns symptm dysfnc</span></span>
<span><span class="co">#&gt; ses          0.000                            </span></span>
<span><span class="co">#&gt; morale       0.000  0.000                     </span></span>
<span><span class="co">#&gt; relations   -0.901 -0.080 -0.069              </span></span>
<span><span class="co">#&gt; symptoms     0.000  0.000  0.573  0.000       </span></span>
<span><span class="co">#&gt; dysfunction  0.000  0.680  0.370  0.000  0.000</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">lavaan</span><span class="fu">::</span><span class="fu">residuals</span><span class="op">(</span><span class="va">medical</span>, type <span class="op">=</span> <span class="st">"cor.bollen"</span><span class="op">)</span> </span>
<span><span class="co">#&gt; $type</span></span>
<span><span class="co">#&gt; [1] "cor.bollen"</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $cov</span></span>
<span><span class="co">#&gt;                ses morale reltns symptm dysfnc</span></span>
<span><span class="co">#&gt; ses          0.000                            </span></span>
<span><span class="co">#&gt; morale       0.000  0.000                     </span></span>
<span><span class="co">#&gt; relations   -0.041 -0.003  0.000              </span></span>
<span><span class="co">#&gt; symptoms     0.000  0.000  0.028  0.000       </span></span>
<span><span class="co">#&gt; dysfunction  0.000  0.032  0.017  0.000  0.000</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In conclusione, i valori i valori degli indici di adattamento predittivo per i due modelli alternativi di Romney et al.&nbsp;(1992) sono stati generati seguendo le istruzioni precedentemente descritte. Non sorprende che l’adattamento globale del modello medico convenzionale, più complesso (con $ dfM = 3 $), sia migliore rispetto a quello del modello psicosomatico, più semplice (con $ dfM = 5 $). Nonostante il modello medico convenzionale sia più complesso e quindi soggetto a una penalità maggiore per il minor numero di gradi di libertà, i valori ottenuti sia nell’AIC che nel BIC sono inferiori rispetto a quelli del modello psicosomatico. Questo indica che il vantaggio in termini di adattamento del modello medico convenzionale è sufficiente a superare la penalità per la sua maggiore complessità. In base a queste analisi, il modello medico convenzionale è considerato più adatto rispetto al modello psicosomatico, come evidenziato dai valori più bassi nei criteri AIC e BIC.</p>
</section><section id="indici-di-modifica-e-statistiche-correlate-nel-sem" class="level2" data-number="51.10"><h2 data-number="51.10" class="anchored" data-anchor-id="indici-di-modifica-e-statistiche-correlate-nel-sem">
<span class="header-section-number">51.10</span> Indici di Modifica e Statistiche Correlate nel SEM</h2>
<p>Nell’elaborazione di modelli SEM (Structural Equation Modeling), esiste la possibilità di implementare modifiche attraverso processi automatizzati. Questi interventi, di carattere esplorativo, si basano sull’aggiunta o sulla rimozione di parametri seguendo criteri empirici, come la significatività statistica di un indice di modifica (MI) o di un test di punteggio. Gli indici di modifica, in particolare, sono calcolati per quei parametri che nel modello sono stati inizialmente vincolati e servono a stimare quanto il chi-quadrato del modello di massima verosimiglianza (chiML) si ridurrebbe se un dato parametro vincolato venisse liberato.</p>
<p>Il meccanismo di modifica automatica opera liberando, ad ogni iterazione, il parametro vincolato che presenta il valore di MI più alto. Questo processo continua finché non si raggiunge un MI che è statisticamente significativo secondo i criteri stabiliti dal ricercatore. È cruciale, tuttavia, riconoscere che l’uso di questa metodologia, specialmente in campioni di piccole dimensioni, può portare alla formulazione di modelli che si basano eccessivamente sul caso. Di conseguenza, questi modelli potrebbero risultare poco robusti e difficilmente replicabili in studi successivi. L’automazione nel processo di ottimizzazione dei modelli SEM richiede dunque un’attenta valutazione del contesto e della dimensione del campione per garantire l’affidabilità e la validità dei risultati ottenuti.</p>
<p>Un altro strumento di uso frequente nei SEM è il test di Wald, basato sulla statistica W. Questo test è progettato per valutare l’impatto che avrebbe la fissazione a zero di un parametro precedentemente stimato liberamente nel modello. In termini più tecnici, il test di Wald stima l’incremento che si verificherebbe nel chi-quadrato del modello di massima verosimiglianza (chiML) se tale parametro fosse “potato”, ovvero escluso dal modello.</p>
<p>Similmente ai processi di modifica automatica, l’efficacia del test di Wald può essere influenzata dalla casualità. Un aspetto cruciale da considerare è la sensibilità di questi test alla dimensione del campione. Infatti, anche piccole modifiche nella bontà di adattamento del modello possono assumere una significatività statistica notevole in campioni di ampie dimensioni.</p>
<p>Di conseguenza, quando si valutano gli indici di modifica come il MI (Modifica Index), è essenziale che il ricercatore non si limiti a considerarne la sola significatività statistica. È importante anche valutare l’entità del cambiamento che si verificherebbe nel coefficiente del parametro se fosse liberato. Se il cambiamento previsto è minimo, la significatività statistica dell’indice di modifica potrebbe essere più indicativa della dimensione del campione che non della sostanziale rilevanza dell’effetto analizzato. Questa considerazione sottolinea l’importanza di un approccio olistico e critico nell’interpretazione dei risultati dei test diagnostici in SEM, specialmente in contesti dove la dimensione del campione può influenzare significativamente i risultati.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_mdd</span> <span class="op">&lt;-</span> <span class="fu">cfa</span><span class="op">(</span></span>
<span>    <span class="va">model_mdd</span>,</span>
<span>    data <span class="op">=</span> <span class="va">d_mdd</span></span>
<span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Calcoliamo gli indici di modifica.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">modification_indices</span> <span class="op">&lt;-</span> <span class="fu">lavInspect</span><span class="op">(</span><span class="va">fit_mdd</span>, <span class="st">"mi"</span><span class="op">)</span></span>
<span><span class="va">modification_indices</span> </span>
<span><span class="co">#&gt;     lhs op  rhs     mi    epc sepc.lv sepc.all sepc.nox</span></span>
<span><span class="co">#&gt; 20 mdd1 ~~ mdd2 46.877  0.732   0.732    0.560    0.560</span></span>
<span><span class="co">#&gt; 21 mdd1 ~~ mdd3  4.996 -0.211  -0.211   -0.108   -0.108</span></span>
<span><span class="co">#&gt; 22 mdd1 ~~ mdd4  4.625 -0.215  -0.215   -0.108   -0.108</span></span>
<span><span class="co">#&gt; 23 mdd1 ~~ mdd5  7.797 -0.266  -0.266   -0.137   -0.137</span></span>
<span><span class="co">#&gt; 24 mdd1 ~~ mdd6  6.434 -0.236  -0.236   -0.132   -0.132</span></span>
<span><span class="co">#&gt; 25 mdd1 ~~ mdd7  0.293  0.053   0.053    0.026    0.026</span></span>
<span><span class="co">#&gt; 26 mdd1 ~~ mdd8  5.046 -0.219  -0.219   -0.116   -0.116</span></span>
<span><span class="co">#&gt; 27 mdd1 ~~ mdd9  5.385  0.187   0.187    0.111    0.111</span></span>
<span><span class="co">#&gt; 28 mdd2 ~~ mdd3  1.435 -0.138  -0.138   -0.055   -0.055</span></span>
<span><span class="co">#&gt; 29 mdd2 ~~ mdd4 10.931 -0.402  -0.402   -0.158   -0.158</span></span>
<span><span class="co">#&gt; 30 mdd2 ~~ mdd5  5.835 -0.281  -0.281   -0.113   -0.113</span></span>
<span><span class="co">#&gt; 31 mdd2 ~~ mdd6  2.235 -0.169  -0.169   -0.074   -0.074</span></span>
<span><span class="co">#&gt; 32 mdd2 ~~ mdd7  0.394 -0.076  -0.076   -0.029   -0.029</span></span>
<span><span class="co">#&gt; 33 mdd2 ~~ mdd8  0.027 -0.019  -0.019   -0.008   -0.008</span></span>
<span><span class="co">#&gt; 34 mdd2 ~~ mdd9  2.070 -0.142  -0.142   -0.066   -0.066</span></span>
<span><span class="co">#&gt; 35 mdd3 ~~ mdd4 16.199  0.591   0.591    0.155    0.155</span></span>
<span><span class="co">#&gt; 36 mdd3 ~~ mdd5  3.298  0.258   0.258    0.069    0.069</span></span>
<span><span class="co">#&gt; 37 mdd3 ~~ mdd6  6.361  0.337   0.337    0.098    0.098</span></span>
<span><span class="co">#&gt; 38 mdd3 ~~ mdd7  0.499 -0.106  -0.106   -0.027   -0.027</span></span>
<span><span class="co">#&gt; 39 mdd3 ~~ mdd8  0.014 -0.017  -0.017   -0.005   -0.005</span></span>
<span><span class="co">#&gt; 40 mdd3 ~~ mdd9  2.860 -0.208  -0.208   -0.064   -0.064</span></span>
<span><span class="co">#&gt; 41 mdd4 ~~ mdd5 12.198  0.509   0.509    0.136    0.136</span></span>
<span><span class="co">#&gt; 42 mdd4 ~~ mdd6 17.435  0.573   0.573    0.165    0.165</span></span>
<span><span class="co">#&gt; 43 mdd4 ~~ mdd7  1.272 -0.174  -0.174   -0.043   -0.043</span></span>
<span><span class="co">#&gt; 44 mdd4 ~~ mdd8  0.975  0.143   0.143    0.039    0.039</span></span>
<span><span class="co">#&gt; 45 mdd4 ~~ mdd9  1.879 -0.173  -0.173   -0.053   -0.053</span></span>
<span><span class="co">#&gt; 46 mdd5 ~~ mdd6  7.502  0.364   0.364    0.107    0.107</span></span>
<span><span class="co">#&gt; 47 mdd5 ~~ mdd7  0.096  0.046   0.046    0.012    0.012</span></span>
<span><span class="co">#&gt; 48 mdd5 ~~ mdd8  4.217  0.288   0.288    0.080    0.080</span></span>
<span><span class="co">#&gt; 49 mdd5 ~~ mdd9  0.544 -0.090  -0.090   -0.028   -0.028</span></span>
<span><span class="co">#&gt; 50 mdd6 ~~ mdd7  2.046 -0.201  -0.201   -0.055   -0.055</span></span>
<span><span class="co">#&gt; 51 mdd6 ~~ mdd8  0.877  0.124   0.124    0.037    0.037</span></span>
<span><span class="co">#&gt; 52 mdd6 ~~ mdd9  2.479 -0.180  -0.180   -0.061   -0.061</span></span>
<span><span class="co">#&gt; 53 mdd7 ~~ mdd8  0.188  0.064   0.064    0.017    0.017</span></span>
<span><span class="co">#&gt; 54 mdd7 ~~ mdd9 13.527  0.474   0.474    0.139    0.139</span></span>
<span><span class="co">#&gt; 55 mdd8 ~~ mdd9  0.322  0.069   0.069    0.022    0.022</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nel modello che stiamo analizzando, l’indice di modifica (MI) più elevato si riferisce alla possibile modifica del parametro che governa la correlazione tra i residui degli indicatori <code>mm1</code> e <code>mm2</code>. Nel modello <code>model_mdd</code> questa correlazione residua è impostata a zero, indicando l’assenza di una correlazione diretta tra questi residui. Tuttavia, l’indice di modifica suggerisce che se permettessimo a questa correlazione di essere stimata liberamente dal modello (anziché tenerla fissa a zero), si verificherebbe un miglioramento dell’adattamento del modello ai dati osservati. Questa osservazione è in linea con il modello alternativo che è stato proposto per questi dati proposto da <span class="citation" data-cites="brown2015confirmatory">Brown (<a href="../../99-references.html#ref-brown2015confirmatory" role="doc-biblioref">2015</a>)</span>.</p>
<p>Incorporare una correlazione residua tra <code>mm1</code> e <code>mm2</code> significa riconoscere che, oltre alla variazione spiegata dalle variabili latenti comuni, esiste una relazione unica tra questi due indicatori che non è catturata dal modello. Tale relazione potrebbe essere dovuta a fattori specifici relativi a questi indicatori o a una misurazione comune non prevista dal modello originale.</p>
<p>È importante sottolineare che ogni modifica al modello basata sugli indici di modifica dovrebbe essere attentamente valutata per assicurarsi che sia supportata sia da giustificazioni teoriche che empiriche. Aggiungere correlazioni residue può migliorare l’adattamento del modello, ma dovrebbe essere fatto con cautela per evitare di creare un modello eccessivamente complesso che potrebbe non essere generalizzabile al di fuori del campione di dati specifico utilizzato.</p>
</section><section id="riflessioni-conclusive" class="level2" data-number="51.11"><h2 data-number="51.11" class="anchored" data-anchor-id="riflessioni-conclusive">
<span class="header-section-number">51.11</span> Riflessioni Conclusive</h2>
<p>Nel campo dei modelli SEM, è pratica comune selezionare il modello più appropriato da un insieme di alternative, tutte calibrate sugli stessi dati. È frequente il confronto tra modelli gerarchicamente collegati, in cui il modello più restrittivo è incluso, o annidato, in quello meno restrittivo. In queste situazioni, il test di differenza del chi-quadrato viene impiegato per valutare se i modelli hanno un adattamento equivalente. Utilizzare questo test e le statistiche diagnostiche correlate, come gli indici di modifica, richiede un approccio guidato dalla teoria, non solo da criteri empirici. Un eccessivo affidamento su criteri puramente empirici, come la significatività statistica, può portare a una dipendenza eccessiva dal caso.</p>
<p>Per confrontare modelli non annidati, il test di differenza del chi-quadrato non è idoneo, ma si possono adottare gli indici di adattamento predittivo, basati sulla teoria dell’informazione, per la loro valutazione. Quando si decide di mantenere un modello, è cruciale prendere in considerazione anche altri modelli alternativi potenzialmente equivalenti. È importante fornire motivazioni solide su perché il modello selezionato dal ricercatore sia da preferire rispetto a queste alternative equivalenti.</p>
<p>Questo approccio consente una comprensione più profonda e una scelta più informata del modello, assicurando che la selezione sia fondata su basi teoriche solide e non solamente su risultati statistici.</p>
</section><section id="session-info" class="level2" data-number="51.12"><h2 data-number="51.12" class="anchored" data-anchor-id="session-info">
<span class="header-section-number">51.12</span> Session Info</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; R version 4.4.2 (2024-10-31)</span></span>
<span><span class="co">#&gt; Platform: aarch64-apple-darwin20</span></span>
<span><span class="co">#&gt; Running under: macOS Sequoia 15.3</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Matrix products: default</span></span>
<span><span class="co">#&gt; BLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib </span></span>
<span><span class="co">#&gt; LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; locale:</span></span>
<span><span class="co">#&gt; [1] C/UTF-8/C/C/C/C</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; time zone: Europe/Rome</span></span>
<span><span class="co">#&gt; tzcode source: internal</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; attached base packages:</span></span>
<span><span class="co">#&gt; [1] stats     graphics  grDevices utils     datasets  methods   base     </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; other attached packages:</span></span>
<span><span class="co">#&gt;  [1] effectsize_1.0.0   rsvg_2.6.1         DiagrammeRsvg_0.1 </span></span>
<span><span class="co">#&gt;  [4] mvnormalTest_1.0.0 lavaanPlot_0.8.1   lavaanExtra_0.2.1 </span></span>
<span><span class="co">#&gt;  [7] ggokabeito_0.1.0   see_0.9.0          MASS_7.3-64       </span></span>
<span><span class="co">#&gt; [10] viridis_0.6.5      viridisLite_0.4.2  ggpubr_0.6.0      </span></span>
<span><span class="co">#&gt; [13] ggExtra_0.10.1     gridExtra_2.3      patchwork_1.3.0   </span></span>
<span><span class="co">#&gt; [16] bayesplot_1.11.1   semTools_0.5-6     semPlot_1.1.6     </span></span>
<span><span class="co">#&gt; [19] lavaan_0.6-19      psych_2.4.12       scales_1.3.0      </span></span>
<span><span class="co">#&gt; [22] markdown_1.13      knitr_1.49         lubridate_1.9.4   </span></span>
<span><span class="co">#&gt; [25] forcats_1.0.0      stringr_1.5.1      dplyr_1.1.4       </span></span>
<span><span class="co">#&gt; [28] purrr_1.0.2        readr_2.1.5        tidyr_1.3.1       </span></span>
<span><span class="co">#&gt; [31] tibble_3.2.1       ggplot2_3.5.1      tidyverse_2.0.0   </span></span>
<span><span class="co">#&gt; [34] here_1.0.1        </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; loaded via a namespace (and not attached):</span></span>
<span><span class="co">#&gt;   [1] splines_4.4.2       later_1.4.1         datawizard_1.0.0   </span></span>
<span><span class="co">#&gt;   [4] XML_3.99-0.18       rpart_4.1.24        lifecycle_1.0.4    </span></span>
<span><span class="co">#&gt;   [7] Rdpack_2.6.2        rstatix_0.7.2       rprojroot_2.0.4    </span></span>
<span><span class="co">#&gt;  [10] lattice_0.22-6      insight_1.0.1       rockchalk_1.8.157  </span></span>
<span><span class="co">#&gt;  [13] backports_1.5.0     magrittr_2.0.3      openxlsx_4.2.7.1   </span></span>
<span><span class="co">#&gt;  [16] Hmisc_5.2-2         rmarkdown_2.29      httpuv_1.6.15      </span></span>
<span><span class="co">#&gt;  [19] qgraph_1.9.8        zip_2.3.1           pbapply_1.7-2      </span></span>
<span><span class="co">#&gt;  [22] minqa_1.2.8         RColorBrewer_1.1-3  ADGofTest_0.3      </span></span>
<span><span class="co">#&gt;  [25] multcomp_1.4-26     abind_1.4-8         quadprog_1.5-8     </span></span>
<span><span class="co">#&gt;  [28] pspline_1.0-21      nnet_7.3-20         TH.data_1.1-2      </span></span>
<span><span class="co">#&gt;  [31] sandwich_3.1-1      moments_0.14.1      nortest_1.0-4      </span></span>
<span><span class="co">#&gt;  [34] arm_1.14-4          performance_0.13.0  codetools_0.2-20   </span></span>
<span><span class="co">#&gt;  [37] tidyselect_1.2.1    farver_2.1.2        lme4_1.1-36        </span></span>
<span><span class="co">#&gt;  [40] stats4_4.4.2        base64enc_0.1-3     jsonlite_1.8.9     </span></span>
<span><span class="co">#&gt;  [43] Formula_1.2-5       survival_3.8-3      emmeans_1.10.6     </span></span>
<span><span class="co">#&gt;  [46] tools_4.4.2         Rcpp_1.0.14         glue_1.8.0         </span></span>
<span><span class="co">#&gt;  [49] mnormt_2.1.1        xfun_0.50           withr_3.0.2        </span></span>
<span><span class="co">#&gt;  [52] numDeriv_2016.8-1.1 fastmap_1.2.0       boot_1.3-31        </span></span>
<span><span class="co">#&gt;  [55] digest_0.6.37       mi_1.1              timechange_0.3.0   </span></span>
<span><span class="co">#&gt;  [58] R6_2.5.1            mime_0.12           estimability_1.5.1 </span></span>
<span><span class="co">#&gt;  [61] colorspace_2.1-1    gtools_3.9.5        jpeg_0.1-10        </span></span>
<span><span class="co">#&gt;  [64] copula_1.1-4        DiagrammeR_1.0.11   generics_0.1.3     </span></span>
<span><span class="co">#&gt;  [67] data.table_1.16.4   corpcor_1.6.10      htmlwidgets_1.6.4  </span></span>
<span><span class="co">#&gt;  [70] parameters_0.24.1   pkgconfig_2.0.3     sem_3.1-16         </span></span>
<span><span class="co">#&gt;  [73] gtable_0.3.6        pcaPP_2.0-5         htmltools_0.5.8.1  </span></span>
<span><span class="co">#&gt;  [76] carData_3.0-5       png_0.1-8           reformulas_0.4.0   </span></span>
<span><span class="co">#&gt;  [79] rstudioapi_0.17.1   tzdb_0.4.0          reshape2_1.4.4     </span></span>
<span><span class="co">#&gt;  [82] coda_0.19-4.1       visNetwork_2.1.2    checkmate_2.3.2    </span></span>
<span><span class="co">#&gt;  [85] nlme_3.1-166        curl_6.1.0          nloptr_2.1.1       </span></span>
<span><span class="co">#&gt;  [88] zoo_1.8-12          parallel_4.4.2      miniUI_0.1.1.1     </span></span>
<span><span class="co">#&gt;  [91] foreign_0.8-88      pillar_1.10.1       grid_4.4.2         </span></span>
<span><span class="co">#&gt;  [94] vctrs_0.6.5         promises_1.3.2      car_3.1-3          </span></span>
<span><span class="co">#&gt;  [97] OpenMx_2.21.13      xtable_1.8-4        cluster_2.1.8      </span></span>
<span><span class="co">#&gt; [100] htmlTable_2.4.3     evaluate_1.0.3      pbivnorm_0.6.0     </span></span>
<span><span class="co">#&gt; [103] mvtnorm_1.3-3       cli_3.6.3           kutils_1.73        </span></span>
<span><span class="co">#&gt; [106] compiler_4.4.2      rlang_1.1.4         ggsignif_0.6.4     </span></span>
<span><span class="co">#&gt; [109] fdrtool_1.2.18      plyr_1.8.9          stringi_1.8.4      </span></span>
<span><span class="co">#&gt; [112] munsell_0.5.1       gsl_2.1-8           lisrelToR_0.3      </span></span>
<span><span class="co">#&gt; [115] bayestestR_0.15.0   pacman_0.5.1        V8_6.0.0           </span></span>
<span><span class="co">#&gt; [118] Matrix_1.7-1        hms_1.1.3           stabledist_0.7-2   </span></span>
<span><span class="co">#&gt; [121] glasso_1.11         shiny_1.10.0        rbibutils_2.3      </span></span>
<span><span class="co">#&gt; [124] igraph_2.1.2        broom_1.0.7         RcppParallel_5.1.9</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-brown2015confirmatory" class="csl-entry" role="listitem">
Brown, T. A. (2015). <em>Confirmatory factor analysis for applied research</em>. Guilford publications.
</div>
<div id="ref-kline2023principles" class="csl-entry" role="listitem">
Kline, R. B. (2023). <em>Principles and practice of structural equation modeling</em>. Guilford publications.
</div>
<div id="ref-petersen2024principles" class="csl-entry" role="listitem">
Petersen, I. T. (2024). <em>Principles of psychological assessment: With applied examples in R</em>. CRC Press.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiato!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiato!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ccaudek\.github\.io\/testing_psicologico\/intro\.html");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../chapters/sem/03_gof.html" class="pagination-link" aria-label="Test del Modello e Indicizzazione">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Test del Modello e Indicizzazione</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/sem/05_cfa_mod_comp.html" class="pagination-link" aria-label="CFA: confronto tra modelli">
        <span class="nav-page-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">CFA: confronto tra modelli</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Testing Psicologico</strong> è una dispensa scritta da Corrado Caudek.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


</body></html>