<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>57&nbsp; Dimensione Campionaria e Analisi della Potenza – Testing Psicologico</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/sem/E_01.html" rel="next">
<link href="../../chapters/sem/13_esem.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script>
<script type="application/json" class="js-hypothesis-config">
{
  "theme": "clean"
}
</script>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/sem/01_sem_intro.html">SEM</a></li><li class="breadcrumb-item"><a href="../../chapters/sem/14_sem_power.html"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Dimensione Campionaria e Analisi della Potenza</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Testing Psicologico</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ccaudek/testing_psicologico/" title="Eseguire il codice" class="quarto-navigation-tool px-1" aria-label="Eseguire il codice"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Attiva/disattiva la modalità oscura"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Ricerca"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Benvenuti</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../prefazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefazione</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Programmazione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../cal_testing_psic_2025.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Calendario delle lezioni</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Punteggi e scale</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/01_scores_scales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Punteggi e scale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E1_likert.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E2_optimal_scoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/E3_thurstone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/02_development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Sviluppo dello strumento</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/measurement/03_equating.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Equating nei Test Psicologici</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">CTT</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/01_ctt_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Fondamenti teorici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/02_ctt_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">L’affidabilità del test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/03_ctt_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Metodi di stima dell’affidabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/04_err_std_mis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">L’errore standard della misurazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/05_err_std_stima.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">La stima del punteggio vero</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ctt/06_ctt_applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Applicazioni della CTT</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Giudici</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/01_multilevel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Modelli multilivello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/02_interrater_reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">L’affidabilità tra giudici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/raters/E1_irr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Validità</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/validity/01_validity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">La validità del test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/validity/02_other_variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Relazioni test-criterio</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Generalizzabilità</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/gtheory/01_gtheory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Teoria della generalizzabilità</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Items</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/items/01_item_development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Lo sviluppo degli item</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/items/02_item_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Analisi degli item</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Analisi dei percorsi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/path_analysis/01_path_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Analisi dei percorsi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/path_analysis/02_clement_2022.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Riparazione affettiva post-infedeltà</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">FA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/01_intro_fa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Introduzione all’analisi fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/02_analisi_fattoriale_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Il modello unifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/03_analisi_fattoriale_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Il modello statistico dell’analisi fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/04_analisi_fattoriale_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Il modello multifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/05_factor_scores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">I punteggi fattoriali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/06_constraints_on_parms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Attendibilità e modello fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/fa/07_total_score.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Punteggio totale e modello fattoriale</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">Costruzione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/01_val_matrici.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Valutazione della matrice di correlazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/02_estrazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">L’estrazione dei fattori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/03_numero_fattori.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Il numero dei fattori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/04_rotazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">La rotazione fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/extraction/05_val_soluzione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Valutare e rifinire la soluzione fattoriale</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">CFA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/01_cfa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Analisti Fattoriale Confermativa</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/02_meanstructure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">La struttura delle medie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/03_cat_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Dati non gaussiani e categoriali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/04_mmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">CFA per matrici multi-tratto multi-metodo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/05_bifactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Modello bifattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/06_efa_lavaan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Exploratory Structural Equation Modeling (ESEM)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/07_fa_in_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Strategia Integrata per un’Analisi Fattoriale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/cfa/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true">
 <span class="menu-text">SEM</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/01_sem_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Introduzione ai Modelli SEM</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/02_data_preparation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Preparazione dei Dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/03_gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Test del Modello e Indicizzazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/04_mod_comp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Confronto tra modelli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/05_cfa_mod_comp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">CFA: confronto tra modelli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/06_refine_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">La revisione del modello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/07_group_invariance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Invarianza di misura</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/08_multilevel_sem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Modelli di Equazioni Strutturali Multilivello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/09_structural_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Modelli di Regressione Strutturale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/10_missing_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Dati mancanti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/11_small_samples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Modellizzazione SEM in Piccoli Campioni</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/12_temp_reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Affidabilità longitudinale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/13_esem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Exploratory structural equation modelling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/14_sem_power.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Dimensione Campionaria e Analisi della Potenza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/sem/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Mokken</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/01_core_issues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Analisi della Scala di Mokken</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mokken/02_applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Applicazione Pratica</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false">
 <span class="menu-text">IRT</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/01_logistic_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">Modello di Regressione Logistica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/E_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/02_rasch_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Modello di Rasch</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/03_assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">Assunzioni e Proprietà del Modello di Rasch</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/04_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Stima</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/05_1pl_2pl_3pl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Modelli 1PL, 2PL e 3PL</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/irt/06_implementation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">Implementazione</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false">
 <span class="menu-text">LGM</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/01_lgm_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">68</span>&nbsp; <span class="chapter-title">Curve di crescita latente</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/02_lgm_prelims.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title">Considerazioni Preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/06_lgm_mixed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">LGM e modelli misti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/03_time_effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Dati longitudinali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/05_intro_panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">72</span>&nbsp; <span class="chapter-title">Specificare e Interpretare un Modello Longitudinale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/07_growth_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">73</span>&nbsp; <span class="chapter-title">Curve di crescita latente</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/08_growth_cont.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">74</span>&nbsp; <span class="chapter-title">Il tempo su una metrica continua</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/09_time_inv_cov.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">75</span>&nbsp; <span class="chapter-title">Covariate indipendenti dal tempo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/10_growth_groups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">76</span>&nbsp; <span class="chapter-title">Modelli di crescita latenti a gruppi multipli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/lgm/11_lgm_wais.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">77</span>&nbsp; <span class="chapter-title">Lo Sviluppo dell’Intelligenza</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false">
 <span class="menu-text">Predizione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/prediction/01_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">78</span>&nbsp; <span class="chapter-title">Predizione</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false">
 <span class="menu-text">Networks</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/networks/01_networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">79</span>&nbsp; <span class="chapter-title">Network psicologici</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../99-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliografia</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendici</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a1_intro_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linguaggio R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a2_sums.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Simbolo di somma</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a3_calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Per liberarvi dai terrori preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a4_linear_alg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Elementi di algebra lineare</span></span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false">
 <span class="menu-text">Soluzioni degli esercizi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/solutions_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Probabilità</span></span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Indice</h2>
   
  <ul>
  <li><a href="#introduzione" id="toc-introduzione" class="nav-link active" data-scroll-target="#introduzione"><span class="header-section-number">57.1</span> Introduzione</a></li>
  <li><a href="#obiettivi-principali-dei-modelli-sem" id="toc-obiettivi-principali-dei-modelli-sem" class="nav-link" data-scroll-target="#obiettivi-principali-dei-modelli-sem"><span class="header-section-number">57.2</span> Obiettivi Principali dei Modelli SEM</a></li>
  <li><a href="#dimensione-campionaria-per-confronti-tra-gruppi" id="toc-dimensione-campionaria-per-confronti-tra-gruppi" class="nav-link" data-scroll-target="#dimensione-campionaria-per-confronti-tra-gruppi"><span class="header-section-number">57.3</span> Dimensione Campionaria per Confronti tra Gruppi</a>
  <ul>
  <li><a href="#formula-per-la-dimensione-campionaria-per-gruppo" id="toc-formula-per-la-dimensione-campionaria-per-gruppo" class="nav-link" data-scroll-target="#formula-per-la-dimensione-campionaria-per-gruppo"><span class="header-section-number">57.3.1</span> Formula per la Dimensione Campionaria per Gruppo</a></li>
  <li><a href="#derivazione" id="toc-derivazione" class="nav-link" data-scroll-target="#derivazione"><span class="header-section-number">57.3.2</span> Derivazione</a></li>
  </ul></li>
  <li><a href="#esempio-pratico" id="toc-esempio-pratico" class="nav-link" data-scroll-target="#esempio-pratico"><span class="header-section-number">57.4</span> Esempio Pratico</a></li>
  <li><a href="#collegamento-con-la-modellazione-a-equazioni-strutturali" id="toc-collegamento-con-la-modellazione-a-equazioni-strutturali" class="nav-link" data-scroll-target="#collegamento-con-la-modellazione-a-equazioni-strutturali"><span class="header-section-number">57.5</span> Collegamento con la Modellazione a Equazioni Strutturali</a>
  <ul>
  <li><a href="#applicazione-del-metodo-mcsb" id="toc-applicazione-del-metodo-mcsb" class="nav-link" data-scroll-target="#applicazione-del-metodo-mcsb"><span class="header-section-number">57.5.1</span> Applicazione del Metodo MCSB</a></li>
  <li><a href="#riformulazione-del-confronto-tra-trattamenti-come-modello-di-regressione" id="toc-riformulazione-del-confronto-tra-trattamenti-come-modello-di-regressione" class="nav-link" data-scroll-target="#riformulazione-del-confronto-tra-trattamenti-come-modello-di-regressione"><span class="header-section-number">57.5.2</span> Riformulazione del Confronto tra Trattamenti come Modello di Regressione</a></li>
  <li><a href="#implementazione-in-r-dellapproccio-mcsb-con-simsem" id="toc-implementazione-in-r-dellapproccio-mcsb-con-simsem" class="nav-link" data-scroll-target="#implementazione-in-r-dellapproccio-mcsb-con-simsem"><span class="header-section-number">57.5.3</span> Implementazione in R dell’Approccio MCSB con <code>simsem</code></a></li>
  </ul></li>
  <li><a href="#analisi-di-potenza-nei-modelli-sem" id="toc-analisi-di-potenza-nei-modelli-sem" class="nav-link" data-scroll-target="#analisi-di-potenza-nei-modelli-sem"><span class="header-section-number">57.6</span> Analisi di Potenza nei Modelli SEM</a>
  <ul>
  <li><a href="#modello-di-crescita-latente-lgc" id="toc-modello-di-crescita-latente-lgc" class="nav-link" data-scroll-target="#modello-di-crescita-latente-lgc"><span class="header-section-number">57.6.1</span> Modello di Crescita Latente (LGC)</a></li>
  <li><a href="#calcolo-della-dimensione-campionaria" id="toc-calcolo-della-dimensione-campionaria" class="nav-link" data-scroll-target="#calcolo-della-dimensione-campionaria"><span class="header-section-number">57.6.2</span> Calcolo della Dimensione Campionaria</a></li>
  </ul></li>
  <li><a href="#riflessioni-conclusive" id="toc-riflessioni-conclusive" class="nav-link" data-scroll-target="#riflessioni-conclusive"><span class="header-section-number">57.7</span> Riflessioni Conclusive</a></li>
  <li><a href="#informazioni-sullambiente-di-sviluppo" id="toc-informazioni-sullambiente-di-sviluppo" class="nav-link" data-scroll-target="#informazioni-sullambiente-di-sviluppo">Informazioni sull’Ambiente di Sviluppo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/sem/01_sem_intro.html">SEM</a></li><li class="breadcrumb-item"><a href="../../chapters/sem/14_sem_power.html"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Dimensione Campionaria e Analisi della Potenza</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-n-power-sem" class="quarto-section-identifier"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Dimensione Campionaria e Analisi della Potenza</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="chapterintro">
<p>Nel contesto dei modelli di equazioni strutturali (SEM), è essenziale assicurarsi che uno studio abbia una dimensione campionaria sufficiente per ottenere stime attendibili degli effetti di interesse. La capacità di un modello di rilevare effetti dipende dal numero di osservazioni, dall’intensità dell’effetto da osservare e dalla precisione delle misurazioni. Stabilire a priori la dimensione campionaria necessaria permette di progettare studi solidi e informativi. Nei SEM, la complessità del modello richiede considerazioni specifiche per ottenere una buona qualità delle stime, sia per l’individuazione di effetti mirati che per il confronto tra modelli alternativi.</p>
</div>
<p><strong>Prerequisiti</strong></p>
<ul>
<li>Leggere l’articolo <em>Estimating statistical power for structural equation models in developmental cognitive science: A tutorial in R</em> di <span class="citation" data-cites="buchberger2024estimating">Buchberger et al. (<a href="../../99-references.html#ref-buchberger2024estimating" role="doc-biblioref">2024</a>)</span>.</li>
<li>Leggere il capitolo 12 <em>Sample Size Determination and Power Analysis</em> del testo <em>Structural Equation Modeling Using R/SAS: A Step-by-step Approach with Real Data Analysis</em> <span class="citation" data-cites="chen2023structural">(<a href="../../99-references.html#ref-chen2023structural" role="doc-biblioref">Chen &amp; Yung, 2023</a>)</span>.</li>
</ul>
<p><strong>Concetti e Competenze Chiave</strong></p>
<ul>
<li>Determinazione della numerosità campionaria con metodi analitici nel caso della differenza tra due medie.</li>
<li>Analisi di potenza nei modelli SEM.</li>
<li>Utilizzo dei pacchetti <code>simsem</code> e <code>compute.es</code>.</li>
</ul>
<p><strong>Preparazione del Notebook</strong></p>
<div id="cell-3" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"code"</span>, <span class="st">"_common.R"</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">source</span>()</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">"pacman"</span>)) <span class="fu">install.packages</span>(<span class="st">"pacman"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    semTools, tidyr, psych, lavaan, kableExtra, stringr, simsem, compute.es</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="introduzione" class="level2" data-number="57.1">
<h2 data-number="57.1" class="anchored" data-anchor-id="introduzione"><span class="header-section-number">57.1</span> Introduzione</h2>
<p><span class="citation" data-cites="buchberger2024estimating">Buchberger et al. (<a href="../../99-references.html#ref-buchberger2024estimating" role="doc-biblioref">2024</a>)</span> osservano che, nell’ultimo decennio, la questione della bassa potenza statistica e delle sue conseguenze sull’interpretazione dei risultati scientifici ha attirato un’attenzione crescente nella ricerca psicologica. La <strong>potenza statistica</strong> rappresenta la capacità di rilevare effetti reali, ovvero la probabilità di individuare correttamente un effetto quando è effettivamente presente. Questo valore dipende strettamente dalla dimensione campionaria, dall’entità dell’effetto che si intende rilevare e dall’affidabilità delle misurazioni.</p>
<p>La bassa potenza rappresenta un problema in quanto può limitare l’utilità scientifica dei risultati; inoltre, anche se si rilevano effetti significativi, questi potrebbero non riflettere associazioni reali. Per garantire che gli studi empirici siano adeguatamente progettati per rilevare gli effetti nei campioni esaminati, è cruciale calcolare in anticipo la potenza e stabilire la dimensione campionaria necessaria, evitando studi sotto-dimensionati.</p>
<p>In genere, in psicologia, si considera adeguata una potenza intorno a 0.80, anche se alcuni autori suggeriscono di puntare a valori più elevati, come 0.95, per bilanciare meglio gli errori di tipo I e tipo II.</p>
<p>Diversi autori hanno proposto regole pratiche per stabilire la dimensione campionaria nei modelli SEM, come un numero minimo di osservazioni o un rapporto tra osservazioni e parametri da stimare. Tuttavia, queste regole empiriche possono essere fuorvianti, poiché la potenza nei SEM dipende anche da fattori quali l’entità dei carichi fattoriali e la complessità del modello. Inoltre, la dimensione campionaria necessaria dipende dalla specifica domanda di ricerca.</p>
</section>
<section id="obiettivi-principali-dei-modelli-sem" class="level2" data-number="57.2">
<h2 data-number="57.2" class="anchored" data-anchor-id="obiettivi-principali-dei-modelli-sem"><span class="header-section-number">57.2</span> Obiettivi Principali dei Modelli SEM</h2>
<p><span class="citation" data-cites="buchberger2024estimating">Buchberger et al. (<a href="../../99-references.html#ref-buchberger2024estimating" role="doc-biblioref">2024</a>)</span> fanno notare che i due obiettivi principali dei SEM sono:</p>
<ol type="1">
<li><strong>Rilevare un effetto specifico</strong>, come determinare se la correlazione tra due fattori latenti è diversa da zero.</li>
<li><strong>Confrontare modelli</strong>, verificando quale tra due o più modelli spiega meglio i dati.</li>
</ol>
<p>Questi due obiettivi richiedono approcci diversi: il primo riguarda la potenza per rilevare un effetto mirato, mentre il secondo si concentra sulla potenza per individuare errori di specificazione del modello. Nei confronti tra modelli non nidificati (non derivabili l’uno dall’altro tramite restrizioni parametriche), i test basati sul <span class="math inline">\(\chi^2\)</span> non sono utilizzabili; è quindi necessario ricorrere a metodi alternativi, come le simulazioni Monte Carlo.</p>
<p>Molti studi SEM mirano a determinare se un parametro specifico differisca da un valore atteso. In tal caso, si confronta un modello in cui il parametro è stimato liberamente con uno in cui è fissato a un valore specifico. Se il confronto tra i modelli suggerisce una differenza significativa, si può concludere che il parametro differisce effettivamente dal valore atteso.</p>
<p>Per molti ricercatori, è rilevante individuare quale tra modelli teorici concorrenti descriva meglio i dati. Quando i modelli sono nidificati, è possibile usare metodi analitici basati sul <span class="math inline">\(\chi^2\)</span>, mentre per modelli non nidificati si ricorre a tecniche di randomizzazione, come le simulazioni Monte Carlo. Questo approccio consente di stimare la potenza per confrontare modelli non nidificati senza compromettere le assunzioni teoriche del modello.</p>
<p>In conclusione, la determinazione della dimensione campionaria e l’analisi di potenza per i SEM richiedono una valutazione accurata della specificità della domanda di ricerca e delle ipotesi del modello, utilizzando approcci sia analitici che di simulazione per ottenere stime affidabili.</p>
</section>
<section id="dimensione-campionaria-per-confronti-tra-gruppi" class="level2" data-number="57.3">
<h2 data-number="57.3" class="anchored" data-anchor-id="dimensione-campionaria-per-confronti-tra-gruppi"><span class="header-section-number">57.3</span> Dimensione Campionaria per Confronti tra Gruppi</h2>
<p>Per introdurre il metodo della simulazione Monte Carlo applicato all’analisi di potenza nei modelli SEM, seguiremo il tutorial di <span class="citation" data-cites="chen2023structural">Chen &amp; Yung (<a href="../../99-references.html#ref-chen2023structural" role="doc-biblioref">2023</a>)</span>. Prima di esplorare l’uso della simulazione Monte Carlo per stimare la potenza in contesti SEM, è utile applicare questo metodo a un caso più semplice: il calcolo della dimensione campionaria necessaria per rilevare una differenza clinicamente rilevante tra due gruppi. Questo esempio introduttivo aiuterà a chiarire il funzionamento della simulazione Monte Carlo. Successivamente, applicheremo lo stesso approccio alla determinazione della potenza per i modelli SEM, un caso più complesso che richiede tecniche avanzate di simulazione per stimare accuratamente la potenza.</p>
<section id="formula-per-la-dimensione-campionaria-per-gruppo" class="level3" data-number="57.3.1">
<h3 data-number="57.3.1" class="anchored" data-anchor-id="formula-per-la-dimensione-campionaria-per-gruppo"><span class="header-section-number">57.3.1</span> Formula per la Dimensione Campionaria per Gruppo</h3>
<p>La formula per determinare la dimensione campionaria per ciascun gruppo, per rilevare una differenza clinicamente significativa tra due gruppi, è:</p>
<p><span id="eq-sample-size-power"><span class="math display">\[
n \geq 2 \left(\frac{s^2}{\delta^2}\right) \left[z_{1 - \alpha/2} + z_{1 - \beta}\right]^2,
\tag{57.1}\]</span></span></p>
<p>dove:</p>
<ul>
<li><span class="math inline">\(s\)</span> è la stima della deviazione standard (assumendo varianze omogenee tra i gruppi);</li>
<li><span class="math inline">\(\delta\)</span> è la differenza clinicamente rilevante tra i gruppi, cioè l’effetto minimo che si desidera rilevare;</li>
<li><span class="math inline">\(z_{1 - \alpha/2}\)</span> e <span class="math inline">\(z_{1 - \beta}\)</span> sono i valori critici della distribuzione normale standard per i limiti degli errori di tipo I e tipo II.</li>
</ul>
</section>
<section id="derivazione" class="level3" data-number="57.3.2">
<h3 data-number="57.3.2" class="anchored" data-anchor-id="derivazione"><span class="header-section-number">57.3.2</span> Derivazione</h3>
<p>Per calcolare la dimensione campionaria necessaria a confrontare le medie di due gruppi indipendenti, seguiamo i passaggi teorici necessari per derivare la formula finale. Il nostro interesse è quantificare la differenza tra le medie dei due gruppi, indicata come <span class="math inline">\(\mu_1 - \mu_2\)</span>. Supponiamo che le due medie siano stimate da campioni con deviazione standard comune <span class="math inline">\(\sigma\)</span>.</p>
<p>Poiché ciascuna media di campione (<span class="math inline">\(\bar{X}_1\)</span> per il gruppo 1 e <span class="math inline">\(\bar{X}_2\)</span> per il gruppo 2) ha varianza <span class="math inline">\(\frac{\sigma^2}{n}\)</span> e i campioni sono indipendenti, la varianza della differenza <span class="math inline">\(\bar{X}_1 - \bar{X}_2\)</span> è data dalla somma delle varianze:</p>
<p><span class="math display">\[
\text{Var}(\bar{X}_1 - \bar{X}_2) = \frac{\sigma^2}{n} + \frac{\sigma^2}{n} = \frac{2\sigma^2}{n}.
\]</span></p>
<p>Da qui, la deviazione standard della differenza tra le medie è quindi:</p>
<p><span class="math display">\[
\text{Deviazione standard} = \sqrt{\frac{2\sigma^2}{n}}.
\]</span></p>
<p>Per il teorema del limite centrale, questa differenza tra le medie segue una distribuzione normale, dato che <span class="math inline">\(n\)</span> è sufficientemente grande.</p>
<p>Per determinare la potenza del test e la dimensione campionaria necessaria, definiamo:</p>
<ul>
<li><strong>Ipotesi nulla <span class="math inline">\(H_0\)</span></strong>: <span class="math inline">\(\mu_1 - \mu_2 = 0\)</span> (assenza di differenza significativa).</li>
<li><strong>Ipotesi alternativa <span class="math inline">\(H_1\)</span></strong>: <span class="math inline">\(\mu_1 - \mu_2 = \delta\)</span>, dove <span class="math inline">\(\delta\)</span> rappresenta una differenza significativa che vogliamo rilevare.</li>
<li><strong>Livello di significatività</strong> <span class="math inline">\(\alpha\)</span>: probabilità di rifiutare <span class="math inline">\(H_0\)</span> quando è vera (errore di Tipo I).</li>
<li><strong>Potenza desiderata</strong> <span class="math inline">\(1-\beta\)</span>: probabilità di rilevare una vera differenza <span class="math inline">\(\delta\)</span> (cioè non commettere un errore di Tipo II).</li>
</ul>
<p>Sotto l’ipotesi nulla, la differenza tra le medie campionarie, <span class="math inline">\(\bar{X}_1 - \bar{X}_2\)</span>, ha media zero e deviazione standard <span class="math inline">\(\sqrt{\frac{2\sigma^2}{n}}\)</span>. Possiamo quindi utilizzare la statistica <span class="math inline">\(Z\)</span> per standardizzare questa differenza:</p>
<p><span class="math display">\[
Z = \frac{(\bar{X}_1 - \bar{X}_2) - 0}{\sqrt{\frac{2\sigma^2}{n}}}.
\]</span></p>
<p>In un test a due code con livello di significatività <span class="math inline">\(\alpha\)</span>, rifiutiamo <span class="math inline">\(H_0\)</span> se il valore assoluto di <span class="math inline">\(Z\)</span> supera <span class="math inline">\(z_{1-\alpha/2}\)</span>, ovvero se:</p>
<p><span class="math display">\[
|\bar{X}_1 - \bar{X}_2| &gt; z_{1-\alpha/2} \cdot \sqrt{\frac{2\sigma^2}{n}}.
\]</span></p>
<p>Questo ci dice che il valore critico per rifiutare <span class="math inline">\(H_0\)</span> è pari a <span class="math inline">\(z_{1-\alpha/2} \cdot \sqrt{\frac{2\sigma^2}{n}}\)</span>. Tuttavia, poiché vogliamo assicurare una potenza del test pari a <span class="math inline">\(1-\beta\)</span>, la differenza <span class="math inline">\(\delta\)</span> deve superare questo valore critico con probabilità <span class="math inline">\(1 - \beta\)</span>.</p>
<p>Sotto l’ipotesi alternativa <span class="math inline">\(H_1\)</span>, la differenza attesa tra le medie campionarie è <span class="math inline">\(\delta\)</span>, e quindi standardizziamo rispetto alla deviazione standard della differenza:</p>
<p><span class="math display">\[
Z = \frac{\delta}{\sqrt{\frac{2\sigma^2}{n}}}.
\]</span></p>
<p>Imponiamo ora che la somma dei valori critici <span class="math inline">\(z_{1-\alpha/2}\)</span> e <span class="math inline">\(z_{1-\beta}\)</span> sia uguale a questa statistica test, ottenendo:</p>
<p><span class="math display">\[
\delta = \sqrt{\frac{2\sigma^2}{n}} (z_{1-\alpha/2} + z_{1-\beta}).
\]</span></p>
<p>Risolviamo questa equazione per <span class="math inline">\(n\)</span> al fine di ottenere la dimensione campionaria necessaria:</p>
<p><span class="math display">\[
n \geq \frac{2\sigma^2}{\delta^2} (z_{1-\alpha/2} + z_{1-\beta})^2.
\]</span></p>
<p>Nella pratica, non sempre conosciamo <span class="math inline">\(\sigma^2\)</span>; pertanto, lo sostituiamo con la stima <span class="math inline">\(s^2\)</span>, ottenendo:</p>
<p><span class="math display">\[
n \geq 2 \left(\frac{s^2}{\delta^2}\right) [z_{1-\alpha/2} + z_{1-\beta}]^2.
\]</span></p>
<p>Questa formula fornisce un modo pratico per calcolare la dimensione campionaria minima necessaria per garantire che il test abbia la potenza desiderata, tenendo conto della variabilità dei dati (<span class="math inline">\(s^2\)</span>), dell’errore di Tipo I (<span class="math inline">\(\alpha\)</span>), dell’errore di Tipo II (<span class="math inline">\(\beta\)</span>), e della differenza minima rilevante <span class="math inline">\(\delta\)</span>.</p>
<p>In conclusione, questa derivazione della dimensione campionaria è utile poiché:</p>
<ul>
<li>Consente di specificare il livello di controllo sugli errori di Tipo I e Tipo II.</li>
<li>Tiene conto della variabilità campionaria attraverso la stima <span class="math inline">\(s^2\)</span>.</li>
<li>Permette di impostare una differenza minima rilevante da rilevare tra i gruppi.</li>
<li>Fornisce una stima della dimensione campionaria necessaria per garantire la potenza statistica richiesta.</li>
</ul>
</section>
</section>
<section id="esempio-pratico" class="level2" data-number="57.4">
<h2 data-number="57.4" class="anchored" data-anchor-id="esempio-pratico"><span class="header-section-number">57.4</span> Esempio Pratico</h2>
<p>Consideriamo i dati seguenti, ponendo <span class="math inline">\(\alpha\)</span> = 0.05 e la potenza <span class="math inline">\(1-\beta\)</span> = 0.80:</p>
<div id="cell-5" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mu2 <span class="ot">&lt;-</span> <span class="fl">1.2</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>mu1 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>sd <span class="ot">&lt;-</span> <span class="fl">0.5</span> <span class="co"># SD of each group</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="fl">0.2</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Calcoliamo la dimensione minima campionaria per ciascun gruppo:</p>
<div id="cell-7" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean difference</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>delta <span class="ot">&lt;-</span> mu2 <span class="sc">-</span> mu1</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Required sample size</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> sd<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> delta<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> (<span class="fu">qnorm</span>(<span class="dv">1</span> <span class="sc">-</span> alpha <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="dv">1</span> <span class="sc">-</span> beta))<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>n</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
98.1109966793636
</div>
</div>
</section>
<section id="collegamento-con-la-modellazione-a-equazioni-strutturali" class="level2" data-number="57.5">
<h2 data-number="57.5" class="anchored" data-anchor-id="collegamento-con-la-modellazione-a-equazioni-strutturali"><span class="header-section-number">57.5</span> Collegamento con la Modellazione a Equazioni Strutturali</h2>
<p>Il confronto tra due gruppi è un caso relativamente semplice rispetto alla complessità dei modelli a equazioni strutturali (SEM), i quali spesso richiedono approcci avanzati per il calcolo della potenza, come il <strong>Monte Carlo Simulation-Based Approach</strong> (MCSB). Per comprendere meglio questo metodo, è utile applicare inizialmente il MCSB a un caso base come il confronto tra le medie di due gruppi. Successivamente, estenderemo questo approccio per includere i SEM, dove la complessità delle relazioni e dei parametri richiede strumenti di simulazione più sofisticati.</p>
<section id="applicazione-del-metodo-mcsb" class="level3" data-number="57.5.1">
<h3 data-number="57.5.1" class="anchored" data-anchor-id="applicazione-del-metodo-mcsb"><span class="header-section-number">57.5.1</span> Applicazione del Metodo MCSB</h3>
<p>Per implementare il metodo MCSB, dobbiamo definire due componenti principali:</p>
<ul>
<li><strong>Il modello generativo dei dati</strong>, che descrive i parametri noti e serve per simulare i dati, come le differenze attese tra i gruppi e la variabilità delle misure.</li>
<li><strong>Il modello di stima dei parametri</strong>, che specifica come i parametri saranno stimati dai dati simulati, utilizzando un software di modellazione SEM come <code>lavaan</code> o <code>simsem</code>.</li>
</ul>
</section>
<section id="riformulazione-del-confronto-tra-trattamenti-come-modello-di-regressione" class="level3" data-number="57.5.2">
<h3 data-number="57.5.2" class="anchored" data-anchor-id="riformulazione-del-confronto-tra-trattamenti-come-modello-di-regressione"><span class="header-section-number">57.5.2</span> Riformulazione del Confronto tra Trattamenti come Modello di Regressione</h3>
<p>Possiamo rappresentare il confronto tra gruppi anche come modello di regressione lineare:</p>
<p><span class="math display">\[
y = \beta_0 + \beta_1 \cdot TRT + \epsilon,
\]</span></p>
<p>dove:</p>
<ul>
<li><span class="math inline">\(y\)</span> è la variabile di esito,</li>
<li><span class="math inline">\(TRT\)</span> è una variabile indicatrice che differenzia i gruppi (1 per il gruppo trattato, 0 per il gruppo di controllo),</li>
<li><span class="math inline">\(\beta_0\)</span> rappresenta la media del gruppo di controllo,</li>
<li><span class="math inline">\(\beta_1\)</span> rappresenta la differenza media tra i gruppi,</li>
<li><span class="math inline">\(\epsilon\)</span> è il termine di errore, distribuito normalmente con media zero.</li>
</ul>
</section>
<section id="implementazione-in-r-dellapproccio-mcsb-con-simsem" class="level3" data-number="57.5.3">
<h3 data-number="57.5.3" class="anchored" data-anchor-id="implementazione-in-r-dellapproccio-mcsb-con-simsem"><span class="header-section-number">57.5.3</span> Implementazione in R dell’Approccio MCSB con <code>simsem</code></h3>
<p>Per calcolare la potenza e stimare correttamente i parametri, è necessario determinare la dimensione dell’effetto e la varianza residua dell’esito <span class="math inline">\(y\)</span> in questa equazione. Di seguito, i passaggi per implementare il metodo MCSB:</p>
<ol type="1">
<li><p><strong>Calcolo del <span class="math inline">\(d\)</span> di Cohen</strong>:<br>
Supponiamo di avere una differenza clinicamente rilevante <span class="math inline">\(\delta = 0.2\)</span> e una deviazione standard <span class="math inline">\(sd = 0.5\)</span>. La dimensione dell’effetto standardizzata, o <span class="math inline">\(d\)</span> di Cohen, è calcolata come:</p>
<p><span class="math display">\[
d = \frac{\delta}{sd} = \frac{0.2}{0.5} = 0.4.
\]</span></p></li>
<li><p><strong>Conversione di <span class="math inline">\(d\)</span> in Coefficiente di Correlazione <span class="math inline">\(r\)</span></strong>:<br>
Spesso è utile esprimere la dimensione dell’effetto in termini di coefficiente di correlazione <span class="math inline">\(r\)</span>, che riflette la forza dell’associazione tra trattamento e esito. Il pacchetto <code>compute.es</code> in R include la funzione <code>des()</code> per convertire <span class="math inline">\(d\)</span> in un valore di correlazione equivalente <span class="math inline">\(r\)</span>.</p>
<p>Usando <code>des(d, n.1 = n, n.2 = n)</code>, otteniamo un valore approssimativo di <span class="math inline">\(r \approx 0.2\)</span>.</p></li>
<li><p><strong>Calcolo della Varianza di <span class="math inline">\(y\)</span></strong>:<br>
In questo contesto, il coefficiente <span class="math inline">\(r = 0.2\)</span> rappresenta l’associazione tra il trattamento (TRT) e l’esito <span class="math inline">\(y\)</span>. La varianza totale di <span class="math inline">\(y\)</span> può essere separata in una parte spiegata (dall’effetto di <span class="math inline">\(TRT\)</span>) e una parte non spiegata. La varianza residua di <span class="math inline">\(y\)</span>, dopo aver tenuto conto del predittore, è data da <span class="math inline">\(1 - r^2\)</span>, poiché <span class="math inline">\(r^2\)</span> rappresenta la proporzione della varianza di <span class="math inline">\(y\)</span> spiegata dal trattamento:</p>
<p><span class="math display">\[
\text{var}(y) = 1 - r^2.
\]</span></p>
<p>Sostituendo <span class="math inline">\(r = 0.2\)</span>:</p>
<p><span class="math display">\[
\text{var}(y) = 1 - (0.2)^2 = 1 - 0.04 = 0.96.
\]</span></p></li>
</ol>
<p>Questi passaggi possono essere implementati in R utilizzando il pacchetto <code>compute.es</code>, facilitando il calcolo e la configurazione della simulazione per l’analisi di potenza con <code>simsem</code>.</p>
<div id="cell-9" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcolo dell'ES in termini di d</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> delta <span class="sc">/</span> sd</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># print(d) # E.g., [1] 0.4</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Conversione in altre misure di ES</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>d2ES <span class="ot">&lt;-</span> <span class="fu">des</span>(d, <span class="at">n.1 =</span> n, <span class="at">n.2 =</span> n, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Estrazione di r</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> d2ES<span class="sc">$</span>r</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(r) <span class="co"># E.g., [1] 0.2</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcolo della varianza di y</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>var.y <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> r<span class="sc">**</span><span class="dv">2</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(var.y) <span class="co"># E.g., [1] 0.96</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2
[1] 0.96</code></pre>
</div>
</div>
<p>Per utilizzare <code>simsem</code>, è necessario specificare il processo di generazione dei dati. Per il caso presente abbiamo:</p>
<div id="cell-11" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modello di generazione dei dati</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>datMod <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="st">    # Regressione con correlazione nota di 0.2</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="st">    y ~ 0.2*TRT</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="st">    # Varianza dell'errore</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="st">    y ~~ 0.96*y</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Il valore <span class="math inline">\(0.2\)</span> in <code>y ~ 0.2*TRT</code> rappresenta tecnicamente un <strong>coefficiente di regressione</strong>. Tuttavia, se le variabili sono standardizzate, questo valore coincide con la <strong>correlazione</strong> tra la variabile predittore <span class="math inline">\(TRT\)</span> e la variabile di risposta <span class="math inline">\(y\)</span>.</p>
<p>In questo contesto, considerare il coefficiente di correlazione è utile poiché ci permette di calcolare facilmente la varianza residua di <span class="math inline">\(y\)</span>. Conoscendo <span class="math inline">\(r\)</span>, infatti, possiamo stabilire la varianza residua come <span class="math inline">\(1 - r^2\)</span>, semplificando la specifica del modello.</p>
<p>Il modello di stima è il seguente:</p>
<div id="cell-13" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="6">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modello di stima</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>estMod <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="st">    # Regressione</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="st">    y ~ TRT</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Possiamo ora eseguire la simulazione MCSB:</p>
<div id="cell-15" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="8">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>simOut <span class="ot">&lt;-</span> <span class="fu">sim</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">nRep =</span> <span class="dv">1000</span>, </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">generate =</span> datMod, </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">model =</span> estMod, </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="dv">198</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">lavaanfun =</span> <span class="st">"sem"</span>, </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">seed =</span> <span class="dv">123</span>, </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">silent =</span> <span class="cn">TRUE</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nella simulazione eseguita con <code>simOut</code>, il parametro <code>nRep</code> indica il numero di repliche, che è stato impostato a 1000 per ridurre i tempi di esecuzione. Idealmente, sarebbe preferibile un numero più elevato (ad esempio &gt;10.000) per ottenere risultati più precisi. Il parametro <code>generate</code> specifica il modello di generazione dei dati (qui <code>datMod</code>), mentre <code>model</code> collega al modello di stima (qui <code>estMod</code>) utilizzando la funzione <code>lavaanfun = "sem"</code>. La dimensione del campione, <code>n</code>, è impostata a 198 per il calcolo della potenza statistica, e <code>seed</code> consente di riprodurre la simulazione con gli stessi risultati. L’opzione <code>silent = TRUE</code> sopprime l’output intermedio per semplificare la visualizzazione.</p>
<p>Esaminiamo l’output della simulazione.</p>
<div id="cell-17" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="9">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summaryParam</span>(simOut)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>A data.frame: 2 x 10</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">Estimate Average</th>
<th data-quarto-table-cell-role="th" scope="col">Estimate SD</th>
<th data-quarto-table-cell-role="th" scope="col">Average SE</th>
<th data-quarto-table-cell-role="th" scope="col">Power (Not equal 0)</th>
<th data-quarto-table-cell-role="th" scope="col">Std Est</th>
<th data-quarto-table-cell-role="th" scope="col">Std Est SD</th>
<th data-quarto-table-cell-role="th" scope="col">Std Ave SE</th>
<th data-quarto-table-cell-role="th" scope="col">Average Param</th>
<th data-quarto-table-cell-role="th" scope="col">Average Bias</th>
<th data-quarto-table-cell-role="th" scope="col">Coverage</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">y~TRT</td>
<td>0.202</td>
<td>0.0693</td>
<td>0.0698</td>
<td>0.816</td>
<td>0.201</td>
<td>0.0675</td>
<td>0.0671</td>
<td>0.20</td>
<td>0.00219</td>
<td>0.953</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">y~~y</td>
<td>0.956</td>
<td>0.0969</td>
<td>0.0960</td>
<td>1.000</td>
<td>0.955</td>
<td>0.0271</td>
<td>0.0267</td>
<td>0.96</td>
<td>-0.00433</td>
<td>0.942</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>L’output mostra diverse colonne relative ai parametri stimati con due righe: la prima riga è per lo stimatore della correlazione tra <span class="math inline">\(y\)</span> e <code>TRT</code> (cioè il coefficiente di regressione), mentre la seconda riga si riferisce alla varianza residua di <span class="math inline">\(y\)</span> in <code>y ~~ y</code>.</p>
<ol type="1">
<li><p><strong>Estimate Average</strong>: È la media delle stime dei parametri nelle 1000 repliche. I valori ottenuti (0.202 per <code>y ~ TRT</code> e 0.956 per <code>y ~~ y</code>) sono molto vicini ai valori simulati, cioè <span class="math inline">\(r = 0.2\)</span> e <span class="math inline">\(\text{var}(y) = 0.96\)</span>, indicando che le stime sono coerenti con i parametri di partenza.</p></li>
<li><p><strong>Estimate SD</strong>: È la deviazione standard delle stime dei parametri tra le repliche. Rappresenta la variabilità delle stime nei vari set di dati simulati, e aiuta a capire la precisione delle stime.</p></li>
<li><p><strong>Average SE</strong>: È la media degli errori standard delle stime in tutte le repliche, un’indicazione della variabilità stimata del parametro per ogni replica.</p></li>
<li><p><strong>Power (Not equal 0)</strong>: Questa colonna indica la proporzione di repliche in cui i parametri sono risultati significativamente diversi da zero. Qui la potenza statistica per <code>y ~ TRT</code> è 0.816, vicina al valore target di 0.80. La lieve differenza potrebbe essere ridotta aumentando <code>nRep</code>.</p></li>
<li><p><strong>Average Param</strong>: Rappresenta i valori medi dei parametri simulati. In questo caso, sono i valori di partenza utilizzati nel modello di generazione dei dati, cioè 0.20 per <code>y ~ TRT</code> e 0.96 per <code>y ~~ y</code>.</p></li>
<li><p><strong>Average Bias</strong>: È la differenza tra i valori medi stimati e i parametri di partenza. Nel nostro caso, il bias è molto piccolo, indicando che le stime sono ben centrate attorno ai parametri di partenza.</p></li>
<li><p><strong>Coverage</strong>: Indica la percentuale di intervalli di confidenza che contengono i valori veri dei parametri. In generale, ci si aspetta una copertura intorno al 95% per un intervallo di confidenza al 95%, qui abbiamo coperture di 95.3% e 94.2%, il che è in linea con le aspettative.</p></li>
</ol>
<p>In sintesi, i risultati della simulazione mostrano stime accurate e, con una numerosità campionaria totale di <span class="math inline">\(n = 198\)</span>, raggiungono una potenza statistica vicina all’obiettivo di 0.80, accompagnata da un bias minimo e una buona copertura.</p>
<p>In altre parole, questa dimostrazione evidenzia come la tecnica di simulazione MCSB riesca, nel caso del confronto tra le medie di due gruppi, a collegare la dimensione del campione alla potenza del test, tenendo conto dell’ampiezza dell’effetto e della variabilità campionaria, in linea con le aspettative teoriche.</p>
</section>
</section>
<section id="analisi-di-potenza-nei-modelli-sem" class="level2" data-number="57.6">
<h2 data-number="57.6" class="anchored" data-anchor-id="analisi-di-potenza-nei-modelli-sem"><span class="header-section-number">57.6</span> Analisi di Potenza nei Modelli SEM</h2>
<p>Dopo aver compreso l’approccio MCSB e la sua implementazione in <strong>simsem</strong>, possiamo ora illustrare come calcolare la potenza per modelli di equazioni strutturali (SEM) generali. Un esempio è offerto da <span class="citation" data-cites="chen2023structural">Chen &amp; Yung (<a href="../../99-references.html#ref-chen2023structural" role="doc-biblioref">2023</a>)</span>, che utilizzano un modello di crescita latente (LGC) per analizzare i dati di <span class="citation" data-cites="byrne2013structural">Byrne (<a href="../../99-references.html#ref-byrne2013structural" role="doc-biblioref">2013</a>)</span>.</p>
<div class="data">
<p>Il dataset raccoglie i dati longitudinali raccolti da 405 donne di Hong Kong, sottoposte a valutazione post-chirurgica per il tumore al seno <span class="citation" data-cites="byrne2013structural">(<a href="../../99-references.html#ref-byrne2013structural" role="doc-biblioref">Byrne, 2013</a>)</span>.</p>
</div>
<p>I dati, disponibili nel file <code>hkcancer_red2.dat</code>, includono 10 variabili:</p>
<ul>
<li><strong>ID</strong>: identificatore di ciascuna partecipante.</li>
<li><strong>MOOD1, MOOD4, MOOD8</strong>: valutazioni soggettive dello stato d’animo a 1, 4 e 8 mesi dall’intervento; punteggi più alti indicano un umore peggiore.</li>
<li><strong>SOCADJ1, SOCADJ4, SOCADJ8</strong>: misure di adattamento sociale a 1, 4 e 8 mesi; punteggi più alti indicano un miglior adattamento sociale.</li>
<li><strong>Age</strong>: età della partecipante al momento dell’intervento.</li>
<li><strong>AgeGrp</strong>: categoria di età (dichotomizzata) con ‘Younger’ (&lt; 50 anni) e ‘Older’ (&gt; 50 anni).</li>
<li><strong>SurgTX</strong>: tipo di intervento chirurgico, distinguendo tra lumpectomia e mastectomia.</li>
</ul>
<section id="modello-di-crescita-latente-lgc" class="level3" data-number="57.6.1">
<h3 data-number="57.6.1" class="anchored" data-anchor-id="modello-di-crescita-latente-lgc"><span class="header-section-number">57.6.1</span> Modello di Crescita Latente (LGC)</h3>
<p>Il modello di crescita latente consente di modellare le traiettorie di crescita nel tempo e di confrontare differenze tra gruppi (ad esempio, tra gruppi di età o di intervento). Questo modello permette di analizzare sia le variazioni intra-individuali che quelle inter-individuali nel contesto delle traiettorie longitudinali. Nel caso del dataset sul tumore al seno, possiamo modellare sia il cambiamento longitudinale dello stato d’animo (MOOD) che dell’adattamento sociale (SOCADJ) lungo un periodo di 8 mesi, includendo le variazioni tra le partecipanti nelle loro traiettorie.</p>
<p><span class="citation" data-cites="chen2023structural">Chen &amp; Yung (<a href="../../99-references.html#ref-chen2023structural" role="doc-biblioref">2023</a>)</span> affrontano la questione della determinazione della dimensione campionaria necessaria per rilevare un effetto significativo su “MOOD” con una potenza statistica pari a 0.80.</p>
</section>
<section id="calcolo-della-dimensione-campionaria" class="level3" data-number="57.6.2">
<h3 data-number="57.6.2" class="anchored" data-anchor-id="calcolo-della-dimensione-campionaria"><span class="header-section-number">57.6.2</span> Calcolo della Dimensione Campionaria</h3>
<p>Per determinare la dimensione campionaria necessaria a rilevare l’effetto dell’intervento chirurgico su “MOOD”, è necessario specificare il modello generativo dei dati, che comprende tutti i parametri del modello. Questi parametri descrivono il cambiamento atteso dello stato d’animo nel tempo in relazione al tipo di intervento.</p>
<p>Prima di procedere con l’analisi di potenza, carichiamo i dati in R per adattare il modello in base alle osservazioni empiriche. Ecco come eseguire il caricamento dei dati:</p>
<div id="cell-20" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="11">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>dCancer <span class="ot">&lt;-</span> rio<span class="sc">::</span><span class="fu">import</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"hkcancer_red2.dat"</span>))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-21" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="12">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace all "*" with NA in dCancer</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>dCancer[dCancer <span class="sc">==</span> <span class="st">"*"</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dCancer)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>A data.frame: 6 x 11</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">V1</th>
<th data-quarto-table-cell-role="th" scope="col">V2</th>
<th data-quarto-table-cell-role="th" scope="col">V3</th>
<th data-quarto-table-cell-role="th" scope="col">V4</th>
<th data-quarto-table-cell-role="th" scope="col">V5</th>
<th data-quarto-table-cell-role="th" scope="col">V6</th>
<th data-quarto-table-cell-role="th" scope="col">V7</th>
<th data-quarto-table-cell-role="th" scope="col">V8</th>
<th data-quarto-table-cell-role="th" scope="col">V9</th>
<th data-quarto-table-cell-role="th" scope="col">V10</th>
<th data-quarto-table-cell-role="th" scope="col">V11</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;chr&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;chr&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;chr&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;chr&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;chr&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;chr&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">1</td>
<td>3</td>
<td>2</td>
<td>15.000000</td>
<td>NA</td>
<td>NA</td>
<td>95.906250</td>
<td>NA</td>
<td>NA</td>
<td>70</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">2</td>
<td>2</td>
<td>3</td>
<td>16.000000</td>
<td>25.000000</td>
<td>22.000000</td>
<td>114.888889</td>
<td>105.111111</td>
<td>90.444444</td>
<td>47</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">3</td>
<td>2</td>
<td>2</td>
<td>37.000000</td>
<td>26.000000</td>
<td>25.000000</td>
<td>80.666667</td>
<td>95.333333</td>
<td>95.333333</td>
<td>47</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">4</td>
<td>2</td>
<td>2</td>
<td>19.000000</td>
<td>16.000000</td>
<td>15.000000</td>
<td>112.838710</td>
<td>108.580645</td>
<td>99.000000</td>
<td>52</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">5</td>
<td>1</td>
<td>2</td>
<td>13.000000</td>
<td>16.000000</td>
<td>14.000000</td>
<td>115.000000</td>
<td>105.000000</td>
<td>101.000000</td>
<td>43</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">6</td>
<td>1</td>
<td>1</td>
<td>21.000000</td>
<td>28.000000</td>
<td>19.000000</td>
<td>106.451613</td>
<td>114.967742</td>
<td>107.516129</td>
<td>34</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="cell-22" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="13">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>var_names <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="st">"X1"</span>, <span class="st">"X2"</span>, <span class="st">"MOOD1"</span>, <span class="st">"MOOD4"</span>, <span class="st">"MOOD8"</span>, <span class="st">"SOCADJ1"</span>, <span class="st">"SOCADJ4"</span>, <span class="st">"SOCADJ8"</span>, <span class="st">"Age"</span>,  </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="st">"AgeGrp"</span>, <span class="st">"SurgTx"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(dCancer) <span class="ot">&lt;-</span> var_names</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dCancer)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>A data.frame: 6 x 11</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">X1</th>
<th data-quarto-table-cell-role="th" scope="col">X2</th>
<th data-quarto-table-cell-role="th" scope="col">MOOD1</th>
<th data-quarto-table-cell-role="th" scope="col">MOOD4</th>
<th data-quarto-table-cell-role="th" scope="col">MOOD8</th>
<th data-quarto-table-cell-role="th" scope="col">SOCADJ1</th>
<th data-quarto-table-cell-role="th" scope="col">SOCADJ4</th>
<th data-quarto-table-cell-role="th" scope="col">SOCADJ8</th>
<th data-quarto-table-cell-role="th" scope="col">Age</th>
<th data-quarto-table-cell-role="th" scope="col">AgeGrp</th>
<th data-quarto-table-cell-role="th" scope="col">SurgTx</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;chr&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;chr&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;chr&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;chr&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;chr&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;chr&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">1</td>
<td>3</td>
<td>2</td>
<td>15.000000</td>
<td>NA</td>
<td>NA</td>
<td>95.906250</td>
<td>NA</td>
<td>NA</td>
<td>70</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">2</td>
<td>2</td>
<td>3</td>
<td>16.000000</td>
<td>25.000000</td>
<td>22.000000</td>
<td>114.888889</td>
<td>105.111111</td>
<td>90.444444</td>
<td>47</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">3</td>
<td>2</td>
<td>2</td>
<td>37.000000</td>
<td>26.000000</td>
<td>25.000000</td>
<td>80.666667</td>
<td>95.333333</td>
<td>95.333333</td>
<td>47</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">4</td>
<td>2</td>
<td>2</td>
<td>19.000000</td>
<td>16.000000</td>
<td>15.000000</td>
<td>112.838710</td>
<td>108.580645</td>
<td>99.000000</td>
<td>52</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">5</td>
<td>1</td>
<td>2</td>
<td>13.000000</td>
<td>16.000000</td>
<td>14.000000</td>
<td>115.000000</td>
<td>105.000000</td>
<td>101.000000</td>
<td>43</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">6</td>
<td>1</td>
<td>1</td>
<td>21.000000</td>
<td>28.000000</td>
<td>19.000000</td>
<td>106.451613</td>
<td>114.967742</td>
<td>107.516129</td>
<td>34</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Questa preparazione ci consentirà di configurare il modello LGC con <code>simsem</code>, impostando i parametri di interesse in modo da simulare la potenza con il metodo MCSB e verificare la capacità del modello di rilevare gli effetti desiderati su “MOOD”.</p>
<p>Definiamo il modello a crescita latente.</p>
<div id="cell-24" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="16">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>mod4MOOD <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="st">    # Intercept and Slope with fixed-coefficients</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="st">    iMOOD =~ 1*MOOD1 + 1*MOOD4 + 1*MOOD8</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="st">    sMOOD =~ 0*MOOD1 + 1*MOOD4 + 2.33*MOOD8</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="st">    </span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="st">    # Regression with a labeled for simulation</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="st">    iMOOD ~ SurgTx</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="st">    sMOOD ~ a*SurgTx</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Questo modello di crescita latente è utilizzato per analizzare l’evoluzione dello stato d’animo (MOOD) di un gruppo di persone a tre momenti distinti nel tempo (1, 4 e 8 mesi dopo l’intervento chirurgico).</p>
<p>Il modello ha due componenti principali: <strong>intercetta</strong> e <strong>pendenza</strong>. Queste rappresentano rispettivamente il valore iniziale e la velocità di cambiamento dello stato d’animo nel tempo.</p>
<ol type="1">
<li><p><strong>Intercetta (iMOOD)</strong>: l’intercetta rappresenta il punto di partenza o il livello iniziale dello stato d’animo (MOOD). Nel modello, è definita come:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>iMOOD <span class="ot">=</span><span class="er">~</span> <span class="dv">1</span><span class="sc">*</span>MOOD1 <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span>MOOD4 <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span>MOOD8</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Qui, <code>iMOOD</code> è una variabile latente che cattura il livello medio dello stato d’animo in ciascun momento, usando coefficienti fissati a 1 per indicare che ogni misura contribuisce allo stesso modo alla stima dell’intercetta. Questo implica che l’intercetta è il valore di base dello stato d’animo comune a tutti i partecipanti nei tre punti temporali.</p></li>
<li><p><strong>Pendenza (sMOOD)</strong>: la pendenza rappresenta la velocità e la direzione del cambiamento dello stato d’animo nel tempo.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>sMOOD <span class="ot">=</span><span class="er">~</span> <span class="dv">0</span><span class="sc">*</span>MOOD1 <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span>MOOD4 <span class="sc">+</span> <span class="fl">2.33</span><span class="sc">*</span>MOOD8</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Qui, <code>sMOOD</code> è una variabile latente che descrive come cambia lo stato d’animo nei diversi momenti temporali. I coefficienti (0, 1, 2.33) riflettono l’intervallo di tempo tra le misurazioni (ad esempio, da 1 a 8 mesi). Il coefficiente 2.33 per MOOD8 indica che l’effetto temporale si accumula, essendo il punto finale del periodo di osservazione.</p></li>
</ol>
<p>Il modello include anche delle <strong>regressioni</strong> che collegano l’intercetta e la pendenza a una variabile predittiva, il tipo di intervento chirurgico (SurgTx), che distingue tra due gruppi (lumpectomia e mastectomia).</p>
<ul>
<li><code>iMOOD ~ SurgTx</code>: questa regressione rappresenta l’effetto del tipo di intervento sul livello iniziale dello stato d’animo. In altre parole, cerca di vedere se esiste una differenza nello stato d’animo iniziale in base al tipo di intervento ricevuto.</li>
<li><code>sMOOD ~ a*SurgTx</code>: questa regressione, con un coefficiente etichettato <code>a</code>, rappresenta l’effetto del tipo di intervento sul tasso di cambiamento dello stato d’animo nel tempo. Il coefficiente <code>a</code> mostra se il tipo di intervento influisce sulla velocità di miglioramento o peggioramento dello stato d’animo lungo i mesi.</li>
</ul>
<p>In sintesi, questo modello di crescita latente analizza sia il livello iniziale dello stato d’animo (intercetta) sia il cambiamento nel tempo (pendenza) e verifica se il tipo di intervento chirurgico influenza questi due aspetti.</p>
<p>Adattiamo il modello ai dati.</p>
<div id="cell-26" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="17">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Call growth function to fit the LGC</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>fitMOOD <span class="ot">&lt;-</span> <span class="fu">growth</span>(mod4MOOD,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> dCancer, </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">estimator =</span> <span class="st">"MLR"</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">missing =</span> <span class="st">"fiml"</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-27" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="28">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fitMOOD) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-19 ended normally after 75 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        10

  Number of observations                           405
  Number of missing patterns                         8

Model Test User Model:
                                              Standard      Scaled
  Test Statistic                                 2.022       2.077
  Degrees of freedom                                 2           2
  P-value (Chi-square)                           0.364       0.354
  Scaling correction factor                                  0.974
    Yuan-Bentler correction (Mplus variant)                       

Parameter Estimates:

  Standard errors                             Sandwich
  Information bread                           Observed
  Observed information based on                Hessian

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  iMOOD =~                                            
    MOOD1             1.000                           
    MOOD4             1.000                           
    MOOD8             1.000                           
  sMOOD =~                                            
    MOOD1             0.000                           
    MOOD4             1.000                           
    MOOD8             2.330                           

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  iMOOD ~                                             
    SurgTx           -0.118    0.758   -0.155    0.876
  sMOOD ~                                             
    SurgTx     (a)   -0.282    0.332   -0.850    0.395

Covariances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
 .iMOOD ~~                                            
   .sMOOD            -2.650    1.581   -1.676    0.094

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .iMOOD            10.550    0.671   15.715    0.000
   .sMOOD            -0.389    0.298   -1.304    0.192

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MOOD1            13.492    3.384    3.987    0.000
   .MOOD4            18.792    2.415    7.782    0.000
   .MOOD8             5.398    3.880    1.391    0.164
   .iMOOD            25.827    3.574    7.226    0.000
   .sMOOD             2.563    1.259    2.036    0.042
</code></pre>
</div>
</div>
<div id="cell-28" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="43">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>semPlot<span class="sc">::</span><span class="fu">semPaths</span>(fitMOOD,</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">what =</span> <span class="st">"col"</span>, </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">whatLabels =</span> <span class="st">"par"</span>, </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">nCharNodes =</span> <span class="dv">8</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">shapeMan =</span> <span class="st">"rectangle"</span>, </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sizeMan =</span> <span class="dv">8</span>, </span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sizeMan2 =</span> <span class="dv">7</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="14_sem_power_files/figure-html/cell-16-output-1.png" width="600" height="370" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Una volta ottenute le stime dei parametri del modello, possiamo utilizzarle per costruire la componente di generazione dei dati come segue (nel codice seguente, utilizzo i valori usati da <span class="citation" data-cites="chen2023structural">Chen &amp; Yung (<a href="../../99-references.html#ref-chen2023structural" role="doc-biblioref">2023</a>)</span> per riprodurre il loro risultato).</p>
<div id="cell-30" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="32">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>dat.mod4MOOD <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="st">    # Intercept and Slope with MOOD</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="st">    iMOOD =~ 1*MOOD1 + 1*MOOD4 + 1*MOOD8</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="st">    sMOOD =~ 0*MOOD1 + 1*MOOD4 + 2.33*MOOD8</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="st">    # residual variances for observed</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="st">    MOOD1 ~~ 14.307*MOOD1</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="st">    MOOD4 ~~ 18.637*MOOD4</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="st">    MOOD8 ~~ 6.745*MOOD8</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="st">    # Regression paths to covariates</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a><span class="st">    iMOOD ~ (-0.116)*SurgTx</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="st">    sMOOD ~ a*SurgTx + (-0.332)*SurgTx</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a><span class="st">    # latent Intercepts</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a><span class="st">    iMOOD ~ 21.683*1</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a><span class="st">    sMOOD ~ 0.004*1</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a><span class="st">    # latent variances/coVariances</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a><span class="st">    iMOOD ~~ 25.826*iMOOD</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a><span class="st">    sMOOD ~~ 2.272*sMOOD</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a><span class="st">    iMOOD ~~ (-2.135)*sMOOD</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a><span class="st">    # mean and variance for SurgTX</span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a><span class="st">    SurgTx ~ 0.5*1</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a><span class="st">    SurgTx ~~ 0.25*SurgTx</span></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Possiamo ora usare la funzione <code>sim()</code> di <code>simsem</code>. Seguendo il tutorial di <span class="citation" data-cites="chen2023structural">Chen &amp; Yung (<a href="../../99-references.html#ref-chen2023structural" role="doc-biblioref">2023</a>)</span>, fissiamo la dimensione campionaria complesiva a <code>n = 405</code>:</p>
<div id="cell-32" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="33">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>simOut1 <span class="ot">&lt;-</span> <span class="fu">sim</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">nRep =</span> <span class="dv">1000</span>, </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">generate =</span> dat.mod4MOOD,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">model =</span> mod4MOOD, </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="dv">405</span>, </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">lavaanfun =</span> <span class="st">"growth"</span>,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">seed =</span> <span class="dv">123</span>, </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">silent =</span> <span class="cn">TRUE</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-33" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="34">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># simulation output</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(simOut1)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>RESULT OBJECT
Model Type
[1] "lavaan"
========= Fit Indices Cutoffs ============
           Alpha
Fit Indices      0.1     0.05     0.01    0.001     Mean     SD
      chisq    4.455    5.665    8.871   11.378    1.980  1.888
      aic   7571.694 7588.105 7624.726 7667.762 7508.592 49.361
      bic   7611.733 7628.144 7664.765 7707.801 7548.631 49.361
      rmsea    0.055    0.067    0.092    0.108    0.016  0.025
      cfi      0.994    0.991    0.983    0.975    0.998  0.004
      tli      0.982    0.972    0.948    0.926    1.000  0.014
      srmr     0.018    0.020    0.026    0.028    0.011  0.005
========= Parameter Estimates and Standard Errors ============
             Estimate Average Estimate SD Average SE Power (Not equal 0)
iMOOD~SurgTx           -0.088       0.614      0.607               0.056
a                      -0.337       0.244      0.242               0.287
MOOD1~~MOOD1           14.312       2.882      2.816               1.000
MOOD4~~MOOD4           18.563       1.831      1.846               1.000
MOOD8~~MOOD8            6.843       3.477      3.401               0.536
iMOOD~~iMOOD           25.691       3.168      3.189               1.000
sMOOD~~sMOOD            2.211       1.124      1.100               0.512
iMOOD~~sMOOD           -2.072       1.278      1.284               0.359
iMOOD~1                21.664       0.440      0.429               1.000
sMOOD~1                 0.007       0.167      0.171               0.043
             Std Est Std Est SD Std Ave SE Average Param Average Bias
iMOOD~SurgTx  -0.009      0.061      0.060        -0.116        0.028
a             -0.126      0.129      0.195        -0.332       -0.005
MOOD1~~MOOD1   0.357      0.067      0.066        14.307        0.005
MOOD4~~MOOD4   0.437      0.031      0.031        18.637       -0.074
MOOD8~~MOOD8   0.195      0.099      0.096         6.745        0.098
iMOOD~~iMOOD   0.996      0.005      0.006        25.826       -0.135
sMOOD~~sMOOD   0.968      0.147      0.311         2.272       -0.061
iMOOD~~sMOOD  -0.272      0.459     13.990        -2.135        0.063
iMOOD~1        4.291      0.282      0.282        21.683       -0.019
sMOOD~1        0.005      0.146      0.194         0.004        0.003
             Coverage
iMOOD~SurgTx    0.949
a               0.955
MOOD1~~MOOD1    0.946
MOOD4~~MOOD4    0.947
MOOD8~~MOOD8    0.949
iMOOD~~iMOOD    0.956
sMOOD~~sMOOD    0.940
iMOOD~~sMOOD    0.949
iMOOD~1         0.938
sMOOD~1         0.956
========= Correlation between Fit Indices ============
       chisq    aic    bic  rmsea    cfi    tli   srmr
chisq  1.000 -0.012 -0.012  0.955 -0.939 -0.995  0.957
aic   -0.012  1.000  1.000 -0.002 -0.014  0.016 -0.040
bic   -0.012  1.000  1.000 -0.002 -0.014  0.016 -0.040
rmsea  0.955 -0.002 -0.002  1.000 -0.932 -0.949  0.890
cfi   -0.939 -0.014 -0.014 -0.932  1.000  0.941 -0.818
tli   -0.995  0.016  0.016 -0.949  0.941  1.000 -0.957
srmr   0.957 -0.040 -0.040  0.890 -0.818 -0.957  1.000
================== Replications =====================
Number of replications = 1000 
Number of converged replications = 947 
Number of nonconverged replications: 
   1. Nonconvergent Results = 0 
   2. Nonconvergent results from multiple imputation = 0 
   3. At least one SE were negative or NA = 0 
   4. Nonpositive-definite latent or observed (residual) covariance matrix 
      (e.g., Heywood case or linear dependency) = 53 </code></pre>
</div>
</div>
<p>Possiamo osservare che la potenza associata al parametro <span class="math inline">\(a\)</span> (cioè, l’effetto dell’intervento chirurgico) è 0.287, il che non sorprende, dato che sapevamo già che questo parametro non è statisticamente significativo con la dimensione campionaria attuale di 405.</p>
<p>La domanda successiva è quindi quale dimensione campionaria sia necessaria per ottenere una potenza pari a 0.80. A questo fine, è necessario applicare l’approccio MCSB per una serie di dimensioni campionarie, in modo da calcolare le rispettive potenze.</p>
<p><span class="citation" data-cites="chen2023structural">Chen &amp; Yung (<a href="../../99-references.html#ref-chen2023structural" role="doc-biblioref">2023</a>)</span> costruiscono una curva che mostra la relazione tra dimensione campionaria e potenza, così da identificare la dimensione campionaria necessaria per raggiungere una potenza di 0.80. Per questo scopo, <span class="citation" data-cites="chen2023structural">Chen &amp; Yung (<a href="../../99-references.html#ref-chen2023structural" role="doc-biblioref">2023</a>)</span> utilizzano <code>n = rep(seq(400, 2000, by = 200), 500)</code>, per eseguire l’MCSB su una sequenza di dimensioni campionarie da 400 a 2000, con incrementi di 200 (ovvero: 400, 600, 800, 1000, 1200, 1400, 1600, 1800, e 2000), ciascuna delle quali sarà utilizzata per 500 simulazioni.</p>
<div id="cell-35" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="35">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulation for sequential sample size</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>simAll <span class="ot">&lt;-</span> <span class="fu">sim</span>(</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">nRep =</span> <span class="cn">NULL</span>, </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">generate =</span> dat.mod4MOOD,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">model =</span> mod4MOOD, </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">rep</span>(<span class="fu">seq</span>(<span class="dv">400</span>, <span class="dv">2000</span>, <span class="dv">200</span>), <span class="dv">500</span>),</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">lavaanfun =</span> <span class="st">"growth"</span>, </span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">seed =</span> <span class="dv">123</span>, </span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">silent =</span> <span class="cn">TRUE</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>    ) </span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-36" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="36">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the simulations</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(simAll)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>RESULT OBJECT
Model Type
[1] "lavaan"
========= Fit Indices Cutoffs ============
     N chisq   aic   bic rmsea   cfi   tli  srmr
1  400  6.19  7503  7545 0.061 0.993 0.978 0.019
2  800  6.04 14933 14979 0.053 0.994 0.983 0.016
3 1200  5.88 22363 22413 0.044 0.996 0.987 0.013
4 1600  5.73 29793 29847 0.036 0.997 0.992 0.011
5 2000  5.57 37223 37281 0.027 0.999 0.996 0.008
========= Parameter Estimates and Standard Errors ============
             Estimate Average Estimate SD Average SE Power (Not equal 0)
iMOOD~SurgTx           -0.122       0.400      0.387               0.066
a                      -0.327       0.163      0.154               0.607
MOOD1~~MOOD1           14.298       1.831      1.794               1.000
MOOD4~~MOOD4           18.662       1.230      1.178               1.000
MOOD8~~MOOD8            6.700       2.223      2.163               0.855
iMOOD~~iMOOD           25.761       2.094      2.033               1.000
sMOOD~~sMOOD            2.265       0.722      0.700               0.877
iMOOD~~sMOOD           -2.130       0.855      0.818               0.761
iMOOD~1                21.687       0.284      0.273               1.000
sMOOD~1                 0.002       0.116      0.109               0.058
             Std Est Std Est SD Std Ave SE Average Param Average Bias
iMOOD~SurgTx  -0.012      0.039      0.038        -0.116       -0.006
a             -0.113      0.079      0.329        -0.332        0.005
MOOD1~~MOOD1   0.357      0.043      0.042        14.307       -0.009
MOOD4~~MOOD4   0.439      0.020      0.020        18.637        0.025
MOOD8~~MOOD8   0.191      0.063      0.061         6.745       -0.045
iMOOD~~iMOOD   0.998      0.003      0.003        25.826       -0.065
sMOOD~~sMOOD   0.981      0.164      1.757         2.272       -0.007
iMOOD~~sMOOD  -0.272      0.097      0.134        -2.135        0.005
iMOOD~1        4.280      0.186      0.178        21.683        0.004
sMOOD~1        0.000      0.086      0.169         0.004       -0.002
             Coverage r_coef.n r_se.n
iMOOD~SurgTx    0.949   -0.008 -0.933
a               0.943   -0.022 -0.933
MOOD1~~MOOD1    0.953   -0.007 -0.931
MOOD4~~MOOD4    0.950   -0.022 -0.925
MOOD8~~MOOD8    0.952    0.016 -0.933
iMOOD~~iMOOD    0.951   -0.001 -0.929
sMOOD~~sMOOD    0.955   -0.004 -0.935
iMOOD~~sMOOD    0.948    0.012 -0.934
iMOOD~1         0.948   -0.003 -0.935
sMOOD~1         0.942    0.012 -0.935
========= Correlation between Fit Indices ============
       chisq    aic    bic  rmsea    cfi    tli   srmr      n
chisq  1.000 -0.007 -0.007  0.911 -0.780 -0.854  0.825 -0.007
aic   -0.007  1.000  1.000 -0.158  0.204  0.015 -0.427  1.000
bic   -0.007  1.000  1.000 -0.158  0.204  0.015 -0.427  1.000
rmsea  0.911 -0.158 -0.158  1.000 -0.875 -0.897  0.866 -0.158
cfi   -0.780  0.204  0.204 -0.875  1.000  0.930 -0.776  0.204
tli   -0.854  0.015  0.015 -0.897  0.930  1.000 -0.818  0.015
srmr   0.825 -0.427 -0.427  0.866 -0.776 -0.818  1.000 -0.427
n     -0.007  1.000  1.000 -0.158  0.204  0.015 -0.427  1.000
================== Replications =====================
Number of replications = 4500 
Number of converged replications = 4455 
Number of nonconverged replications: 
   1. Nonconvergent Results = 0 
   2. Nonconvergent results from multiple imputation = 0 
   3. At least one SE were negative or NA = 0 
   4. Nonpositive-definite latent or observed (residual) covariance matrix 
      (e.g., Heywood case or linear dependency) = 45 
NOTE: The sample size is varying.</code></pre>
</div>
</div>
<p>Utilizzando la funzione <code>getPower</code>, è quindi ottenere le stime di potenza per ciascuna dimensione campionaria come segue:</p>
<div id="cell-38" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="37">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>LGC.N <span class="ot">&lt;-</span> <span class="fu">getPower</span>(simAll)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the samplesize for 80% power</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">findPower</span>(LGC.N, <span class="st">"N"</span>, <span class="fl">0.8</span>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>iMOOD~SurgTx            a MOOD1~~MOOD1 MOOD4~~MOOD4 MOOD8~~MOOD8 
          NA         1710          Inf          Inf          816 
iMOOD~~iMOOD sMOOD~~sMOOD iMOOD~~sMOOD      iMOOD~1      sMOOD~1 
         Inf          748         1161          Inf           NA </code></pre>
</div>
</div>
<p>Pertanto, in base alla simulazione di <span class="citation" data-cites="chen2023structural">Chen &amp; Yung (<a href="../../99-references.html#ref-chen2023structural" role="doc-biblioref">2023</a>)</span>, sarebbe necessaria una dimensione campionaria di 1710 per ottenere una potenza di 0.80.</p>
<p>Questo risultato può essere mostrato graficamente nella figura seguente. In questa figura, la linea tratteggiata orizzontale indica la potenza a 0.80, mentre la linea con la freccia che va da questa linea orizzontale a <span class="math inline">\(N\)</span> = 1710 indica la dimensione campionaria determinata dalla curva di potenza.</p>
<div id="cell-40" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="38">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Call plotPower to plot the power to sample size</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plotPower</span>(simAll, <span class="at">powerParam =</span> <span class="st">"a"</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a horizontal line of 0.80</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fl">0.8</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">8</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">arrows</span>(<span class="dv">1710</span>, <span class="fl">0.8</span>, <span class="dv">1710</span>, <span class="dv">0</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1710</span>,</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span><span class="fl">0.018</span>, <span class="st">"N = 1710"</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="14_sem_power_files/figure-html/cell-23-output-1.png" width="600" height="370" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="riflessioni-conclusive" class="level2" data-number="57.7">
<h2 data-number="57.7" class="anchored" data-anchor-id="riflessioni-conclusive"><span class="header-section-number">57.7</span> Riflessioni Conclusive</h2>
<p>In questo capitolo, abbiamo illustrato come determinare la dimensione campionaria e calcolare la potenza statistica utilizzando l’approccio basato sulla simulazione Monte Carlo. Questo metodo rappresenta l’approccio più generale e flessibile per ottenere stime affidabili della dimensione campionaria e della potenza necessarie alla progettazione di studi in vari contesti di ricerca, inclusi i modelli a equazioni strutturali (SEM).</p>
<p>La simulazione Monte Carlo consente di affrontare situazioni complesse e realistiche che spesso non sono gestibili con metodi analitici tradizionali. Essa permette infatti di modellare vari scenari, includendo la variabilità dei parametri e le incertezze che caratterizzano i dati empirici. Inoltre, il metodo può essere applicato a una vasta gamma di modelli statistici, garantendo flessibilità nell’adattamento a diversi contesti di studio e domande di ricerca.</p>
<p>In conclusione, il metodo basato sulla simulazione Monte Carlo offre un potente strumento per pianificare studi empirici robusti e ben fondati, permettendo ai ricercatori di prendere decisioni informate riguardo alla dimensione del campione e alla configurazione del modello in relazione agli obiettivi specifici del loro studio.</p>
</section>
<section id="informazioni-sullambiente-di-sviluppo" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="informazioni-sullambiente-di-sviluppo">Informazioni sull’Ambiente di Sviluppo</h2>
<div id="cell-43" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="27">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>R version 4.4.2 (2024-10-31)
Platform: aarch64-apple-darwin20
Running under: macOS Sequoia 15.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

Random number generation:
 RNG:     L'Ecuyer-CMRG 
 Normal:  Inversion 
 Sample:  Rejection 
 
locale:
[1] C

time zone: Europe/Rome
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] quantreg_5.99     compute.es_0.2-5  simsem_0.5-16     kableExtra_1.4.0 
 [5] MASS_7.3-61       viridis_0.6.5     viridisLite_0.4.2 ggpubr_0.6.0     
 [9] ggExtra_0.10.1    gridExtra_2.3     patchwork_1.3.0   bayesplot_1.11.1 
[13] semTools_0.5-6    semPlot_1.1.6     lavaan_0.6-19     psych_2.4.6.26   
[17] scales_1.3.0      markdown_1.13     knitr_1.49        lubridate_1.9.3  
[21] forcats_1.0.0     stringr_1.5.1     dplyr_1.1.4       purrr_1.0.2      
[25] readr_2.1.5       tidyr_1.3.1       tibble_3.2.1      ggplot2_3.5.1    
[29] tidyverse_2.0.0   here_1.0.1       

loaded via a namespace (and not attached):
  [1] splines_4.4.2       later_1.3.2         pbdZMQ_0.3-13      
  [4] R.oo_1.27.0         XML_3.99-0.17       rpart_4.1.23       
  [7] lifecycle_1.0.4     rstatix_0.7.2       rprojroot_2.0.4    
 [10] lattice_0.22-6      rockchalk_1.8.157   backports_1.5.0    
 [13] magrittr_2.0.3      openxlsx_4.2.7.1    Hmisc_5.2-0        
 [16] rmarkdown_2.29      httpuv_1.6.15       qgraph_1.9.8       
 [19] zip_2.3.1           pbapply_1.7-2       minqa_1.2.8        
 [22] multcomp_1.4-26     abind_1.4-8         quadprog_1.5-8     
 [25] R.utils_2.12.3      nnet_7.3-19         TH.data_1.1-2      
 [28] sandwich_3.1-1      openintro_2.5.0     arm_1.14-4         
 [31] MatrixModels_0.5-3  airports_0.1.0      svglite_2.1.3      
 [34] codetools_0.2-20    xml2_1.3.6          tidyselect_1.2.1   
 [37] farver_2.1.2        lme4_1.1-35.5       stats4_4.4.2       
 [40] base64enc_0.1-3     jsonlite_1.8.9      Formula_1.2-5      
 [43] survival_3.7-0      emmeans_1.10.5      systemfonts_1.1.0  
 [46] tools_4.4.2         rio_1.2.3           Rcpp_1.0.13-1      
 [49] glue_1.8.0          mnormt_2.1.1        xfun_0.49          
 [52] IRdisplay_1.1       withr_3.0.2         fastmap_1.2.0      
 [55] boot_1.3-31         fansi_1.0.6         SparseM_1.84-2     
 [58] digest_0.6.37       mi_1.1              timechange_0.3.0   
 [61] R6_2.5.1            mime_0.12           estimability_1.5.1 
 [64] colorspace_2.1-1    Cairo_1.6-2         gtools_3.9.5       
 [67] jpeg_0.1-10         R.methodsS3_1.8.2   utf8_1.2.4         
 [70] generics_0.1.3      data.table_1.16.2   corpcor_1.6.10     
 [73] usdata_0.3.1        htmlwidgets_1.6.4   pkgconfig_2.0.3    
 [76] sem_3.1-16          gtable_0.3.6        htmltools_0.5.8.1  
 [79] carData_3.0-5       png_0.1-8           rstudioapi_0.17.1  
 [82] tzdb_0.4.0          reshape2_1.4.4      uuid_1.2-1         
 [85] coda_0.19-4.1       checkmate_2.3.2     nlme_3.1-166       
 [88] nloptr_2.1.1        repr_1.1.7          zoo_1.8-12         
 [91] parallel_4.4.2      miniUI_0.1.1.1      foreign_0.8-87     
 [94] pillar_1.9.0        grid_4.4.2          vctrs_0.6.5        
 [97] promises_1.3.0      car_3.1-3           OpenMx_2.21.13     
[100] xtable_1.8-4        cluster_2.1.6       htmlTable_2.4.3    
[103] evaluate_1.0.1      pbivnorm_0.6.0      mvtnorm_1.3-2      
[106] cli_3.6.3           kutils_1.73         compiler_4.4.2     
[109] rlang_1.1.4         crayon_1.5.3        ggsignif_0.6.4     
[112] fdrtool_1.2.18      plyr_1.8.9          stringi_1.8.4      
[115] munsell_0.5.1       lisrelToR_0.3       pacman_0.5.1       
[118] Matrix_1.7-1        IRkernel_1.3.2      hms_1.1.3          
[121] glasso_1.11         shiny_1.9.1         igraph_2.1.1       
[124] broom_1.0.7         RcppParallel_5.1.9  cherryblossom_0.1.0</code></pre>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-buchberger2024estimating" class="csl-entry" role="listitem">
Buchberger, E. S., Ngo, C. T., Peikert, A., Brandmaier, A. M., &amp; Werkle-Bergner, M. (2024). Estimating statistical power for structural equation models in developmental cognitive science: A tutorial in R: Power simulation for SEMs. <em>Behavior Research Methods</em>, 1–18.
</div>
<div id="ref-byrne2013structural" class="csl-entry" role="listitem">
Byrne, B. M. (2013). <em>Structural equation modeling with Mplus: Basic concepts, applications, and programming</em>. routledge.
</div>
<div id="ref-chen2023structural" class="csl-entry" role="listitem">
Chen, D.-G., &amp; Yung, Y.-F. (2023). <em>Structural Equation Modeling Using R/SAS: A Step-by-step Approach with Real Data Analysis</em>. CRC Press.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiato!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiato!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ccaudek\.github\.io\/testing_psicologico\/intro\.html");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/sem/13_esem.html" class="pagination-link" aria-label="Exploratory structural equation modelling">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Exploratory structural equation modelling</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/sem/E_01.html" class="pagination-link" aria-label="✏️ Esercizi">
        <span class="nav-page-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">✏️ Esercizi</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Testing Psicologico</strong> è una dispensa scritta da Corrado Caudek.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>